internal static class MedicalBrutalismTrTw
{
    public static readonly (string En, string Zh)[] Moodles =
    {
        ("Back pain", "背痛"),
        ("Seizure", "癲癇發作"),
        ("Lazarus syndrome", "拉撒路綜合徵【死而復生】"),
        ("Pneumothorax", "氣胸"),
        ("Bilateral pneumothorax", "雙側氣胸"),
        ("Spinal cord rupture", "脊髓斷裂"),
        ("Hyperviscosity", "高黏血癥"),
        ("Hypoviscosity", "低黏血癥"),
        ("Acidosis", "酸中毒"),
        ("Alkalosis", "鹼中毒"),
        ("DNA Damage", "DNA 損傷"),
        ("Mild contusion", "輕度挫傷"),
        ("Contusion", "挫傷"),
        ("Brain liquidification", "腦液化"),
        ("Cold", "感冒"),
        ("Fever", "發熱"),
        ("Severe fever", "高燒"),
        ("Hemolytic reaction", "溶血反應"),
        ("Severe hemolytic reaction", "嚴重溶血反應"),
        ("Systemic infection", "全身性感染"),
        ("Terminal systemic infection", "終 末 期 全 身 性 感 染"),
        ("Unknown stage", "未知階段"),
        ("Insomnia", "失眠"),
        ("Lethal insomnia", "致命性失眠"),
        ("Liver disfunction", "肝功能障礙"),
        ("Liver failure", "肝衰竭"),
        ("Terminal liver failure", "終 末 期 肝 衰 竭"),
        ("Liver Failure", "肝衰竭"),
        ("..?", "..？"),
        ("Fractured neck", "頸部骨折"),
        ("Disclocated spine", "脊柱脫位"),
        ("I4S-DS", "I4S-DS"),
        ("Relieved", "舒緩"),
        ("Drug overdose", "藥物過量"),
        ("Myocardial infarction", "心肌梗死"),
        ("Heart tamponade", "心臟壓塞"),
        ("Augmentin", "奧格門汀"),
        ("Persistent lower back pain from overexertion or poor sleep. Reduces mobility and causes constant discomfort.", "過度勞累或睡眠不足導致的持續性下背痛。降低行動能力並造成持續不適。"),
        ("By all means, you should've been dead, but seemingly you've lucked out. ", "按理說 你 早 該 死 了，但看來你走運了。"),
        ("A puncture in the chest cavity caused air to get sucked in it, making breathing painful and rather difficult. Decompression needed.", "胸腔穿孔導致空氣被吸入，使呼吸疼痛且困難。需要進行減壓處理。"),
        ("Air in the chest cavity makes breathing practically impossible, lethal if not treated. Decompression essential.", "胸腔積氣使呼吸幾乎不可能，不及時處理會致命。減壓至關重要。"),
        ("Critical spinal cord rupture paralyzing your limbs from waist down. You might never walk again.", "危急性脊髓斷裂，導致腰部以下肢體癱瘓。你可能再也無法行走。"),
        ("Blood viscosity slightly above normal.", "血液黏稠度略高於正常水平。"),
        ("Blood viscosity moderately above normal.", "血液黏稠度中度升高。"),
        ("Severely elevated blood viscosity, something is very wrong with your blood.", "血液黏稠度嚴重升高，你的血液出了大問題。"),
        ("Critically high blood viscosity, pulmonary embolism imminent.", "血液黏稠度極高，肺栓塞迫在眉睫。"),
        ("Blood viscosity slightly below normal.", "血液黏稠度略低於正常水平。"),
        ("Blood viscosity moderately below normal.", "血液黏稠度中度降低。"),
        ("Severely lowered blood viscosity, something is very wrong with your blood.", "血液黏稠度嚴重降低，你的血液出了大問題。"),
        ("Life-threating low blood viscosity, oxygen delivery is severely impaired.", "低黏血癥危及生命，氧氣輸送嚴重受損。"),
        ("A mild brain injury causing tinnitus occasional disorientation and confusion.", "輕度腦損傷，會引起耳鳴、偶爾的定向障礙和意識混亂。"),
        ("Moderate brain trauma causing frequent disorientation and severe headaches.", "中度腦外傷，導致頻繁的定向障礙和劇烈頭痛。"),
        ("Catastrophic brain damage. High risk of stroke, constant disorientation and loss of motor control.", "災難性腦損傷。中風風險高，持續定向障礙並喪失運動控制能力。"),
        ("You caught a cold. Wont take much and long to recover.", "你感冒了。不需要太多時間就能恢復。"),
        ("Your cold is getting worse. Frequent sneezing, fever, and weakness.", "你的感冒正在加重。頻繁打噴嚏、發燒且虛弱無力。"),
        ("Severe flu. You're losing fluids rapidly, vomiting occasionally. Immediate care needed.", "嚴重流感。你正在快速流失體液，偶爾嘔吐。需要立即治療。"),
        ("Mild hemolytic reaction, slight blood pressure drop, fever, and stomach ache.", "輕度溶血反應：血壓輕微下降、發燒和胃痛。"),
        ("Moderate hemolytic reaction, possible health complications, fever, pain, lowered Sp02.", "中度溶血反應：可能出現健康併發症，發燒、疼痛、血氧飽和度下降。"),
        ("Severe hemolytic reaction, critical blood pressure drop and organ disfunction, you are actively dying.", "嚴重溶血反應：血壓急劇下降、器官功能障礙，你正在走向死亡。"),
        ("Your insides feel weird, you better take some antibiotics before it gets worse.", "你的體內感覺不對勁，最好在惡化前吃些抗生素。"),
        ("Systemic infection settled in. You feel sluggish, and warmer than usual. Using antibiotics are essential to reset infection's progress.", "全身性感染已經紮根。你感到遲鈍，比平時更熱。使用抗生素對於逆轉感染進展至關重要。"),
        ("Systemic infection worsened. You feel even worse than before, something is wrong on the inside. Using antibiotics are essential to reset infection's progress.", "全身性感染惡化。你感覺比以前更糟，體內有什麼東西不對勁。使用抗生素對於逆轉感染進展至關重要。"),
        ("Systemic infection evolved into critical stage, you feel like the end is near, perhaps it is. Using antibiotics are essential to reset infection's progress.", "全身性感染已發展到危重階段，你感覺末日將近，也許確實如此。使用抗生素對於逆轉感染進展至關重要。"),
        ("Terminal systemic infection. Your body is shutting down slowly. Death is imminent. Antibiotics won't help with this one...", "終末期全身性感染。你的身體正在慢慢衰竭。\n死 亡 迫 在 眉 睫。抗生素已無能為力..."),
        ("Terminal systemic infection. Your body is shutting down slowly. Death is imminent. Antibiotics won't help with this one...\n\n<color=#ff3333>Terminal – no cure, only delay.</color>", "終末期全身性感染。你的身體正在慢慢衰竭。\n死 亡 迫 在 眉 睫。抗生素已無能為力...\n\n<color=#ff3333>終 末 期 —— 無 藥 可 醫 ，只 能 延 緩 。</color>"),
        ("You can't sleep. Your mind is racing, and your body refuses to rest. May or may not resolve on it's own", "你無法入睡。思緒萬千，身體拒絕休息。可能會自行緩解，也可能不會。"),
        ("Your body is giving up from exhaustion. If you don't find a way to sleep, this will most likely be lethal.", "你的身體因疲憊而瀕臨崩潰。如果找不到辦法入睡，這很可能是致命的。"),
        ("Your body is giving up from exhaustion, if you don't find a way to sleep this will most likely be lethal.", "你的身體因疲憊而瀕臨崩潰，如果找不到辦法入睡，這很可能是致命的。"),
        ("You can't sleep. Your mind is racing, and your body refuses to rest.", "你無法入睡。思緒萬千，身體拒絕休息。"),
        ("Your liver is failing causing nausea, pain, and weakness. Seek treatment.", "你的肝臟正在衰竭，導致噁心、疼痛和虛弱。儘快尋求治療。"),
        ("Severe liver failure. Your body is yellowing, energy fading, and sickness worsening.", "嚴重肝衰竭。你的身體正在發黃、精力衰退、病情惡化。"),
        ("Terminal liver failure. Your organs are shutting down. Death is nearing in.", "終末期肝衰竭。你的器官正在衰竭。\n死 亡 臨 近"),
        ("Your neck is broken. Moving around is agonizing and has a chance to sever your spinal cord if it's not already. Physically weaker from the neck down. Eating is painful.", "你的頸部骨折了。移動極其痛苦，如果脊髓尚未斷裂，移動還有可能導致脊髓斷裂。頸部以下身體虛弱。進食時感到疼痛。"),
        ("Your spine is dislocated. Moving around is painful and has a chance to sever your spinal cord if it's not already. Physically weaker from the waist down.", "你的脊柱脫位了。移動時感到疼痛，如果脊髓尚未斷裂，移動還有可能導致脊髓斷裂。腰部以下身體虛弱。"),
        ("Mild acidosis. You feel slightly fatigued.", "輕度酸中毒。你感到輕微疲勞。"),
        ("Moderate acidosis. Breathing is heavy, stamina depletes faster.", "中度酸中毒。呼吸沉重，體力消耗更快。"),
        ("Severe acidosis. Organs are failing, brain damage imminent.", "重度酸中毒。器官正在衰竭，腦損傷迫在眉睫。"),
        ("Mild alkalosis. Muscle twitching and slight confusion.", "輕度鹼中毒。肌肉抽搐並伴有輕微意識混亂。"),
        ("Moderate alkalosis. Severe muscle cramps and breathing difficulties.", "中度鹼中毒。嚴重肌肉痙攣和呼吸困難。"),
        ("Severe alkalosis. Seizures, brain damage, risk of death.", "重度鹼中毒。癲癇發作、腦損傷，有死亡風險。"),
        ("Your DNA is slightly damaged. Immune system and regeneration are impaired.", "你的 DNA 受到輕微損傷。免疫系統和再生能力受損。"),
        ("Moderate DNA damage. Your body is struggling to repair itself.", "中度 DNA 損傷。你的身體正在艱難地自我修復。"),
        ("<i>That's strange that you didn't turn into a puddle.</i>", "<i>真奇怪，你居然沒有變成一灘爛泥。</i>"),
        ("You have overdosed on a non-opioid drug. Health complications likely.", "你已過量服用一種非阿片類藥物。很可能出現健康併發症。"),
        ("Irreversible myocardial infarction. The heart is failing. Death is inevitable.", "不可逆的心肌梗死。心臟正在衰竭。死亡已不可避免。"),
    };
    public static readonly (string En, string Zh)[] MoodleFormats =
    {
        ("Your insides feel weird, you better take some antibiotics before it gets worse. <color=grey>({0})</color>", "你的體內感覺不對勁，最好在惡化前吃些抗生素。<color=grey>（{0}）</color>"),
        ("Systemic infection settled in. You feel sluggish, and warmer than usual. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染已經紮根。你感到遲鈍，比平時更熱。使用抗生素對於逆轉感染進展至關重要。<color=grey>（{0}）</color>"),
        ("Systemic infection worsened. You feel even worse than before, something is wrong on the inside. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染惡化。你感覺比以前更糟，體內有什麼東西不對勁。使用抗生素對於逆轉感染進展至關重要。<color=grey>（{0}）</color>"),
        ("Systemic infection evolved into critical stage, you feel like the end is near, perhaps it is. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染已發展到危重階段，你感覺末日將近，也許確實如此。使用抗生素對於逆轉感染進展至關重要。<color=grey>（{0}）</color>"),
        ("Powerful experimental drug in bloodstream. Regeneration boosted and consciousness protection acquired. <color=grey>({0})</color>", "強大的實驗性藥物已進入血液。再生能力提升，並獲得意識保護。<color=grey>（{0}）</color>"),
        ("Feeling calm and deep relief, you wish it never ended. <color=grey>({0})</color>", "你感到平靜與深沉的解脫，但願這一切永不結束。<color=grey>（{0}）</color>"),
        ("Augmentin antibiotic active in your system, halting systemic infection progress is present and not letting one appear if not. <color=grey>({0})</color>", "奧格門汀抗生素正在你的體內發揮作用，阻止全身性感染的進展，若尚未感染則防止其出現。<color=grey>（{0}）</color>"),
        ("Massive blood clot broke off and lodged itself in massive heart artery cutting off it's blood supply. Seek treatment. Use streptokinase to break the clot. ({0}%)", "大量血栓脫落並卡在心臟大動脈中，切斷了血液供應。請儘快治療。使用鏈激酶溶解血栓。（{0}%）"),
        ("Moderate heart attack. Your heart is starting to necrose slowly. You NEED to break the clot somehow. ({0}%)", "中度心臟病發作。你的心臟開始緩慢壞死。你必須設法溶解血栓。（{0}%）"),
        ("Severe heart attack. Life-threatening heart necrosis imminent, immediate treatment needed. ({0}%)", "重度心臟病發作。危及生命的心肌壞死迫在眉睫，需要立即治療。（{0}%）"),
        ("Critical myocardial infarction. Heart muscle is dying rapidly. Prepare for cardiac arrest. ({0}%)", "危重心肌梗死。心肌正在迅速壞死。為心臟驟停做好準備。（{0}%）"),
        ("Mild heart tamponade. Blood is accumulating in the pericardium. ({0}%)", "輕度心臟壓塞。血液正在心包內積聚。（{0}%）"),
        ("Moderate heart tamponade. Heart is being compressed, reducing output. ({0}%)", "中度心臟壓塞。心臟受到壓迫，輸出量減少。（{0}%）"),
        ("Severe heart tamponade. Heart output severely reduced, risk of cardiac arrest. ({0}%)", "重度心臟壓塞。心臟輸出量嚴重減少，有心臟驟停風險。（{0}%）"),
        ("Critical heart tamponade. Heart is nearly crushed, heart failure imminent. ({0}%)", "危重心臟壓塞。心臟幾乎被壓碎，心力衰竭迫在眉睫。（{0}%）"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Remove parasites", "移除寄生蟲"),
        ("Claw out the parasites feasting on this limb.", "將啃食這條肢體的寄生蟲忍痛挖出。"),
        ("Hold LMB and drag over parasites to claw them out.", "按住鼠標左鍵並在寄生蟲上拖動，將它們挖出。"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("*sneezes*", "*啊啾*"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("MedicalBrutalism: Кнопка добавлена в меню (X={0}, Y={1}, W={2}, H={3})", "MedicalBrutalism: 菜單按鈕已添加（X={0}，Y={1}，W={2}，H={3}）"),
        ("<color=yellow>MedicalBrutalism: Панель меню не найдена.; {0}</color>", "<color=yellow>MedicalBrutalism: 未找到菜單面板；{0}</color>"),
        ("<color=yellow>MedicalBrutalism: Не найдена эталонная кнопка Radio/TutorialRadio.; {0}</color>", "<color=yellow>MedicalBrutalism: 未找到參考按鈕 Radio/TutorialRadio；{0}</color>"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Lazarus: additional cleanup completed.", "拉撒路 : 額外清理已完成。"),
        ("Lazarus: resurrection performed. DNA healed, acid-base reset, hemolytic reduced.", "拉撒路 : 復活已執行。DNA 已修復，酸鹼平衡已重置，溶血反應已減輕。"),
    };
    public static readonly (string En, string Zh)[] Fragments =
    {
        ("BldT: ", "血型："),
        ("Blood type: ", "血型："),
        ("Compatible with: ", "相容："),
        ("All types", "全部血型"),
        ("Unknown", "未知"),
    };
    public static readonly (string En, string Zh)[] LiquidKeys =
    {
        ("Amoxcilin", "阿莫西林"),
        ("Amoxcilindsc", "一種用於治療全身感染的抗生素。服用後可重置感染進展。"),
        ("amoxcilin", "阿莫西林"),
        ("amoxcilindsc", "一種用於治療全身感染的抗生素。服用後可重置感染進展。"),
        ("Augmentin", "奧格門汀"),
        ("Augmentindsc", "一種強力抗生素，可暫時阻斷全身感染並減緩普通感染的進展。"),
        ("augmentin", "奧格門汀"),
        ("augmentindsc", "一種強力抗生素，可暫時阻斷全身感染並減緩普通感染的進展。"),
        ("I4S-DS", "I4S-DS"),
        ("I4S-DSdsc", "一種強效再生化合物，必須直接注入血液。劑量約為35mL。"),
        ("i4sds", "I4S-DS"),
        ("i4sdsdsc", "一種強效再生化合物，必須直接注入血液。劑量約為35mL。"),
        ("i4s-dsdsc", "一種強效再生化合物，必須直接注入血液。劑量約為35mL。"),
        ("Koldera mix", "科爾德拉合劑"),
        ("Koldera mixdsc", "一種鎮靜劑，可誘發平靜與解脫感。劑量約為20mL。"),
        ("kolderamix", "科爾德拉合劑"),
        ("kolderamixdsc", "一種鎮靜劑，可誘發平靜與解脫感。劑量約為20mL。"),
        ("Blood A+", "A+ 型血液"),
        ("Blood A+dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：A+、AB+。"),
        ("Blood A-", "A- 型血液"),
        ("Blood A-dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：A-、A+、AB-、AB+。"),
        ("Blood B+", "B+ 型血液"),
        ("Blood B+dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：B+、AB+。"),
        ("Blood B-", "B- 型血液"),
        ("Blood B-dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：B-、B+、AB-、AB+。"),
        ("Blood AB+", "AB+ 型血液"),
        ("Blood AB+dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：AB+。"),
        ("Blood AB-", "AB- 型血液"),
        ("Blood AB-dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：AB-、AB+。"),
        ("Blood O+", "O+ 型血液"),
        ("Blood O+dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：O+、A+、B+、AB+。"),
        ("Blood O-", "O- 型血液"),
        ("Blood O-dsc", "黃色血液。雖然顏色在你看來正常，但這顯然是生物工程過程的副作用。用於治療低血容量。\n \n相容：全部血型。"),
    };
    public static readonly (string En, string Zh)[] BloodLiquidNames =
    {
        ("Blood A+", "A+ 型血液"),
        ("Blood A-", "A- 型血液"),
        ("Blood B+", "B+ 型血液"),
        ("Blood B-", "B- 型血液"),
        ("Blood AB+", "AB+ 型血液"),
        ("Blood AB-", "AB- 型血液"),
        ("Blood O+", "O+ 型血液"),
        ("Blood O-", "O- 型血液"),
    };
}
