internal static class MedicalBrutalismTr
{
    public static readonly (string En, string Zh)[] Moodles =
    {
        ("Back pain", "背痛"),
        ("Seizure", "癫痫发作"),
        ("Lazarus syndrome", "拉撒路综合征【死而复生】"),
        ("Pneumothorax", "气胸"),
        ("Bilateral pneumothorax", "双侧气胸"),
        ("Spinal cord rupture", "脊髓断裂"),
        ("Hyperviscosity", "高黏血症"),
        ("Hypoviscosity", "低黏血症"),
        ("Acidosis", "酸中毒"),
        ("Alkalosis", "碱中毒"),
        ("DNA Damage", "DNA 损伤"),
        ("Mild contusion", "轻度挫伤"),
        ("Contusion", "挫伤"),
        ("Brain liquidification", "脑液化"),
        ("Cold", "感冒"),
        ("Fever", "发热"),
        ("Severe fever", "高烧"),
        ("Hemolytic reaction", "溶血反应"),
        ("Severe hemolytic reaction", "严重溶血反应"),
        ("Systemic infection", "全身性感染"),
        ("Terminal systemic infection", "终 末 期 全 身 性 感 染"),
        ("Unknown stage", "未知阶段"),
        ("Insomnia", "失眠"),
        ("Lethal insomnia", "致命性失眠"),
        ("Liver disfunction", "肝功能障碍"),
        ("Liver failure", "肝衰竭"),
        ("Terminal liver failure", "终 末 期 肝 衰 竭"),
        ("Liver Failure", "肝衰竭"),
        ("..?", "..？"),
        ("Fractured neck", "颈部骨折"),
        ("Disclocated spine", "脊柱脱位"),
        ("I4S-DS", "I4S-DS"),
        ("Relieved", "舒缓"),
        ("Drug overdose", "药物过量"),
        ("Myocardial infarction", "心肌梗死"),
        ("Heart tamponade", "心脏压塞"),
        ("Augmentin", "奥格门汀"),
        ("Persistent lower back pain from overexertion or poor sleep. Reduces mobility and causes constant discomfort.", "过度劳累或睡眠不足导致的持续性下背痛。降低行动能力并造成持续不适。"),
        ("By all means, you should've been dead, but seemingly you've lucked out. ", "按理说 你 早 该 死 了，但看来你走运了。"),
        ("A puncture in the chest cavity caused air to get sucked in it, making breathing painful and rather difficult. Decompression needed.", "胸腔穿孔导致空气被吸入，使呼吸疼痛且困难。需要进行减压处理。"),
        ("Air in the chest cavity makes breathing practically impossible, lethal if not treated. Decompression essential.", "胸腔积气使呼吸几乎不可能，不及时处理会致命。减压至关重要。"),
        ("Critical spinal cord rupture paralyzing your limbs from waist down. You might never walk again.", "危急性脊髓断裂，导致腰部以下肢体瘫痪。你可能再也无法行走。"),
        ("Blood viscosity slightly above normal.", "血液黏稠度略高于正常水平。"),
        ("Blood viscosity moderately above normal.", "血液黏稠度中度升高。"),
        ("Severely elevated blood viscosity, something is very wrong with your blood.", "血液黏稠度严重升高，你的血液出了大问题。"),
        ("Critically high blood viscosity, pulmonary embolism imminent.", "血液黏稠度极高，肺栓塞迫在眉睫。"),
        ("Blood viscosity slightly below normal.", "血液黏稠度略低于正常水平。"),
        ("Blood viscosity moderately below normal.", "血液黏稠度中度降低。"),
        ("Severely lowered blood viscosity, something is very wrong with your blood.", "血液黏稠度严重降低，你的血液出了大问题。"),
        ("Life-threating low blood viscosity, oxygen delivery is severely impaired.", "低黏血症危及生命，氧气输送严重受损。"),
        ("A mild brain injury causing tinnitus occasional disorientation and confusion.", "轻度脑损伤，会引起耳鸣、偶尔的定向障碍和意识混乱。"),
        ("Moderate brain trauma causing frequent disorientation and severe headaches.", "中度脑外伤，导致频繁的定向障碍和剧烈头痛。"),
        ("Catastrophic brain damage. High risk of stroke, constant disorientation and loss of motor control.", "灾难性脑损伤。中风风险高，持续定向障碍并丧失运动控制能力。"),
        ("You caught a cold. Wont take much and long to recover.", "你感冒了。不需要太多时间就能恢复。"),
        ("Your cold is getting worse. Frequent sneezing, fever, and weakness.", "你的感冒正在加重。频繁打喷嚏、发烧且虚弱无力。"),
        ("Severe flu. You're losing fluids rapidly, vomiting occasionally. Immediate care needed.", "严重流感。你正在快速流失体液，偶尔呕吐。需要立即治疗。"),
        ("Mild hemolytic reaction, slight blood pressure drop, fever, and stomach ache.", "轻度溶血反应：血压轻微下降、发烧和胃痛。"),
        ("Moderate hemolytic reaction, possible health complications, fever, pain, lowered Sp02.", "中度溶血反应：可能出现健康并发症，发烧、疼痛、血氧饱和度下降。"),
        ("Severe hemolytic reaction, critical blood pressure drop and organ disfunction, you are actively dying.", "严重溶血反应：血压急剧下降、器官功能障碍，你正在走向死亡。"),
        ("Your insides feel weird, you better take some antibiotics before it gets worse.", "你的体内感觉不对劲，最好在恶化前吃些抗生素。"),
        ("Systemic infection settled in. You feel sluggish, and warmer than usual. Using antibiotics are essential to reset infection's progress.", "全身性感染已经扎根。你感到迟钝，比平时更热。使用抗生素对于逆转感染进展至关重要。"),
        ("Systemic infection worsened. You feel even worse than before, something is wrong on the inside. Using antibiotics are essential to reset infection's progress.", "全身性感染恶化。你感觉比以前更糟，体内有什么东西不对劲。使用抗生素对于逆转感染进展至关重要。"),
        ("Systemic infection evolved into critical stage, you feel like the end is near, perhaps it is. Using antibiotics are essential to reset infection's progress.", "全身性感染已发展到危重阶段，你感觉末日将近，也许确实如此。使用抗生素对于逆转感染进展至关重要。"),
        ("Terminal systemic infection. Your body is shutting down slowly. Death is imminent. Antibiotics won't help with this one...", "终末期全身性感染。你的身体正在慢慢衰竭。\n死 亡 迫 在 眉 睫。抗生素已无能为力..."),
        ("Terminal systemic infection. Your body is shutting down slowly. Death is imminent. Antibiotics won't help with this one...\n\n<color=#ff3333>Terminal – no cure, only delay.</color>", "终末期全身性感染。你的身体正在慢慢衰竭。\n死 亡 迫 在 眉 睫。抗生素已无能为力...\n\n<color=#ff3333>终 末 期 —— 无 药 可 医 ，只 能 延 缓 。</color>"),
        ("You can't sleep. Your mind is racing, and your body refuses to rest. May or may not resolve on it's own", "你无法入睡。思绪万千，身体拒绝休息。可能会自行缓解，也可能不会。"),
        ("Your body is giving up from exhaustion. If you don't find a way to sleep, this will most likely be lethal.", "你的身体因疲惫而濒临崩溃。如果找不到办法入睡，这很可能是致命的。"),
        ("Your body is giving up from exhaustion, if you don't find a way to sleep this will most likely be lethal.", "你的身体因疲惫而濒临崩溃，如果找不到办法入睡，这很可能是致命的。"),
        ("You can't sleep. Your mind is racing, and your body refuses to rest.", "你无法入睡。思绪万千，身体拒绝休息。"),
        ("Your liver is failing causing nausea, pain, and weakness. Seek treatment.", "你的肝脏正在衰竭，导致恶心、疼痛和虚弱。尽快寻求治疗。"),
        ("Severe liver failure. Your body is yellowing, energy fading, and sickness worsening.", "严重肝衰竭。你的身体正在发黄、精力衰退、病情恶化。"),
        ("Terminal liver failure. Your organs are shutting down. Death is nearing in.", "终末期肝衰竭。你的器官正在衰竭。\n死 亡 临 近"),
        ("Your neck is broken. Moving around is agonizing and has a chance to sever your spinal cord if it's not already. Physically weaker from the neck down. Eating is painful.", "你的颈部骨折了。移动极其痛苦，如果脊髓尚未断裂，移动还有可能导致脊髓断裂。颈部以下身体虚弱。进食时感到疼痛。"),
        ("Your spine is dislocated. Moving around is painful and has a chance to sever your spinal cord if it's not already. Physically weaker from the waist down.", "你的脊柱脱位了。移动时感到疼痛，如果脊髓尚未断裂，移动还有可能导致脊髓断裂。腰部以下身体虚弱。"),
        ("Mild acidosis. You feel slightly fatigued.", "轻度酸中毒。你感到轻微疲劳。"),
        ("Moderate acidosis. Breathing is heavy, stamina depletes faster.", "中度酸中毒。呼吸沉重，体力消耗更快。"),
        ("Severe acidosis. Organs are failing, brain damage imminent.", "重度酸中毒。器官正在衰竭，脑损伤迫在眉睫。"),
        ("Mild alkalosis. Muscle twitching and slight confusion.", "轻度碱中毒。肌肉抽搐并伴有轻微意识混乱。"),
        ("Moderate alkalosis. Severe muscle cramps and breathing difficulties.", "中度碱中毒。严重肌肉痉挛和呼吸困难。"),
        ("Severe alkalosis. Seizures, brain damage, risk of death.", "重度碱中毒。癫痫发作、脑损伤，有死亡风险。"),
        ("Your DNA is slightly damaged. Immune system and regeneration are impaired.", "你的 DNA 受到轻微损伤。免疫系统和再生能力受损。"),
        ("Moderate DNA damage. Your body is struggling to repair itself.", "中度 DNA 损伤。你的身体正在艰难地自我修复。"),
        ("<i>That's strange that you didn't turn into a puddle.</i>", "<i>真奇怪，你居然没有变成一滩烂泥。</i>"),
        ("You have overdosed on a non-opioid drug. Health complications likely.", "你已过量服用一种非阿片类药物。很可能出现健康并发症。"),
        ("Irreversible myocardial infarction. The heart is failing. Death is inevitable.", "不可逆的心肌梗死。心脏正在衰竭。死亡已不可避免。"),
    };
    public static readonly (string En, string Zh)[] MoodleFormats =
    {
        ("Your insides feel weird, you better take some antibiotics before it gets worse. <color=grey>({0})</color>", "你的体内感觉不对劲，最好在恶化前吃些抗生素。<color=grey>（{0}）</color>"),
        ("Systemic infection settled in. You feel sluggish, and warmer than usual. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染已经扎根。你感到迟钝，比平时更热。使用抗生素对于逆转感染进展至关重要。<color=grey>（{0}）</color>"),
        ("Systemic infection worsened. You feel even worse than before, something is wrong on the inside. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染恶化。你感觉比以前更糟，体内有什么东西不对劲。使用抗生素对于逆转感染进展至关重要。<color=grey>（{0}）</color>"),
        ("Systemic infection evolved into critical stage, you feel like the end is near, perhaps it is. Using antibiotics are essential to reset infection's progress. <color=grey>({0})</color>", "全身性感染已发展到危重阶段，你感觉末日将近，也许确实如此。使用抗生素对于逆转感染进展至关重要。<color=grey>（{0}）</color>"),
        ("Powerful experimental drug in bloodstream. Regeneration boosted and consciousness protection acquired. <color=grey>({0})</color>", "强大的实验性药物已进入血液。再生能力提升，并获得意识保护。<color=grey>（{0}）</color>"),
        ("Feeling calm and deep relief, you wish it never ended. <color=grey>({0})</color>", "你感到平静与深沉的解脱，但愿这一切永不结束。<color=grey>（{0}）</color>"),
        ("Augmentin antibiotic active in your system, halting systemic infection progress is present and not letting one appear if not. <color=grey>({0})</color>", "奥格门汀抗生素正在你的体内发挥作用，阻止全身性感染的进展，若尚未感染则防止其出现。<color=grey>（{0}）</color>"),
        ("Massive blood clot broke off and lodged itself in massive heart artery cutting off it's blood supply. Seek treatment. Use streptokinase to break the clot. ({0}%)", "大量血栓脱落并卡在心脏大动脉中，切断了血液供应。请尽快治疗。使用链激酶溶解血栓。（{0}%）"),
        ("Moderate heart attack. Your heart is starting to necrose slowly. You NEED to break the clot somehow. ({0}%)", "中度心脏病发作。你的心脏开始缓慢坏死。你必须设法溶解血栓。（{0}%）"),
        ("Severe heart attack. Life-threatening heart necrosis imminent, immediate treatment needed. ({0}%)", "重度心脏病发作。危及生命的心肌坏死迫在眉睫，需要立即治疗。（{0}%）"),
        ("Critical myocardial infarction. Heart muscle is dying rapidly. Prepare for cardiac arrest. ({0}%)", "危重心肌梗死。心肌正在迅速坏死。为心脏骤停做好准备。（{0}%）"),
        ("Mild heart tamponade. Blood is accumulating in the pericardium. ({0}%)", "轻度心脏压塞。血液正在心包内积聚。（{0}%）"),
        ("Moderate heart tamponade. Heart is being compressed, reducing output. ({0}%)", "中度心脏压塞。心脏受到压迫，输出量减少。（{0}%）"),
        ("Severe heart tamponade. Heart output severely reduced, risk of cardiac arrest. ({0}%)", "重度心脏压塞。心脏输出量严重减少，有心脏骤停风险。（{0}%）"),
        ("Critical heart tamponade. Heart is nearly crushed, heart failure imminent. ({0}%)", "危重心脏压塞。心脏几乎被压碎，心力衰竭迫在眉睫。（{0}%）"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Remove parasites", "移除寄生虫"),
        ("Claw out the parasites feasting on this limb.", "将啃食这条肢体的寄生虫忍痛挖出。"),
        ("Hold LMB and drag over parasites to claw them out.", "按住鼠标左键并在寄生虫上拖动，将它们挖出。"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("*sneezes*", "*啊啾*"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("MedicalBrutalism: Кнопка добавлена в меню (X={0}, Y={1}, W={2}, H={3})", "MedicalBrutalism: 菜单按钮已添加（X={0}，Y={1}，W={2}，H={3}）"),
        ("<color=yellow>MedicalBrutalism: Панель меню не найдена.; {0}</color>", "<color=yellow>MedicalBrutalism: 未找到菜单面板；{0}</color>"),
        ("<color=yellow>MedicalBrutalism: Не найдена эталонная кнопка Radio/TutorialRadio.; {0}</color>", "<color=yellow>MedicalBrutalism: 未找到参考按钮 Radio/TutorialRadio；{0}</color>"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Lazarus: additional cleanup completed.", "拉撒路 : 额外清理已完成。"),
        ("Lazarus: resurrection performed. DNA healed, acid-base reset, hemolytic reduced.", "拉撒路 : 复活已执行。DNA 已修复，酸碱平衡已重置，溶血反应已减轻。"),
    };
    public static readonly (string En, string Zh)[] Fragments =
    {
        ("BldT: ", "血型："),
        ("Blood type: ", "血型："),
        ("Compatible with: ", "相容："),
        ("All types", "全部血型"),
        ("Unknown", "未知"),
    };
    public static readonly (string En, string Zh)[] LiquidKeys =
    {
        ("Amoxcilin", "阿莫西林"),
        ("Amoxcilindsc", "一种用于治疗全身感染的抗生素。服用后可重置感染进展。"),
        ("amoxcilin", "阿莫西林"),
        ("amoxcilindsc", "一种用于治疗全身感染的抗生素。服用后可重置感染进展。"),
        ("Augmentin", "奥格门汀"),
        ("Augmentindsc", "一种强力抗生素，可暂时阻断全身感染并减缓普通感染的进展。"),
        ("augmentin", "奥格门汀"),
        ("augmentindsc", "一种强力抗生素，可暂时阻断全身感染并减缓普通感染的进展。"),
        ("I4S-DS", "I4S-DS"),
        ("I4S-DSdsc", "一种强效再生化合物，必须直接注入血液。剂量约为35mL。"),
        ("i4sds", "I4S-DS"),
        ("i4sdsdsc", "一种强效再生化合物，必须直接注入血液。剂量约为35mL。"),
        ("i4s-dsdsc", "一种强效再生化合物，必须直接注入血液。剂量约为35mL。"),
        ("Koldera mix", "科尔德拉合剂"),
        ("Koldera mixdsc", "一种镇静剂，可诱发平静与解脱感。剂量约为20mL。"),
        ("kolderamix", "科尔德拉合剂"),
        ("kolderamixdsc", "一种镇静剂，可诱发平静与解脱感。剂量约为20mL。"),
        ("Blood A+", "A+ 型血液"),
        ("Blood A+dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：A+、AB+。"),
        ("Blood A-", "A- 型血液"),
        ("Blood A-dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：A-、A+、AB-、AB+。"),
        ("Blood B+", "B+ 型血液"),
        ("Blood B+dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：B+、AB+。"),
        ("Blood B-", "B- 型血液"),
        ("Blood B-dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：B-、B+、AB-、AB+。"),
        ("Blood AB+", "AB+ 型血液"),
        ("Blood AB+dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：AB+。"),
        ("Blood AB-", "AB- 型血液"),
        ("Blood AB-dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：AB-、AB+。"),
        ("Blood O+", "O+ 型血液"),
        ("Blood O+dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：O+、A+、B+、AB+。"),
        ("Blood O-", "O- 型血液"),
        ("Blood O-dsc", "黄色血液。虽然颜色在你看来正常，但这显然是生物工程过程的副作用。用于治疗低血容量。\n \n相容：全部血型。"),
    };
    public static readonly (string En, string Zh)[] BloodLiquidNames =
    {
        ("Blood A+", "A+ 型血液"),
        ("Blood A-", "A- 型血液"),
        ("Blood B+", "B+ 型血液"),
        ("Blood B-", "B- 型血液"),
        ("Blood AB+", "AB+ 型血液"),
        ("Blood AB-", "AB- 型血液"),
        ("Blood O+", "O+ 型血液"),
        ("Blood O-", "O- 型血液"),
    };
}
