internal static class ExtraDialogueTrTw
{
    public static readonly (string En, string Zh)[] Talks =
    {
        ("Maybe this will be the last one?", "也許這是最後一次了？"),
        ("Didn't think I'd get here..", "沒想到我會走到這一步.."),
        ("...One more.", "...再來一層。"),
        ("I can't fucking take any of this anymore", "我他媽再也受不了這一切了"),
        ("Can't go back now huh.. I'll die here anyway.", "現在也回不去了哈...反正我會死在這裡。"),
        ("Will this ever end?", "這會有盡頭嗎？"),
        ("Look ahead for better days.", "向前看，日子會好起來的。"),
        ("Hope this is better than the last...", "希望這層比上一層好..."),
        ("Deeper I go...", "越走越深..."),
        ("Maybe I'll find someone here?", "也許我能在這裡找到什麼人？"),
        ("Just gotta keep going.", "只能繼續走了。"),
        ("I don't have a good feeling about this.", "我對這事有種不祥的預感。"),
        ("Good thing that timer reset now.", "還好計時器重置了。"),
        ("This looks new.", "這看起來是新的。"),
        ("Hm.", "嗯。"),
        ("What's that over there?", "那邊是什麼？"),
        ("Deeper I go.", "越走越深。"),
        ("I thought this would be different.", "我本以為這裡會不一樣。"),
        ("Trader up there told me about this one.", "上面那個倖存者跟我說過這層。"),
        ("How many of those are there?", "那種東西有多少個？"),
        ("So many layers.", "這麼多地層。"),
        ("Did I hear something...?", "我是不是聽到了什麼...？"),
        ("There's gotta be some good loot here...", "這裡肯定有好東西..."),
        ("Good Expie...", "好樣的 Expie..."),
        ("They told me I'd get everything I wanted if I grabbed the thing, I better be the first one!", "他們說我只要拿到那東西就能得到想要的一切，我得做第一個！"),
        ("One layer more.", "再下一層。"),
        ("Deeper I go!", "越走越深！"),
        ("I think I'm going down, down, down, down, down!", "我覺得我要一路向下、向下、向下、向下、向下！"),
        ("Let me cook!", "讓我來發揮！"),
        ("Maybe I'll be the one to get this tech afterall.", "也許我終究會是拿到這項技術的人。"),
        ("Hoping this never ends!", "希望這一切永無止境！"),
        ("Darker yet darker.", "越來越暗，越來越暗。"),
        ("Second of many.", "眾多地層中的第二層。"),
        ("Maybe I'm getting close?", "也許我快到了？"),
        ("Great... no more sunlight...", "太好了...再也見不到陽光了..."),
        ("I am going to miss the sun...", "我會想念太陽的..."),
        ("It's... so dark... down here...", "這下面...好黑..."),
        ("The sunlight's gone, but not my spirit!", "陽光沒了，但我的精神還在！"),
        ("An interesting change in atmosphere.", "這裡的氣氛發生了有趣的變化。"),
        ("Where did I put that light source...?", "我把光源放哪了...？"),
        ("Do I have enough liquids stored?", "我存的液體夠嗎？"),
        ("I better find some water.", "我最好找點水。"),
        ("I can already feel the heat from here!", "我在這就能感覺到那股熱！"),
        ("Hopefully the later layers are cooler.", "希望後面的地層能涼快點。"),
        ("Warm...", "好熱..."),
        ("I am going to die of thirst here.", "我會渴死在這裡的。"),
        ("It's so hot down here...", "這下面好熱..."),
        ("There's... there's no water here...", "這裡...這裡沒有水..."),
        ("I am enjoying the change in scenery here.", "我很享受這裡景色的變化。"),
        ("Hot, but not too hot.", "熱，但也不算太熱。"),
        ("I will adapt to the heat, I know it!", "我會適應這高溫的，我肯定能！"),
        ("More of this?", "又是這個？"),
        ("Maybe there will be more water here?", "也許這裡會有更多水？"),
        ("Boring", "無聊"),
        ("I have a really bad feeling about these barrels.", "這些桶讓我有種很不好的預感。"),
        ("More of the same?", "又是老一套？"),
        ("Really hoping I won't get shot.", "真心希望我不會挨槍子。"),
        ("My chip feels really important here.", "我的芯片在這裡顯得特別重要。"),
        ("Maybe if I just took a nap on top of those barrels..", "也許我該在那些桶頂上打個盹..."),
        ("I could get used to the sand.", "我也許能習慣這沙子。"),
        ("Wasteland 3 Happy", "廢土3 快樂"),
        ("Did I hear something? Hopefully nothing to worry about...", "我是不是聽到了什麼？希望沒什麼好擔心的..."),
        ("Is it just me, or did it get a bit cooler?", "是我的錯覺嗎，還是這裡變涼快了？"),
        ("Are those geofruits!?", "那些是地生果嗎！？"),
        ("Oh... great... plants everywhere...", "哦...真好...到處都是植物..."),
        ("I can hear so many... things... everywhere...", "我能聽到好多...東西...到處都是..."),
        ("I'm... I'm scared.", "我...我好害怕。"),
        ("I've never heard those sounds before. They sound... serene.", "我以前從沒聽過這些聲音。它們聽起來...寧靜。"),
        ("I've never heard those sounds before. They sound... beautiful.", "我以前從沒聽過這些聲音。它們聽起來...美妙。"),
        ("There's so many plants and water everywhere!", "到處都是植物和水！"),
        ("Back to an abundance of food and water!", "又回到了食物和水充足的地方！"),
        ("Those better work..", "這些最好有用..."),
        ("Finally.", "終於。"),
        ("...........", "..........."),
        ("How long do these take to kick in?", "這些要多久才能起效？"),
        ("Those should convince me to function for a while.", "這些應該能讓我正常一陣子。"),
        ("I really let everything get this bad huh?", "我真是把一切都搞到這麼糟了啊？"),
        ("Please... please make me better...", "求求了...求求你讓我好起來..."),
        ("How LONG do these take to kick in!??", "這些到底要多久才能起效！？？"),
        ("Is this even going to work..?", "這真的會有用嗎...？"),
        ("misclick?", "點錯了？"),
        ("?", "？"),
        ("This does not taste good-", "這嚐起來不對勁-"),
        ("what.", "啥。"),
        ("Why did I-", "我為什麼要-"),
        ("I shouldn't be drinking random pills.", "我不該亂吃藥片的。"),
        ("I might be stupid.", "我可能是個傻子。"),
        ("...What?", "...啥？"),
        ("this does not taste good", "這嚐起來不對勁"),
        ("Mh.. I shouldn't be taking this right now", "嗯...我現在不該吃這個"),
        ("But it refused.", "但它拒絕了。"),
        ("Was that just a bad dream..?", "那只是一場噩夢嗎...？"),
        ("Despite all odds!", "儘管困難重重！"),
        ("Holy shit, nobody is going to believe me.", "臥槽，沒人會相信我的。"),
        ("Just keep on traveling on!", "繼續前行就好！"),
        ("I REFUSE to die in this cave", "我 絕 不 接 受 死在這個洞裡"),
        ("Hahahahaha! I'm still alive!", "哈哈哈哈！我還活著！"),
        ("I'm still here..? I'M STILL HERE!!", "我還在這...？我 還 在 這 裡 ！！"),
        ("Didn't expect anything else from myself.", "我沒指望自己還能有別的表現。"),
        ("I'll never lose, I'll never die!", "我永遠不會輸，永遠不會死！"),
        ("I'm still standing better than I ever been!", "我還站著，狀態比以往任何時候都好！"),
        ("Lookin like a true survivor! Feeling like a little kid!", "看起來像個真正的倖存者！感覺像個小孩！"),
        ("Things WILL be better soon!..", "一切很快就會好起來的！..."),
        ("Despite all odds!..", "儘管困難重重！..."),
        ("How did I-", "我怎麼-"),
        ("There's no achievement for this.", "做到這個可沒有成就獎勵。"),
        ("Waow!", "哇哦！"),
        ("I should reward myself with something after this.", "做完這個我該給自己點獎勵。"),
        ("yay!", "耶！"),
        ("Bigger better stronger!", "更大更好更強！"),
        ("Getting stronger!", "變強了！"),
        ("I'm getting better at this.", "我越來越擅長這個了。"),
        ("How do they even measure this?", "他們到底是怎麼衡量這個的？"),
        ("yay..", "耶..."),
        ("That's nice I guess.", "還行吧，大概。"),
        ("They really want us gone..", "他們真的想讓我們消失..."),
        ("Just what I needed.", "正合我意。"),
        ("I better hurry up.", "我最好快點。"),
        ("That's one more thing to worry about", "又多了一件要擔心的事"),
        ("Too long in just one place?", "在一個地方待得太久了？"),
        ("Radiation line.", "輻射線。"),
        ("Line of death and doom", "死亡與厄運之線"),
        ("There's still time.", "還有時間。"),
        ("Nothing to worry about.", "沒什麼好擔心的。"),
        ("I thought it would be closer", "我本以為它會更近的"),
        ("I really need to hurry.", "我真的得抓緊了。"),
        ("Oh that's bad", "哦，那糟了"),
        ("Is that going to...", "那會不會..."),
        ("Maybe I could just wait a little.. and....", "也許我可以再等一會兒...然後..."),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("Test custom dialogue", "【額外對話】測試自定義對話"),
        ("Dialogue", "對話"),
        ("Specific", "具體"),
        ("Generic chance", "通用概率"),
        ("JSON thingy for what expi gotta say", "設定 expi 要說的話的 JSON 內容"),
        ("The specific dialogue from a category", "某類別下的具體對話"),
        ("Chance to say a generic dialogue for the category", "說該類別通用對話的概率"),
        ("Chance to say a dialogue for neutral mood despite current mood", "無視當前心情、說中性對話的概率"),
    };
}
