using A.Multi_Mod.Chinese.Localization.Core;
namespace A.Multi_Mod.Chinese.Localization.Mods.ExtraDialogue;
internal static class ExtraDialogueTr
{
    public static readonly (string En, string Zh)[] Talks =
    {
        ("Maybe this will be the last one?", "也许这是最后一次了？"),
        ("Didn't think I'd get here..", "没想到我会走到这一步.."),
        ("...One more.", "...再来一层。"),
        ("I can't fucking take any of this anymore", "我他妈再也受不了这一切了"),
        ("Can't go back now huh.. I'll die here anyway.", "现在也回不去了哈...反正我会死在这里。"),
        ("Will this ever end?", "这会有尽头吗？"),
        ("Look ahead for better days.", "向前看，日子会好起来的。"),
        ("Hope this is better than the last...", "希望这层比上一层好..."),
        ("Deeper I go...", "越走越深..."),
        ("Maybe I'll find someone here?", "也许我能在这里找到什么人？"),
        ("Just gotta keep going.", "只能继续走了。"),
        ("I don't have a good feeling about this.", "我对这事有种不祥的预感。"),
        ("Good thing that timer reset now.", "还好计时器重置了。"),
        ("This looks new.", "这看起来是新的。"),
        ("Hm.", "嗯。"),
        ("What's that over there?", "那边是什么？"),
        ("Deeper I go.", "越走越深。"),
        ("I thought this would be different.", "我本以为这里会不一样。"),
        ("Trader up there told me about this one.", "上面那个幸存者跟我说过这层。"),
        ("How many of those are there?", "那种东西有多少个？"),
        ("So many layers.", "这么多地层。"),
        ("Did I hear something...?", "我是不是听到了什么...？"),
        ("There's gotta be some good loot here...", "这里肯定有好东西..."),
        ("Good Expie...", "好样的 Expie..."),
        ("They told me I'd get everything I wanted if I grabbed the thing, I better be the first one!", "他们说我只要拿到那东西就能得到想要的一切，我得做第一个！"),
        ("One layer more.", "再下一层。"),
        ("Deeper I go!", "越走越深！"),
        ("I think I'm going down, down, down, down, down!", "我觉得我要一路向下、向下、向下、向下、向下！"),
        ("Let me cook!", "让我来发挥！"),
        ("Maybe I'll be the one to get this tech afterall.", "也许我终究会是拿到这项技术的人。"),
        ("Hoping this never ends!", "希望这一切永无止境！"),
        ("Darker yet darker.", "越来越暗，越来越暗。"),
        ("Second of many.", "众多地层中的第二层。"),
        ("Maybe I'm getting close?", "也许我快到了？"),
        ("Great... no more sunlight...", "太好了...再也见不到阳光了..."),
        ("I am going to miss the sun...", "我会想念太阳的..."),
        ("It's... so dark... down here...", "这下面...好黑..."),
        ("The sunlight's gone, but not my spirit!", "阳光没了，但我的精神还在！"),
        ("An interesting change in atmosphere.", "这里的气氛发生了有趣的变化。"),
        ("Where did I put that light source...?", "我把光源放哪了...？"),
        ("Do I have enough liquids stored?", "我存的液体够吗？"),
        ("I better find some water.", "我最好找点水。"),
        ("I can already feel the heat from here!", "我在这就能感觉到那股热！"),
        ("Hopefully the later layers are cooler.", "希望后面的地层能凉快点。"),
        ("Warm...", "好热..."),
        ("I am going to die of thirst here.", "我会渴死在这里的。"),
        ("It's so hot down here...", "这下面好热..."),
        ("There's... there's no water here...", "这里...这里没有水..."),
        ("I am enjoying the change in scenery here.", "我很享受这里景色的变化。"),
        ("Hot, but not too hot.", "热，但也不算太热。"),
        ("I will adapt to the heat, I know it!", "我会适应这高温的，我肯定能！"),
        ("More of this?", "又是这个？"),
        ("Maybe there will be more water here?", "也许这里会有更多水？"),
        ("Boring", "无聊"),
        ("I have a really bad feeling about these barrels.", "这些桶让我有种很不好的预感。"),
        ("More of the same?", "又是老一套？"),
        ("Really hoping I won't get shot.", "真心希望我不会挨枪子。"),
        ("My chip feels really important here.", "我的芯片在这里显得特别重要。"),
        ("Maybe if I just took a nap on top of those barrels..", "也许我该在那些桶顶上打个盹..."),
        ("I could get used to the sand.", "我也许能习惯这沙子。"),
        ("Wasteland 3 Happy", "废土3 快乐"),
        ("Did I hear something? Hopefully nothing to worry about...", "我是不是听到了什么？希望没什么好担心的..."),
        ("Is it just me, or did it get a bit cooler?", "是我的错觉吗，还是这里变凉快了？"),
        ("Are those geofruits!?", "那些是地生果吗！？"),
        ("Oh... great... plants everywhere...", "哦...真好...到处都是植物..."),
        ("I can hear so many... things... everywhere...", "我能听到好多...东西...到处都是..."),
        ("I'm... I'm scared.", "我...我好害怕。"),
        ("I've never heard those sounds before. They sound... serene.", "我以前从没听过这些声音。它们听起来...宁静。"),
        ("I've never heard those sounds before. They sound... beautiful.", "我以前从没听过这些声音。它们听起来...美妙。"),
        ("There's so many plants and water everywhere!", "到处都是植物和水！"),
        ("Back to an abundance of food and water!", "又回到了食物和水充足的地方！"),
        ("Those better work..", "这些最好有用..."),
        ("Finally.", "终于。"),
        ("...........", "..........."),
        ("How long do these take to kick in?", "这些要多久才能起效？"),
        ("Those should convince me to function for a while.", "这些应该能让我正常一阵子。"),
        ("I really let everything get this bad huh?", "我真是把一切都搞到这么糟了啊？"),
        ("Please... please make me better...", "求求了...求求你让我好起来..."),
        ("How LONG do these take to kick in!??", "这些到底要多久才能起效！？？"),
        ("Is this even going to work..?", "这真的会有用吗...？"),
        ("misclick?", "点错了？"),
        ("?", "？"),
        ("This does not taste good-", "这尝起来不对劲-"),
        ("what.", "啥。"),
        ("Why did I-", "我为什么要-"),
        ("I shouldn't be drinking random pills.", "我不该乱吃药片的。"),
        ("I might be stupid.", "我可能是个傻子。"),
        ("...What?", "...啥？"),
        ("this does not taste good", "这尝起来不对劲"),
        ("Mh.. I shouldn't be taking this right now", "嗯...我现在不该吃这个"),
        ("But it refused.", "但它拒绝了。"),
        ("Was that just a bad dream..?", "那只是一场噩梦吗...？"),
        ("Despite all odds!", "尽管困难重重！"),
        ("Holy shit, nobody is going to believe me.", "卧槽，没人会相信我的。"),
        ("Just keep on traveling on!", "继续前行就好！"),
        ("I REFUSE to die in this cave", "我 绝 不 接 受 死在这个洞里"),
        ("Hahahahaha! I'm still alive!", "哈哈哈哈！我还活着！"),
        ("I'm still here..? I'M STILL HERE!!", "我还在这...？我 还 在 这 里 ！！"),
        ("Didn't expect anything else from myself.", "我没指望自己还能有别的表现。"),
        ("I'll never lose, I'll never die!", "我永远不会输，永远不会死！"),
        ("I'm still standing better than I ever been!", "我还站着，状态比以往任何时候都好！"),
        ("Lookin like a true survivor! Feeling like a little kid!", "看起来像个真正的幸存者！感觉像个小孩！"),
        ("Things WILL be better soon!..", "一切很快就会好起来的！..."),
        ("Despite all odds!..", "尽管困难重重！..."),
        ("How did I-", "我怎么-"),
        ("There's no achievement for this.", "做到这个可没有成就奖励。"),
        ("Waow!", "哇哦！"),
        ("I should reward myself with something after this.", "做完这个我该给自己点奖励。"),
        ("yay!", "耶！"),
        ("Bigger better stronger!", "更大更好更强！"),
        ("Getting stronger!", "变强了！"),
        ("I'm getting better at this.", "我越来越擅长这个了。"),
        ("How do they even measure this?", "他们到底是怎么衡量这个的？"),
        ("yay..", "耶..."),
        ("That's nice I guess.", "还行吧，大概。"),
        ("They really want us gone..", "他们真的想让我们消失..."),
        ("Just what I needed.", "正合我意。"),
        ("I better hurry up.", "我最好快点。"),
        ("That's one more thing to worry about", "又多了一件要担心的事"),
        ("Too long in just one place?", "在一个地方待得太久了？"),
        ("Radiation line.", "辐射线。"),
        ("Line of death and doom", "死亡与厄运之线"),
        ("There's still time.", "还有时间。"),
        ("Nothing to worry about.", "没什么好担心的。"),
        ("I thought it would be closer", "我本以为它会更近的"),
        ("I really need to hurry.", "我真的得抓紧了。"),
        ("Oh that's bad", "哦，那糟了"),
        ("Is that going to...", "那会不会..."),
        ("Maybe I could just wait a little.. and....", "也许我可以再等一会儿...然后..."),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("Test custom dialogue", "【额外对话】测试自定义对话"),
        ("Dialogue", "对话"),
        ("Specific", "具体"),
        ("Generic chance", "通用概率"),
        ("JSON thingy for what expi gotta say", "设定 expi 要说的话的 JSON 内容"),
        ("The specific dialogue from a category", "某类别下的具体对话"),
        ("Chance to say a generic dialogue for the category", "说该类别通用对话的概率"),
        ("Chance to say a dialogue for neutral mood despite current mood", "无视当前心情、说中性对话的概率"),
    };
}
