internal static class QoLUnknownTr
{
    public static readonly (string En, string Zh)[] ModLocaleKeys =
    {
        ("qol.keybind.quick_stash.name", "【QoL】快速收纳"),
        ("qol.keybind.quick_stash.description", "把光标下的物品快速放入可用的物品栏格子、穿戴栏或随身携带的容器中。"),
        ("qol.keybind.inventory_interaction.name", "【QoL】物品栏交互辅助键"),
        ("qol.keybind.inventory_interaction.description", "拖拽物品时按住此键，可交换容器或将兼容的工具和电池放入容器。"),
        ("qol.craft.bulk.max", "最大"),
        ("qol.craft.bulk.will_craft", "将制作：{0}"),
    };
    public static readonly (string En, string Zh)[] Settings =
    {
        ("qol.video.intensity", "亮度强度"),
        ("qol.video.intensitydsc", "控制游戏内光源的最大亮度。类似于 V6 的亮度滑块（范围更高）。"),
        ("qol.video.effects", "滤镜效果％"),
        ("qol.video.effectsdsc", "调整屏幕滤镜强度。"),
        ("qol.video.antiepilepsy", "防癫痫"),
        ("qol.video.antiepilepsydsc", "减少闪烁和频闪效果。"),
        ("qol.video.uiscale", "UI 缩放"),
        ("qol.video.uiscaledsc", "调整菜单和覆盖层界面的 UI 缩放。"),
        ("qol.video.fpscounter", "FPS 显示"),
        ("qol.video.fpscounterdsc", "显示 QoL 的 FPS 计数器覆盖层。【右上角】"),
        ("qol.game.pauseonunfocus", "失焦时暂停"),
        ("qol.game.pauseonunfocusdsc", "游戏失去焦点时自动暂停。"),
        ("qol.game.v6ilmenite", "V6 钛铁矿生成"),
        ("qol.game.v6ilmenitedsc", "让钛铁矿块在更浅的层位生成（类似 V6）。"),
        ("qol.game.skipexitanimation", "跳过退出动画"),
        ("qol.game.skipexitanimationdsc", "“放弃”时立即返回主菜单，不播放退出动画。"),
        ("qol.game.autosaveonexit", "退出时自动保存"),
        ("qol.game.autosaveonexitdsc", "使用“保存并退出”时更新自动存档。"),
        ("qol.game.deleteautosaveondeath", "死亡时删除自动存档"),
        ("qol.game.deleteautosaveondeathdsc", "进入死亡界面时删除自动存档。"),
        ("qol.game.disableradline", "禁用辐射线"),
        ("qol.game.disableradlinedsc", "阻止辐射线出现，即使已经出现。"),
        ("qol.game.disablelineofsight", "禁用未植入芯片的视线"),
        ("qol.game.disablelineofsightdsc", "在未植入芯片时禁用视线。哇哦。"),
        ("qol.game.minigameqol", "小游戏加速"),
        ("qol.game.minigameqoldsc", "加快开锁速度，并将密码锁缩短为 5-9 位。"),
        ("qol.game.skillallocation", "技能点分配"),
        ("qol.game.skillallocationdsc", "启用 QoL 的初始属性技能点分配调整。"),
        ("qol.game.skillallocation.str", "初始力量"),
        ("qol.game.skillallocation.strdsc", "设置 QoL 技能点分配补丁使用的初始属性值。"),
        ("qol.game.skillallocation.res", "初始韧性"),
        ("qol.game.skillallocation.resdsc", "设置 QoL 技能点分配补丁使用的初始属性值。"),
        ("qol.game.skillallocation.int", "初始智力"),
        ("qol.game.skillallocation.intdsc", "设置 QoL 技能点分配补丁使用的初始属性值。"),
        ("qol.game.downloadlocale", "下载语言包"),
        ("qol.game.downloadlocaledsc", "从官方语言仓库 GitHub 下载并安装语言文件。警告：在游戏内使用将重置当前层！"),
        ("qol.game.entitydensity", "单个实体密度"),
        ("qol.game.entitydensitydsc", "调整任意实体的生成倍率。"),
        ("qol.game.structuredensity", "单个结构密度"),
        ("qol.game.structuredensitydsc", "调整任意结构的生成倍率。\n\n【超过100%会有显示问题，重进设置会变成100%，不是汉化的锅，重启游戏后正常显示你调过大于100%的值】"),
        ("qol.game.layermodifierdensity", "地层随机效果频率"),
        ("qol.game.layermodifierdensitydsc", "调整地层随机效果频率。"),
        ("qol.audio.soundoverride", "单个音效覆盖"),
        ("qol.audio.soundoverridedsc", "调整任意特定音效的音量。"),
        ("qol.game.discordpresence", "Discord 状态"),
        ("qol.game.discordpresencedsc", "编辑 Discord 状态模板的详情、状态和图像提示。"),
        ("qol.input.quickstash", "【QoL】快速收纳"),
        ("qol.input.quickstashdsc", "把光标下的物品快速放入可用的物品栏格子、穿戴栏或随身携带的容器中。"),
        ("qol.input.inventoryinteraction", "【QoL】物品栏交互辅助键"),
        ("qol.input.inventoryinteractiondsc", "拖拽物品时按住此键，可交换容器或将兼容的工具和电池放入容器。"),
    };
    public static readonly (string En, string Zh)[] ModuleDefs =
    {
        ("qol_ui_discord", "Discord 状态"),
        ("qol_ui_discorddsc", "【建议关闭。无法连接DC，会刷连接错误日志】富媒体状态集成。"),
        ("qol_vis_los", "视线阴影修复"),
        ("qol_vis_losdsc", "调整视线着色器，避免在黑暗中描绘出未探明方块的轮廓。"),
        ("qol_craft_bulk", "批量制作"),
        ("qol_craft_bulkdsc", "添加批量制作和自动制作。"),
        ("qol_ui_preview", "制作预览"),
        ("qol_ui_previewdsc", "增强制作菜单中的物品预览。"),
        ("qol_ui_scroll", "容器滚轮"),
        ("qol_ui_scrolldsc", "为容器添加滚轮滚动支持。"),
        ("qol_inv_sortbtn", "整理按钮"),
        ("qol_inv_sortbtndsc", "添加用于整理的 UI 按钮。"),
        ("qol_inv_quickstash", "快速收纳"),
        ("qol_inv_quickstashdsc", "使用快速收纳快捷键立即拾取物品。"),
        ("qol_inv_liquid", "物品栏辅助键"),
        ("qol_inv_liquiddsc", "添加 Shift 交互和可配置的物品栏交互辅助键。"),
        ("qol_game_pusher", "水体物理"),
        ("qol_game_pusherdsc", "1.5 格水不再推动你。"),
        ("qol_game_soundcannon_indicator", "音波炮指示器"),
        ("qol_game_soundcannon_indicatordsc", "通过说话和箭头警示正在充能的音波炮。"),
        ("qol_game_modifiers", "地层随机效果修改器"),
        ("qol_game_modifiersdsc", "启用/禁用地层随机效果修改器调整。"),
        ("qol_audio_safety", "音频安全"),
        ("qol_audio_safetydsc", "降低高音和尖锐的声音。"),
        ("qol_save_menu", "存档菜单"),
        ("qol_save_menudsc", "在暂停菜单添加存档栏选择菜单"),
        ("qol_timer", "计时器"),
        ("qol_timerdsc", "在暂停菜单中添加计时器。"),
        ("qol_autosave", "自动保存"),
        ("qol_autosavedsc", "定期自动保存游戏。【３分钟保存一次】"),
    };
    public static readonly (string En, string Zh)[] LangNames =
    {
        ("es-419", "西班牙语（拉丁美洲）"),
        ("es-ES", "西班牙语（西班牙）"),
        ("ar-001", "阿拉伯语"),
        ("be-BY", "白俄罗斯语"),
        ("de-DE", "德语"),
        ("fi-FI", "芬兰语"),
        ("fr-FR", "法语"),
        ("id-ID", "印尼语"),
        ("it-IT", "意大利语"),
        ("ja-JP", "日语"),
        ("kk-KZ", "哈萨克语"),
        ("ko-KR", "韩语"),
        ("pl-PL", "波兰语"),
        ("pt-BR", "葡萄牙语（巴西）"),
        ("ro-RO", "罗马尼亚语"),
        ("ru-RU", "俄语"),
        ("th-TH", "泰语"),
        ("uk-UA", "乌克兰语"),
        ("vi-VN", "越南语"),
        ("ca-ES", "加泰罗尼亚语"),
        ("zh-CN", "简体中文"),
        ("zh-TW", "繁體中文"),
        ("EN", "英文"),
    };
    public static readonly (string En, string Zh)[] EntityNames =
    {
        ("animalcorpse", "动物尸体"),
        ("bananaplant", "香蕉草"),
        ("bandage", "绷带"),
        ("barbedwirefence", "铁丝网"),
        ("beartrap", "捕兽夹 老旧机械"),
        ("BloodCrystal", "生血晶"),
        ("browncap", "棕帽菇"),
        ("brownshroom", "棕蘑菇"),
        ("cactus", "仙人掌"),
        ("CaveTicks", "洞穴蜱虫 CaveTicks"),
        ("caveticks", "洞穴蜱虫 caveticks"),
        ("ceilingrye", "天花板垂麦"),
        ("coil", "线圈"),
        ("containercrate", "物资箱"),
        ("corpse", "尸体"),
        ("DigestionCrystal", "消化晶"),
        ("drillpod", "钻探舱"),
        ("drillpodbroken", "损毁的钻探舱"),
        ("dropcapsule", "空投舱"),
        ("droppings", "屎"),
        ("drybush", "枯灌木"),
        ("EmissiveCrystal", "夜明晶"),
        ("experimentflesh", "黄色肉块"),
        ("fleshchunk", "巨大肉块"),
        ("foodbox", "食物箱"),
        ("geotree", "地生树"),
        ("geyser", "间歇泉"),
        ("glowplant", "发光草"),
        ("grabberplant", "抓缠草"),
        ("internalorgans", "内脏团"),
        ("jumppad", "弹射陷阱 老旧机械"),
        ("landmine", "地雷"),
        ("leadbush", "铅灌丛"),
        ("lifepodchest", "维生舱箱子"),
        ("LifepodStart", "初始维生舱 LifepodStart"),
        ("LoreNote", "手写笔记"),
        ("medcrate", "医疗箱"),
        ("minibarrel", "迷你桶"),
        ("mushplant", "菌类植物 mushplant"),
        ("oilpipe", "废液管"),
        ("overgrowntick", "巨型蜱虫"),
        ("OxygenCrystal", "氧晶"),
        ("plantiation", "植物 plantiation"),
        ("rag", "旧布条"),
        ("ReliefCrystal", "镇痛晶"),
        ("sandrose", "沙玫瑰"),
        ("shadecrawler", "暗影爬行者"),
        ("skullcrusher", "碎颅者"),
        ("SoothingCrystal", "宁神晶"),
        ("soundcannon", "音波炮"),
        ("Special/sandvinehook", "特殊/沙藤钩"),
        ("Special/sandvinerope", "特殊/沙藤绳"),
        ("Special/wallholes", "特殊/墙洞"),
        ("spentfuel", "废弃燃料"),
        ("spikestabber", "尖刺陷阱 老旧机械"),
        ("stalactite", "钟乳石"),
        ("stalagmite", "石笋"),
        ("stoneplant", "石生花"),
        ("thornbackelder", "棘背兽长老"),
        ("thornbackyoung", "棘背兽"),
        ("TurbulentCrystal", "激荡晶"),
        ("turret", "自动炮塔"),
        ("wallbiter", "巨噬沙行兽"),
        ("wallflower", "墙花 wallflower"),
    };
    public static readonly (string En, string Zh)[] StructureNames =
    {
        ("BioContainer", "生物容器 BioContainer"),
        ("BrickLoot", "砖块堆"),
        ("CratePod", "板条箱舱"),
        ("Lifepod", "维生舱"),
        ("LifepodCollapsed", "倒塌的维生舱"),
        ("MedicalBuilding", "医疗建筑 MedicalBuilding"),
        ("MiniPod", "迷你舱"),
        ("SteelBridge", "钢桥 SteelBridge"),
        ("SteelThing", "钢制物 SteelThing"),
        ("TutorialStructure", "训练建筑 TutorialStructure"),
        ("WoodCross", "木十字架 WoodCross"),
        ("WoodHorizontal", "水平木梁 WoodHorizontal"),
    };
    public static readonly (string En, string Zh)[] ModifierNames =
    {
        ("Cold", "寒冷"),
        ("Dry", "干燥"),
        ("Flooded", "积水"),
        ("Foggy", "多雾"),
        ("Freezing", "严寒"),
        ("Hot", "炎热"),
        ("Infested", "虫害"),
        ("Ionized", "辐射"),
        ("Rainy", "多雨"),
        ("Unchipped", "耀斑侵袭 Unchipped"),
        ("Warm", "温暖"),
    };
    public static readonly (string En, string Zh)[] PreRun =
    {
        ("clicktocontinue", "点击继续...\n或点击 鼠标右键/Esc 立即关闭。"),
    };
    public static readonly (string En, string Zh)[] Exact =
    {
        ("<color=orange>Client-side MP spawn forwarding does not support random positions.</color>", "<color=orange>客户端多人生成转发不支持随机位置。</color>"),
        ("<color=orange>Cannot resolve player position right now.</color>", "<color=orange>暂时无法获取玩家位置。</color>"),
        ("<color=orange>Cannot resolve cursor position right now.</color>", "<color=orange>暂时无法获取光标位置。</color>"),
        ("Unknown", "未知"),
        ("Cannot resolve player position right now.", "暂时无法获取玩家位置。"),
        ("Cannot resolve cursor position right now.", "暂时无法获取光标位置。"),
        ("Client-side MP spawn forwarding does not support random positions.", "客户端多人生成转发不支持随机位置。"),
    };
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Cannot save while dead!", "死亡时无法保存！"),
        ("Cannot save while ragdolled!", "布娃娃状态时无法保存！"),
        ("Multiplayer save failed!", "多人联机保存失败！"),
        ("Client snapshot save failed!", "客户端快照保存失败！"),
        ("Save failed!", "保存失败！"),
        ("Slot is empty!", "存档为空！"),
        ("Clients can only restore MP item snapshots.", "客户端只能恢复多人物品快照。"),
        ("Disable multiplayer before loading QoL saves.", "加载 QoL 存档前请禁用多人模式。"),
        ("Host is loading a save. Please rejoin after the load finishes.", "主机正在加载存档，请在加载完成后重新加入。"),
        ("Inventory restore failed.", "物品栏恢复失败。"),
        ("Inventory restored.", "物品栏已恢复。"),
        ("Inventory restore failed on host.", "主机端物品栏恢复失败。"),
        ("Spawn request failed on host.", "主机端生成请求失败。"),
        ("Spawn request completed.", "生成请求已完成。"),
        ("Spawn request failed.", "生成请求失败。"),
        ("Host has sv_cheats or client commands disabled.", "主机已禁用 sv_cheats 或客户端命令。"),
        ("Spawn command was empty.", "生成命令为空。"),
        ("Only spawn commands can be forwarded.", "只能转发生成命令。"),
        ("Healed player on host.", "已在主机端治疗玩家。"),
        ("Heal request failed on host.", "主机端治疗请求失败。"),
        ("Heal request completed.", "治疗请求已完成。"),
        ("Heal request failed.", "治疗请求失败。"),
        ("Host could not find your player body.", "主机无法找到你的玩家身体。"),
        ("Host could not find your player name.", "主机无法找到你的玩家名称。"),
        ("Host could not find your body.", "主机无法找到你的身体。"),
        ("Host player body is unavailable for player position.", "主机玩家身体不可用，无法获取玩家位置。"),
        ("Host camera is unavailable for cursor position.", "主机摄像机不可用，无法获取光标位置。"),
        ("Inventory snapshot was empty.", "物品栏快照为空。"),
        ("This slot has no client inventory snapshot.", "此存档没有客户端物品栏快照。"),
        ("Client inventory snapshot is empty.", "客户端物品栏快照为空。"),
        ("Could not send inventory restore request. The host needs QoL and client commands enabled.", "无法发送物品栏恢复请求。主机需启用 QoL 和客户端命令。"),
        ("Client saves can only be loaded in a singleplayer game", "客户端存档只能在单人游戏中加载"),
        ("No player body found.", "未找到玩家身体。"),
        ("QoL Unknown imported singleplayer slot for Krokosha MP host", "QoL Unknown 已为 Krokosha 多人主机导入单人槽位。"),
        ("Restored inventory from QoL slot.", "已从 QoL 存档恢复物品栏。"),
        ("MP save bundle is missing or corrupt.", "多人存档包缺失或损坏。"),
        ("Could not stage QoL save for multiplayer host.", "无法为多人主机暂存 QoL 存档。"),
        ("Client reconnect clicked!", "客户端重连已点击！"),
        ("Client Connect clicked!", "客户端连接已点击！"),
        ("No active world on host.", "主机上没有活跃的世界。"),
        ("Discord Presence editor unavailable: canvas not found.", "Discord 状态编辑器不可用：找不到画布。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("D-Pad:", "十字键 : "),
        ("<color=orange>No active world! :p</color>", "<color=orange>没有活跃的世界！:p</color>"),
        ("Always skipping the lore now...", "现在总是会跳过剧情..."),
        ("Always showing the lore now.", "现在总是会显示剧情"),
        ("Usage: disablelayermodifiers [true/false]", "用法 : disablelayermodifiers [true/false]"),
        ("<color=orange>Failed to send spawn request to host.</color>", "<color=orange>向主机转发生成请求失败。</color>"),
        ("<color=grey>Forwarded spawn request to host.</color>", "<color=grey>已向主机转发生成请求。</color>"),
        ("Experimental features enabled. Reopen the settings menu to refresh experimental options.", "已启用实验性功能。重新打开设置菜单以刷新实验选项。"),
        ("Experimental features disabled. Reopen the settings menu to refresh experimental options.", "已禁用实验性功能。重新打开设置菜单以刷新实验选项。"),
        ("No start commands set.", "没有设置启动命令。"),
        ("Cleared start commands!", "已清除启动命令！"),
        ("Running your startup commands!...", "正在执行你的启动命令！..."),
        ("Saved the game and quit to menu.", "已保存游戏并返回主菜单。"),
        ("<color=yellow>Autosaved game.</color>", "<color=yellow>已自动保存游戏。</color>"),
        ("No custom sound overrides set.", "没有自定义音效覆盖。"),
        ("Cleared all custom sound overrides.", "已清除所有自定义音效覆盖。"),
        ("Missing sound name argument.", "缺少音效名称参数。"),
        ("Missing volume argument. Usage: noise change [name] [volume]", "缺少音量参数。用法 : noise change [名称] [音量]"),
        ("Invalid volume number.", "无效的音量数值。"),
        ("Current Sound Overrides", "当前音效覆盖"),
        ("<color=green>Controller bindings reset to defaults</color>", "<color=green>控制器按键已重置为默认</color>"),
        ("<color=orange>Controller manager not initialized</color>", "<color=orange>控制器管理器未初始化</color>"),
        ("<color=orange>Usage: controllerbind <button> <action> OR controllerbind reset/actions/info</color>", "<color=orange>用法 : controllerbind <按键> <动作> 或 controllerbind reset/actions/info</color>"),
        ("<color=orange>Too many arguments</color>", "<color=orange>参数过多</color>"),
        ("Use: controllerbind <button> <action>", "用法 : controllerbind <按键> <动作>"),
        ("Face Buttons:", "正面按键 : "),
        ("Triggers:", "扳机键 : "),
        ("Bumpers:", "肩键 : "),
        ("Stick Press:", "摇杆按下 : "),
        ("Special:", "特殊 : "),
        ("Valid actions: ", "有效动作 : "),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("button", "按钮"),
        ("action", "动作"),
        ("string action", "文本 操作"),
        ("string sound", "文本 音效"),
        ("float volume", "浮点 音量"),
        ("bool disable", "真假"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Shows current loot% and traps% multipliers.", "【QoL】显示当前战利品和陷阱倍率。"),
        ("Toggles always skipping the fullscreen intro lore.", "【QoL】切换是否总是跳过全屏开场剧情。"),
        ("Toggles experimental QoL features.", "【QoL】切换 QoL 实验性功能。"),
        ("Disables/enables all layer modifiers.", "【QoL】禁用/启用所有地层随机效果。"),
        ("Set or view controller button bindings", "【QoL】设置或查看控制器按键绑定"),
        ("Button name (A, B, X, Y, DpadUp, etc.)", "按键名称（A、B、X、Y、DpadUp 等）"),
        ("Action to bind (jump, attack, craft, etc.)", "要绑定的动作（jump、attack、craft 等）"),
        ("Sets commands to execute on a fresh run (split by ;). Usage: runatstart [commands] OR runatstart clear", "【QoL】设置在新开一局时自动执行的命令（用 ; 分隔）。用法 : runatstart [命令] 或 runatstart clear"),
        ("Manage sound volume overrides.", "【QoL】管理音效音量覆盖。"),
        ("Name of the sound file", "音效文件名称"),
        ("New volume (0.0 - 1.2 or 0 - 120)", "新音量（0.0到1.2 或 0到120）"),
        ("True to set all to 0%, False to set to default", "设为 true 将所有倍率设为 0%，设为 false 恢复默认"),
        ("Displays the current world seed.", "【QoL】显示当前世界种子。"),
        ("!! NOT RECOMMENDED !!. Instantly saves the game and exits to the main menu as per vanilla. Loading the save will put you at the beginning of the current layer.", "【QoL 表示】！！不推荐！！立即保存游戏并按原版行为返回主菜单。读取存档会让你回到当前地层的起点。"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("点击继续...\n按ESC跳过", "点击继续...\n或点击 鼠标右键/Esc 立即关闭。"),
        ("Seed", "种子"),
        ("Locked", "已锁定"),
        ("Mods", "模组"),
        ("Play", "播放"),
        ("Edit", "编辑"),
        ("Close", "关闭"),
        ("Reset", "重置"),
        ("Apply", "应用"),
        ("SAVE SLOTS", "存 档 栏"),
        ("Continue", "继续前进"),
        ("Continue MP Host", "继续前进 多人主机"),
        ("MP Client Save", "多人客户端 存档"),
        ("Start a deterministic seeded run", "开始确定性种子对局"),
        ("Corrupt", "损坏"),
        ("<color=#66ccff>[MP Host]</color> ", "<color=#66ccff>[多人主机]</color> "),
        ("<color=#66ccff>[MP Client]</color> ", "<color=#66ccff>[多人客户端]</color> "),
        ("<color=#66ccff>[MP]</color> ", "<color=#66ccff>[多人]</color> "),
        ("<color=yellow>[ID: {0}]</color> ", "<color=yellow>[ID: {0}]</color> "),
        ("OPTION\nMENU", "选项\n菜单"),
        ("QoL\nSettings", "QoL\n设置"),
        ("Show Options", "显示选项"),
        ("Update available! click to open Nexus page", "有新版本！点击打开Ｎ网页面"),
        ("<color=#54a5dc>Please restart the game for QoL module settings changes to take effect!", "<color=#54a5dc>请重启游戏，QoL 模块设置更改才能生效！"),
        ("Made by Orsoniks\nLoading art by Wickflix\nMenu art by @GatoCataco ~", "作者：Orsoniks\n加载美术：Wickflix\n菜单美术：@GatoCataco～"),
        (" <color=#FFEA00>\nPlease restart your game for changes to take effect!", " <color=#FFEA00>\n请重启游戏以使更改生效！"),
        ("Restart Apply", "重启＆应用"),
        ("Restart Game", "重启游戏"),
        ("Open Nexus", "打开Ｎ网"),
        ("Custom settings", "自定义设置"),
        ("Type to rename", "输入以重命名"),
        ("Right click to delete", "右键删除"),
        ("Select...", "选择..."),
        ("Waiting...", "稍后..."),
        ("Fetching List...", "获取列表..."),
        ("Connection Error", "连接错误"),
        ("Failed to reach GitHub", "无法\n连接 GitHub"),
        ("Select Language...", "选择语言..."),
        ("Discord Presence", "Discord 状态"),
        ("Details", "详情"),
        ("Variables", "变量"),
        ("Template text...", "模板文本..."),
        ("State rules", "状态规则"),
        ("Other fields", "其他字段"),
        ("Large tooltip", "大图提示"),
        ("Small tooltip", "小图提示"),
        ("Live preview", "实时预览"),
        ("Reset State", "重置状态"),
        ("Reset All", "全部重置"),
        ("Preview", "预览"),
        ("Applied Discord Presence templates.", "已应用 Discord 状态模板。"),
        ("Reset all Discord Presence templates.", "已重置全部 Discord 状态模板。"),
        ("Presence context is unavailable.", "状态上下文不可用。"),
        ("Crafting", "制作"),
        ("<b>IGT:</b>", "<b>游玩时间</b>"),
        ("<b>RTA:</b>", "<b>运行时间</b>"),
        ("Left Click", "左键单击"),
        ("Right Click", "右键单击"),
        ("Middle Click", "中键单击"),
        ("Sorts your inventory to minimize weight use", "整理物品栏以最小化负重"),
        ("Sleep, those little slices of death. How I loathe them.", "“睡眠，那一段段小小的死亡，我是何其憎恶。”"),
        ("Also try Custom Structures!", "“也试试 Custom Structures 吧！”"),
        ("Also try CUCoreLib!", "“也试试 CUCoreLib 吧！”"),
        ("Those burial-clouds that lower victorious soon to devour all", "“那低垂的葬云，以凯旋之姿迫近，转瞬将吞噬万物”"),
        ("This shall be a story like none other before.", "“这将是一个前无古人的故事。”"),
        ("I had planned my life's endeavor", "“我曾为一生的事业精心筹谋”"),
        ("but my life had plans for me.", "“可我的人生对我另有安排。”"),
        ("I am lost but not forever,", "“我虽迷失，却非永世，”"),
        ("I am where I am meant to be.", "“我正身处命定之地。”"),
        ("Imagine now unbearably, how unutterly cold the universe would be if one is all alone.", "“此刻试想，那不堪忍受、无以言表的寒冷——若你孤身一人，宇宙便是如此。”"),
        ("There's really no hard limit to how long these pause menu names can be and to be quite honest I'm rather curious to see how far we can go. Adolphus W. Green (1844–1917) started as the Principal of the Groton School in 1864. By 1865, he became second assistant librarian - oh wait nevermind there' a limit.", "“其实暂停菜单的文字并没有真正的硬性长度限制，老实说，我挺好奇究竟能写多长。阿道弗斯·W·格林（1844–1917）于 1864 年开始担任格罗顿学校校长，到 1865 年，他当上了第二助理图书管理员——哦等等，算了，看来还是有限制的。”"),
        ("Astralsounds", "星籁"),
        ("Everything will be okay.", "“一切都会没事的。”"),
        ("Remember to do an act of good today.", "“记得今天要做一件善事。”"),
        ("Pause and hydrate. It'll help.", "“暂停一下，喝点水。会有帮助的。”"),
        ("Don't forget to eat, now...", "“别忘了吃点东西，好吗...”"),
        ("Little one.", "“小家伙。”"),
        ("You're almost there. Just a couple more steps.", "“你就快到了，再多走几步。”"),
        ("To the north, a new future.", "“向北方去，一片崭新的未来。”"),
        ("To reach the antechamber.", "“只为抵达前厅。”"),
        ("To remember, to forget. To forget, to remember.", "“去铭记，去遗忘。去遗忘，再去铭记。”"),
        ("Take care of yourself. You deserve it.", "“照顾好自己，你值得被善待。”"),
        ("From now on you’re going to have to think. There’s a reason why we’re born with brains in our heads, not rocks.", "“从现在起，你可得动脑子了。我们生来脑袋里装的是大脑而非石头，并非毫无缘由。”"),
        ("Remember the past, live in the present, and fear not the future, for it doesn't exist and never shall. There is only now", "“铭记过往，活在当下，莫惧未来，因为未来并不存在，也永不存在。只有现在。”"),
        ("Change itself is nether good nor bad, but knowledge is always useful.", "“变化本身非善非恶，但知识永远有益。”"),
        ("Then I shall keep myself, to myself.", "“那我便将自我守住，只交予自身。”"),
        ("Do questions not taste best in the absence of answers?", "“问题不正是因为没有答案时，才最令人回味吗？”"),
        ("In the silent, hidden spaces where we watch and wait, we see the artistry of all that is.", "“在那寂静隐秘的角落，我们守望等待，得见万物的匠心。”"),
        ("When a being dies, a world dies.", "“一命逝去，一界随之消亡。”"),
        ("Never is a very, very long time.", "“‘永远’，是一段很久、很久的时间。”"),
        ("We're all just stories in the end, so let's make ours a good one.", "“到头来，我们都只不过是故事罢了。既然如此，就让我们的故事精彩一些吧。”"),
        ("You cannot retreat from this fight. Stand with pride and fight with honor.", "“此战无路可退，骄傲地挺立，光荣地战斗吧。”"),
        ("...to have turned the wheel and approached genius...", "“...转动了命运之轮，向天才之境靠近...”"),
        ("We are creatures of habit.", "“我们是习惯的造物。”"),
        ("Fear is a good servant, but a poor leader.", "“恐惧是个好仆从，却是个糟糕的主宰。”"),
        ("Wisdom is neither a knowing nor a finding but rather a seeking.", "“智慧并非已知，亦非已得，而是无尽的追寻。”"),
        ("A box without hinges, key, or lid, yet golden treasure inside is hid.", "“无铰无钥也无盖，内里却藏金色宝藏。”"),
        ("One learns more from defeat than victory. Therefore, fear the general that has never won a battle.", "“人从失败中学到的，远多于从胜利中学到的。因此，要畏惧那未尝一胜的将军。”"),
        ("The price of entry to being good at something is to suck at that something.", "“把一件事做得糟糕透顶，正是擅长它的入场券。”"),
        ("Death is only the end if you think the story is about you.", "“如果你认为这故事只关乎你时，死亡才是终点。”"),
        ("If you bring only these quotes, then it will be bereft of the meaning and lesson. You must seek these lessons and live them.", "“若你只带来这些语录，便会失了其中的意义与教诲。你须得亲自求索，并亲身践行。”"),
        ("The gods envy us, because of our mortality. Death is what makes everything worthwhile and beautiful.", "“众神因我们终有一死而嫉妒我们。正是死亡，赋予万物意义与至美。”"),
        ("When they speak, they shake the very earth.", "“他们开口之时，大地也为之震颤。”"),
        ("Don't be afraid. Jump.", "“别怕，跳吧。”"),
        ("Un du evarínya ono varda.", "“願星辰守護你。”"),
        ("In the Main Menu", "在主菜单"),
        ("Main Menu", "主菜单"),
        ("Preparing to descend...", "准备下潜..."),
        ("Depth: Unknown..", "深度：未知..."),
        ("Died in tutorial", "死于教程"),
        ("In the tutorial", "在教程中"),
        ("Being tranquilized.!", "正在被麻醉！"),
        ("Currently attempting the basics course", "正在尝试基础课程"),
        ("Currently attempting the first aid course", "正在尝试急救课程"),
        ("Currently attempting the crafting course", "正在尝试制作课程"),
        ("In the sandbox", "在沙盒中"),
        ("Cardiac arrest. No pulse detected.", "心脏骤停。检测不到脉搏。"),
        ("Chipless. Status unknown.", "未植入芯片。状态未知。"),
        ("RUNNING FROM AN ELDER THORNBACK!!", "正在逃离老年刺背兽！！"),
        (" .. Hollow .. ", " .. 空洞 .. "),
        ("Feeling hungry", "感到饥饿"),
        ("Feeling peckish", "有点饿"),
        ("Parched of water!", "口渴难耐！"),
        ("Feeling very thirsty", "非常口渴"),
        ("Feeling a bit thirsty", "有点口渴"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("..what's that noise?", "..有什么怪响？"),
    };
    public static readonly (string En, string Zh)[] Formats =
    {
        ("<color=orange>\"{0}\" is not a valid position for spawn forwarding.</color>", "<color=orange>「{0}」不是转发生成命令的有效位置。</color>"),
        ("\"{0}\" became craftable after waiting.", "等待后「{0}」变为可制作。"),
        ("\"{0}\" never became craftable.", "「{0}」始终未能变为可制作。"),
        ("Waiting for \"{0}\" to become craftable.", "正在等待「{0}」变为可制作。"),
        ("Waiting for final recipe \"{0}\" to become craftable.", "正在等待最终配方「{0}」变为可制作。"),
        ("\"{0}\" is not a valid position for spawn forwarding.", "「{0}」不是有效的生成转发位置。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("Saved MP host bundle to Slot {0}", "已将多人主机存档包保存到存档 {0}"),
        ("Saved MP client snapshot to Slot {0}", "已将多人客户端快照保存到存档 {0}"),
        ("Saved to Slot {0}", "已保存到存档 {0}"),
        ("Returning {0} client{1} to the main menu before host save load.", "在主机进入存档前，正在将 {0} 名联机玩家返回至主菜单。"),
        ("\"{0}\" is not a valid condition value.", "「{0}」不是有效的耐久值。"),
        ("\"{0}\" is not a valid amount value.", "「{0}」不是有效的数量值。"),
        ("Could not find entity \"{0}\".", "找不到实体「{0}」。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("<color=green>Loot: {0}% | Traps: {1}%</color> <color=grey>(layer: {2}%/{3}%)</color>", "<color=green>战利品 : {0}% | 陷阱 : {1}%</color> <color=grey>（地层 : {2}%/{3}%）</color>"),
        ("Current start commands: {0}", "当前启动命令 : {0}"),
        ("Saved start commands: {0}", "已保存启动命令 : {0}"),
        ("<color=green>Bound {0} to {1}</color>", "<color=green>已将 {0} 绑定到 {1}</color>"),
        ("<color=red>Failed to bind {0} to {1}</color>", "<color=red>绑定 {0} 到 {1} 失败</color>"),
        ("Unknown action '{0}'. Use change, list, remove, or clear.", "未知操作「{0}」。请使用 change、list、remove 或 clear。"),
        ("Removed override for \"{0}\".", "已移除「{0}」的覆盖。"),
        ("No override found for \"{0}\".", "没有找到「{0}」的覆盖。"),
        ("Set volume for \"{0}\" to {1} ({2}%).", "已将「{0}」的音量设为 {1}（{2}%）。"),
        (" - \"{0}\": {1}%", " - 「{0}」 : {1}%"),
        ("<color=green>Seed: {0} ({1})</color>", "<color=green>种子 : {0}（{1}）</color>"),
        ("X: {0} px from the left, Y : {1} px from the top", "X : 距左侧 {0} 像素，Y : 距顶部 {1} 像素"),
        ("Controller source: {0} | Device: {1} | Profile: {2} | Active: {3}", "控制器源 : {0} | 设备 : {1} | 配置 : {2} | 活动 : {3}"),
        ("<color=red>[LocaleDownloader] Failed to fetch list: {0}", "<color=red>[LocaleDownloader] 语言列表获取失败 : {0}"),
        ("<color=red>[LocaleDownloader] Parse error: {0}", "<color=red>[LocaleDownloader] 语言列表解析错误 : {0}"),
        ("<color=red>[LocaleDownloader] Failed download: {0}", "<color=red>[LocaleDownloader] 语言下载失败 : {0}"),
        ("<color=red>[LocaleDownloader] Write error: {0}", "<color=red>[LocaleDownloader] 语言文件写入错误 : {0}"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("No expedition data in Slot {0}.", "存档 {0} 中没有探索数据。"),
        ("Resume your {0} expedition with Experiment #{1}.\n\nSeed: {2}\nIn-game time: {3}", "继续你与 Experiment #{1} 的 {0} 探险。\n\n种子：{2}\n游戏时间：{3}"),
        ("<b>Slot {0}{1}</b> {2}<size=70%>\n{3} | {4} run time</size>\n<size=60%><color=grey>{5}</color></size>", "<b>存档 {0}{1}</b> {2}<size=70%>\n{3} | 游玩时间 {4}</size>\n<size=60%><color=grey>{5}</color></size>"),
        ("<b>Slot {0}</b>\n<size=70%><color=grey>Empty</color></size>", "<b>存档 {0}</b>\n<size=70%><color=grey>空</color></size>"),
        ("{0}m deep", "深度 {0} 米"),
        ("Custom Settings Preset {0}", "自定义设置预设 {0}"),
        ("Downloading {0}...", "正在\n下载 {0}..."),
        ("Installed {0}", "已安装 {0}"),
        ("{0} (Installed)", "{0}（已安装）"),
        ("Crafting {0}x", "制作 ｘ{0}"),
        ("QoL is out of date! ({0} -> {1})\n(Click here to open the github release)", "QoL 已过时！（{0} → {1}）\n（点此打开 GitHub 发布页）"),
        ("Died at {0}m", "死于 {0} 米深"),
        ("Descending the {0} ({1}m)", "正在下潜至 {0}（{1} 米）"),
        ("Fibrillation crisis! {0}% severity.", "纤颤危机！严重度 {0}%。"),
        ("Fibrillation worsening... ({0}% severity).", "纤颤恶化...（严重度 {0}%）。"),
        ("Experiencing a stroke. ({0}% severity).", "正在中风。（严重度 {0}%）。"),
        ("Profound hypotension! {0} mmHg.", "重度低血压！{0} 毫米汞柱。"),
        ("Hypertensive crisis! {0} mmHg.", "高血压危象！{0} 毫米汞柱。"),
        ("Severe hypertension! {0} mmHg.", "重度高血压！{0} 毫米汞柱。"),
        ("Lung failure! {0} thorax health.", "肺衰竭！胸腔健康 {0}。"),
        ("In septic shock! {0}% severity.", "感染性休克！严重度 {0}%。"),
        ("In shock from {0}% pain!", "因 {0}% 疼痛而休克！"),
        ("Taking a nap... {0}% energy..", "正在小憩..体力 {0}%..."),
        ("Comatose! {0}% brain health.", "昏迷！脑部健康 {0}%。"),
        ("Cardiac Arrest!! {0}% brain health.", "心脏骤停！！脑部健康 {0}%。"),
        ("Hypotensive! {0} mmHg.", "低血压！{0} 毫米汞柱。"),
        ("Bleeding Out!! {0}L/m bleed rate.", "大出血！！出血速率 {0} 升/分钟。"),
        ("Drowning!! {0}% oxygen remaining.", "溺水！！剩余氧气 {0}%。"),
        ("Hypovolemic! {0}L blood amount.", "血容量不足！血量 {0} 升。"),
        ("Irradiated! {0}% severity.", "受到辐射！严重度 {0}%。"),
        ("Hypothermic! {0}C body temp.", "体温过低！体温 {0}℃。"),
        ("Heatstroke! {0}C body temp.", "中暑！体温 {0}℃。"),
        ("Starving! {0}% fullness.", "快饿死了！饱腹度 {0}%。"),
        ("Dessicated! {0}% thirst.", "脱水！口渴度 {0}%。"),
        ("Treating {0}L/m of bleeding...", "正在处理 {0} 升/分钟的出血..."),
        ("In {0}% pain. Ouch!", "疼痛 {0}%。哎哟！"),
        ("{0}% exhausted... phew..", "疲惫 {0}%...呼..."),
        ("Healing a {0} fracture...", "正在愈合{0}的骨折..."),
        ("Removing shrapnel from the {0}...", "正在从{0}取出弹片..."),
        ("Tending a {0} dislocation...", "正在处理{0}的脱臼..."),
        ("Feeling {0} sick. ({1}% sickness)", "感觉{0}不适。（疾病 {1}%）"),
        ("{0} brain damage! ({1}% brain health)", "{0}脑损伤！（脑部健康 {1}%）"),
        ("Feeling {0}... ({1} happiness)", "感觉{0}...（心情 {1}）"),
        ("{0}.. ({1} hunger)", "{0}...（饥饿值 {1}）"),
        ("{0}.. ({1} thirst)", "{0}...（口渴值 {1}）"),
        ("Feeling {0}{1} ({2} happiness)", "感觉{0}{1}（心情 {2}）"),
        ("Feeling {0}. ({1} happiness)", "感觉{0}。（心情 {1}）"),
        ("A limb is {0} infected! ({1}% infection)", "一个肢体正在{0}感染！（感染 {1}%）"),
        ("{0} limbs are {1} infected! ({2}% infection)", "{0} 个肢体正在{1}感染！（感染 {2}%）"),
        ("State rule error: {0}", "状态规则错误：{0}"),
    };
    public static readonly (string En, string Zh)[] ModRowFragments =
    {
        ("Queued: Disable", "待执行：禁用"),
        ("Queued: Enable", "待执行：启用"),
        ("Disabled", "已禁用"),
        ("Enabled", "已启用"),
        (" Nexus version)", " Ｎ网版本)"),
    };
    public static readonly (string En, string Zh)[] ConsoleFragments =
    {
        ("... (", "...（"),
        (" more)", " 更多）"),
    };
    public static readonly (string En, string Zh)[] DiscordValues =
    {
        ("upper right arm", "右上臂"),
        ("Parched of water!", "口渴难耐！"),
        ("Feeling very thirsty", "非常口渴"),
        ("Feeling a bit thirsty", "有点口渴"),
        ("Feeling hungry", "感到饥饿"),
        ("Feeling peckish", "有点饿"),
        ("Near-starving", "快饿死了"),
        (" and well-fed.", "且吃得很饱。"),
        (" and satisfied.", "且很满足。"),
        ("upper left arm", "左上臂"),
        ("right forearm", "右前臂"),
        ("left forearm", "左前臂"),
        ("right shins", "右小腿"),
        ("left shins", "左小腿"),
        ("right thigh", "右大腿"),
        ("left thigh", "左大腿"),
        ("right hand", "右手"),
        ("left hand", "左手"),
        ("right foot", "右脚"),
        ("left foot", "左脚"),
        ("extremely", "极度"),
        ("depressed", "抑郁"),
        ("suicidal", "想自杀"),
        ("ecstatic", "欣喜若狂"),
        ("severely", "严重"),
        ("Moderate", "中度"),
        ("Severe", "重度"),
        ("content", "满足"),
        ("abdomen", "腹部"),
        ("mildly", "轻微"),
        ("thorax", "胸腔"),
        ("badly", "严重"),
        ("happy", "开心"),
        ("Minor", "轻度"),
        ("a bit", "有点"),
        ("very", "非常"),
        ("down", "低落"),
        ("head", "头部"),
        ("Presence context is unavailable.", "状态上下文不可用。"),
    };
    public static readonly (string En, string Zh)[] SlotFragments =
    {
        ("[MP Client]", "[多人客户端]"),
        ("[MP Host]", "[多人主机]"),
        ("m Deep", "米深"),
        ("m deep", "米深"),
        ("Unknown", "未知"),
        ("[MP]", "[多人]"),
    };
    public static readonly (string En, string Zh)[] TooltipFragments =
    {
        ("Update available! click to open Nexus page", "有新版本可用！点击打开Ｎ网页面"),
    };
    public static readonly (string En, string Zh)[] DepthUnit =
    {
        ("m", "米"),
    };
}
