internal static class QoLUnknownTrTw
{
    public static readonly (string En, string Zh)[] ModLocaleKeys =
    {
        ("qol.keybind.quick_stash.name", "【QoL】快速收納"),
        ("qol.keybind.quick_stash.description", "把光標下的物品快速放入可用的物品欄格子、穿戴欄或隨身攜帶的容器中。"),
        ("qol.keybind.inventory_interaction.name", "【QoL】物品欄交互輔助鍵"),
        ("qol.keybind.inventory_interaction.description", "拖拽物品時按住此鍵，可交換容器或將兼容的工具和電池放入容器。"),
        ("qol.craft.bulk.max", "最大"),
        ("qol.craft.bulk.will_craft", "將製作：{0}"),
    };
    public static readonly (string En, string Zh)[] Settings =
    {
        ("qol.video.intensity", "亮度強度"),
        ("qol.video.intensitydsc", "控制遊戲內光源的最大亮度。類似於 V6 的亮度滑塊（範圍更高）。"),
        ("qol.video.effects", "濾鏡效果％"),
        ("qol.video.effectsdsc", "調整屏幕濾鏡強度。"),
        ("qol.video.antiepilepsy", "防癲癇"),
        ("qol.video.antiepilepsydsc", "減少閃爍和頻閃效果。"),
        ("qol.video.uiscale", "UI 縮放"),
        ("qol.video.uiscaledsc", "調整菜單和覆蓋層界面的 UI 縮放。"),
        ("qol.video.fpscounter", "FPS 顯示"),
        ("qol.video.fpscounterdsc", "顯示 QoL 的 FPS 計數器覆蓋層。【右上角】"),
        ("qol.game.pauseonunfocus", "失焦時暫停"),
        ("qol.game.pauseonunfocusdsc", "遊戲失去焦點時自動暫停。"),
        ("qol.game.v6ilmenite", "V6 鈦鐵礦生成"),
        ("qol.game.v6ilmenitedsc", "讓鈦鐵礦塊在更淺的層位生成（類似 V6）。"),
        ("qol.game.skipexitanimation", "跳過退出動畫"),
        ("qol.game.skipexitanimationdsc", "“放棄”時立即返回主菜單，不播放退出動畫。"),
        ("qol.game.autosaveonexit", "退出時自動保存"),
        ("qol.game.autosaveonexitdsc", "使用“保存並退出”時更新自動存檔。"),
        ("qol.game.deleteautosaveondeath", "死亡時刪除自動存檔"),
        ("qol.game.deleteautosaveondeathdsc", "進入死亡界面時刪除自動存檔。"),
        ("qol.game.disableradline", "禁用輻射線"),
        ("qol.game.disableradlinedsc", "阻止輻射線出現，即使已經出現。"),
        ("qol.game.disablelineofsight", "禁用未植入芯片的視線"),
        ("qol.game.disablelineofsightdsc", "在未植入芯片時禁用視線。哇哦。"),
        ("qol.game.minigameqol", "小遊戲加速"),
        ("qol.game.minigameqoldsc", "加快開鎖速度，並將密碼鎖縮短為 5-9 位。"),
        ("qol.game.skillallocation", "技能點分配"),
        ("qol.game.skillallocationdsc", "啟用 QoL 的初始屬性技能點分配調整。"),
        ("qol.game.skillallocation.str", "初始力量"),
        ("qol.game.skillallocation.strdsc", "設置 QoL 技能點分配補丁使用的初始屬性值。"),
        ("qol.game.skillallocation.res", "初始韌性"),
        ("qol.game.skillallocation.resdsc", "設置 QoL 技能點分配補丁使用的初始屬性值。"),
        ("qol.game.skillallocation.int", "初始智力"),
        ("qol.game.skillallocation.intdsc", "設置 QoL 技能點分配補丁使用的初始屬性值。"),
        ("qol.game.downloadlocale", "下載語言包"),
        ("qol.game.downloadlocaledsc", "從官方語言倉庫 GitHub 下載並安裝語言文件。警告：在遊戲內使用將重置當前層！"),
        ("qol.game.entitydensity", "單個實體密度"),
        ("qol.game.entitydensitydsc", "調整任意實體的生成倍率。"),
        ("qol.game.structuredensity", "單個結構密度"),
        ("qol.game.structuredensitydsc", "調整任意結構的生成倍率。\n\n【超過100%會有顯示問題，重進設置會變成100%，不是漢化的鍋，重啟遊戲後正常顯示你調過大於100%的值】"),
        ("qol.game.layermodifierdensity", "地層隨機效果頻率"),
        ("qol.game.layermodifierdensitydsc", "調整地層隨機效果頻率。"),
        ("qol.audio.soundoverride", "單個音效覆蓋"),
        ("qol.audio.soundoverridedsc", "調整任意特定音效的音量。"),
        ("qol.game.discordpresence", "Discord 狀態"),
        ("qol.game.discordpresencedsc", "編輯 Discord 狀態模板的詳情、狀態和圖像提示。"),
        ("qol.input.quickstash", "【QoL】快速收納"),
        ("qol.input.quickstashdsc", "把光標下的物品快速放入可用的物品欄格子、穿戴欄或隨身攜帶的容器中。"),
        ("qol.input.inventoryinteraction", "【QoL】物品欄交互輔助鍵"),
        ("qol.input.inventoryinteractiondsc", "拖拽物品時按住此鍵，可交換容器或將兼容的工具和電池放入容器。"),
    };
    public static readonly (string En, string Zh)[] ModuleDefs =
    {
        ("qol_ui_discord", "Discord 狀態"),
        ("qol_ui_discorddsc", "【建議關閉。無法連接DC，會刷連接錯誤日誌】富媒體狀態集成。"),
        ("qol_vis_los", "視線陰影修復"),
        ("qol_vis_losdsc", "調整視線著色器，避免在黑暗中描繪出未探明方塊的輪廓。"),
        ("qol_craft_bulk", "批量製作"),
        ("qol_craft_bulkdsc", "添加批量製作和自動製作。"),
        ("qol_ui_preview", "製作預覽"),
        ("qol_ui_previewdsc", "增強制作菜單中的物品預覽。"),
        ("qol_ui_scroll", "容器滾輪"),
        ("qol_ui_scrolldsc", "為容器添加滾輪滾動支持。"),
        ("qol_inv_sortbtn", "整理按鈕"),
        ("qol_inv_sortbtndsc", "添加用於整理的 UI 按鈕。"),
        ("qol_inv_quickstash", "快速收納"),
        ("qol_inv_quickstashdsc", "使用快速收納快捷鍵立即拾取物品。"),
        ("qol_inv_liquid", "物品欄輔助鍵"),
        ("qol_inv_liquiddsc", "添加 Shift 交互和可配置的物品欄交互輔助鍵。"),
        ("qol_game_pusher", "水體物理"),
        ("qol_game_pusherdsc", "1.5 格水不再推動你。"),
        ("qol_game_soundcannon_indicator", "音波炮指示器"),
        ("qol_game_soundcannon_indicatordsc", "通過說話和箭頭警示正在充能的音波炮。"),
        ("qol_game_modifiers", "地層隨機效果修改器"),
        ("qol_game_modifiersdsc", "啟用/禁用地層隨機效果修改器調整。"),
        ("qol_audio_safety", "音頻安全"),
        ("qol_audio_safetydsc", "降低高音和尖銳的聲音。"),
        ("qol_save_menu", "存檔菜單"),
        ("qol_save_menudsc", "在暫停菜單添加存檔欄選擇菜單"),
        ("qol_timer", "計時器"),
        ("qol_timerdsc", "在暫停菜單中添加計時器。"),
        ("qol_autosave", "自動保存"),
        ("qol_autosavedsc", "定期自動保存遊戲。【３分鐘保存一次】"),
    };
    public static readonly (string En, string Zh)[] LangNames =
    {
        ("es-419", "西班牙語（拉丁美洲）"),
        ("es-ES", "西班牙語（西班牙）"),
        ("ar-001", "阿拉伯語"),
        ("be-BY", "白俄羅斯語"),
        ("de-DE", "德語"),
        ("fi-FI", "芬蘭語"),
        ("fr-FR", "法語"),
        ("id-ID", "印尼語"),
        ("it-IT", "意大利語"),
        ("ja-JP", "日語"),
        ("kk-KZ", "哈薩克語"),
        ("ko-KR", "韓語"),
        ("pl-PL", "波蘭語"),
        ("pt-BR", "葡萄牙語（巴西）"),
        ("ro-RO", "羅馬尼亞語"),
        ("ru-RU", "俄語"),
        ("th-TH", "泰語"),
        ("uk-UA", "烏克蘭語"),
        ("vi-VN", "越南語"),
        ("ca-ES", "加泰羅尼亞語"),
        ("zh-CN", "簡體中文"),
        ("zh-TW", "繁體中文"),
        ("EN", "英文"),
    };
    public static readonly (string En, string Zh)[] EntityNames =
    {
        ("animalcorpse", "動物屍體"),
        ("bananaplant", "香蕉草"),
        ("bandage", "繃帶"),
        ("barbedwirefence", "鐵絲網"),
        ("beartrap", "捕獸夾 老舊機械"),
        ("BloodCrystal", "生血晶"),
        ("browncap", "棕帽菇"),
        ("brownshroom", "棕蘑菇"),
        ("cactus", "仙人掌"),
        ("CaveTicks", "洞穴蜱蟲 CaveTicks"),
        ("caveticks", "洞穴蜱蟲 caveticks"),
        ("ceilingrye", "天花板垂麥"),
        ("coil", "線圈"),
        ("containercrate", "物資箱"),
        ("corpse", "屍體"),
        ("DigestionCrystal", "消化晶"),
        ("drillpod", "鑽探艙"),
        ("drillpodbroken", "損毀的鑽探艙"),
        ("dropcapsule", "空投艙"),
        ("droppings", "屎"),
        ("drybush", "枯灌木"),
        ("EmissiveCrystal", "夜明晶"),
        ("experimentflesh", "黃色肉塊"),
        ("fleshchunk", "巨大肉塊"),
        ("foodbox", "食物箱"),
        ("geotree", "地生樹"),
        ("geyser", "間歇泉"),
        ("glowplant", "發光草"),
        ("grabberplant", "抓纏草"),
        ("internalorgans", "內臟團"),
        ("jumppad", "彈射陷阱 老舊機械"),
        ("landmine", "地雷"),
        ("leadbush", "鉛灌叢"),
        ("lifepodchest", "維生艙箱子"),
        ("LifepodStart", "初始維生艙 LifepodStart"),
        ("LoreNote", "手寫筆記"),
        ("medcrate", "醫療箱"),
        ("minibarrel", "迷你桶"),
        ("mushplant", "菌類植物 mushplant"),
        ("oilpipe", "廢液管"),
        ("overgrowntick", "巨型蜱蟲"),
        ("OxygenCrystal", "氧晶"),
        ("plantiation", "植物 plantiation"),
        ("rag", "舊布條"),
        ("ReliefCrystal", "鎮痛晶"),
        ("sandrose", "沙玫瑰"),
        ("shadecrawler", "暗影爬行者"),
        ("skullcrusher", "碎顱者"),
        ("SoothingCrystal", "寧神晶"),
        ("soundcannon", "音波炮"),
        ("Special/sandvinehook", "特殊/沙藤鉤"),
        ("Special/sandvinerope", "特殊/沙藤繩"),
        ("Special/wallholes", "特殊/牆洞"),
        ("spentfuel", "廢棄燃料"),
        ("spikestabber", "尖刺陷阱 老舊機械"),
        ("stalactite", "鐘乳石"),
        ("stalagmite", "石筍"),
        ("stoneplant", "石生花"),
        ("thornbackelder", "棘背獸長老"),
        ("thornbackyoung", "棘背獸"),
        ("TurbulentCrystal", "激盪晶"),
        ("turret", "自動炮塔"),
        ("wallbiter", "巨噬沙行獸"),
        ("wallflower", "牆花 wallflower"),
    };
    public static readonly (string En, string Zh)[] StructureNames =
    {
        ("BioContainer", "生物容器 BioContainer"),
        ("BrickLoot", "磚塊堆"),
        ("CratePod", "板條箱艙"),
        ("Lifepod", "維生艙"),
        ("LifepodCollapsed", "倒塌的維生艙"),
        ("MedicalBuilding", "醫療建築 MedicalBuilding"),
        ("MiniPod", "迷你艙"),
        ("SteelBridge", "鋼橋 SteelBridge"),
        ("SteelThing", "鋼製物 SteelThing"),
        ("TutorialStructure", "訓練建築 TutorialStructure"),
        ("WoodCross", "木十字架 WoodCross"),
        ("WoodHorizontal", "水平木樑 WoodHorizontal"),
    };
    public static readonly (string En, string Zh)[] ModifierNames =
    {
        ("Cold", "寒冷"),
        ("Dry", "乾燥"),
        ("Flooded", "積水"),
        ("Foggy", "多霧"),
        ("Freezing", "嚴寒"),
        ("Hot", "炎熱"),
        ("Infested", "蟲害"),
        ("Ionized", "輻射"),
        ("Rainy", "多雨"),
        ("Unchipped", "耀斑侵襲 Unchipped"),
        ("Warm", "溫暖"),
    };
    public static readonly (string En, string Zh)[] PreRun =
    {
        ("clicktocontinue", "點擊繼續...\n或點擊 鼠標右鍵/Esc 立即關閉。"),
    };
    public static readonly (string En, string Zh)[] Exact =
    {
        ("<color=orange>Client-side MP spawn forwarding does not support random positions.</color>", "<color=orange>客戶端多人生成轉發不支持隨機位置。</color>"),
        ("<color=orange>Cannot resolve player position right now.</color>", "<color=orange>暫時無法獲取玩家位置。</color>"),
        ("<color=orange>Cannot resolve cursor position right now.</color>", "<color=orange>暫時無法獲取光標位置。</color>"),
        ("Unknown", "未知"),
        ("Cannot resolve player position right now.", "暫時無法獲取玩家位置。"),
        ("Cannot resolve cursor position right now.", "暫時無法獲取光標位置。"),
        ("Client-side MP spawn forwarding does not support random positions.", "客戶端多人生成轉發不支持隨機位置。"),
    };
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Cannot save while dead!", "死亡時無法保存！"),
        ("Cannot save while ragdolled!", "布娃娃狀態時無法保存！"),
        ("Multiplayer save failed!", "多人聯機保存失敗！"),
        ("Client snapshot save failed!", "客戶端快照保存失敗！"),
        ("Save failed!", "保存失敗！"),
        ("Slot is empty!", "存檔為空！"),
        ("Clients can only restore MP item snapshots.", "客戶端只能恢復多人物品快照。"),
        ("Disable multiplayer before loading QoL saves.", "加載 QoL 存檔前請禁用多人模式。"),
        ("Host is loading a save. Please rejoin after the load finishes.", "主機正在加載存檔，請在加載完成後重新加入。"),
        ("Inventory restore failed.", "物品欄恢復失敗。"),
        ("Inventory restored.", "物品欄已恢復。"),
        ("Inventory restore failed on host.", "主機端物品欄恢復失敗。"),
        ("Spawn request failed on host.", "主機端生成請求失敗。"),
        ("Spawn request completed.", "生成請求已完成。"),
        ("Spawn request failed.", "生成請求失敗。"),
        ("Host has sv_cheats or client commands disabled.", "主機已禁用 sv_cheats 或客戶端命令。"),
        ("Spawn command was empty.", "生成命令為空。"),
        ("Only spawn commands can be forwarded.", "只能轉發生成命令。"),
        ("Healed player on host.", "已在主機端治療玩家。"),
        ("Heal request failed on host.", "主機端治療請求失敗。"),
        ("Heal request completed.", "治療請求已完成。"),
        ("Heal request failed.", "治療請求失敗。"),
        ("Host could not find your player body.", "主機無法找到你的玩家身體。"),
        ("Host could not find your player name.", "主機無法找到你的玩家名稱。"),
        ("Host could not find your body.", "主機無法找到你的身體。"),
        ("Host player body is unavailable for player position.", "主機玩家身體不可用，無法獲取玩家位置。"),
        ("Host camera is unavailable for cursor position.", "主機攝像機不可用，無法獲取光標位置。"),
        ("Inventory snapshot was empty.", "物品欄快照為空。"),
        ("This slot has no client inventory snapshot.", "此存檔沒有客戶端物品欄快照。"),
        ("Client inventory snapshot is empty.", "客戶端物品欄快照為空。"),
        ("Could not send inventory restore request. The host needs QoL and client commands enabled.", "無法發送物品欄恢復請求。主機需啟用 QoL 和客戶端命令。"),
        ("Client saves can only be loaded in a singleplayer game", "客戶端存檔只能在單人遊戲中加載"),
        ("No player body found.", "未找到玩家身體。"),
        ("QoL Unknown imported singleplayer slot for Krokosha MP host", "QoL Unknown 已為 Krokosha 多人主機導入單人槽位。"),
        ("Restored inventory from QoL slot.", "已從 QoL 存檔恢復物品欄。"),
        ("MP save bundle is missing or corrupt.", "多人存檔包缺失或損壞。"),
        ("Could not stage QoL save for multiplayer host.", "無法為多人主機暫存 QoL 存檔。"),
        ("Client reconnect clicked!", "客戶端重連已點擊！"),
        ("Client Connect clicked!", "客戶端連接已點擊！"),
        ("No active world on host.", "主機上沒有活躍的世界。"),
        ("Discord Presence editor unavailable: canvas not found.", "Discord 狀態編輯器不可用：找不到畫布。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("D-Pad:", "十字鍵 : "),
        ("<color=orange>No active world! :p</color>", "<color=orange>沒有活躍的世界！:p</color>"),
        ("Always skipping the lore now...", "現在總是會跳過劇情..."),
        ("Always showing the lore now.", "現在總是會顯示劇情"),
        ("Usage: disablelayermodifiers [true/false]", "用法 : disablelayermodifiers [true/false]"),
        ("<color=orange>Failed to send spawn request to host.</color>", "<color=orange>向主機轉發生成請求失敗。</color>"),
        ("<color=grey>Forwarded spawn request to host.</color>", "<color=grey>已向主機轉發生成請求。</color>"),
        ("Experimental features enabled. Reopen the settings menu to refresh experimental options.", "已啟用實驗性功能。重新打開設置菜單以刷新實驗選項。"),
        ("Experimental features disabled. Reopen the settings menu to refresh experimental options.", "已禁用實驗性功能。重新打開設置菜單以刷新實驗選項。"),
        ("No start commands set.", "沒有設置啟動命令。"),
        ("Cleared start commands!", "已清除啟動命令！"),
        ("Running your startup commands!...", "正在執行你的啟動命令！..."),
        ("Saved the game and quit to menu.", "已保存遊戲並返回主菜單。"),
        ("<color=yellow>Autosaved game.</color>", "<color=yellow>已自動保存遊戲。</color>"),
        ("No custom sound overrides set.", "沒有自定義音效覆蓋。"),
        ("Cleared all custom sound overrides.", "已清除所有自定義音效覆蓋。"),
        ("Missing sound name argument.", "缺少音效名稱參數。"),
        ("Missing volume argument. Usage: noise change [name] [volume]", "缺少音量參數。用法 : noise change [名稱] [音量]"),
        ("Invalid volume number.", "無效的音量數值。"),
        ("Current Sound Overrides", "當前音效覆蓋"),
        ("<color=green>Controller bindings reset to defaults</color>", "<color=green>控制器按鍵已重置為默認</color>"),
        ("<color=orange>Controller manager not initialized</color>", "<color=orange>控制器管理器未初始化</color>"),
        ("<color=orange>Usage: controllerbind <button> <action> OR controllerbind reset/actions/info</color>", "<color=orange>用法 : controllerbind <按鍵> <動作> 或 controllerbind reset/actions/info</color>"),
        ("<color=orange>Too many arguments</color>", "<color=orange>參數過多</color>"),
        ("Use: controllerbind <button> <action>", "用法 : controllerbind <按鍵> <動作>"),
        ("Face Buttons:", "正面按鍵 : "),
        ("Triggers:", "扳機鍵 : "),
        ("Bumpers:", "肩鍵 : "),
        ("Stick Press:", "搖桿按下 : "),
        ("Special:", "特殊 : "),
        ("Valid actions: ", "有效動作 : "),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("button", "按鈕"),
        ("action", "動作"),
        ("string action", "文本 操作"),
        ("string sound", "文本 音效"),
        ("float volume", "浮點 音量"),
        ("bool disable", "真假"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Shows current loot% and traps% multipliers.", "【QoL】顯示當前戰利品和陷阱倍率。"),
        ("Toggles always skipping the fullscreen intro lore.", "【QoL】切換是否總是跳過全屏開場劇情。"),
        ("Toggles experimental QoL features.", "【QoL】切換 QoL 實驗性功能。"),
        ("Disables/enables all layer modifiers.", "【QoL】禁用/啟用所有地層隨機效果。"),
        ("Set or view controller button bindings", "【QoL】設置或查看控制器按鍵綁定"),
        ("Button name (A, B, X, Y, DpadUp, etc.)", "按鍵名稱（A、B、X、Y、DpadUp 等）"),
        ("Action to bind (jump, attack, craft, etc.)", "要綁定的動作（jump、attack、craft 等）"),
        ("Sets commands to execute on a fresh run (split by ;). Usage: runatstart [commands] OR runatstart clear", "【QoL】設置在新開一局時自動執行的命令（用 ; 分隔）。用法 : runatstart [命令] 或 runatstart clear"),
        ("Manage sound volume overrides.", "【QoL】管理音效音量覆蓋。"),
        ("Name of the sound file", "音效文件名稱"),
        ("New volume (0.0 - 1.2 or 0 - 120)", "新音量（0.0到1.2 或 0到120）"),
        ("True to set all to 0%, False to set to default", "設為 true 將所有倍率設為 0%，設為 false 恢復默認"),
        ("Displays the current world seed.", "【QoL】顯示當前世界種子。"),
        ("!! NOT RECOMMENDED !!. Instantly saves the game and exits to the main menu as per vanilla. Loading the save will put you at the beginning of the current layer.", "【QoL 表示】！！不推薦！！立即保存遊戲並按原版行為返回主菜單。讀取存檔會讓你回到當前地層的起點。"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("点击继续...\n按ESC跳过", "點擊繼續...\n或點擊 鼠標右鍵/Esc 立即關閉。"),
        ("Seed", "種子"),
        ("Locked", "已鎖定"),
        ("Mods", "模組"),
        ("Play", "播放"),
        ("Edit", "編輯"),
        ("Close", "關閉"),
        ("Reset", "重置"),
        ("Apply", "應用"),
        ("SAVE SLOTS", "存 檔 欄"),
        ("Continue", "繼續前進"),
        ("Continue MP Host", "繼續前進 多人主機"),
        ("MP Client Save", "多人客戶端 存檔"),
        ("Start a deterministic seeded run", "開始確定性種子對局"),
        ("Corrupt", "損壞"),
        ("<color=#66ccff>[MP Host]</color> ", "<color=#66ccff>[多人主機]</color> "),
        ("<color=#66ccff>[MP Client]</color> ", "<color=#66ccff>[多人客戶端]</color> "),
        ("<color=#66ccff>[MP]</color> ", "<color=#66ccff>[多人]</color> "),
        ("<color=yellow>[ID: {0}]</color> ", "<color=yellow>[ID: {0}]</color> "),
        ("OPTION\nMENU", "選項\n菜單"),
        ("QoL\nSettings", "QoL\n設置"),
        ("Show Options", "顯示選項"),
        ("Update available! click to open Nexus page", "有新版本！點擊打開Ｎ網頁面"),
        ("<color=#54a5dc>Please restart the game for QoL module settings changes to take effect!", "<color=#54a5dc>請重啟遊戲，QoL 模塊設置更改才能生效！"),
        ("Made by Orsoniks\nLoading art by Wickflix\nMenu art by @GatoCataco ~", "作者：Orsoniks\n加載美術：Wickflix\n菜單美術：@GatoCataco～"),
        (" <color=#FFEA00>\nPlease restart your game for changes to take effect!", " <color=#FFEA00>\n請重啟遊戲以使更改生效！"),
        ("Restart Apply", "重啟＆應用"),
        ("Restart Game", "重啟遊戲"),
        ("Open Nexus", "打開Ｎ網"),
        ("Custom settings", "自定義設置"),
        ("Type to rename", "輸入以重命名"),
        ("Right click to delete", "右鍵刪除"),
        ("Select...", "選擇..."),
        ("Waiting...", "稍後..."),
        ("Fetching List...", "獲取列表..."),
        ("Connection Error", "連接錯誤"),
        ("Failed to reach GitHub", "無法\n連接 GitHub"),
        ("Select Language...", "選擇語言..."),
        ("Discord Presence", "Discord 狀態"),
        ("Details", "詳情"),
        ("Variables", "變量"),
        ("Template text...", "模板文本..."),
        ("State rules", "狀態規則"),
        ("Other fields", "其他字段"),
        ("Large tooltip", "大圖提示"),
        ("Small tooltip", "小圖提示"),
        ("Live preview", "實時預覽"),
        ("Reset State", "重置狀態"),
        ("Reset All", "全部重置"),
        ("Preview", "預覽"),
        ("Applied Discord Presence templates.", "已應用 Discord 狀態模板。"),
        ("Reset all Discord Presence templates.", "已重置全部 Discord 狀態模板。"),
        ("Presence context is unavailable.", "狀態上下文不可用。"),
        ("Crafting", "製作"),
        ("<b>IGT:</b>", "<b>遊玩時間</b>"),
        ("<b>RTA:</b>", "<b>運行時間</b>"),
        ("Left Click", "左鍵單擊"),
        ("Right Click", "右鍵單擊"),
        ("Middle Click", "中鍵單擊"),
        ("Sorts your inventory to minimize weight use", "整理物品欄以最小化負重"),
        ("Sleep, those little slices of death. How I loathe them.", "“睡眠，那一段段小小的死亡，我是何其憎惡。”"),
        ("Also try Custom Structures!", "“也試試 Custom Structures 吧！”"),
        ("Also try CUCoreLib!", "“也試試 CUCoreLib 吧！”"),
        ("Those burial-clouds that lower victorious soon to devour all", "“那低垂的葬雲，以凱旋之姿迫近，轉瞬將吞噬萬物”"),
        ("This shall be a story like none other before.", "“這將是一個前無古人的故事。”"),
        ("I had planned my life's endeavor", "“我曾為一生的事業精心籌謀”"),
        ("but my life had plans for me.", "“可我的人生對我另有安排。”"),
        ("I am lost but not forever,", "“我雖迷失，卻非永世，”"),
        ("I am where I am meant to be.", "“我正身處命定之地。”"),
        ("Imagine now unbearably, how unutterly cold the universe would be if one is all alone.", "“此刻試想，那不堪忍受、無以言表的寒冷——若你孤身一人，宇宙便是如此。”"),
        ("There's really no hard limit to how long these pause menu names can be and to be quite honest I'm rather curious to see how far we can go. Adolphus W. Green (1844–1917) started as the Principal of the Groton School in 1864. By 1865, he became second assistant librarian - oh wait nevermind there' a limit.", "“其實暫停菜單的文字並沒有真正的硬性長度限制，老實說，我挺好奇究竟能寫多長。阿道弗斯·W·格林（1844–1917）於 1864 年開始擔任格羅頓學校校長，到 1865 年，他當上了第二助理圖書管理員——哦等等，算了，看來還是有限制的。”"),
        ("Astralsounds", "星籟"),
        ("Everything will be okay.", "“一切都會沒事的。”"),
        ("Remember to do an act of good today.", "“記得今天要做一件善事。”"),
        ("Pause and hydrate. It'll help.", "“暫停一下，喝點水。會有幫助的。”"),
        ("Don't forget to eat, now...", "“別忘了吃點東西，好嗎...”"),
        ("Little one.", "“小傢伙。”"),
        ("You're almost there. Just a couple more steps.", "“你就快到了，再多走幾步。”"),
        ("To the north, a new future.", "“向北方去，一片嶄新的未來。”"),
        ("To reach the antechamber.", "“只為抵達前廳。”"),
        ("To remember, to forget. To forget, to remember.", "“去銘記，去遺忘。去遺忘，再去銘記。”"),
        ("Take care of yourself. You deserve it.", "“照顧好自己，你值得被善待。”"),
        ("From now on you’re going to have to think. There’s a reason why we’re born with brains in our heads, not rocks.", "“從現在起，你可得動腦子了。我們生來腦袋裡裝的是大腦而非石頭，並非毫無緣由。”"),
        ("Remember the past, live in the present, and fear not the future, for it doesn't exist and never shall. There is only now", "“銘記過往，活在當下，莫懼未來，因為未來並不存在，也永不存在。只有現在。”"),
        ("Change itself is nether good nor bad, but knowledge is always useful.", "“變化本身非善非惡，但知識永遠有益。”"),
        ("Then I shall keep myself, to myself.", "“那我便將自我守住，只交予自身。”"),
        ("Do questions not taste best in the absence of answers?", "“問題不正是因為沒有答案時，才最令人回味嗎？”"),
        ("In the silent, hidden spaces where we watch and wait, we see the artistry of all that is.", "“在那寂靜隱秘的角落，我們守望等待，得見萬物的匠心。”"),
        ("When a being dies, a world dies.", "“一命逝去，一界隨之消亡。”"),
        ("Never is a very, very long time.", "“‘永遠’，是一段很久、很久的時間。”"),
        ("We're all just stories in the end, so let's make ours a good one.", "“到頭來，我們都只不過是故事罷了。既然如此，就讓我們的故事精彩一些吧。”"),
        ("You cannot retreat from this fight. Stand with pride and fight with honor.", "“此戰無路可退，驕傲地挺立，光榮地戰鬥吧。”"),
        ("...to have turned the wheel and approached genius...", "“...轉動了命運之輪，向天才之境靠近...”"),
        ("We are creatures of habit.", "“我們是習慣的造物。”"),
        ("Fear is a good servant, but a poor leader.", "“恐懼是個好僕從，卻是個糟糕的主宰。”"),
        ("Wisdom is neither a knowing nor a finding but rather a seeking.", "“智慧並非已知，亦非已得，而是無盡的追尋。”"),
        ("A box without hinges, key, or lid, yet golden treasure inside is hid.", "“無鉸無鑰也無蓋，內裡卻藏金色寶藏。”"),
        ("One learns more from defeat than victory. Therefore, fear the general that has never won a battle.", "“人從失敗中學到的，遠多於從勝利中學到的。因此，要畏懼那未嘗一勝的將軍。”"),
        ("The price of entry to being good at something is to suck at that something.", "“把一件事做得糟糕透頂，正是擅長它的入場券。”"),
        ("Death is only the end if you think the story is about you.", "“如果你認為這故事只關乎你時，死亡才是終點。”"),
        ("If you bring only these quotes, then it will be bereft of the meaning and lesson. You must seek these lessons and live them.", "“若你只帶來這些語錄，便會失了其中的意義與教誨。你須得親自求索，並親身踐行。”"),
        ("The gods envy us, because of our mortality. Death is what makes everything worthwhile and beautiful.", "“眾神因我們終有一死而嫉妒我們。正是死亡，賦予萬物意義與至美。”"),
        ("When they speak, they shake the very earth.", "“他們開口之時，大地也為之震顫。”"),
        ("Don't be afraid. Jump.", "“別怕，跳吧。”"),
        ("Un du evarínya ono varda.", "“願星辰守護你。”"),
        ("In the Main Menu", "在主菜單"),
        ("Main Menu", "主菜單"),
        ("Preparing to descend...", "準備下潛..."),
        ("Depth: Unknown..", "深度：未知..."),
        ("Died in tutorial", "死於教程"),
        ("In the tutorial", "在教程中"),
        ("Being tranquilized.!", "正在被麻醉！"),
        ("Currently attempting the basics course", "正在嘗試基礎課程"),
        ("Currently attempting the first aid course", "正在嘗試急救課程"),
        ("Currently attempting the crafting course", "正在嘗試製作課程"),
        ("In the sandbox", "在沙盒中"),
        ("Cardiac arrest. No pulse detected.", "心臟驟停。檢測不到脈搏。"),
        ("Chipless. Status unknown.", "未植入芯片。狀態未知。"),
        ("RUNNING FROM AN ELDER THORNBACK!!", "正在逃離老年刺背獸！！"),
        (" .. Hollow .. ", " .. 空洞 .. "),
        ("Feeling hungry", "感到飢餓"),
        ("Feeling peckish", "有點餓"),
        ("Parched of water!", "口渴難耐！"),
        ("Feeling very thirsty", "非常口渴"),
        ("Feeling a bit thirsty", "有點口渴"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("..what's that noise?", "..有什麼怪響？"),
    };
    public static readonly (string En, string Zh)[] Formats =
    {
        ("<color=orange>\"{0}\" is not a valid position for spawn forwarding.</color>", "<color=orange>「{0}」不是轉發生成命令的有效位置。</color>"),
        ("\"{0}\" became craftable after waiting.", "等待後「{0}」變為可製作。"),
        ("\"{0}\" never became craftable.", "「{0}」始終未能變為可製作。"),
        ("Waiting for \"{0}\" to become craftable.", "正在等待「{0}」變為可製作。"),
        ("Waiting for final recipe \"{0}\" to become craftable.", "正在等待最終配方「{0}」變為可製作。"),
        ("\"{0}\" is not a valid position for spawn forwarding.", "「{0}」不是有效的生成轉發位置。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("Saved MP host bundle to Slot {0}", "已將多人主機存檔包保存到存檔 {0}"),
        ("Saved MP client snapshot to Slot {0}", "已將多人客戶端快照保存到存檔 {0}"),
        ("Saved to Slot {0}", "已保存到存檔 {0}"),
        ("Returning {0} client{1} to the main menu before host save load.", "在主機進入存檔前，正在將 {0} 名聯機玩家返回至主菜單。"),
        ("\"{0}\" is not a valid condition value.", "「{0}」不是有效的耐久值。"),
        ("\"{0}\" is not a valid amount value.", "「{0}」不是有效的數量值。"),
        ("Could not find entity \"{0}\".", "找不到實體「{0}」。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("<color=green>Loot: {0}% | Traps: {1}%</color> <color=grey>(layer: {2}%/{3}%)</color>", "<color=green>戰利品 : {0}% | 陷阱 : {1}%</color> <color=grey>（地層 : {2}%/{3}%）</color>"),
        ("Current start commands: {0}", "當前啟動命令 : {0}"),
        ("Saved start commands: {0}", "已保存啟動命令 : {0}"),
        ("<color=green>Bound {0} to {1}</color>", "<color=green>已將 {0} 綁定到 {1}</color>"),
        ("<color=red>Failed to bind {0} to {1}</color>", "<color=red>綁定 {0} 到 {1} 失敗</color>"),
        ("Unknown action '{0}'. Use change, list, remove, or clear.", "未知操作「{0}」。請使用 change、list、remove 或 clear。"),
        ("Removed override for \"{0}\".", "已移除「{0}」的覆蓋。"),
        ("No override found for \"{0}\".", "沒有找到「{0}」的覆蓋。"),
        ("Set volume for \"{0}\" to {1} ({2}%).", "已將「{0}」的音量設為 {1}（{2}%）。"),
        (" - \"{0}\": {1}%", " - 「{0}」 : {1}%"),
        ("<color=green>Seed: {0} ({1})</color>", "<color=green>種子 : {0}（{1}）</color>"),
        ("X: {0} px from the left, Y : {1} px from the top", "X : 距左側 {0} 像素，Y : 距頂部 {1} 像素"),
        ("Controller source: {0} | Device: {1} | Profile: {2} | Active: {3}", "控制器源 : {0} | 設備 : {1} | 配置 : {2} | 活動 : {3}"),
        ("<color=red>[LocaleDownloader] Failed to fetch list: {0}", "<color=red>[LocaleDownloader] 語言列表獲取失敗 : {0}"),
        ("<color=red>[LocaleDownloader] Parse error: {0}", "<color=red>[LocaleDownloader] 語言列表解析錯誤 : {0}"),
        ("<color=red>[LocaleDownloader] Failed download: {0}", "<color=red>[LocaleDownloader] 語言下載失敗 : {0}"),
        ("<color=red>[LocaleDownloader] Write error: {0}", "<color=red>[LocaleDownloader] 語言文件寫入錯誤 : {0}"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("No expedition data in Slot {0}.", "存檔 {0} 中沒有探索數據。"),
        ("Resume your {0} expedition with Experiment #{1}.\n\nSeed: {2}\nIn-game time: {3}", "繼續你與 Experiment #{1} 的 {0} 探險。\n\n種子：{2}\n遊戲時間：{3}"),
        ("<b>Slot {0}{1}</b> {2}<size=70%>\n{3} | {4} run time</size>\n<size=60%><color=grey>{5}</color></size>", "<b>存檔 {0}{1}</b> {2}<size=70%>\n{3} | 遊玩時間 {4}</size>\n<size=60%><color=grey>{5}</color></size>"),
        ("<b>Slot {0}</b>\n<size=70%><color=grey>Empty</color></size>", "<b>存檔 {0}</b>\n<size=70%><color=grey>空</color></size>"),
        ("{0}m deep", "深度 {0} 米"),
        ("Custom Settings Preset {0}", "自定義設置預設 {0}"),
        ("Downloading {0}...", "正在\n下載 {0}..."),
        ("Installed {0}", "已安裝 {0}"),
        ("{0} (Installed)", "{0}（已安裝）"),
        ("Crafting {0}x", "製作 ｘ{0}"),
        ("QoL is out of date! ({0} -> {1})\n(Click here to open the github release)", "QoL 已過時！（{0} → {1}）\n（點此打開 GitHub 發佈頁）"),
        ("Died at {0}m", "死於 {0} 米深"),
        ("Descending the {0} ({1}m)", "正在下潛至 {0}（{1} 米）"),
        ("Fibrillation crisis! {0}% severity.", "纖顫危機！嚴重度 {0}%。"),
        ("Fibrillation worsening... ({0}% severity).", "纖顫惡化...（嚴重度 {0}%）。"),
        ("Experiencing a stroke. ({0}% severity).", "正在中風。（嚴重度 {0}%）。"),
        ("Profound hypotension! {0} mmHg.", "重度低血壓！{0} 毫米汞柱。"),
        ("Hypertensive crisis! {0} mmHg.", "高血壓危象！{0} 毫米汞柱。"),
        ("Severe hypertension! {0} mmHg.", "重度高血壓！{0} 毫米汞柱。"),
        ("Lung failure! {0} thorax health.", "肺衰竭！胸腔健康 {0}。"),
        ("In septic shock! {0}% severity.", "感染性休克！嚴重度 {0}%。"),
        ("In shock from {0}% pain!", "因 {0}% 疼痛而休克！"),
        ("Taking a nap... {0}% energy..", "正在小憩..體力 {0}%..."),
        ("Comatose! {0}% brain health.", "昏迷！腦部健康 {0}%。"),
        ("Cardiac Arrest!! {0}% brain health.", "心臟驟停！！腦部健康 {0}%。"),
        ("Hypotensive! {0} mmHg.", "低血壓！{0} 毫米汞柱。"),
        ("Bleeding Out!! {0}L/m bleed rate.", "大出血！！出血速率 {0} 升/分鐘。"),
        ("Drowning!! {0}% oxygen remaining.", "溺水！！剩餘氧氣 {0}%。"),
        ("Hypovolemic! {0}L blood amount.", "血容量不足！血量 {0} 升。"),
        ("Irradiated! {0}% severity.", "受到輻射！嚴重度 {0}%。"),
        ("Hypothermic! {0}C body temp.", "體溫過低！體溫 {0}℃。"),
        ("Heatstroke! {0}C body temp.", "中暑！體溫 {0}℃。"),
        ("Starving! {0}% fullness.", "快餓死了！飽腹度 {0}%。"),
        ("Dessicated! {0}% thirst.", "脫水！口渴度 {0}%。"),
        ("Treating {0}L/m of bleeding...", "正在處理 {0} 升/分鐘的出血..."),
        ("In {0}% pain. Ouch!", "疼痛 {0}%。哎喲！"),
        ("{0}% exhausted... phew..", "疲憊 {0}%...呼..."),
        ("Healing a {0} fracture...", "正在癒合{0}的骨折..."),
        ("Removing shrapnel from the {0}...", "正在從{0}取出彈片..."),
        ("Tending a {0} dislocation...", "正在處理{0}的脫臼..."),
        ("Feeling {0} sick. ({1}% sickness)", "感覺{0}不適。（疾病 {1}%）"),
        ("{0} brain damage! ({1}% brain health)", "{0}腦損傷！（腦部健康 {1}%）"),
        ("Feeling {0}... ({1} happiness)", "感覺{0}...（心情 {1}）"),
        ("{0}.. ({1} hunger)", "{0}...（飢餓值 {1}）"),
        ("{0}.. ({1} thirst)", "{0}...（口渴值 {1}）"),
        ("Feeling {0}{1} ({2} happiness)", "感覺{0}{1}（心情 {2}）"),
        ("Feeling {0}. ({1} happiness)", "感覺{0}。（心情 {1}）"),
        ("A limb is {0} infected! ({1}% infection)", "一個肢體正在{0}感染！（感染 {1}%）"),
        ("{0} limbs are {1} infected! ({2}% infection)", "{0} 個肢體正在{1}感染！（感染 {2}%）"),
        ("State rule error: {0}", "狀態規則錯誤：{0}"),
    };
    public static readonly (string En, string Zh)[] ModRowFragments =
    {
        ("Queued: Disable", "待執行：禁用"),
        ("Queued: Enable", "待執行：啟用"),
        ("Disabled", "已禁用"),
        ("Enabled", "已啟用"),
        (" Nexus version)", " Ｎ網版本)"),
    };
    public static readonly (string En, string Zh)[] ConsoleFragments =
    {
        ("... (", "...（"),
        (" more)", " 更多）"),
    };
    public static readonly (string En, string Zh)[] DiscordValues =
    {
        ("upper right arm", "右上臂"),
        ("Parched of water!", "口渴難耐！"),
        ("Feeling very thirsty", "非常口渴"),
        ("Feeling a bit thirsty", "有點口渴"),
        ("Feeling hungry", "感到飢餓"),
        ("Feeling peckish", "有點餓"),
        ("Near-starving", "快餓死了"),
        (" and well-fed.", "且吃得很飽。"),
        (" and satisfied.", "且很滿足。"),
        ("upper left arm", "左上臂"),
        ("right forearm", "右前臂"),
        ("left forearm", "左前臂"),
        ("right shins", "右小腿"),
        ("left shins", "左小腿"),
        ("right thigh", "右大腿"),
        ("left thigh", "左大腿"),
        ("right hand", "右手"),
        ("left hand", "左手"),
        ("right foot", "右腳"),
        ("left foot", "左腳"),
        ("extremely", "極度"),
        ("depressed", "抑鬱"),
        ("suicidal", "想自殺"),
        ("ecstatic", "欣喜若狂"),
        ("severely", "嚴重"),
        ("Moderate", "中度"),
        ("Severe", "重度"),
        ("content", "滿足"),
        ("abdomen", "腹部"),
        ("mildly", "輕微"),
        ("thorax", "胸腔"),
        ("badly", "嚴重"),
        ("happy", "開心"),
        ("Minor", "輕度"),
        ("a bit", "有點"),
        ("very", "非常"),
        ("down", "低落"),
        ("head", "頭部"),
        ("Presence context is unavailable.", "狀態上下文不可用。"),
    };
    public static readonly (string En, string Zh)[] SlotFragments =
    {
        ("[MP Client]", "[多人客戶端]"),
        ("[MP Host]", "[多人主機]"),
        ("m Deep", "米深"),
        ("m deep", "米深"),
        ("Unknown", "未知"),
        ("[MP]", "[多人]"),
    };
    public static readonly (string En, string Zh)[] TooltipFragments =
    {
        ("Update available! click to open Nexus page", "有新版本可用！點擊打開Ｎ網頁面"),
    };
    public static readonly (string En, string Zh)[] DepthUnit =
    {
        ("m", "米"),
    };
}
