internal static class CUCoreLibTrTw
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Spawns all items from a given loot pool with zero gravity.", "【CUCoreLib】從指定戰利品池中生成所有物品（零重力）。"),
        ("Spawns a vanilla prefab or CUCoreLib-registered item/building.", "【CUCoreLib】生成原版預設物體或 CUCoreLib 註冊的物品/建築。"),
        ("Places a vanilla or CUCoreLib-registered tile at the chosen block position.", "【CUCoreLib】在指定位置放置原版或 CUCoreLib 註冊的物塊。"),
        ("Sends a diagnostic bug report with debug logs. Thanks!", "【CUCoreLib】發送帶調試日誌的診斷性 bug 報告。感謝！"),
        ("Writes or updates CUCoreLib generated locale data. WARNING: Overrides EN.json", "【CUCoreLib】寫入或更新 CUCoreLib 生成的本地化數據。警告: 會覆蓋BepInEx\\config\\CUCoreLib\\Locales\\EN.json"),
        ("Prints the loaded BepInEx plugin list to the in-game console and Unity log.", "【CUCoreLib】將已加載的 BepInEx 插件列表打印到遊戲內控制檯和 BepInEx 日誌。"),
        ("Strictly reloads item/liquid/recipe/locale content from a rebuilt mod DLL.", "【CUCoreLib】從重新構建的模組 DLL 嚴格重載物品/液體/配方/本地化內容。"),
        ("Enables automatic hot reloading after detecting a loaded mod DLL file change.", "【CUCoreLib】檢測到已加載模組 DLL 文件變化後啟用自動熱重載。"),
        ("Manages a live top-right overlay of watched static fields for runtime debugging.", "【CUCoreLib】管理運行時調試的右上角靜態字段監視覆蓋層。"),
    };
    public static readonly (string En, string Zh)[] ArgShort =
    {
        ("category", "類別"),
        ("modGUID", "模組GUID"),
        ("id", "ID"),
        ("condition", "耐久"),
        ("count", "數量"),
        ("tileIndex", "物塊ID"),
        ("path", "路徑"),
        ("modGuid", "模組GUID"),
        ("enable", "啟用"),
        ("action", "操作"),
        ("Type.member", "類型.成員"),
        ("description", "描述"),
        ("bool screenshot", "是否截圖"),
        ("severity", "嚴重度"),
    };
    public static readonly (string En, string Zh)[] ArgLong =
    {
        ("The ID of the category to spawn from.", "要生成的類別 ID。"),
        ("Where to spawn the item", "物品生成位置"),
        ("Spawn position.", "生成位置。"),
        ("Tile position.", "物塊位置。"),
        ("Optional BepInEx plugin GUID filter for the modded category. Use normal for no filter.", "（可選）模組類別的 BepInEx 插件 GUID 過濾器。使用 normal 表示不過濾。"),
        ("Item or object ID.", "物品或對象 ID"),
        ("Item condition.", "物品耐久。"),
        ("Number of objects to spawn.", "要生成的對象數量。"),
        ("Vanilla index or registered custom tile ID/index.", "原版索引或註冊的自定義物塊 ID/索引。"),
        ("Optional output path. Defaults to BepInEx/config/CUCoreLib/Locales/EN.json.", "（可選）輸出路徑。默認為 BepInEx/config/CUCoreLib/Locales/EN.json"),
        ("BepInEx plugin GUID to strictly reload from a rebuilt DLL.", "要從重新構建的 DLL 嚴格重載的 BepInEx 插件 GUID。"),
        ("BepInEx plugin GUID that previously called ContentReloadManager.EnableHotReload(GUID).", "先前調用過 ContentReloadManager.EnableHotReload(GUID) 的 BepInEx 插件 GUID。"),
        ("true to enable watch mode for that DLL, false to disable it.", "true 啟用該 DLL 的監視模式，false 禁用它。"),
        ("add, remove, list, clear, show, or hide.", "add添加、remove移除、list列出、clear清除、show顯示、hide隱藏。"),
        ("Reflected static field to watch, such as Namespace.Plugin.healthRate.", "要監視的反射靜態字段，例如 Namespace.Plugin.healthRate。"),
        ("Optional description in quotation marks \"\". Optional, but highly recommended.", "（可選）用引號包裹的描述文本。可選，但強烈推薦。"),
        ("True/false. Captures the current game screen if true. Optional.", "true/false。為 true 時截取當前遊戲畫面。可選。"),
        ("low/medium/high/critical. Optional.", "low、medium、high、critical。（可選）"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Debug watch overlay hidden.", "調試監視覆蓋層已隱藏。"),
        ("Debug watch overlay shown.", "調試監視覆蓋層已顯示。"),
        ("Cleared all debug watches.", "已清除所有調試監視。"),
        ("No active debug watches.", "沒有活躍的調試監視。"),
        ("Enable must be 'true' or 'false'.", "啟用值必須為「true」或「false」。"),
        ("Mod GUID was empty.", "模組 GUID 為空。"),
        ("Mod GUID was invalid.", "模組 GUID 無效。"),
        ("Strict content DLL reload is singleplayer-only.", "嚴格內容 DLL 重載僅限單人模式。"),
        ("Usage: spawncategory [category] [position] [modGUID]", "用法 : spawncategory [類別] [位置] [模組GUID]"),
        ("Usage: cuspawn [id]", "用法 : cuspawn [ID]"),
        ("Usage: settile [tileIndex or tileId] [position]", "用法 : settile [物塊索引或物塊ID] [位置]"),
        ("Usage: reloadcontent [modGuid]", "用法 : reloadcontent [模組GUID]"),
        ("Usage: autohotreload [modGuid] [enable]", "用法 : autohotreload [模組GUID] [啟用]"),
        ("Usage: debugwatch [add|remove|list|clear|show|hide] [Type.member]", "用法 : debugwatch [add|remove|list|clear|show|hide] [類型.成員]"),
        ("Usage: debugwatch add [Type.member]", "用法 : debugwatch add [類型.成員]"),
        ("Usage: debugwatch remove [Type.member]", "用法 : debugwatch remove [類型.成員]"),
        ("Usage: bug-report [\"description text\"] [bool screenshot] [severity]", "用法 : bug-report [\"描述文本\"] [是否截圖] [嚴重度]"),
        ("A bug report is already being sent.", "已在發送 bug 報告。"),
        ("Screenshot must be 'true' or 'false'.", "截圖參數必須為「true」或「false」。"),
        ("Severity must be low, medium, high, or critical.", "嚴重度必須為 low、medium、high 或 critical。"),
        ("Sending! Thanks for contributing!", "正在發送！感謝貢獻！"),
        ("CUCoreLib could not check for updates.", "CUCoreLib 無法檢查更新。"),
        ("CUCoreLib could not read the latest release version.", "CUCoreLib 無法讀取最新版本號。"),
        ("Strict content reload result was null.", "嚴格內容重載結果為空。"),
        ("Plugin type was null.", "插件類型為空。"),
        ("Compatibility report was null.", "兼容性報告為空。"),
        ("No invokable content methods were resolved from the reloaded assembly.", "無法從重載的程序集中解析出可調用的內容方法。"),
        ("Strict content reload completed.", "嚴格內容重載已完成。"),
        ("No rebuilt DLL source path was found. The loaded plugin path and runtime override path were both unavailable.", "未找到重新構建的 DLL 源路徑。已加載的插件路徑與運行時覆蓋路徑均不可用。"),
        ("No supported content reload entry methods were found. All discovered candidates were skipped.", "未找到受支持的內容重載入口方法。所有發現的候選方法均被跳過。"),
        ("No supported content reload entry methods were found after EnableHotReload(GUID). CUCoreLib could not discover any replayable supported content registrations.", "EnableHotReload(GUID) 之後未找到受支持的內容重載入口方法。CUCoreLib 未能發現任何可重放的內容註冊。"),
        ("Awake() must call ContentReloadManager.EnableHotReload(GUID) with a literal GUID argument.", "Awake() 必須使用字面量 GUID 參數調用 ContentReloadManager.EnableHotReload(GUID)。"),
        ("ContentReloadManager.EnableHotReload() must be called from the owning plugin Awake().", "ContentReloadManager.EnableHotReload() 必須從所屬插件的 Awake() 中調用。"),
        ("Host type was null.", "宿主類型為空。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("created locale at {0}", "已在 {0} 創建本地化文件"),
        ("Reloaded {0}!", "已重載 {0}！"),
        ("Spawned all items from category \"{0}\" at {1}.", "已在 {1} 生成類別「{0}」的所有物品。"),
        ("Placed tile {0} ({1}) at {2},{3}.", "已在 {2},{3} 放置地塊 {0}（{1}）。"),
        ("Loaded mods ({0}):", "已加載的模組（共 {0} 個） : "),
        ("Active debug watches ({0}) - overlay {1}:", "活躍的調試監視（{0} 個）- 覆蓋層 {1} : "),
        ("  {0} v{1} ({2})", "  {0} v{1}（{2}）"),
        ("Watching {0}.", "正在監視 {0}。"),
        ("Already watching {0}.", "已在監視 {0}。"),
        ("Stopped watching {0}.", "已停止監視 {0}。"),
        ("{0} is not currently watched.", "當前未在監視 {0}。"),
        ("Enabled automatic hot reload for {0} ({1}).", "已為 {0}（{1}）啟用自動熱重載。"),
        ("Disabled automatic hot reload for {0} ({1}).", "已為 {0}（{1}）禁用自動熱重載。"),
        ("Loaded plugin GUID was not found: {0}", "未找到已加載的插件 GUID : {0}"),
        ("Hot reload is not enabled for '{0}'. Call ContentReloadManager.EnableHotReload(GUID) from Awake() first.", "「{0}」未啟用熱重載。請先在 Awake() 中調用 ContentReloadManager.EnableHotReload(GUID)。"),
        ("Invalid item category \"{0}\".", "無效的物品類別「{0}」。"),
        ("Could not find entity '{0}'.", "找不到實體「{0}」。"),
        ("'{0}' is not a valid tile index or registered tile ID.", "「{0}」不是有效的物塊索引或已註冊的物塊 ID。"),
        ("Tile index '{0}' is not registered.", "物塊ID「{0}」未註冊。"),
        ("Failed to place tile '{0}' at block {1}.", "放置物塊「{0}」在方塊 {1} 失敗。"),
        ("Unknown debugwatch action '{0}'.", "未知的 debugwatch 操作「{0}」。"),
        ("Ambiguous debug watch '{0}'. Use a more specific type path.", "調試監視「{0}」存在歧義。請使用更具體的類型路徑。"),
        ("Could not find supported static field '{0}'.", "找不到受支持的靜態字段「{0}」。"),
        ("Please wait {0} seconds before sending another bug report.", "請等待 {0} 秒後再發送另一個 bug 報告。"),
        ("<color=#66FF66>Bug report sent successfully. ID: {0}</color>", "<color=#66FF66>bug 報告發送成功。ID : {0}</color>"),
        ("<color=orange>Bug report failed: {0}</color>", "<color=orange>bug 報告發送失敗 : {0}</color>"),
        ("<color=orange>Bug report failed: The bug report did not send for some reason! Uh-oh.</color>", "<color=orange>bug 報告發送失敗 : 出於某種原因未能發送！呃-哦。</color>"),
        ("The bug report description has an opening quote but no closing quote. Usage: bug-report [\"description text\"] [bool screenshot] [severity]", "bug 報告描述有起始引號但沒有結束引號。用法 : bug-report [\"描述文本\"] [是否截圖] [嚴重度]"),
        ("<color=#FFA500>CUCoreLib update available! {0} -> {1}</color>", "<color=#FFA500>CUCoreLib 有可用更新！{0} -> {1}</color>"),
        ("CUCoreLib is up to date! Current: {0}, Latest: {1}", "CUCoreLib 已是最新版本！當前 : {0}，最新 : {1}"),
        ("Mod <color=#{0}>{1}</color> is out of date! (Version {2} -> Version {3})", "模組 <color=#{0}>{1}</color> 已過期！（版本 {2} → 版本 {3}）"),
        ("Set player body field \"{0}\" to \"{1}\".", "已設置玩家身體字段「{0}」為「{1}」。"),
        ("Set \"{0}\" field \"{1}\" to \"{2}\".", "已設置「{0}」的字段「{1}」為「{2}」。"),
        ("Status field \"{0}\" is ambiguous. Use StatusType.Field to choose one.", "狀態字段「{0}」存在歧義。請使用 StatusType.Field 指定其一。"),
        ("Blocked during flexible hot reload: {0} called {1}.", "靈活熱重載期間被阻止 : {0} 調用了 {1}。"),
        ("Blocked during flexible hot reload: {0} called {1}. {2}", "靈活熱重載期間被阻止 : {0} 調用了 {1}。{2}"),
        ("Reloaded assembly did not contain plugin type '{0}'.", "重載的程序集中不包含插件類型「{0}」。"),
        ("Ran {0}().", "已運行 {0}()。"),
        ("Method '{0}' failed: {1}", "方法「{0}」執行失敗 : {1}"),
        ("{0}: Reloaded assembly did not contain declaring type '{1}'.", "{0} : 重載的程序集不包含聲明類型「{1}」。"),
        ("{0}: Reloaded assembly did not contain an invokable parameterless method.", "{0} : 重載的程序集不包含可調用的無參方法。"),
        ("Reload failed. Restored the previous successful content state for '{0}'.", "重載失敗。已恢復「{0}」此前成功的內容狀態。"),
        ("The selected rebuilt DLL path does not exist: {0}", "所選的重建 DLL 路徑不存在 : {0}"),
        ("No [BepInPlugin] type matching '{0}' was found in the rebuilt DLL.", "在重建的 DLL 中未找到匹配「{0}」的 [BepInPlugin] 類型。"),
        ("Compatibility scan failed: {0}", "兼容性掃描失敗 : {0}"),
        ("Plugin '{0}' must define an Awake() method with a ContentReloadManager.EnableHotReload(GUID) call.", "插件「{0}」必須定義一個包含 ContentReloadManager.EnableHotReload(GUID) 調用的 Awake() 方法。"),
        ("Awake() called EnableHotReload('{0}') but CUCoreLib could not discover any replayable supported content registrations after the marker.", "Awake() 調用了 EnableHotReload('{0}')，但 CUCoreLib 在該標記之後未能發現任何可重放的內容註冊。"),
        ("Method '{0}' has no method body. Strict content reload can only inspect methods with IL bodies.", "方法「{0}」沒有方法體。嚴格內容重載只能檢查包含 IL 方法體的方法。"),
        ("Method '{0}' did not call a supported content registration API. Replay roots must directly register supported content or call helper methods that do.", "方法「{0}」未調用受支持的內容註冊 API。重放根必須直接註冊受支持內容，或調用執行該操作的輔助方法。"),
        ("Method '{0}' touches multiple supported registration surfaces. CUCoreLib can often recover by replaying deeper helper methods, but this method itself is not a direct replay leaf.", "方法「{0}」觸及多個受支持的註冊面。CUCoreLib 通常可通過重放更深層的輔助方法恢復，但該方法本身不是直接重放葉節點。"),
        ("Awake() must call ContentReloadManager.EnableHotReload(\"{0}\").", "Awake() 必須調用 ContentReloadManager.EnableHotReload(\"{0}\")。"),
        ("Awake() called ContentReloadManager.EnableHotReload(\"{0}\") but the plugin GUID is \"{1}\".", "Awake() 調用了 ContentReloadManager.EnableHotReload(\"{0}\")，但插件 GUID 是「{1}」。"),
        ("Method '{0}' is tagged for stage '{1}' but does not call the matching supported registration API.", "方法「{0}」標記了階段「{1}」，但未調用匹配的受支持註冊 API。"),
        ("Method '{0}' calls BuildingEntityRegistry.{1}(). Only basic building registration is supported during strict content reload.", "方法「{0}」調用了 BuildingEntityRegistry.{1}()。嚴格內容重載期間僅支持基礎建築註冊。"),
        ("Method '{0}' is not strict content-only: it calls ModOptionsRegistry.{1}(). Mod options are excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 ModOptionsRegistry.{1}()。嚴格內容重載排除模組選項。"),
        ("Method '{0}' is not strict content-only: it calls SaveRegistry.{1}(). Save providers are excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 SaveRegistry.{1}()。嚴格內容重載排除存檔提供器。"),
        ("Method '{0}' is not strict content-only: it calls {1}.{2}(). Status and moodle registration are excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 {1}.{2}()。嚴格內容重載排除狀態與狀態圖標註冊。"),
        ("Method '{0}' is not strict content-only: it calls multiplayer registration/setup code. Multiplayer hooks are excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了多人遊戲註冊/設置代碼。嚴格內容重載排除多人遊戲鉤子。"),
        ("Method '{0}' is not strict content-only: it calls TileRegistry.{1}(). Tile registration is excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 TileRegistry.{1}()。嚴格內容重載排除地塊註冊。"),
        ("Method '{0}' is not strict content-only: it calls StructureRegistry.{1}(). Structure registration is excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 StructureRegistry.{1}()。嚴格內容重載排除結構註冊。"),
        ("Method '{0}' is not strict content-only: it calls ConsoleCommandRegistry.{1}(). Console command registration is excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它調用了 ConsoleCommandRegistry.{1}()。嚴格內容重載排除控制檯命令註冊。"),
        ("Method '{0}' is not strict content-only: it performs Harmony setup. Patch registration is excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它執行了 Harmony 設置。嚴格內容重載排除補丁註冊。"),
        ("Method '{0}' is not strict content-only: it mutates the live scene or inventory. Runtime scene side effects are excluded from strict content reload.", "方法「{0}」不是嚴格內容專用 : 它修改了實時場景或物品欄。嚴格內容重載排除運行時場景副作用。"),
        ("Method '{0}' is not strict content-only: {1}", "方法「{0}」不是嚴格內容專用 : {1}"),
        ("Method '{0}' registers a building definition using unsupported member '{1}'. Only basic/scriptless building definitions can be hot reloaded.", "方法「{0}」使用不受支持的成員「{1}」註冊建築定義。僅基礎/無腳本建築定義可熱重載。"),
        ("EnableHotReload('{0}') was called from '{1}'. The GUID must match the owning plugin's [BepInPlugin] GUID.", "EnableHotReload('{0}') 由「{1}」調用。GUID 必須與所屬插件的 [BepInPlugin] GUID 匹配。"),
        ("Host type '{0}' is abstract.", "宿主類型「{0}」是抽象的。"),
        ("Host type '{0}' is static and cannot be instantiated.", "宿主類型「{0}」是靜態的，無法實例化。"),
        ("Host type '{0}' must expose a parameterless constructor or a constructor taking BaseUnityPlugin.", "宿主類型「{0}」必須提供無參構造函數或接受 BaseUnityPlugin 的構造函數。"),
        ("Host type '{0}' must expose a parameterless constructor.", "宿主類型「{0}」必須提供無參構造函數。"),
        ("Strict content reload for {0}: {1}, {2} info, {3} skipped, {4} errors.", "嚴格內容重載 {0} : {1}，{2} 條信息，{3} 條跳過，{4} 個錯誤。"),
        ("Strict content reload for {0}: {1}, {2} info, {3} skipped, {4} errors. hash={5}.", "嚴格內容重載 {0} : {1}，{2} 條信息，{3} 條跳過，{4} 個錯誤。hash={5}。"),
        ("Cleared {0} item registrations owned by '{1}'.", "已清除「{1}」擁有的 {0} 個物品註冊。"),
        ("Cleared {0} building registrations owned by '{1}'.", "已清除「{1}」擁有的 {0} 個建築註冊。"),
        ("Cleared {0} liquid registrations owned by '{1}'.", "已清除「{1}」擁有的 {0} 個液體註冊。"),
        ("Cleared {0} liquid tile registrations owned by '{1}'.", "已清除「{1}」擁有的 {0} 個液體物塊註冊。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Generating CUCoreLib Structures..\n {0} ({1}/{2})\n\n", "正在生成 CUCoreLib 結構..\n {0}（{1}/{2}）\n\n"),
    };
}
