internal static class CUCoreLibTr
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Spawns all items from a given loot pool with zero gravity.", "【CUCoreLib】从指定战利品池中生成所有物品（零重力）。"),
        ("Spawns a vanilla prefab or CUCoreLib-registered item/building.", "【CUCoreLib】生成原版预设物体或 CUCoreLib 注册的物品/建筑。"),
        ("Places a vanilla or CUCoreLib-registered tile at the chosen block position.", "【CUCoreLib】在指定位置放置原版或 CUCoreLib 注册的物块。"),
        ("Sends a diagnostic bug report with debug logs. Thanks!", "【CUCoreLib】发送带调试日志的诊断性 bug 报告。感谢！"),
        ("Writes or updates CUCoreLib generated locale data. WARNING: Overrides EN.json", "【CUCoreLib】写入或更新 CUCoreLib 生成的本地化数据。警告: 会覆盖BepInEx\\config\\CUCoreLib\\Locales\\EN.json"),
        ("Prints the loaded BepInEx plugin list to the in-game console and Unity log.", "【CUCoreLib】将已加载的 BepInEx 插件列表打印到游戏内控制台和 BepInEx 日志。"),
        ("Strictly reloads item/liquid/recipe/locale content from a rebuilt mod DLL.", "【CUCoreLib】从重新构建的模组 DLL 严格重载物品/液体/配方/本地化内容。"),
        ("Enables automatic hot reloading after detecting a loaded mod DLL file change.", "【CUCoreLib】检测到已加载模组 DLL 文件变化后启用自动热重载。"),
        ("Manages a live top-right overlay of watched static fields for runtime debugging.", "【CUCoreLib】管理运行时调试的右上角静态字段监视覆盖层。"),
    };
    public static readonly (string En, string Zh)[] ArgShort =
    {
        ("category", "类别"),
        ("modGUID", "模组GUID"),
        ("id", "ID"),
        ("condition", "耐久"),
        ("count", "数量"),
        ("tileIndex", "物块ID"),
        ("path", "路径"),
        ("modGuid", "模组GUID"),
        ("enable", "启用"),
        ("action", "操作"),
        ("Type.member", "类型.成员"),
        ("description", "描述"),
        ("bool screenshot", "是否截图"),
        ("severity", "严重度"),
    };
    public static readonly (string En, string Zh)[] ArgLong =
    {
        ("The ID of the category to spawn from.", "要生成的类别 ID。"),
        ("Where to spawn the item", "物品生成位置"),
        ("Spawn position.", "生成位置。"),
        ("Tile position.", "物块位置。"),
        ("Optional BepInEx plugin GUID filter for the modded category. Use normal for no filter.", "（可选）模组类别的 BepInEx 插件 GUID 过滤器。使用 normal 表示不过滤。"),
        ("Item or object ID.", "物品或对象 ID"),
        ("Item condition.", "物品耐久。"),
        ("Number of objects to spawn.", "要生成的对象数量。"),
        ("Vanilla index or registered custom tile ID/index.", "原版索引或注册的自定义物块 ID/索引。"),
        ("Optional output path. Defaults to BepInEx/config/CUCoreLib/Locales/EN.json.", "（可选）输出路径。默认为 BepInEx/config/CUCoreLib/Locales/EN.json"),
        ("BepInEx plugin GUID to strictly reload from a rebuilt DLL.", "要从重新构建的 DLL 严格重载的 BepInEx 插件 GUID。"),
        ("BepInEx plugin GUID that previously called ContentReloadManager.EnableHotReload(GUID).", "先前调用过 ContentReloadManager.EnableHotReload(GUID) 的 BepInEx 插件 GUID。"),
        ("true to enable watch mode for that DLL, false to disable it.", "true 启用该 DLL 的监视模式，false 禁用它。"),
        ("add, remove, list, clear, show, or hide.", "add添加、remove移除、list列出、clear清除、show显示、hide隐藏。"),
        ("Reflected static field to watch, such as Namespace.Plugin.healthRate.", "要监视的反射静态字段，例如 Namespace.Plugin.healthRate。"),
        ("Optional description in quotation marks \"\". Optional, but highly recommended.", "（可选）用引号包裹的描述文本。可选，但强烈推荐。"),
        ("True/false. Captures the current game screen if true. Optional.", "true/false。为 true 时截取当前游戏画面。可选。"),
        ("low/medium/high/critical. Optional.", "low、medium、high、critical。（可选）"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Debug watch overlay hidden.", "调试监视覆盖层已隐藏。"),
        ("Debug watch overlay shown.", "调试监视覆盖层已显示。"),
        ("Cleared all debug watches.", "已清除所有调试监视。"),
        ("No active debug watches.", "没有活跃的调试监视。"),
        ("Enable must be 'true' or 'false'.", "启用值必须为「true」或「false」。"),
        ("Mod GUID was empty.", "模组 GUID 为空。"),
        ("Mod GUID was invalid.", "模组 GUID 无效。"),
        ("Strict content DLL reload is singleplayer-only.", "严格内容 DLL 重载仅限单人模式。"),
        ("Usage: spawncategory [category] [position] [modGUID]", "用法 : spawncategory [类别] [位置] [模组GUID]"),
        ("Usage: cuspawn [id]", "用法 : cuspawn [ID]"),
        ("Usage: settile [tileIndex or tileId] [position]", "用法 : settile [物块索引或物块ID] [位置]"),
        ("Usage: reloadcontent [modGuid]", "用法 : reloadcontent [模组GUID]"),
        ("Usage: autohotreload [modGuid] [enable]", "用法 : autohotreload [模组GUID] [启用]"),
        ("Usage: debugwatch [add|remove|list|clear|show|hide] [Type.member]", "用法 : debugwatch [add|remove|list|clear|show|hide] [类型.成员]"),
        ("Usage: debugwatch add [Type.member]", "用法 : debugwatch add [类型.成员]"),
        ("Usage: debugwatch remove [Type.member]", "用法 : debugwatch remove [类型.成员]"),
        ("Usage: bug-report [\"description text\"] [bool screenshot] [severity]", "用法 : bug-report [\"描述文本\"] [是否截图] [严重度]"),
        ("A bug report is already being sent.", "已在发送 bug 报告。"),
        ("Screenshot must be 'true' or 'false'.", "截图参数必须为「true」或「false」。"),
        ("Severity must be low, medium, high, or critical.", "严重度必须为 low、medium、high 或 critical。"),
        ("Sending! Thanks for contributing!", "正在发送！感谢贡献！"),
        ("CUCoreLib could not check for updates.", "CUCoreLib 无法检查更新。"),
        ("CUCoreLib could not read the latest release version.", "CUCoreLib 无法读取最新版本号。"),
        ("Strict content reload result was null.", "严格内容重载结果为空。"),
        ("Plugin type was null.", "插件类型为空。"),
        ("Compatibility report was null.", "兼容性报告为空。"),
        ("No invokable content methods were resolved from the reloaded assembly.", "无法从重载的程序集中解析出可调用的内容方法。"),
        ("Strict content reload completed.", "严格内容重载已完成。"),
        ("No rebuilt DLL source path was found. The loaded plugin path and runtime override path were both unavailable.", "未找到重新构建的 DLL 源路径。已加载的插件路径与运行时覆盖路径均不可用。"),
        ("No supported content reload entry methods were found. All discovered candidates were skipped.", "未找到受支持的内容重载入口方法。所有发现的候选方法均被跳过。"),
        ("No supported content reload entry methods were found after EnableHotReload(GUID). CUCoreLib could not discover any replayable supported content registrations.", "EnableHotReload(GUID) 之后未找到受支持的内容重载入口方法。CUCoreLib 未能发现任何可重放的内容注册。"),
        ("Awake() must call ContentReloadManager.EnableHotReload(GUID) with a literal GUID argument.", "Awake() 必须使用字面量 GUID 参数调用 ContentReloadManager.EnableHotReload(GUID)。"),
        ("ContentReloadManager.EnableHotReload() must be called from the owning plugin Awake().", "ContentReloadManager.EnableHotReload() 必须从所属插件的 Awake() 中调用。"),
        ("Host type was null.", "宿主类型为空。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("created locale at {0}", "已在 {0} 创建本地化文件"),
        ("Reloaded {0}!", "已重载 {0}！"),
        ("Spawned all items from category \"{0}\" at {1}.", "已在 {1} 生成类别「{0}」的所有物品。"),
        ("Placed tile {0} ({1}) at {2},{3}.", "已在 {2},{3} 放置地块 {0}（{1}）。"),
        ("Loaded mods ({0}):", "已加载的模组（共 {0} 个） : "),
        ("Active debug watches ({0}) - overlay {1}:", "活跃的调试监视（{0} 个）- 覆盖层 {1} : "),
        ("  {0} v{1} ({2})", "  {0} v{1}（{2}）"),
        ("Watching {0}.", "正在监视 {0}。"),
        ("Already watching {0}.", "已在监视 {0}。"),
        ("Stopped watching {0}.", "已停止监视 {0}。"),
        ("{0} is not currently watched.", "当前未在监视 {0}。"),
        ("Enabled automatic hot reload for {0} ({1}).", "已为 {0}（{1}）启用自动热重载。"),
        ("Disabled automatic hot reload for {0} ({1}).", "已为 {0}（{1}）禁用自动热重载。"),
        ("Loaded plugin GUID was not found: {0}", "未找到已加载的插件 GUID : {0}"),
        ("Hot reload is not enabled for '{0}'. Call ContentReloadManager.EnableHotReload(GUID) from Awake() first.", "「{0}」未启用热重载。请先在 Awake() 中调用 ContentReloadManager.EnableHotReload(GUID)。"),
        ("Invalid item category \"{0}\".", "无效的物品类别「{0}」。"),
        ("Could not find entity '{0}'.", "找不到实体「{0}」。"),
        ("'{0}' is not a valid tile index or registered tile ID.", "「{0}」不是有效的物块索引或已注册的物块 ID。"),
        ("Tile index '{0}' is not registered.", "物块ID「{0}」未注册。"),
        ("Failed to place tile '{0}' at block {1}.", "放置物块「{0}」在方块 {1} 失败。"),
        ("Unknown debugwatch action '{0}'.", "未知的 debugwatch 操作「{0}」。"),
        ("Ambiguous debug watch '{0}'. Use a more specific type path.", "调试监视「{0}」存在歧义。请使用更具体的类型路径。"),
        ("Could not find supported static field '{0}'.", "找不到受支持的静态字段「{0}」。"),
        ("Please wait {0} seconds before sending another bug report.", "请等待 {0} 秒后再发送另一个 bug 报告。"),
        ("<color=#66FF66>Bug report sent successfully. ID: {0}</color>", "<color=#66FF66>bug 报告发送成功。ID : {0}</color>"),
        ("<color=orange>Bug report failed: {0}</color>", "<color=orange>bug 报告发送失败 : {0}</color>"),
        ("<color=orange>Bug report failed: The bug report did not send for some reason! Uh-oh.</color>", "<color=orange>bug 报告发送失败 : 出于某种原因未能发送！呃-哦。</color>"),
        ("The bug report description has an opening quote but no closing quote. Usage: bug-report [\"description text\"] [bool screenshot] [severity]", "bug 报告描述有起始引号但没有结束引号。用法 : bug-report [\"描述文本\"] [是否截图] [严重度]"),
        ("<color=#FFA500>CUCoreLib update available! {0} -> {1}</color>", "<color=#FFA500>CUCoreLib 有可用更新！{0} -> {1}</color>"),
        ("CUCoreLib is up to date! Current: {0}, Latest: {1}", "CUCoreLib 已是最新版本！当前 : {0}，最新 : {1}"),
        ("Blocked during flexible hot reload: {0} called {1}.", "灵活热重载期间被阻止 : {0} 调用了 {1}。"),
        ("Blocked during flexible hot reload: {0} called {1}. {2}", "灵活热重载期间被阻止 : {0} 调用了 {1}。{2}"),
        ("Reloaded assembly did not contain plugin type '{0}'.", "重载的程序集中不包含插件类型「{0}」。"),
        ("Ran {0}().", "已运行 {0}()。"),
        ("Method '{0}' failed: {1}", "方法「{0}」执行失败 : {1}"),
        ("{0}: Reloaded assembly did not contain declaring type '{1}'.", "{0} : 重载的程序集不包含声明类型「{1}」。"),
        ("{0}: Reloaded assembly did not contain an invokable parameterless method.", "{0} : 重载的程序集不包含可调用的无参方法。"),
        ("Reload failed. Restored the previous successful content state for '{0}'.", "重载失败。已恢复「{0}」此前成功的内容状态。"),
        ("The selected rebuilt DLL path does not exist: {0}", "所选的重建 DLL 路径不存在 : {0}"),
        ("No [BepInPlugin] type matching '{0}' was found in the rebuilt DLL.", "在重建的 DLL 中未找到匹配「{0}」的 [BepInPlugin] 类型。"),
        ("Compatibility scan failed: {0}", "兼容性扫描失败 : {0}"),
        ("Plugin '{0}' must define an Awake() method with a ContentReloadManager.EnableHotReload(GUID) call.", "插件「{0}」必须定义一个包含 ContentReloadManager.EnableHotReload(GUID) 调用的 Awake() 方法。"),
        ("Awake() called EnableHotReload('{0}') but CUCoreLib could not discover any replayable supported content registrations after the marker.", "Awake() 调用了 EnableHotReload('{0}')，但 CUCoreLib 在该标记之后未能发现任何可重放的内容注册。"),
        ("Method '{0}' has no method body. Strict content reload can only inspect methods with IL bodies.", "方法「{0}」没有方法体。严格内容重载只能检查包含 IL 方法体的方法。"),
        ("Method '{0}' did not call a supported content registration API. Replay roots must directly register supported content or call helper methods that do.", "方法「{0}」未调用受支持的内容注册 API。重放根必须直接注册受支持内容，或调用执行该操作的辅助方法。"),
        ("Method '{0}' touches multiple supported registration surfaces. CUCoreLib can often recover by replaying deeper helper methods, but this method itself is not a direct replay leaf.", "方法「{0}」触及多个受支持的注册面。CUCoreLib 通常可通过重放更深层的辅助方法恢复，但该方法本身不是直接重放叶节点。"),
        ("Awake() must call ContentReloadManager.EnableHotReload(\"{0}\").", "Awake() 必须调用 ContentReloadManager.EnableHotReload(\"{0}\")。"),
        ("Awake() called ContentReloadManager.EnableHotReload(\"{0}\") but the plugin GUID is \"{1}\".", "Awake() 调用了 ContentReloadManager.EnableHotReload(\"{0}\")，但插件 GUID 是「{1}」。"),
        ("Method '{0}' is tagged for stage '{1}' but does not call the matching supported registration API.", "方法「{0}」标记了阶段「{1}」，但未调用匹配的受支持注册 API。"),
        ("Method '{0}' calls BuildingEntityRegistry.{1}(). Only basic building registration is supported during strict content reload.", "方法「{0}」调用了 BuildingEntityRegistry.{1}()。严格内容重载期间仅支持基础建筑注册。"),
        ("Method '{0}' is not strict content-only: it calls ModOptionsRegistry.{1}(). Mod options are excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 ModOptionsRegistry.{1}()。严格内容重载排除模组选项。"),
        ("Method '{0}' is not strict content-only: it calls SaveRegistry.{1}(). Save providers are excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 SaveRegistry.{1}()。严格内容重载排除存档提供器。"),
        ("Method '{0}' is not strict content-only: it calls {1}.{2}(). Status and moodle registration are excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 {1}.{2}()。严格内容重载排除状态与状态图标注册。"),
        ("Method '{0}' is not strict content-only: it calls multiplayer registration/setup code. Multiplayer hooks are excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了多人游戏注册/设置代码。严格内容重载排除多人游戏钩子。"),
        ("Method '{0}' is not strict content-only: it calls TileRegistry.{1}(). Tile registration is excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 TileRegistry.{1}()。严格内容重载排除地块注册。"),
        ("Method '{0}' is not strict content-only: it calls StructureRegistry.{1}(). Structure registration is excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 StructureRegistry.{1}()。严格内容重载排除结构注册。"),
        ("Method '{0}' is not strict content-only: it calls ConsoleCommandRegistry.{1}(). Console command registration is excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它调用了 ConsoleCommandRegistry.{1}()。严格内容重载排除控制台命令注册。"),
        ("Method '{0}' is not strict content-only: it performs Harmony setup. Patch registration is excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它执行了 Harmony 设置。严格内容重载排除补丁注册。"),
        ("Method '{0}' is not strict content-only: it mutates the live scene or inventory. Runtime scene side effects are excluded from strict content reload.", "方法「{0}」不是严格内容专用 : 它修改了实时场景或物品栏。严格内容重载排除运行时场景副作用。"),
        ("Method '{0}' is not strict content-only: {1}", "方法「{0}」不是严格内容专用 : {1}"),
        ("Method '{0}' registers a building definition using unsupported member '{1}'. Only basic/scriptless building definitions can be hot reloaded.", "方法「{0}」使用不受支持的成员「{1}」注册建筑定义。仅基础/无脚本建筑定义可热重载。"),
        ("EnableHotReload('{0}') was called from '{1}'. The GUID must match the owning plugin's [BepInPlugin] GUID.", "EnableHotReload('{0}') 由「{1}」调用。GUID 必须与所属插件的 [BepInPlugin] GUID 匹配。"),
        ("Host type '{0}' is abstract.", "宿主类型「{0}」是抽象的。"),
        ("Host type '{0}' is static and cannot be instantiated.", "宿主类型「{0}」是静态的，无法实例化。"),
        ("Host type '{0}' must expose a parameterless constructor or a constructor taking BaseUnityPlugin.", "宿主类型「{0}」必须提供无参构造函数或接受 BaseUnityPlugin 的构造函数。"),
        ("Host type '{0}' must expose a parameterless constructor.", "宿主类型「{0}」必须提供无参构造函数。"),
        ("Strict content reload for {0}: {1}, {2} info, {3} skipped, {4} errors.", "严格内容重载 {0} : {1}，{2} 条信息，{3} 条跳过，{4} 个错误。"),
        ("Strict content reload for {0}: {1}, {2} info, {3} skipped, {4} errors. hash={5}.", "严格内容重载 {0} : {1}，{2} 条信息，{3} 条跳过，{4} 个错误。hash={5}。"),
        ("Cleared {0} item registrations owned by '{1}'.", "已清除「{1}」拥有的 {0} 个物品注册。"),
        ("Cleared {0} building registrations owned by '{1}'.", "已清除「{1}」拥有的 {0} 个建筑注册。"),
        ("Cleared {0} liquid registrations owned by '{1}'.", "已清除「{1}」拥有的 {0} 个液体注册。"),
        ("Cleared {0} liquid tile registrations owned by '{1}'.", "已清除「{1}」拥有的 {0} 个液体物块注册。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Generating CUCoreLib Structures..\n {0} ({1}/{2})\n\n", "正在生成 CUCoreLib 结构..\n {0}（{1}/{2}）\n\n"),
    };
}
