[概要]
"GUID" = "com.rushellxyz.newfirearms/autoarsenal"
"翻译版本" = "v1.0.0"
"模组版本" = "v2.0"
[Locale]
# Original: AA-12
"autoarsenal.aa12" = "AA-12霰弹枪"
# Original: A fully automatic shotgun, shockingly small recoil. Uses Shotgun mags
"autoarsenal.aa12dsc" = "一把全自动霰弹枪，后坐力惊人地小。使用霰弹弹匣。"
# Original: Karabiner 98k
"autoarsenal.kar98k" = "Karabiner 98k步枪"
# Original: A supprisingly accurate rifle, somehow still works. Uses 5.56 rounds.
"autoarsenal.kar98kdsc" = "一支异常精准的步枪，不知为何还能用。使用5.56毫米子弹。"
# Original: M1918 Tankgewehr
"autoarsenal.m1918tankgewehr" = "M1918反坦克步枪"
# Original: You dont know whats more horrifying - this or the thing it was made to destroy... Uses 13.2mm TuF rounds.
"autoarsenal.m1918tankgewehrdsc" = "你不知道哪个更可怕——这个还是它用来摧毁的东西...使用13.2mm TuF子弹。"
# Original: MP7
"autoarsenal.mp7" = "MP7冲锋枪"
# Original: Very fast firing SMG. Can fit small magazines or SMG magazines
"autoarsenal.mp7dsc" = "射速极快的冲锋枪。可使用小型弹匣或冲锋枪弹匣。"
# Original: Revolver
"autoarsenal.revolver" = "左轮手枪"
# Original: Heavy caliber handgun. uses .357 Magnum rounds
"autoarsenal.revolverdsc" = "大口径手枪。使用.357马格南子弹。"
# Original: 13.2mm TuF
"autoarsenal.132tuf" = "13.2mm TuF子弹"
# Original: a round of truly unholy caliber... Can only be loaded directly
"autoarsenal.132tufdsc" = "一发真正亵渎口径的子弹...只能直接装填。"
# Original: .357 Magnum
"autoarsenal.357magnum" = ".357马格南"
# Original: A big handgun round. Can only be loaded directly.
"autoarsenal.357magnumdsc" = "一种大口径手枪子弹。只能直接装填。"
# Original: Box of .357 Magnum
"autoarsenal.boxof357magnum" = ".357马格南弹药盒"
# Original: A box made to hold .357 rounds, can hold up to 18 of them
"autoarsenal.boxof357magnumdsc" = "专为容纳.357子弹设计的盒子，最多可装18发。"
# Original: Case of 13.2mm TuF
"autoarsenal.caseof132tuf" = "13.2mm TuF弹箱"
# Original: So much power in such a small package.
"autoarsenal.caseof132tufdsc" = "如此小的包装蕴含如此强大的力量。"
# Original: Shotgun magazine
"autoarsenal.shotgunmag" = "霰弹枪弹匣"
# Original: A special magazaine made to hold 32 12-Gauge rounds.
"autoarsenal.shotgunmagdsc" = "一种专为容纳32发12号口径霰弹而设计的特殊弹匣。"
