[概要]
"GUID" = "com.balaur.BetterLogic"
"翻译版本" = "1.0.1"
"模组版本" = "1.0.5"
[Locale]
# Original: <color=purple>Crafting</color>: Prefer on floor
"gamesetprefer_on_floor" = "<color=purple>制作</color>：优先使用地面材料"
# Original: Use materials on the floor before things in your inventory.
"gamesetprefer_on_floordsc" = "在消耗背包物品前，先使用地面上的材料。"
# Original: <color=purple>Crafting</color>: Prefer not containers
"gamesetprefer_not_container" = "<color=purple>制作</color>：延后使用容器"
# Original: Use containers, like bags, later.
"gamesetprefer_not_containerdsc" = "延后使用容器（如背包）。"
# Original: <color=purple>Crafting</color>: Prefer not wearables
"gamesetprefer_not_wearable" = "<color=purple>制作</color>：延后使用可穿戴物品"
# Original: Use wearables, like clothing, later.
"gamesetprefer_not_wearabledsc" = "延后使用可穿戴物品（如衣物）。"
# Original: <color=purple>Crafting</color>: Prefer held
"gamesetprefer_on_body" = "<color=purple>制作</color>：优先使用身上材料"
# Original: Use materials in your hands/mouth/back before things in your inventory.
"gamesetprefer_on_bodydsc" = "在消耗背包物品前，先使用手上/嘴里/背上的材料。"
# Original: <color=purple>Crafting</color>: Prefer higher quality
"gamesetprefer_high_quality" = "<color=purple>制作</color>：优先使用高质量物品"
# Original: Use items of lower quality, like lower hammering, later.
"gamesetprefer_high_qualitydsc" = "延后使用低质量物品（如锤击值较低的物品）。"
# Original: <color=purple>Crafting</color>: Prefer lower value
"gamesetprefer_low_value" = "<color=purple>制作</color>：优先使用低价值物品"
# Original: Use items of higher trading value later.
"gamesetprefer_low_valuedsc" = "延后使用交易价值较高的物品。"
# Original: <color=purple>Crafting</color>: Prefer lower condition
"gamesetprefer_low_condition" = "<color=purple>制作</color>：优先使用低耐久物品"
# Original: Use items with higher condition later.
"gamesetprefer_low_conditiondsc" = "延后使用耐久较高的物品。"
# Original: <color=purple>Storage (Liquid)</color>: Allow stacking into mixed
"gamesetliquids_can_mix" = "<color=purple>储存液体</color>：允许液体混合"
# Original: Allow a pouring this liquid into a bottle that has other liquids, only if it already has some of this liquid.
"gamesetliquids_can_mixdsc" = "允许将这种液体倒入已装有其他液体的瓶子中，但前提是瓶子里已经有一些这种液体。"
# Original: <color=purple>Storage (Liquid)</color>: Allow filling new bottles
"gamesetliquids_can_fill_new_bottles" = "<color=purple>储存液体</color>：允许装满新瓶子"
# Original: Allow liquids to fill bottles that are empty.
"gamesetliquids_can_fill_new_bottlesdsc" = "允许液体装满空瓶子。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer liquids unmixed
"gamesetcompare_liquid_unmixed_enabled" = "<color=purple>储存液体</color>：优先使用未混合液体"
# Original: If 'Allow liquids to mix' is enabled, fill containers with the fewest different liquids.
"gamesetcompare_liquid_unmixed_enableddsc" = "如果“允许液体混合”启用，则填充含有不同液体种类最少的容器。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer liquid stack
"gamesetcompare_liquid_stacking_enabled" = "<color=purple>储存液体</color>：优先使用混合液体"
# Original: Fill containers that have the highest amount of this liquid first.
"gamesetcompare_liquid_stacking_enableddsc" = "优先填充含有该液体数量最多的容器。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer low weight liquid containers
"gamesetcompare_liquid_weight_enabled" = "<color=purple>储存液体</color>：优先使用重量比高的液体容器"
# Original: Prefer containers that have the lowest weight to highest liquid ratio when full.
"gamesetcompare_liquid_weight_enableddsc" = "优先使用装满时重量与液体比例最低的容器。"
# Original: <color=purple>Storage</color>: Notify where stored
"gamesetnotify_where_stored" = "<color=purple>储存</color>：通知储存位置"
# Original: Create a popup that specifies where the output of crafting recipes was placed.
"gamesetnotify_where_storeddsc" = "创建一个弹出窗口，指明制作配方的输出放置位置。"
# Original: <color=purple>Storage</color>: Store in containers first
"gamesetstore_in_containers_first" = "<color=purple>储存</color>：优先存放在容器中"
# Original: Put crafted items into containers first, rather than in hands/mouth/back.
"gamesetstore_in_containers_firstdsc" = "优先将制作物品放入容器，而非手中/嘴里/背上。"
# Original: <color=purple>Storage</color>: Prefer matched container type
"gamesetcompare_storage_type" = "<color=purple>储存</color>：优先使用匹配的容器类型"
# Original: When storing crafted items, choose containers specific to this item type, such as the material pouch for materials.
"gamesetcompare_storage_typedsc" = "当储存制作物品时，选择该物品类型专用的容器，例如材料的材料袋。"
# Original: <color=purple>Storage</color>: Prefer higher container reduction
"gamesetcompare_storage_reduction" = "<color=purple>储存</color>：优先使用负重减免更高的容器"
# Original: When storing crafted items, prefer containers that have a better encumbrance reduction.
"gamesetcompare_storage_reductiondsc" = "当储存制作物品时，优先使用负重减免更好的容器。"
# Original: <color=purple>Storage</color>: Prefer fuller container
"gamesetcompare_storage_full" = "<color=purple>储存</color>：优先使用容量占用更高的容器"
# Original: When storing crafted items, prefer containers that are more full.
"gamesetcompare_storage_fulldsc" = "当储存制作物品时，优先使用容量占用更高的容器。"
# Original: <color=purple>Storage</color>: Prefer larger containers
"gamesetcompare_storage_capacity" = "<color=purple>储存</color>：优先使用容量更大的容器"
# Original: When storing crafted items, prefer containers that are larger.
"gamesetcompare_storage_capacitydsc" = "当储存制作物品时，优先使用容量更大的容器。"
# Original: <color=purple>Storage</color>: Prefer best condition container
"gamesetcompare_storage_best_condition" = "<color=purple>储存</color>：优先使用耐久最高的容器"
# Original: When storing crafted items, prefer containers that have higher condition.
"gamesetcompare_storage_best_conditiondsc" = "当储存制作物品时，优先使用耐久更高的容器。"