[概要]
"GUID" = "me.danimineiro.modsettings"
"翻译版本" = "v1.0.0"
"模组版本" = "v1.0.2.1"
[Locale]
# Original: Mod Settings
"me.danimineiro.modsettings.MOD_NAME" = "模组设置"
# Original: Your installed version of {0} [<color=#AC3232>{1}</color>] is <color=#AC3232>outdated</color>.<br>The newest version is [<color=#6ABE30>{2}.</color>]. Check github for a new version.
"me.danimineiro.modsettings.MOD_VERSION_OUTDATED" = "你安装的 {0} 版本 [<color=#AC3232>{1}</color>] 已<color=#AC3232>过时</color>。<br>最新版本为 [<color=#6ABE30>{2}</color>]。请前往 GitHub 查看新版本。"
# Original: You're on the <color=#6ABE30>newest version</color> of {0} [<color=#6ABE30>{1}</color>].
"me.danimineiro.modsettings.MOD_VERSION_NEWEST" = "你正在使用 {0} 的<color=#6ABE30>最新版本</color> [<color=#6ABE30>{1}</color>]。"
# Original: Click the button to check out the latest release of <color=#8F8F8F>{0}</color> on {1}:
"me.danimineiro.modsettings.CHECKOUT_GITHUB" = "点击按钮在 {1} 上查看 <color=#8F8F8F>{0}</color> 的最新版本："
# Original: GitHub
"me.danimineiro.modsettings.GITHUB" = "GitHub"
[GameSettingDropdown/Label]
"Select Mod" = "选择模组"
[MouseOver/TitleBack/Title]
"Select which Mods settings you want to change." = "选择你想要更改的模组设置。"
[leftObject/textObject]
"Click the button to check out the latest release of <color=ys0>Mod Settings</color> on GitHub:" = "点击按钮在 GitHub 上查看<color=ys0> 模组设置 </color>的最新版本："
[rootObject/textObject]
"[Reg]^You're on the <color=ys0>newest version</color> of Mod Settings \[<color=ys1>(.+)</color>\]\.$" = "你正在使用模组设置的<color=ys0>最新版本</color> [<color=ys1>$1</color>]。"
