[概要]
"GUID" = "CUZoomPlus"
"翻译版本" = "v1.0.0"
"模组版本" = "v1.0.1"
[Locale]
# Original: View scale
"cuzoomplus.zoom.multiplier" = "123"
# Original: The current view scale. It is also updated when the zoom keys are pressed.
"cuzoomplus.zoom.multiplierdsc" = "wqedas"
