[概要]
"GUID" = "com.rushellxyz.newclothing"
"翻译版本" = "1.0.0"
"模组版本" = "1.6.2"
[Locale]
# Original: Arm warmers
"armwarmers" = "护臂套"
# Original: A pair of arm warmers. Provides some insulation against the cold.
"armwarmersdsc" = "一副护臂套。有一定保暖作用。"
# Original: Holiday hat
"holidayhat" = "节日帽"
# Original: You've heard that people wear these for some kind of special occasion, though you're not sure what it's about. It's nice that you were sent with one, at least.
"holidayhatdsc" = "你听说人们会在某些特殊时间佩戴这些，虽然你并不清楚具体原因。但至少有人送你一件倒也挺不错。"
# Original: Combat Boots
"newclothing.boots" = "战斗靴"
# Original: A pair of heavy-duty leather boots, will last you quite a while and is fairly protective.
"newclothing.bootsdsc" = "一双厚重皮靴，相当耐穿且防护性不错。"
# Original: Crop shirt
"newclothing.cropshirt" = "露脐衬衫"
# Original: A crop shirt made to cover your thorax. Provides mild insulation and some protection
"newclothing.cropshirtdsc" = "一件覆盖躯干的露脐衬衫。提供轻度保暖和一定防护。"
# Original: Crop T-Shirt
"newclothing.croptshirt" = "露脐T恤"
# Original: A crop t-shirt made to cover your thorax and upper arms. Provides medium insulation and some protection
"newclothing.croptshirtdsc" = "一件覆盖躯干和上臂的露脐T恤。提供中等保暖和一定防护。"
# Original: Jeans
"newclothing.jeans" = "牛仔裤"
# Original: Jeans, provides protection and insulation. Have an exceptional high durability
"newclothing.jeansdsc" = "牛仔裤，提供防护和保暖。耐久度异常高。"
# Original: Long Sleeve Shirt
"newclothing.longshirt" = "长袖衬衫"
# Original: A long-sleeve shirt meant to cover your upper torso. Provides good insulation and some protection
"newclothing.longshirtdsc" = "一件覆盖上半身的长袖衬衫。提供良好保暖和一定防护。"
# Original: Shirt
"newclothing.shirt" = "衬衫"
# Original: A shirt made to cover your thorax and abdomen. Provides medium insulation and some protection
"newclothing.shirtdsc" = "一件覆盖胸部和腹部的衬衫。提供中等保暖和一定防护。"
# Original: Shorts
"newclothing.shorts" = "短裤"
# Original: Shorted version of jeans, provides some protection and insulation. Have an exceptional high durability
"newclothing.shortsdsc" = "牛仔裤的短款，提供一定防护和保暖。耐久度异常高。"
# Original: Socks
"newclothing.socks" = "袜子"
# Original: A pair of socks. Provides protection for yout paws. Have no effect against glass shards.
"newclothing.socksdsc" = "一双袜子。保护你的脚掌。对玻璃碎片无效。"
# Original: Thigh highs
"newclothing.thighhighs" = "过膝袜"
# Original: A pair of thigh highs. Provides protection and insulation against the cold.
"newclothing.thighhighsdsc" = "一双过膝袜。提供防护和御寒。"
# Original: T-Shirt
"newclothing.tshirt" = "T恤"
# Original: A t-shirt made to cover your thorax, abdomen and upper arms. Provides good insulation and some protection
"newclothing.tshirtdsc" = "一件覆盖胸部、腹部和上臂的T恤。提供良好保暖和一定防护。"