[概要]
"GUID" = "com.rushellxyz.newfirearms"
"翻译版本" = "1.0.1"
"模组版本" = "1.5.4"
[Locale]
# Original: Bolt-action rifle
"makeshiftrifle" = "栓动步枪"
# Original: TODO
"makeshiftrifledsc" = "待办"
# Original: Glock 18
"newfirearms.glock18" = "格洛克18"
# Original: A select-fire 9mm handgun. Functionaly it's exaclty like glock 17 but with option for full-auto. Can only fit small magazines
"newfirearms.glock18dsc" = "一把可选择射击模式的9毫米手枪。功能上与格洛克17完全相同，但增加了全自动选项。只能装填手枪弹匣。"
# Original: M1911
"newfirearms.m1911" = "M1911手枪"
# Original: An old, small, magazine-feed 9mm handgun. Would do well in combat. Can only fit m1911 magazines
"newfirearms.m1911dsc" = "一把老旧的小型9毫米弹匣供弹手枪。适合战斗使用。只能装填M1911弹匣。"
# Original: Makeshift pistol
"newfirearms.makeshiftpistol" = "简易手枪"
# Original: A crude basic handgun, holds two 9mm rounds in chambers. Doesn't have safety. Won't last for a long. Consider switching to more capacble firearms in case of combat
"newfirearms.makeshiftpistoldsc" = "一把粗糙的基础手枪，弹膛内可容纳两发9毫米子弹。没有保险。使用寿命不长。如需战斗，考虑换用更趁手的武器。"
# Original: MP5
"newfirearms.mp5" = "MP5冲锋枪"
# Original: A stocked select-fire submachine gun. Can fit small magazines or SMG magazines
"newfirearms.mp5dsc" = "一把带枪托的可切换射击模式冲锋枪。可装填手枪弹匣或冲锋枪弹匣。"
# Original: P90
"newfirearms.p90" = "P90冲锋枪"
# Original: A 9mm bullpup submachine gun, uses specialized P90 magazines.
"newfirearms.p90dsc" = "一把9毫米无托式冲锋枪，使用专用的P90弹匣。"
# Original: Saiga
"newfirearms.saiga" = "Saiga"
# Original: TODO
"newfirearms.saigadsc" = "待办"
# Original: Sawed off
"newfirearms.sawedoff" = "锯短霰弹枪"
# Original: An level-action shotgun with cutoff barrels, only holds 2 rounds. Can be loaded with any 12-gauge round
"newfirearms.sawedoffdsc" = "一把截短枪管的杠杆式霰弹枪，只能装填2发弹药。可装填任何12号口径弹药。"
# Original: Semi-auto shotgun
"newfirearms.semiautoshotgun" = "半自动霰弹枪"
# Original: TODO
"newfirearms.semiautoshotgundsc" = "待办"
# Original: UZI
"newfirearms.uzi" = "UZI冲锋枪"
# Original: A full-auto 9mm submachine gun. The recoil is rather, unplessant. Can fit small magazines or SMG magazines
"newfirearms.uzidsc" = "一把全自动9毫米冲锋枪。后坐力相当，令人不快。可使用手枪弹匣或冲锋枪弹匣。"
# Original: Vector
"newfirearms.vector" = "Vector冲锋枪"
# Original: An 9mm selct-fire submachine gun with a special recoil-reduction mechanism and a low fire rate. Can only fit smg magazines
"newfirearms.vectordsc" = "一把使用特殊减后坐力机制且射速较低的9毫米可切换射击模式冲锋枪。只能装填冲锋枪弹匣。"
# Original: Glock 17
"pistol" = "格洛克17"
# Original: A common 9mm semi-auto handgun. You remember your capitors carrying it back on Earth. Can only fit small magazines
"pistoldsc" = "一把常见的9毫米半自动手枪。你记得在地球上时，看管你们的人曾随身携带过它。只能装填手枪弹匣。"
# Original: Carbine
"rifle" = "卡宾枪"
# Original: TODO
"rifledsc" = "待办"
# Original: Pump-action shotgun
"shotgun" = "泵动霰弹枪"
# Original: TODO
"shotgundsc" = "待办"
# Original: Box of 12gauge
"boxof12gauge" = "12号霰弹弹盒"
# Original: TODO
"boxof12gaugedsc" = "待办"
# Original: Box of 5.56
"boxof556" = "5.56毫米弹盒"
# Original: TODO
"boxof556dsc" = "待办"
# Original: Box of 9mm
"boxof9mm" = "9毫米弹盒"
# Original: An box made to hold up to thirty-two 9mm round. Use to remove round
"boxof9mmdsc" = "可容纳最多32发9毫米子弹的弹盒。用于退弹。"
# Original: M1911 magazine
"newfirearms.m1911mag" = "M1911弹匣"
# Original: An handgun magazine. Can hold up to eight 9mm rounds in it
"newfirearms.m1911magdsc" = "一个手枪弹匣。可容纳最多8发9毫米子弹。"
# Original: P90 magazine
"newfirearms.p90mag" = "P90弹匣"
# Original: TODO
"newfirearms.p90magdsc" = "待办"
# Original: Saiga magazine
"newfirearms.saigamag" = "Saiga弹匣"
# Original: TODO
"newfirearms.saigamagdsc" = "待办"
# Original: SMG magazine
"newfirearms.smgmag" = "冲锋枪弹匣"
# Original: An magazine for use in subamchine guns. Can hold up to thirty 9mm rounds
"newfirearms.smgmagdsc" = "一个用于冲锋枪的弹匣。可容纳最多30发9毫米子弹。"
# Original: Rifle magazine
"riflemagazine" = "步枪弹匣"
# Original: TODO
"riflemagazinedsc" = "待办"
# Original: Small magazine
"smallmagazine" = "手枪弹匣"
# Original: An handgun magazine. Can hold up to seventeen 9mm rounds in it
"smallmagazinedsc" = "一个手枪弹匣。可容纳最多17发9毫米子弹。"
# Original: 12gauge birdshot
"12gaugebird" = "12号鸟弹"
# Original: An variation of 12gauge with more pellets and higher spread. Can be loaded into shotguns, or directly into the chamber if the gun's bolt is open.
"12gaugebirddsc" = "12号鸟弹的变种，弹丸更多、散布更大。可直接装入霰弹枪，或直接上膛（需打开枪机）。"
# Original: 12gauge slugshot
"12gaugeslug" = "12号独头弹"
# Original: An variation of 12gauge with only one big pellet. Can be loaded into shotguns, or directly into the chamber if the gun's bolt is open
"12gaugeslugdsc" = "12号独头弹的变种，只有一枚大弹丸。可直接装入霰弹枪，或直接上膛（需打开枪机）。"
# Original: 9mm hollow round
"9mmhollow" = "9毫米空尖弹"
# Original: An variation of 9mm round with hollow points, deals more damage against living targets, but not as penetrating. Can be loaded into magazines, or directly into the chamber if the gun's bolt is open.
"9mmhollowdsc" = "9毫米子弹的空尖弹变种，对活体目标伤害更高，但穿透力较弱。可装入弹匣，或直接上膛（需打开枪机）。"
# Original: 9mm venomus round
"9mmvenomus" = "9毫米毒弹"
# Original: An variation of 9mm round with venomus points, deals toxicosis against living targets, but not as penetrating. Can be loaded into magazines, or directly into the chamber if the gun's bolt is open.
"9mmvenomusdsc" = "9毫米子弹的毒弹变种，对活体目标造成中毒效果，但穿透力较弱。可装入弹匣，或直接上膛（需打开枪机）。"
# Original: Gun jamming
"runsetnewfirearms.gunjamming" = "枪械卡壳"
# Original: Can guns jam?
"runsetnewfirearms.gunjammingdsc" = "枪械会卡壳吗？"
# Original: Gun damage multiplier
"runsetnewfirearms.gundmgmult" = "枪械伤害倍率"
# Original: Gun eject casing
"runsetnewfirearms.gunejectcasing" = "枪械抛壳"
# Original: Should guns eject casings after firing?
"runsetnewfirearms.gunejectcasingdsc" = "射击后枪械应抛壳吗？"
# Original: Stun hitbox size
"runsetnewfirearms.stunhitbox" = "眩晕判定框大小"
# Original: When you shoot above or below an enemy, they still get stunned. This determines the size of the stun hitbox.
"runsetnewfirearms.stunhitboxdsc" = "当你射击敌人上方或下方时，他们仍会被眩晕。此选项决定眩晕判定框的大小。"
# Original: Firearm handling course
"newfirearms.firearmhandlingcourse" = "枪械操作训练课程"
# Original: Unlock at level 4
"newfirearms.firearmhandlingcourselock" = "抵达第四层以解锁"
[Tutorial]
# Original: Welcome to the firearm handling course
"Welcome to the firearm handling course" = "欢迎来到枪械操作训练课程"
# Original: Starting off from treating gun related injuries
"Starting off from treating gun related injuries" = "从治疗枪伤开始"
# Original: Uh oh, seems like you are bleeding really bad from your left leg.
"Uh oh, seems like you are bleeding really bad from your left leg." = "哎呀，你的左腿似乎血流不止。"
[Global]
# Original: Firearm handling course
"Firearm handling course" = "枪械操作训练课程"
# Original: How much damage guns deal to tiles, enemies and other players? Gets futrher multiplier by PVPDamageMultiplier rule when hitting another player
"How much damage guns deal to tiles, enemies and other players? Gets futrher multiplier by PVPDamageMultiplier rule when hitting another player" = "枪械对地形、敌人和其他玩家造成多少伤害？击中另一玩家时，会额外乘以PVPDamageMultiplier规则的倍率。"
# Original: How much damage guns deal to tiles and enemies?
"How much damage guns deal to tiles and enemies?" = "枪械对地形和敌人造成多少伤害？"