[概要]
"GUID" = "com.dragoon_103.regrowthserums"
"翻译版本" = "1.0.0"
"模组版本" = "1.7.1"
[Talker]
"I... I can see!" = "我...我能看见了！"
"Nothing left..." = "没有剩余的了..."
"I don't have an empty eye socket to fit this into..." = "我没有空眼窝能容纳它..."
"Nothing to regrow here... Thankfully..." = "这里没什么可再生的...谢天谢地..."
"Not yet... Its too damaged..." = "还不行...它损伤太严重了..."
"Don't think this will work on my eyes..." = "我觉得这对我的眼睛不会起作用..."
"I think my face is just fine enough" = "我觉得我的脸已经够好了"
[main]
# Original: Eye Growth Serum
"dragoon_103.eyegrowthserum" = "眼球生长血清"
# Original: Administer to missing eye socket to stimulate brain tissue to regrow eye tissue, WARNING: Do not use in conjunction while under effects of neuron regeneration sickness
"dragoon_103.eyegrowthserumdsc" = "对缺失的眼窝注射，刺激脑组织重新生长出眼球组织。警告：切勿在神经元再生病效果期间使用。"
# Original: Limb Re-Growth Serum
"dragoon_103.limbgrowthserum" = "肢体再生血清"
# Original: An experimental drug that rapidly converts existing tissue into new stem cell growth. Administer to a body part with a missing adjacent limb
"dragoon_103.limbgrowthserumdsc" = "一种实验性药物，可快速将现有组织转化为新的干细胞组织。对缺失相邻肢体的部位注射。"
# Original: Disfigurement Serum
"dragoon_103.jawgrowthserum" = "畸形修复血清"
# Original: Administer to missing face parts to inject stem cell tissue to regrow jaw bone and tissue, WARNING: Extreme pain while regrowing
"dragoon_103.jawgrowthserumdsc" = "对缺失的面部部位注射干细胞组织，以重新生长颌骨及组织。警告：再生过程中极度疼痛。"