using System;
namespace A.Multi_Mod.Chinese.Localization.Mods.GunsawGenetics;
internal static class GunsawGeneticsTr
{
    public static readonly (string En, string Zh)[] Logs =
    {
        ("[ERROR] Species picker not yet initialized.", "[错误] 物种选择器尚未初始化。"),
        ("[ERROR] You must be playing as Mercenary to use this command.", "[错误] 你必须以 Mercenary 身份进行游戏才能使用此命令。"),
        ("[ERROR] You must be playing as Baron to use this command.", "[错误] 你必须以 Baron 身份进行游戏才能使用此命令。"),
        ("[ERROR] PlayerCamera not found.", "[错误] 未找到 PlayerCamera。"),
        ("Running Last Stand visual/audio sequence.", "正在播放「背水一战」的视觉/音频序列。"),
        ("Forced post-mindwipe state (Hollow moodle + aftermath effects).", "已强制进入精神抹除后的状态（空洞状态图标 + 后续效果）。"),
        ("Cleared forced mindwipe state and vignette.", "已清除强制精神抹除状态与画面暗角。"),
        ("Gunsaw Genetics debug commands:", "Gunsaw Genetics 调试命令 : "),
        ("[ERROR] Usage: GG switchspecies <species> <true/false> [keepStats true/false]", "[错误] 用法 : GG switchspecies <物种> <true/false> [keepStats true/false]"),
        ("[ERROR] Usage: GG merchollow <0-10>", "[错误] 用法 : GG merchollow <0-10>"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("Switched to {0}.", "已切换到 {0}。"),
        ("Mercenary Hollow level set to {0}.", "Mercenary 的空洞等级已设为 {0}。"),
        ("Baron horns broken set to {0}.", "Baron 已折断的角数已设为 {0}。"),
        ("Cleared {0} cached sprite(s), refreshed WoundView, hands, and in-world sprites for {1}.", "已清除 {0} 份贴图缓存，并刷新了 {1} 的伤势视图、手部与场景内贴图。"),
        ("[ERROR] Usage: GG <subcommand> [args...]. Available: {0}", "[错误] 用法 : GG <子命令> [参数...]。可用 : {0}"),
        ("[ERROR] Unknown GG subcommand: {0}. Available: {1}", "[错误] 未知的 GG 子命令 : {0}。可用 : {1}"),
        ("[ERROR] Unknown species: {0}", "[错误] 未知物种 : {0}"),
        ("[ERROR] Invalid heal argument: {0} (expected true/false)", "[错误] heal 参数无效 : {0}（应为 true/false）"),
        ("[ERROR] Invalid keepStats argument: {0} (expected true/false)", "[错误] keepStats 参数无效 : {0}（应为 true/false）"),
        ("[ERROR] Usage: GG debugbaronhorns <0-{0}>", "[错误] 用法 : GG debugbaronhorns <0-{0}>"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("string subcommand", "子命令（文本）"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Gunsaw Genetics debug commands. Usage: GG <subcommand> [args...]", "Gunsaw Genetics 调试命令。用法 : GG <子命令> [参数...]"),
        ("Which Gunsaw Genetics command to run", "要运行的 Gunsaw Genetics 命令"),
        ("Remaining arguments depend on the subcommand", "其余参数取决于具体子命令"),
    };
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Milky Bonus: {0}", "Milky 加成 : {0}"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Gunsaw Genetics", "Gunsaw基因"),
        ("Search", "搜索"),
        ("GUNSAW GENETICS UPDATE AVAILABLE", "GUNSAW 基因工程 有新版本"),
        ("CHANGELOG", "更新日志"),
        ("[ BACK ]", "[ 返回 ]"),
        ("[ GOT IT ]", "[ 知道了 ]"),
        ("[ NEXUS PAGE ]", "[ Ｎ网页面 ]"),
        ("[ VIEW CHANGELOG ]", "[ 查看更新日志 ]"),
        ("[ ] Don't show this again", "[ ] 不再显示此提示"),
        ("No notable ability.", "无显著能力。"),
        ("No info added yet.", "尚未添加信息。"),
        ("Frail, but sharp. A steady hand.", "纤弱却敏锐。一只稳当的手。"),
        ("The baseline. Ordinary in every way.", "基准。各方面都平平无奇。"),
        ("Simple-minded. Built for the water.", "头脑简单。为水而生。"),
        ("<color=#4499ff>CLICK TO SWAP</color>", "<color=#4499ff>点击交换</color>"),
        ("The arms are closer...", "手臂更近了..."),
        ("The legs are thicker...", "腿更粗了..."),
        ("STR", "力量"),
        ("RES", "韧性"),
        ("INT", "智力"),
        ("MOVE SPEED MULT", "移动速度倍率"),
        ("HEALTH MULT", "生命倍率"),
        ("JUMP SPEED MULT", "跳跃速度倍率"),
        ("SKIN HEAL MULT", "皮肤愈合倍率"),
        ("IMMUNITY BONUS", "免疫力加成"),
        ("MODIFIED", "已修改"),
        ("WOUNDVIEW COLOR", "伤势视图颜色"),
        ("TRAITS", "特质"),
        ("e.g. 1.0", "例如 1.0"),
        ("Species name...", "物种名称..."),
        ("Flavor traits text...", "风味特质文本..."),
        ("Short description...", "简短描述..."),
        ("Ctrl + Click", "Ctrl + 左键点击"),
        ("Name can't be empty.", "名称不能为空。"),
        ("That name is already taken.", "该名称已被占用。"),
        ("This can't be undone.", "此操作无法撤销。"),
        ("Sprites folder created:", "已创建贴图文件夹："),
        ("Nothing is generated automatically beyond the empty Body and Head folders. You'll need to add the sprites yourself.", "除空的 Body 与 Head 文件夹外不会自动生成任何内容，贴图需要你自己添加。"),
        ("[NORMAL]", "[常规]"),
        ("- Unchanged", "- 无变化"),
        ("[WIP]", "[开发中]"),
        ("- Not properly implemented yet", "- 尚未完整实现"),
        ("NAME", "名称"),
        ("DESCRIPTION", "描述"),
        ("[ DELETE ]", "[ 删除 ]"),
        ("[ CLOSE ]", "[ 关闭 ]"),
        ("[HYPER-FOCUS]", "[超聚焦]"),
        ("- Slows time while aiming a loaded gun", "- 瞄准已装填枪械时减缓时间"),
        ("[EYE ADAPT]", "[暗适应]"),
        ("- Sees clearly in darkness after adjusting", "- 适应后可在黑暗中看清"),
        ("[STEADY]", "[镇定]"),
        ("- Self-harm shows as vomiting instead", "- 自残表现为呕吐"),
        ("[GENERAL]", "[通用]"),
        ("- Reads blueprints easily, better with tools than claws", "- 更易读懂蓝图，工具使用强于爪击"),
        ("[REGROWTH]", "[再生]"),
        ("- Hold to heal fast, mend bones, and regrow missing limbs, eyes, or jaw", "- 长按可快速治疗、接骨，并再生缺失的肢体、眼睛或下颌"),
        ("[MOBILITY]", "[机动性]"),
        ("- Built to move fast and recover from it", "- 为高速移动而生，也擅长从高速移动中恢复"),
        ("[TORPOR]", "[蛰伏]"),
        ("- Self-cooling ability", "- 自我降温能力"),
        ("[CHILL]", "[耐寒]"),
        ("- Adapted to the cold", "- 适应寒冷"),
        ("[CARING]", "[关怀]"),
        ("- Deeper mood swings, especially around others", "- 情绪波动更强烈，尤其在他人身边时"),
        ("- No diet restriction, uneasy about cannibalism", "- 无饮食限制，但排斥同类相食"),
        ("[CLOAK]", "[隐身]"),
        ("- Toggleable invisibility while standing still", "- 站立不动时可开关的隐形"),
        ("[IDOLATRY]", "[崇物]"),
        ("- Reveres genuine gear, despises makeshift equipment", "- 尊崇正规装备，蔑视自制器械"),
        ("[ARROGANCE]", "[傲慢]"),
        ("- Mood swings hard with pride and ego", "- 情绪随自尊与自我剧烈波动"),
        ("[VOLATILE]", "[暴烈]"),
        ("- Self-harm and suicide escalate violently", "- 自残与自杀行为急剧升级"),
        ("- Looks down on every other species", "- 瞧不起所有其他物种"),
        ("[PRIDEFUL]", "[充满自豪]"),
        ("- Grows more prideful after a strong kill", "- 击杀强敌后更加自豪"),
        ("[HORNS]", "[双角]"),
        ("- Self-harm targets the horns", "- 自残会攻击双角"),
        ("[TOUGH]", "[强健]"),
        ("- Enormous health pool, but no healing", "- 生命值极高，但无法治疗"),
        ("- Strict herbivore", "- 严格食草"),
        ("[WEB]", "[蛛网]"),
        ("- Fires webs to bind, climb, and slow enemies", "- 发射蛛网束缚、攀爬并减速敌人"),
        ("[PSYCHOPATHY]", "[精神变态]"),
        ("- Nothing truly reaches. Not fear, nor guilt", "- 没有任何东西能真正触动它——恐惧与愧疚皆无"),
        ("[CANNIBAL]", "[同类相食]"),
        ("- Enough trust, and a hug turns deadly", "- 信任足够时，拥抱会变得致命"),
        ("- Extra limbs aid mobility (cosmetic rn)", "- 额外的肢体有助于移动（目前仅为外观）"),
        ("- Sawian flesh is just meat", "- Sawian 的血肉不过就是肉"),
        ("[SIMPLE MIND]", "[头脑简单]"),
        ("- Too simple to spiral... or to hope", "- 简单到不会崩溃...也简单到不会期望"),
        ("[WARMTH]", "[耐热]"),
        ("- Adapted to the heat", "- 适应高温"),
        ("- Strict carnivore, resists weight gain and sickness", "- 严格食肉，不易增重，抗病性强"),
        ("[DESYNC]", "[解离]"),
        ("- 3-stage active ability, escalating effects", "- 三阶段主动能力，效果逐级增强"),
        ("[SCARS]", "[旧伤]"),
        ("- Old injuries", "- 陈年伤患"),
        ("- Temperature and stealth both work against them", "- 温度与潜行都对它不利"),
        ("[███████]", "[████]"),
        ("- ██████████ chip installed ", "- 已安装█████芯片 "),
        ("- ███████████ chip installed. ", "- 已安装██████芯片。 "),
        ("PORTRAITS (menu picture)\nLocation: BepInEx/plugins/SpeciesPortraits/\nFilename: <yourspeciesname>.png (all lowercase)\n\nWOUNDVIEW SPRITES (limb outline/middle art)\nLocation: BepInEx/plugins/CustomBodySprites/\nFilenames: <YourSpeciesName>_Limb_0_Outline.png\n           <YourSpeciesName>_Limb_0_Middle.png\n(0 through 14, one Outline + one Middle pair per limb)\n\nIN-WORLD CHARACTER SPRITES (Body/Head)\nLocation: BepInEx/plugins/CustomSprites/st<slot>/Body/ and .../Head/\n(your slot number was shown when you created this species)\nFilenames must match the game's own internal sprite names exactly\n(e.g. experimentHead.png, experimentCrus.png, experimentEyeOpen.png, etc.)\n\nNothing here is generated for you beyond empty folders.\nAll sprites are placed manually.", "立绘（菜单图片）\n位置：BepInEx/plugins/SpeciesPortraits/\n文件名：<你的物种名>.png（全小写）\n\n伤势视图贴图（肢体轮廓 / 中层图）\n位置：BepInEx/plugins/CustomBodySprites/\n文件名：<你的物种名>_Limb_0_Outline.png\n           <你的物种名>_Limb_0_Middle.png\n（0 到 14，每个肢体一对 Outline + Middle）\n\n场景内角色贴图（Body / Head）\n位置：BepInEx/plugins/CustomSprites/st<slot>/Body/ 与 .../Head/\n（创建该物种时会显示你的槽位编号）\n文件名必须与游戏内部贴图名完全一致\n（例如 experimentHead.png、experimentCrus.png、experimentEyeOpen.png 等）\n\n除空文件夹外，这里不会为你生成任何内容。\n所有贴图都需手动放入。"),
        ("[██████]", "[███]"),
        ("- ████████ chip installed.", "- 已安装████芯片。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Your version:  v{0}", "当前版本：  v{0}"),
        ("Latest version:  v{0}", "最新版本：  v{0}"),
        ("Delete \"{0}\"?", "删除「{0}」？"),
    };
    public static readonly (string En, string Zh)[] Fallbacks =
    {
        ("Preferred", "偏好"),
        ("Not Preferred", "不偏好"),
        ("Preferred (Cannibal)", "偏好（同类相食）"),
        ("Preferred (Leapy)", "偏好（Leapy）"),
        ("Not Preferred (Semi)", "不偏好（半）"),
        ("Bite", "咬一口"),
        ("Take a piece for yourself.", "给自己拿一块。"),
        ("Decays in: Never (frozen)", "腐败时间：永不（已冻结）"),
        ("Freezing: ", "冻结："),
        ("Frozen for ", "已冻结 "),
        ("HEAL RATE", "治疗速度"),
        ("HEALTH", "生命"),
        ("IMMUNITY", "免疫力"),
        ("JUMP", "跳跃"),
        ("MOVE", "移动"),
        ("No info added yet.", "尚未添加信息。"),
        ("Marred", "残缺"),
        ("Both horns are gone. Something about this feels permanent.", "双角都没了。总觉得有些事就此成了定局。"),
        ("Regrowth", "再生"),
        ("Hyper-Regeneration. Highly taxing on the body.", "超速再生。对身体负担极大。"),
        ("Hollow", "空洞"),
        ("Every reforged body and borrowed mind takes something with it. It doesn't come back.", "每一次重塑躯体、每一次借用他人的意识，都会带走些什么——而它再也回不来。"),
        ("Hyper-Focus", "超聚焦"),
        ("Adrenaline surging. Perception of time slowed. Weapon handling vastly improved.", "肾上腺素激增。时间感知变慢。枪械操控大幅提升。"),
        ("Sensory Overload", "感官过载"),
        ("Nervous system recovering from extreme strain. Cannot hyper-focus.", "神经系统正从极度紧绷中恢复，无法进入超聚焦。"),
        ("Recovering", "恢复中"),
        ("The body needs time until it can cool again...", "身体需要时间才能再次降温..."),
        ("Torpor", "蛰伏"),
        ("The body is slowly cooling...", "身体正在缓慢降温..."),
        ("Genetic profile corrupted. Fulfill requirement to unlock.", "基因档案已损坏。满足解锁条件即可解锁。"),
        ("[ BACK ]", "[ 返回 ]"),
        ("[ SAVE ]", "[ 保存 ]"),
        ("[ RESET ]", "[ 重置 ]"),
        ("[ CANCEL ]", "[ 取消 ]"),
        ("[ LOCKED ]", "[ 已锁定 ]"),
        ("NEW", "新建"),
        ("EDIT", "编辑"),
        ("DEL", "删除"),
        ("CUSTOM SPECIES", "自定义物种"),
        ("–CUSTOM SPECIES————————", "–自定义物种————————"),
        ("–SPECIES EDITOR————————", "–物种编辑器————————"),
        ("–BALANCE CONFIG————————", "–平衡配置————————"),
        ("–SPRITE GUIDE————————", "–贴图指南————————"),
        ("–CHANGELOG————————", "–更新日志————————"),
        ("No custom species yet.", "还没有自定义物种。"),
        ("Freezing", "冻结中"),
        ("Frozen", "已冻结"),
        ("Steal", "偷窃"),
        ("Take it without paying. {0}% chance. Failure means combat.", "不付钱直接拿走。成功率 {0}%，失败即进入战斗。"),
        ("[███████] - ██████████ chip installed \n[███████] - ███████████ chip installed. \n[██████] - ████████ chip installed.", "[████] - 已安装█████芯片 \n[████] - 已安装█████芯片。 \n[███] - 已安装████芯片。"),
        ("Small Web", "小型蛛网"),
        ("Costs 1 web charge. Fires instantly and anchors on contact. A grab point, not a climbable line. Only 5 webs are able to exist at a time.", "消耗 1 点蛛网储量，瞬间射出、接触即固定。它只是抓握点，不能当作可攀爬的绳索。同时最多只能存在 5 张蛛网。"),
        ("Long Web", "大型蛛网"),
        ("Costs 5 web charges. Considerably more than a small web. Requires holding the ability key briefly to charge before it fires. Produces a full climbable strand able to span gaps too wide to cross normally, climbable both up and down along its length. Only 5 webs are able to exist at a time.", "消耗 5 点蛛网储量，远多于小型蛛网。需要短按技能键蓄力后才能射出。能生成一条完整可攀爬的丝线，可跨越平时无法通过的宽大裂隙，并可沿其上下攀爬。同时最多只能存在 5 张蛛网。"),
        ("Psychopathy", "精神变态"),
        ("Complete trauma immunity. Positive moods run stronger than they should, and outright killing a trader lifts mood rather than damaging it, on top of no mood loss from threatening, harming, or killing them at all. Corpses, whether found or made, cost nothing either. Sleep resets a good mood back to neutral, but only if it was already positive. Anything negative carries over untouched.", "完全免疫心理创伤。正面心情效果强于常态；直接杀死商人不减心情，反而会提升；威胁、伤害或杀死他们也不会造成任何心情损失。无论是发现还是造成的尸体，同样不会带来损失。睡眠会把良好的心情重置为中性，但仅限原本为正面的心情。任何负面状态都会原样保留。"),
        ("Cannibal", "同类相食"),
        ("At 200 reputation, trader hug actions are changed to cannibalization. Cannibalization gives you a large boost to mood, hunger, and thirst afterwards. If your own mood drops low enough on its own, that same hunger turns onto yourself. Eating Yellow Flesh costs nothing. No sickness, no mood loss. Internal Organs give reduced sickness and no longer have mood loss either.", "好感度达到 200 后，对商人的拥抱动作会变为同类相食。同类相食会在之后大幅提升你的心情、饥饿与口渴。若心情自行低落到一定程度，那份饥饿就会转向自身。食用黄色血肉没有任何代价——不会生病，也不会掉心情。内脏造成的疾病更轻，同样不再有心情损失。"),
        ("Cloaking", "隐身"),
        ("Requires a charged battery and standing still to engage. Drains while active. Any movement breaks it, except while crouched. Crouching allows certain traps to be avoided entirely, but drains battery slightly faster. Radiation interferes with the cloak, and enough exposure prevents it from being used at all. Sneak cloaking also allows for stealth attacks on traders. Outcome can be improved with equipment, but could also cause damage to equipment.", "需要电量充足的电池并保持静止才能启动，激活期间持续耗电。任何移动都会解除隐身，蹲伏时除外。蹲伏可以完全避开某些陷阱，但耗电略快。辐射会干扰隐身，累积到一定程度后将完全无法使用。潜行隐身还允许对商人发动潜行攻击。装备可以改善结果，但也可能造成装备损坏。"),
        ("Idolatry", "崇物"),
        ("Genuine human-made gear noticeably improves mood when equipped. Crude, makeshift, or scavenged gear does the opposite, and some items are refused outright. Others may have reduced effectiveness, refusal to fire, or an inability to use certain medical items, unless mood or pain has broken down resistance enough to allow it.", "装备真正由人类制造的装备会明显提升心情。粗制、自制或拾荒得来的装备则相反，有些物品会被直接拒绝；另一些则可能效果下降、拒绝开火，或无法使用某些医疗物品——除非心情或疼痛已把这种抵触削弱到足以接受的程度。"),
        ("Arrogance", "傲慢"),
        ("Mood swings define this. At +30 and above, setbacks land softer. Corpses and killed traders cost far less mood than they would otherwise, and favored gear (certain tools and firearms) hits harder. At -30 and below, the opposite takes hold: those same losses cut twice as deep, and stealth attacks can no longer be used, though desperation loosens the usual refusal of ripped dressings and old rags. At -40 and below, pride collapses further still. Stealing from traders is no longer possible, but for the first time, a hug is accepted from them. Beyond mood swings, negative mood itself resists differently depending on how deep it is: from -30 to -50, 10% of further loss is shrugged off, 30% from -50 to -70, and 40% from -70 to -85, but past -85, whatever's left gives way entirely, and every further blow lands 20% harder.", "情绪波动是它的核心。心情在 +30 以上时，挫折的打击更轻：尸体与被杀的商人造成的心情损失远低于常态，偏爱的装备（某些工具与枪械）伤害更高。心情在 -30 以下时则相反：同样的损失会加倍刺痛，且无法再使用潜行攻击，不过绝望会让它不再拒绝破旧绷带与旧布条。心情在 -40 以下时，自尊进一步崩塌：无法再从商人那里偷窃，但也会第一次接受他们的拥抱。除情绪波动外，负面心情本身也会按深度产生不同的抵抗：-30 到 -50 时后续损失的 10% 被无视，-50 到 -70 为 30%，-70 到 -85 为 40%；但超过 -85 后剩余部分会彻底失守，之后每一次打击都加重 20%。"),
        ("Levitation", "悬浮"),
        ("Grabs any loose or movable object at range through a visible tether, redirecting force between it and its wielder based on relative mass. Heavy objects barely move but reflect force back; light objects move freely and resist little in return. Living targets are far harder to influence. Capable of flinging light objects with precision, or using something too heavy to lift as a launch point. Momentum from movement, jumps, and chained grabs all stack together.", "通过一条可见的牵引线隔空抓取任何松散或可移动的物体，并依据相对质量在物体与持有者之间转移力。重物几乎不动，却会把力反弹回来；轻物可自由移动，反作用力也很小。对活体目标的影响要困难得多。它能精准抛掷轻物，也能把重到无法举起的东西当作借力点。移动、跳跃与连续抓取产生的动量可以叠加。"),
        ("Reformation", "重塑"),
        ("On the verge of true death, time slows and a brief window opens to choose survival. Reforming rebuilds the body from what's left. Bleeding, breaks, and infection cleared. Blood and vitals restored. All at the cost of shared charge, and always a little something more.", "在濒临真正死亡之际，时间会变慢，并短暂开启一个选择生存的窗口。重塑会以残留部分重建身体：止血、接骨、清除感染，恢复血液与生命体征。代价是共用储量，而且总要再多付出一点什么。"),
        ("Mindswap", "意识交换"),
        ("During Reformation's window, an eligible Sawian can be selected instead of reforming. Their body becomes the new host. Stats reset to that species' baseline with a small (random) bonus. Vitals are mostly restored, while INT, hyper-regeneration, and every other chip persist regardless of the body worn. The one left behind does not survive the exchange.", "在重塑的窗口期内，可以改为选择一名符合条件的 Sawian，其身体将成为新的宿主。属性重置为该物种的基准值，并获得少量（随机）加成。生命体征大体恢复；而智力、超速再生与其他所有芯片，无论换到哪具身体都依然保留。被留下的那一方无法在交换中存活。"),
        ("Hollow", "空洞"),
        ("Rises with every Reformation or Mindswap. Mindswap far more, since it means directly hearing another mind. As it climbs: color fades from sight, mood is held closer to neutral, trauma stops taking hold at all, speech grows halting and prone to cutting short, and trader reputation suffers further. None of it reverses. 'Reborn, Rebuilt, Reformed... but never the same again.'", "每次重塑或意识交换都会加深，其中意识交换尤甚——因为它意味着直接听见另一个意识。随着它累积：视野中的色彩逐渐褪去，心情被拉向中性，心理创伤不再留下影响，言语变得断续、容易戛然而止，商人的好感度也会进一步受损。这一切都不可逆。「重生、重建、重塑...却再也不是原来的自己。」"),
        ("Carnivore", "食肉"),
        ("Only meat-based food can be eaten without issue. Anything else reduces mood, increases sickness, and restores less hunger than it should. Mindwipe removes this restriction entirely.", "只有肉类食物可以正常食用。其他任何食物都会降低心情、增加疾病，并恢复更少的饥饿。精神抹除剂可完全解除这一限制。"),
        ("Feeding", "进食"),
        ("With enough trust, a trader can be bitten for hunger instead of trade. One-time offer per trader, and never available until trust is high enough. Another Dune, however, will allow it freely and always, with no trust required and no limit on how often. If hunger falls too far with nothing else to eat, that same instinct turns inward instead.", "信任足够时，可以啃咬商人来充饥，而不必交易。每位商人仅限一次，且信任不足时绝不会开放。不过另一位 Dune 会无条件、不限次数地允许你这么做。如果饥饿过度而再无他物可食，这份本能就会转向自身。"),
        ("Torpor", "蛰伏"),
        ("Actively lowers body temperature while held, deepening the longer it's held, down to a hard limit near freezing. Holding through the heat helps too, though cooling grows harder the higher the temperature climbs. Costs thirst and energy while active, with thirst increasing the longer it's held. Releasing starts a cooldown based on how long it was held. The cooldown increases faster than the hold itself the longer it goes on.", "长按可主动降低体温，按住越久降得越深，直至接近冰点的下限。在高温中按住也有帮助，不过温度越高越难降温。激活期间消耗口渴与体力，按住越久口渴越快。松开后会产生一段与按住时长相关的冷却，且拖得越久，冷却增长得比按住本身更快。"),
        ("Frozen", "冻结"),
        ("Certain food and drink turn solid while held cold enough during {Torpor}. Decay pauses entirely, and neither can be eaten or drunk until they thaw. Frozen items can be used on the body, offering a brief burst of real healing and a little relief, at the cost of some of the item's condition and however long it has left frozen.", "在蛰伏期间保持足够低温时，某些食物与饮品会凝固。腐败会完全暂停，且在解冻之前既不能吃也不能喝。冻结的物品可以用在身体上，带来一次短暂的真实治疗与些许缓解，代价是物品的部分耐久，以及它保持冻结的那段时间。"),
        ("Herbivore", "食草"),
        ("Only plant-based food can be eaten without issue. Anything else reduces mood, increases sickness, and restores less hunger than it should. Mindwipe removes this restriction entirely.", "只有植物类食物可以正常食用。其他任何食物都会降低心情、增加疾病，并恢复更少的饥饿。精神抹除剂可完全解除这一限制。"),
        ("Semi-Herbivore", "半食草"),
        ("Only plant-based food can be eaten without issue, but violations come with a lighter penalty than strict herbivores. Mindwipe removes this restriction entirely.", "只有植物类食物可以正常食用，但违规的惩罚比严格食草者更轻。精神抹除剂可完全解除这一限制。"),
        ("Semi-Carnivore", "半食肉"),
        ("Only meat-based food can be eaten without issue, but violations come with a lighter penalty than strict carnivores. Mindwipe removes this restriction entirely.", "只有肉类食物可以正常食用，但违规的惩罚比严格食肉者更轻。精神抹除剂可完全解除这一限制。"),
        ("Regrowth", "再生"),
        ("Actively accelerates healing while held: bleeding eases, skin and muscle recover quickly, fractures mend, and missing limbs, eyes, or disfigurement regrow in stages. Progress on regrowth stays in stages, though it's lost entirely if the parent limb is destroyed. Cannot be used while too hungry. Costs hunger and thirst while active, and grows harder to sustain the more is being regrown. Immunity and temperature drift, pain and heart rate climb, and the heart itself becomes considerably more vulnerable the longer it's pushed.", "长按可主动加速愈合：出血减轻，皮肤与肌肉快速恢复，骨折愈合，缺失的肢体、眼睛或面部缺损会分阶段再生。再生进度以阶段推进，但若母肢体被摧毁便会完全丢失。过于饥饿时无法使用。激活期间消耗饥饿与口渴，需要再生的部位越多越难维持。免疫力与体温会波动，疼痛与心率上升，而心脏被逼得越久就越脆弱。"),
        ("{Carnivore}\n#VoyagerSupremancy", "{Carnivore}\n#VoyagerSupremacy"),
        ("Clumsy", "笨拙"),
        ("Sensitive", "敏感"),
        ("Eye Adaptation", "暗适应"),
        ("Desync", "解离"),
        ("Old Wounds", "旧伤"),
        ("Horns", "双角"),
        ("Tough", "强健"),
        ("Mobility", "机动性"),
        ("Chill", "耐寒"),
        ("Caring", "关怀"),
        ("Cloak", "隐身"),
        ("Web", "蛛网"),
        ("Volatile", "暴烈"),
        ("Prideful", "充满自豪"),
        ("Simple Mind", "头脑简单"),
        ("Steady", "镇定"),
        ("Unfinished", "未完成"),
        ("General", "通用"),
        ("Warmth", "耐热"),
        ("Levitation Chip", "悬浮芯片"),
        ("Reformation Chip", "重塑芯片"),
        ("Mindswap Chip", "意识交换芯片"),
        ("A last resort against death, at a cost.\n{Reformation} rebuilds what's broken, but never quite all the way.", "绝境中对抗死亡的最后手段，但代价不菲。\n{Reformation} 能重建破损之处，却永远无法完全复原。"),
        ("A side effect, not a chip of its own. Deepens with every use of the others.\n{Hollow} takes the color first. Then the edges. Then, quieter still, the words.", "它不是独立的芯片，而是一种副作用，随其他芯片的每次使用而加深。\n{Hollow} 先带走色彩，然后是轮廓，最后在更深处，带走言语。"),
        ("Active Ability. Hold to actively cool the body.\n{Torpor} helps with controlling the body's temperature, even helping against certain threats.\nCold enough, and objects begin to turn {Frozen} too.", "主动能力。长按可主动为身体降温。\n{Torpor} 有助于控制体温，甚至能抵御某些威胁。\n温度足够低时，物品也会开始转为 {Frozen}。"),
        ("Active Ability. Hold to heal, mend, and regrow. {Regrowth} comes with increasing costs the longer it's pushed.", "主动能力。长按可治疗、接骨与再生。{Regrowth} 维持越久，代价越高。"),
        ("Active Ability. Slows time while you're aiming a loaded gun. Four shots max.", "主动能力。瞄准已装填枪械时减缓时间。最多四发。"),
        ("Active Equipment. Toggle {cloaking} while standing still with charge remaining.\nCrouching while active allows slow movement without breaking it.", "主动装备。在静止且尚有电量时切换 {cloaking}。\n激活期间蹲伏可缓慢移动而不解除隐身。"),
        ("Active ability. 3 Stages. {Desync} effects scale with each use.", "主动能力。共三阶段。{Desync} 的效果随每次使用而增强。"),
        ("An enormous pool of health, paired with wounds that refuse to close on their own.\nBandages are harder to wrap around such a large body\nDoses meant for something smaller barely make a dent.", "生命值极厚，但伤口无法自行愈合。\n如此庞大的身躯更难缠上绷带。\n按较小体型配制的剂量几乎不起作用。"),
        ("Bones and dislocations mend twice as fast, and recent injuries hurt a little less the second time.", "骨骼与脱臼的愈合速度快一倍，旧伤复发时的疼痛也会略轻一些。"),
        ("Built for speed, and built to recover from pushing it too far.\nLosing the ability to move quickly will have negative effects, though.", "为速度而生，也擅长从过度冲刺中恢复。\n不过一旦失去快速移动的能力，后果会很糟糕。"),
        ("Cold is met with comfort, tolerated well past where others Sawians would start to suffer.", "寒冷对它而言反而舒适，耐受程度远超其他 Sawian 开始受苦的界限。"),
        ("Enough trust in a trader, and a hug turns into something else entirely.\nThe same hunger turns inward too. {Cannibal} habits don't stop at other people.", "与商人建立起足够信任后，拥抱会彻底变成另一回事。\n那份饥饿也会转向自身。{Cannibal} 的习惯并不只针对他人。"),
        ("Forces another mind out. Takes the body that remains.\n{Mindswap} lets the user hear everything they were thinking. It doesn't quite stop afterwards.", "将另一个意识强行驱逐，占据留下的躯体。\n{Mindswap} 会让使用者听见对方所有的想法，而此后它并不会真正停下。"),
        ("Heat and cold both catch up faster than they used to. The body doesn't push back like it should.\nSomething out there always seems to notice first. Staying unseen was never easy.\nAgain. Again. Again.", "冷热对它的影响都比从前来得更快，身体也不再像该有的那样抵抗。\n外面的什么东西似乎总能先一步察觉它——不被看见，从来都不容易。\n又一次。又一次。又一次。"),
        ("Heat is welcomed rather than feared, tolerated well past where others would start to suffer.", "它不惧高温反而欢迎它，耐受程度远超他人开始受苦的界限。"),
        ("Looks down upon all other species.\n{Arrogance} swings with ego. Pride sharpens, ruin breaks.", "瞧不起所有其他物种。\n{Arrogance} 随自尊起伏：骄傲使其锐利，破败使其崩塌。"),
        ("Meat is all the same, Sawian or otherwise.\n{Feeding} doesn't always mean hunting.", "肉就是肉，Sawian 与否并无分别。\n{Feeding} 并不总是意味着狩猎。"),
        ("Minigames respond slower to strength. Arms hit harder than most, tools hit softer.", "小游戏中力量的收益更慢。徒手攻击比多数人更重，工具攻击则更轻。"),
        ("Mood runs deeper in every direction, especially when others are hurt.\nHugs are easier and mean more.", "情绪的起伏在各方面都更深，尤其当他人受伤时。\n拥抱更容易达成，也更有意义。"),
        ("Mood swings harder in every direction, and colors first impressions with traders far more than usual.", "情绪在各方面波动更剧烈，也远比常人更能左右商人初见时的观感。"),
        ("No dietary restrictions, but eating another Sawian doesn't sit right.", "没有饮食限制，但吃下另一名 Sawian 让它很不自在。"),
        ("Press for a {small web}, hold for a {long web}.\nWeb supply scales with intelligence. Rebuilds slowly, or fully with sleep.", "轻按发射 {small web}，长按发射 {long web}。\n蛛网储量随智力提升，恢复缓慢，睡觉可完全恢复。"),
        ("Remote kinetic redirection. Force applied is mass-dependent, in both directions.\n{Levitation} was never rated for a body this light.", "隔空转移动能，所施加的力与质量相关，且双向作用。\n{Levitation} 从未针对如此轻的身体做过适配。"),
        ("Reveres genuine human-made gear above all else. Makeshift or scavenged equipment earns nothing but contempt.\n{Idolatry} colors mood around whatever's currently equipped.", "对真正出自人类之手的装备推崇备至，而自制或拾荒得来的器械只会招致蔑视。\n{Idolatry} 会让心情随当前装备的好坏而起伏。"),
        ("Self-harm presents as vomiting instead of the usual.\nSuicide attempts cause heavy vomiting, fibrillation, and a rapidly climbing heart rate.", "自残表现为呕吐，而非通常的方式。\n自杀尝试会导致剧烈呕吐、心室颤动，以及迅速攀升的心率。"),
        ("Self-harm targets the hands. Suicide escalates rapidly, and violently, across the whole body.\nNeither is quick. Neither is quiet.", "自残会针对双手。自杀则会迅速而猛烈地蔓延至全身。\n两者都不快，两者都不安静。"),
        ("Self-harm targets the horns. Each one lost costs something lasting.\nThere are only two to give.", "自残会针对双角。每失去一只，都会留下永久的代价。\n而它只有两只可以交出。"),
        ("Semi-Active ability. Gain {Prideful} after killing an enemy. Scales with enemy killed.\nKept active, and death itself can be shrugged off once.", "半主动能力。击杀敌人后获得 {Prideful}，强度随敌人强弱变化。\n保持激活时，就连死亡也能被硬扛过一次。"),
        ("Staying in darkness for a while lets you see in it clearly. Returning to light should be done carefully.", "在黑暗中待上一阵便能看清四周，但回到光亮处时须格外小心。"),
        ("That scar wasn't quiet. Something put it there, and it's remembered exactly how.\nThe legs are just another part. It'll heal again. It always does.", "那道疤来得并不平静——有什么东西留下了它，而它记得清清楚楚。\n腿不过是又一个部件，它还会再长好，向来如此。"),
        ("This species hasn't been properly made yet. Wait for it's update in the future!", "该物种尚未制作完成，请等待它日后的更新！"),
        ("Too simple to spiral, too simple to hope.\nNo Last Stand waiting at the end.", "简单到不会崩溃，也简单到不会期望。\n尽头没有「背水一战」。"),
        ("Very little truly reaches. Not grief, guilt, or fear. {Psychopathy} runs deep.", "几乎没有什么能真正触动它——悲伤、愧疚或恐惧皆然。{Psychopathy} 根深蒂固。"),
        ("{Carnivore}\nExtra limbs help with mobility (Cosmetic currently)", "{Carnivore}\n额外的肢体有助于移动（目前仅为外观）。"),
        ("{Carnivore}\nLess of what's eaten turns to weight, and overindulgence costs less than it should.\nSickness can only climb so far.", "{Carnivore}\n吃下的东西更少转化为体重，暴食的代价也低于应有水平。\n疾病最多只能累积到一定程度。"),
        ("{Herbivore}\nThreats land far easier coming from him. He never feels good about making them.", "{Herbivore}\n由他说出的威胁格外容易奏效，而他从不为此感到愉快。"),
        ("{Semi-Herbivore}\nFoliage, in every form, is able to be digested far easier.\nFood is needed more often than other Sawians.", "{Semi-Herbivore}\n任何形式的植物都更容易被消化。\n比其他的 Sawian 更频繁地需要进食。"),
        ("{Semi-Herbivore}\nYou can understand blueprints more clearly.\nWorse Claw scaling. Better Tool scaling.", "{Semi-Herbivore}\n更容易读懂蓝图。\n爪击成长更差，工具成长更好。"),
    };
    public static readonly (string En, string Zh)[] HueNames =
    {
        ("Green (Default)", "绿色（默认）"),
        ("Red", "红色"),
        ("Yellow", "黄色"),
        ("Teal", "青色"),
        ("Cyan", "青色（亮）"),
        ("Blue", "蓝色"),
        ("Purple", "紫色"),
        ("Pink", "粉色"),
    };
    public static readonly (string En, string Zh)[] PickerStats =
    {
        ("STR", "力量"),
        ("RES", "韧性"),
        ("INT", "智力"),
        ("MOBILITY", "机动性"),
        ("LEAP POWER", "跳跃力"),
        ("TOUGHNESS", "坚韧"),
        ("REGEN RATE", "恢复速率"),
        ("IMMUNITY", "免疫力"),
    };
    public static readonly (string En, string Zh)[] LimbNames =
    {
        ("Torso Tendril L (Inner)", "躯干触须 左（内侧）"),
        ("Torso Tendril L (Outer)", "躯干触须 左（外侧）"),
        ("Torso Tendril R (Inner)", "躯干触须 右（内侧）"),
        ("Torso Tendril R (Outer)", "躯干触须 右（外侧）"),
        ("Abdomen Tendril L (Inner)", "腹部触须 左（内侧）"),
        ("Abdomen Tendril L (Outer)", "腹部触须 左（外侧）"),
        ("Abdomen Tendril R (Inner)", "腹部触须 右（内侧）"),
        ("Abdomen Tendril R (Outer)", "腹部触须 右（外侧）"),
    };
    public static readonly (string En, string Zh)[] Changelog =
    {
        ("<b>Gunsaw Genetics v1.9.0 changelog:</b>", "<b>Gunsaw Genetics v1.9.0 更新日志：</b>"),
        ("<b>Baron Overhaul:</b>", "<b>Baron 重做：</b>"),
        ("<b>Prideful Changes:</b>", "<b>自豪改动：</b>"),
        ("- Prideful duration scaling changed:", "- 自豪持续时间成长规则改动："),
        ("- - Duration now scales with the strength of the enemy killed (25-120s), instead of being fixed", "- - 持续时间现在随击杀敌人的强度变化（25-120s），而不再是固定值"),
        ("- - Kills below 50 max health no longer grant Prideful at all (Cave ticks, etc.)", "- - 击杀最大生命值低于 50 的敌人不再触发自豪（洞穴蜱虫等）"),
        ("- - Killing the Elder Thornback grants a flat 13-minute duration, regardless of the normal scaling", "- - 击杀棘背兽长老固定获得 13 分钟持续时间，不受常规成长规则影响"),
        ("- Trader Prideful reputation scaling changed:", "- 商人自豪好感度成长规则改动："),
        ("- - Reputation bonus while Prideful now scales with the strength of the kill that triggered it (+12 to +55), instead of a flat bonus", "- - 自豪期间的好感度加成现在随触发它的击杀强度变化（+12 至 +55），而不再是固定加成"),
        ("- - Killing the Elder Thornback grants a flat +95 reputation bonus, regardless of the normal scaling", "- - 击杀棘背兽长老固定获得 +95 好感度加成，不受常规成长规则影响"),
        ("- Baron's Last Stand no longer triggers the same way as other species:", "- Baron 的背水一战不再与其他物种以相同方式触发："),
        ("- - Last Stand is now tied to Prideful. While Prideful, Baron has a 95% chance to trigger Last Stand", "- - 背水一战现在与自豪绑定。处于自豪状态时，Baron 有 95% 几率触发背水一战"),
        ("- - Still limited to once per run (unless Infinite Last Stand is enabled)", "- - 仍限制为每局一次（除非启用了无限背水一战）"),
        ("- - Triggering Last Stand this way clears Prideful", "- - 以此方式触发背水一战会清空自豪"),
        ("- Mood buff removed entirely", "- 完全移除心情加成"),
        ("- Prideful now tracks the strength of the enemy killed", "- 自豪现在会记录击杀敌人的强度"),
        ("- Traders now react to a Prideful Baron", "- 商人现在会对处于自豪状态的 Baron 做出反应"),
        ("- New trader interaction added for returning to a known trader while Prideful.", "- 新增商人互动：在自豪状态下回到已认识的商人处。"),
        ("<b>Self-Harm Overhaul:</b>", "<b>自残重做：</b>"),
        ("- Baron's self-harm event is now a unique minigame instead of the standard vanilla one", "- Baron 的自残事件现在改为专属小游戏，不再是原版标准玩法"),
        ("- - Grab one of Baron's horns and tug to break it free. Letting go and re-grabbing is safe, but resistance builds the longer you hold on", "- - 抓住 Baron 的一只角用力拉扯将其掰断。松手再抓是安全的，但握得越久阻力越大"),
        ("- - Once broken, the horn cannot regrow", "- - 角一旦掰断便无法再生"),
        ("- - Breaking a horn causes heavy head bleeding, pain, and skin damage, and updates Baron's head sprite to reflect the damage", "- - 掰断角会造成严重的头部出血、疼痛和皮肤损伤，并更新 Baron 的头部贴图以体现损伤"),
        ("- - A second horn can be broken the same way. After that, self-harm reverts to vanilla's version", "- - 第二只角也可以用同样方式掰断。此后自残恢复为原版玩法"),
        ("- One horn broken:", "- 掰断一只角："),
        ("- - Prideful's duration and trader reputation bonus are both halved", "- - 自豪的持续时间和商人好感度加成均减半"),
        ("- - Baseline trader reputation bonus reduced (+10 -> +5)", "- - 基础商人好感度加成降低（+10 -> +5）"),
        ("- - Threaten's success odds bonus is halved", "- - 威胁的成功率加成减半"),
        ("- Both horns broken:", "- 掰断两只角："),
        ("- - Prideful is disabled entirely, meaning Last Stand can no longer be triggered through it", "- - 自豪被完全禁用，意味着无法再通过它触发背水一战"),
        ("- - Baseline trader reputation bonus removed, replaced with a flat -10", "- - 移除基础商人好感度加成，改为固定 -10"),
        ("- - Threaten's success odds bonus is removed, reverting to vanilla odds", "- - 移除威胁的成功率加成，恢复为原版成功率"),
        ("- - Reputation and mood gained from hugging traders is permanently halved", "- - 拥抱商人获得的好感度和心情永久减半"),
        ("- - Marred moodle is added (unimportant, hover to see)", "- - 新增残缺状态图标（无关紧要，悬浮查看）"),
        ("<b>Healing Changes:</b>", "<b>治疗改动：</b>"),
        ("- Wound-care item effectiveness reduced by 50% per use (bandages, dressings, sutures, bruise kits, bone welding tool, splints, etc.)", "- 伤口护理物品每次使用效果降低 50%（绷带、敷料、缝合线、瘀伤包、骨焊接工具、夹板等）"),
        ("- - This does not affect how quickly items wear out, just how much they actually heal", "- - 这不会影响物品的损耗速度，只影响其实际治疗量"),
        ("- Drug potency and duration reduced by 50%", "- 药物效力和持续时间降低 50%"),
        ("- - Blood bags, IV bags, and other blood-replenishing items unaffected. Volume is still 1:1 on the body, even with Baron's naturally higher blood volume.", "- - 血袋、输液袋及其他补血物品不受影响。即使 Baron 天生血量更高，注入体内的量仍为 1:1。"),
        ("<b>Blood Changes:</b>", "<b>血液改动：</b>"),
        ("- Blood volume increased by 50% (5.00L -> 7.50L)", "- 血量提高 50%（5.00L -> 7.50L）"),
        ("- Blood loss thresholds (dying/critically dying) increased by 25%", "- 失血阈值（濒死/危重濒死）提高 25%"),
        ("- Losing a large amount of blood is more forgiving than it is for other species, but not by a full 1:1 margin. Baron can still bleed out, it just takes more.", "- 大量失血比其他物种更宽容，但并非完全 1:1 的比例。Baron 仍然会失血而死，只是需要失掉更多血。"),
        ("<b>General:</b>", "<b>通用：</b>"),
        ("- Threaten now has significantly better odds while playing as Baron, at the cost of a much harsher mood and trauma penalty on use", "- 扮演 Baron 时威胁的成功率显著提高，代价是使用时承受更严厉的心情和创伤惩罚"),
        ("- Trauma gained from ongoing pain reduced by 35% (Does not apply to trauma from other sources, such as eye loss, disfigurement, or trader-related incidents)", "- 持续疼痛获得的创伤降低 35%（不适用于其他来源的创伤，如失去眼睛、面部缺损或与商人相关的事件）"),
        ("- Energy regeneration while sleeping reduced by 35%", "- 睡眠时的体力恢复降低 35%"),
        ("- Baron now destroys a wider area of terrain when landing hard enough, scaling with impact force", "- Baron 重摔落地时现在会破坏更大范围的地形，范围随冲击力变化"),
        ("- Hunger and thirst caps increased by 50", "- 饥饿和口渴上限提高 50"),
        ("- Baron reputation buff baseline changed to +10 (Was +15)", "- Baron 好感度加成基础值改为 +10（原为 +15）"),
        ("- Toughness changed from 4.0x to 2.25x", "- 坚韧从 4.0x 改为 2.25x"),
        ("<b>Voyager Changes:</b>", "<b>Voyager 改动：</b>"),
        ("- Cloaking now has sounds for cloaking, uncloaking, and forced decloaking.", "- 隐身在进入隐身、解除隐身和强制解除隐身时现在都有音效。"),
        ("- - All of these are made by Dirasial!", "- - 以上音效均由 Dirasial 制作！"),
        ("<b>Leapy Changes:</b>", "<b>Leapy 改动：</b>"),
        ("- Cannot be older than 20 anymore.", "- 年龄不能再超过 20 岁。"),
        ("<b>Custom Last Stands:</b>", "<b>自定义背水一战：</b>"),
        ("<i>By ThePristineAnt!:</i>", "<i>由 ThePristineAnt 制作！：</i>"),
        ("- Baron Last Stand audio added", "- 新增 Baron 背水一战音效"),
        ("- Baron Last Stand screen(s) added", "- 新增 Baron 背水一战画面"),
        ("- Milky Last Stand screen(s) added", "- 新增 Milky 背水一战画面"),
        ("- Orange Last Stand screen(s) added", "- 新增 Orange 背水一战画面"),
        ("- Roza Last Stand screen(s) added", "- 新增 Roza 背水一战画面"),
        ("- Voyager Last Stand screen(s) added", "- 新增 Voyager 背水一战画面"),
        ("- Velvet Last Stand screen(s) added", "- 新增 Velvet 背水一战画面"),
        ("<i>By Dirasial!:</i>", "<i>由 Dirasial 制作！：</i>"),
        ("- Albino Last Stand screen(s) added", "- 新增 Albino 背水一战画面"),
        ("- Albino Last Stand audio added", "- 新增 Albino 背水一战音效"),
        ("- Roza Last Stand audio added", "- 新增 Roza 背水一战音效"),
        ("<b>Custom Hand (Minigame) Sprites:</b>", "<b>自定义手部（小游戏）贴图：</b>"),
        ("<i>New system to alter the hand / arm visuals during minigames.</i>", "<i>新增系统，用于在小游戏期间改变手部/手臂外观。</i>"),
        ("- (Partial) Voyager hand sprites added", "- 新增（部分）Voyager 手部贴图"),
        ("<b>Custom Dialogue:</b>", "<b>自定义对话：</b>"),
        ("- Roza dialogue added (By BountyXSnipe!!!!)", "- 新增 Roza 对话（由 BountyXSnipe 制作！！！！）"),
        ("- Baron dialogue added (By ThePristineAnt!!!!!)", "- 新增 Baron 对话（由 ThePristineAnt 制作！！！！！）"),
        ("<b>Custom Corpses:</b>", "<b>自定义尸体：</b>"),
        ("<i>Sawian corpses now have more variants, specifically those including other species not in the vanilla pool</i>", "<i>Sawian 尸体现在有更多变体，特别是包含原版池中没有的其他物种的变体</i>"),
        ("<i>By Strag!:</i>", "<i>由 Strag 制作！：</i>"),
        ("- Leapy Corpse 1 added", "- 新增 Leapy 尸体 1"),
        ("- Leapy Corpse 2 added", "- 新增 Leapy 尸体 2"),
        ("- Leapy Corpse 3 added", "- 新增 Leapy 尸体 3"),
        ("- Chompy Corpse 1 added", "- 新增 Chompy 尸体 1"),
        ("- Chompy Corpse 2 added", "- 新增 Chompy 尸体 2"),
        ("<b>Custom Moodles:</b>", "<b>自定义状态图标：</b>"),
        ("- Albino Desync aftermath moodles redrawn by ThePristineAnt!!!!", "- Albino 解离后遗症的状态图标由 ThePristineAnt 重新绘制！！！！"),
        ("<b>Universal Weight:</b>", "<b>通用体重：</b>"),
        ("<i>Species now have different weight that (should) match them. This is purely cosmetic and has zero gameplay effect unless otherwise stated.</i>", "<i>各物种现在有不同的体重，（应该）与其相符。除非另有说明，这纯粹是外观性质，对玩法零影响。</i>"),
        ("- Orange weight is now +15kg higher", "- Orange 体重提高 +15kg"),
        ("- Milky weight is now -10kg lower", "- Milky 体重降低 -10kg"),
        ("- Leapy weight is now -5kg lower", "- Leapy 体重降低 -5kg"),
        ("- Chompy weight is now +10kg higher", "- Chompy 体重提高 +10kg"),
        ("- Roza weight is now +5kg higher", "- Roza 体重提高 +5kg"),
        ("- Voyager weight is now -5kg lower", "- Voyager 体重降低 -5kg"),
        ("- Baron weight is now +30kg higher", "- Baron 体重提高 +30kg"),
        ("- Chik weight is now -15kg lower", "- Chik 体重降低 15kg"),
        ("- Crystal weight is now +10kg higher", "- Crystal 体重提高 10kg"),
        ("- Velvet weight is now +5kg higher", "- Velvet 体重提高 5kg"),
        ("- Shelly weight is now +10kg higher", "- Shelly 体重提高 10kg"),
        ("- Dune weight is now +5kg higher", "- Dune 体重提高 5kg"),
        ("- Albino weight is now -5kg lower", "- Albino 体重降低 5kg"),
        ("<b>Universal Hunger / Thirst Caps:</b>", "<b>通用饥饿／口渴上限：</b>"),
        ("<i>Species now have different hunger and thirst caps that (should) match them. Unlike weight, this has a real gameplay effect. Species with higher caps can eat/drink further past \"full\" before facing the usual downsides, while species with lower caps hit those downsides sooner.</i>", "<i>现在各物种有不同的饥饿和口渴上限，（应该）与其自身相匹配。与体重不同，这会产生实际的玩法影响。上限更高的物种在超过“饱”之后还能继续吃喝更久才会遭遇通常的负面效果，而上限更低的物种会更早遭遇这些负面效果。</i>"),
        ("- Orange caps are now 30 higher", "- Orange 上限提高 30"),
        ("- Milky caps are now 10 lower", "- Milky 上限降低 10"),
        ("- Leapy caps are now 5 lower", "- Leapy 上限降低 5"),
        ("- Chompy caps are now 15 higher", "- Chompy 上限提高 15"),
        ("- Voyager caps are now 5 lower", "- Voyager 上限降低 5"),
        ("- Baron caps are now 50 higher", "- Baron 上限提高 50"),
        ("- Chik caps are now 15 lower", "- Chik 上限降低 15"),
        ("- Velvet caps are now 5 higher", "- Velvet 上限提高 5"),
        ("- Dune caps are now 20 higher", "- Dune 上限提高 20"),
        ("- Albino caps are now 20 lower", "- Albino 上限降低 20"),
        ("<b>E-PDA:</b>", "<b>E-PDA：</b>"),
        ("- Albino E-PDA 2 added", "- 新增 Albino E-PDA 2"),
        ("- Albino E-PDA 3 added (This one is a <i>very</i> long read, so keep that in mind)", "- 新增 Albino E-PDA 3（这一篇<i>非常</i>长，请留意）"),
        ("<i>Written by ThePristineAnt!!:</i>", "<i>由 ThePristineAnt 撰写！！：</i>"),
        ("- Chompy E-PDA 1 added", "- 新增 Chompy E-PDA 1"),
        ("- Icke E-PDA 1 added", "- 新增 Icke E-PDA 1"),
        ("<b>Notes:</b>", "<b>笔记：</b>"),
        ("- Albino Note 1 removed", "- 移除 Albino 笔记 1"),
        ("- - Albino E-PDA 1 is a superior version of this subject and this older note is now redundant.", "- - Albino E-PDA 1 是该对象的更优版本，这篇较旧的笔记现已多余。"),
        ("- Chompy Note 1 added", "- 新增 Chompy 笔记 1"),
        ("- Chompy Note 2 added", "- 新增 Chompy 笔记 2"),
        ("- Icke Note 1 added", "- 新增 Icke 笔记 1"),
        ("- Icke Note 2 added", "- 新增 Icke 笔记 2"),
        ("<b>Woundview:</b>", "<b>伤势视图：</b>"),
        ("- Additional Baron Woundview head sprites added", "- 新增额外的 Baron 伤势视图头部贴图"),
        ("- Milky Woundview Sprites added (By ThePristineAnt!!)", "- 新增 Milky 伤势视图贴图（由 ThePristineAnt 制作！！）"),
        ("- - Yes, Milky already had sprites. This is just the complete version of that.", "- - 是的，Milky 原本就有贴图。这只是它的完整版本。"),
        ("<b>Quality of Life:</b>", "<b>体验优化：</b>"),
        ("- Added a search bar to the settings menu, filtering the current tab's options as you type", "- 设置菜单新增搜索栏，输入时即时筛选当前标签页的选项"),
        ("- Added two new keybinds to step up/down through sprite slots (defaults: [ and ])", "- 新增两个用于在贴图槽位间上／下切换的按键绑定（默认：[ 和 ]）"),
        ("- Added an \"Enable Diet Tooltips\" setting (off by default) that shows a colored tag in the extended item description indicating whether a food is preferred for your current species", "- 新增“启用饮食提示”设置（默认关闭），会在扩展物品描述中显示一个带颜色的标签，标明该食物是否为你当前物种所偏好"),
        ("- Added an additional argument to switchspecies command to toggle stat changes.", "- 为 switchspecies 命令新增一个额外参数，用于切换属性变化。"),
        ("- - Full command is now: GG switchspecies <species> <true/false> <true/false>", "- - 完整命令现为：GG switchspecies <物种> <true/false> <true/false>"),
        ("- - The second true/false determines if stats are changed to the provided species.", "- - 第二个 true/false 决定是否将属性变更为所指定的物种。"),
        ("- Added a new debug command, GG debugbaronhorns, to directly set how many of Baron's horns are broken.", "- 新增调试命令 GG debugbaronhorns，用于直接设置 Baron 有多少只角被折断。"),
        ("- Added a new debug command, GG reloadsprites, to force custom sprites (Woundview, minigame hands, and in-world) to reload from disk without restarting", "- 新增调试命令 GG reloadsprites，可在不重启游戏的情况下强制从磁盘重新加载自定义贴图（伤势视图、小游戏手部以及世界内贴图）"),
        ("- Added new debug commands, GG forcehollow and GG unforcehollow, to force or clear a post-Mindwipe state for testing", "- 新增调试命令 GG forcehollow 与 GG unforcehollow，用于强制或清除精神抹除后的状态以便测试"),
        ("- Added GG help, listing every available GG subcommand and its usage", "- 新增 GG help，列出所有可用的 GG 子命令及其用法"),
        ("<b>Bug Fixes:</b>", "<b>漏洞修复：</b>"),
        ("- Fixed GG switchspecies failing with a \"Species picker not yet initialized\" error on loaded saves", "- 修复了在已读取的存档中 GG switchspecies 因“Species picker not yet initialized”错误而失败的问题"),
        ("- Fixed a vanilla bug where notes and E-PDAs wouldn't scroll correctly at some screen resolutions (By Dirasial!)", "- 修复了一个原版漏洞：在某些屏幕分辨率下笔记和 E-PDA 无法正确滚动（由 Dirasial 修复！）"),
        ("- - GG's loreslop exposed this. #BEASTMODE", "- - GG 的剧情长文暴露了这个问题。#BEASTMODE"),
        ("<b>Gunsaw Genetics v1.8.0 Changelog:</b>", "<b>Gunsaw Genetics v1.8.0 更新日志：</b>"),
        ("<i>Like Roza, Leapy's dialogue is still being worked on. Leapy is also missing a few things, mostly because I'm waiting for CUCoreLib's animation support. That being said, I've been working on a lot of other things, so custom shaders/screen effects, custom mini-games, etc. may be coming in the future.</i>", "<i>和 Roza 一样，Leapy 的对话仍在制作中。Leapy 还缺少一些内容，主要因为我在等 CUCoreLib 的动画支持。话虽如此，我一直在做很多其他工作，所以自定义着色器／屏幕效果、自定义小游戏等可能会在未来推出。</i>"),
        ("<b>Leapy Overhaul:</b>", "<b>Leapy 重做：</b>"),
        ("<b>Regrowth:</b>", "<b>再生：</b>"),
        ("- Active ability. Hold to use.", "- 主动技能。按住使用。"),
        ("- While active:", "- 激活期间："),
        ("- - Regenerates skin and muscle health across the entire body at around ~4.5/sec", "- - 以约 4.5/秒的速度再生全身的皮肤和肌肉生命值"),
        ("- - Reduces active bleeding", "- - 减少活动性出血"),
        ("- - Mends bone fractures (dislocations unaffected)", "- - 修复骨折（脱臼不受影响）"),
        ("- - Regrows missing limbs in stages.", "- - 分阶段再生缺失的肢体。"),
        ("- - Regrows disfigurement and missing eyes in stages.", "- - 分阶段再生面部缺损和缺失的眼睛。"),
        ("- - Cannot be activated below 20 hunger", "- - 饥饿低于 20 时无法激活"),
        ("- Regrowth progress (on limbs, eyes, and disfigurement) will regress if not held, but won't go below the last stage reached. This <i>does</i> get cleared if the parent segment gets dismembered, though.", "- 再生进度（肢体、眼睛和面部缺损）在未按住时会回退，但不会低于已到达的最后阶段。不过，如果上级部位被切断，进度<i>确实</i>会被清空。"),
        ("- Costs, scaling with how much is currently being healed (fractures + heavily damaged limbs below 50/50 health + actively regrowing limbs):", "- 消耗会随当前正在治疗的内容量而增加（骨折 + 生命值低于 50/50 的严重受损肢体 + 正在再生的肢体）："),
        ("- - Drains hunger at 4.5/sec, and thirst at 1/3 that rate", "- - 以 4.5/秒的速度消耗饥饿，口渴的消耗速度为该值的 1/3"),
        ("- - Reduces immunity by 1/sec", "- - 每秒降低 1 点免疫力"),
        ("- - Raises body temperature by 0.1/sec", "- - 每秒提高 0.1 点体温"),
        ("- - Increases pain by 1.2/sec per thing currently healing", "- - 每个正在治疗的项目每秒增加 1.2 点疼痛"),
        ("- - Increases heart rate by 3/sec per thing currently healing", "- - 每个正在治疗的项目每秒增加 3 点心率"),
        ("- - Drains energy by 0.5/sec per thing currently healing", "- - 每个正在治疗的项目每秒消耗 0.5 点体力"),
        ("- - Considerably more susceptible to fibrillation while active, on top of the heart rate increase itself.", "- - 激活期间，除了心率本身的提升之外，还明显更容易发生心室颤动。"),
        ("<b>Leapy's natural (non-Regrowth) healing has been reworked:</b>", "<b>Leapy 的自然（非再生）治疗已重做：</b>"),
        ("- Still uses the game's normal healing formula, but its hunger-based scaling has been replaced with Leapy's own.", "- 仍使用游戏的常规治疗公式，但其基于饥饿的加成已替换为 Leapy 专属的加成。"),
        ("- Scales with average hunger/thirst: full strength at 100/100, normal strength at 20/20, and progressively worse below that.", "- 随饥饿／口渴的平均值缩放：100/100 时效果全满，20/20 时为正常强度，低于该值则逐步变差。"),
        ("<b>Mood:</b>", "<b>心情：</b>"),
        ("- Injured legs now give a constant, but slow, mood drop.", "- 受伤的腿现在会带来持续但缓慢的心情下降。"),
        ("- - -0.1/sec per-leg segment below 50/50 health.", "- - 每个生命值低于 50/50 的腿部部位每秒 -0.1。"),
        ("- Losing a leg segment gives -12 mood, on top of everything else.", "- 失去一个腿部部位会额外造成 -12 心情，且叠加在其他所有效果之上。"),
        ("- Using Regrowth to restore a leg segment gives +6 mood.", "- 使用再生恢复一个腿部部位会给予 +6 心情。"),
        ("<b>Wallslide changed:</b>", "<b>贴墙下滑已改动：</b>"),
        ("- Comes to a (almost) complete stop", "- 会（几乎）完全停下"),
        ("- Drains slightly more stamina", "- 略微增加体力消耗"),
        ("<b>Walk / Run speed changed:</b>", "<b>行走／奔跑速度已改动：</b>"),
        ("- Starts slower, then ramps up in speed", "- 起步更慢，随后速度逐渐提升"),
        ("- - This makes it easier for Leapy to make smaller movements while still retaining their high mobility stats.", "- - 这让 Leapy 更容易做出小幅移动，同时仍保留其高机动属性。"),
        ("- Hunger rate increased to 1.4x", "- 饥饿速度提高至 1.4 倍"),
        ("- Dash ability removed", "- 移除冲刺技能"),
        ("- MoveSpeed changed from 1.36 to 1.3", "- MoveSpeed 从 1.36 改为 1.3"),
        ("- JumpSpeed changed from 1.3 to 1.2", "- JumpSpeed 从 1.3 改为 1.2"),
        ("<b>Universal Diets:</b>", "<b>通用饮食：</b>"),
        ("<i>Processed food is still kinda in a weird spot. A future update might put them into a separate list for diets. For now, the system will use a more simplified format.</i>", "<i>加工食品目前仍处于一个比较尴尬的位置。未来的更新可能会把它们放进单独的饮食列表。就目前而言，系统会采用更简化的格式。</i>"),
        ("- Herbivore diet added", "- 新增食草动物饮食"),
        ("- Semi-Herbivore diet added", "- 新增半食草动物饮食"),
        ("- - Semi-Herbivores use the same list as herbivores, but have a lesser penalty for eating outside of their diet.", "- - 半食草动物使用与食草动物相同的列表，但食用饮食之外的食物时惩罚更轻。"),
        ("- Semi-Carnivore diet added", "- 新增半食肉动物饮食"),
        ("- - Semi-Carnivores use the same list as carnivores, but have a lesser penalty for eating outside of their diet.", "- - 半食肉使用与食肉相同的列表，但进食饮食范围之外的食物时惩罚更轻。"),
        ("- Carnivores and Semi-Carnivores can now eat Animal Flesh without the sickness penalty. Missed this before.", "- 食肉与半食肉现在可以食用动物肉块，且不会受到疾病惩罚。之前漏掉了这一点。"),
        ("- Sickness penalty for eating outside of diets reduced.", "- 进食饮食范围之外的食物时，疾病惩罚已降低。"),
        ("- Leapy is now a Semi-Herbivore", "- Leapy 现在是半食草"),
        ("- - Additionally, Leapy can eat foliage, dried foliage, and foliage meals with less downsides.", "- - 此外，Leapy 可以食用植物纤维、干燥植物纤维和植物纤维餐，负面影响更小。"),
        ("- Milky is now a Semi-Herbivore", "- Milky 现在是半食草"),
        ("- Chik is now a Semi-Herbivore", "- Chik 现在是半食草"),
        ("- Baron is now a Herbivore", "- Baron 现在是食草"),
        ("- Icke is now a Herbivore", "- Icke 现在是食草"),
        ("- Crystal is now a Semi-Carnivore", "- Crystal 现在是半食肉"),
        ("- Chompy is now a Carnivore", "- Chompy 现在是食肉"),
        ("- Voyager is now a Carnivore", "- Voyager 现在是食肉"),
        ("- Velvet is now a Carnivore", "- Velvet 现在是食肉"),
        ("- Setting toggle added to disable diets entirely. Species-specific food bonuses (like Leapy's foliage tolerance) still apply either way.", "- 新增设置开关，可完全禁用饮食系统。无论是否启用，物种特有的食物加成（如 Leapy 的植物纤维耐受）依然生效。"),
        ("<b>Commands added:</b>", "<b>新增指令：</b>"),
        ("<i>GG will be the prefix for all current and future commands.</i>", "<i>GG 将作为当前及今后所有指令的前缀。</i>"),
        ("- Added switchspecies command", "- 新增 switchspecies 指令"),
        ("- - Example: GG switchspecies Leapy <true/false>", "- - 示例：GG switchspecies Leapy <true/false>"),
        ("- - True / false determines if you are healed when running the command. If not defined, you will be healed automatically.", "- - true / false 决定执行指令时是否为你治疗。若不指定，将自动为你治疗。"),
        ("- Added merchollow command", "- 新增 merchollow 指令"),
        ("- - Example: GG merchollow <0-10>", "- - 示例：GG merchollow <0-10>"),
        ("- - Need to be Mercenary to use this command. Sets hollow level to provided number.", "- - 需要是 Mercenary 才能使用此指令。将空洞等级设为指定的数值。"),
        ("<b>Tail Sprites added (ThePristineAnt drew all of these!!!!):</b>", "<b>新增尾部贴图（全部由 ThePristineAnt 绘制！！！！）：</b>"),
        ("- Velvet tail sprite added", "- 新增 Velvet 尾部贴图"),
        ("- Leapy tail sprite added", "- 新增 Leapy 尾部贴图"),
        ("- Roza tail sprite added", "- 新增 Roza 尾部贴图"),
        ("- Baron tail sprite added", "- 新增 Baron 尾部贴图"),
        ("- Experiment tail sprite added", "- 新增 Experiment 尾部贴图"),
        ("- Setting added to toggle these. Default on.", "- 新增设置开关，可切换这些贴图。默认开启。"),
        ("<b>Woundview Sprites:</b>", "<b>伤势视图贴图：</b>"),
        ("- Leapy Regrowth sprites (75 of them!) added (by ThePristineAnt!!!!)", "- 新增 Leapy 再生贴图（多达 75 张！）（由 ThePristineAnt 绘制！！！！）"),
        ("- Voyager resprite! (by ThePristineAnt!!!)", "- Voyager 贴图重制！（由 ThePristineAnt 绘制！！！）"),
        ("- <b>CUCoreLib updated to 1.0.4</b> (1.0.5? Just download the most recent one lol)", "- <b>CUCoreLib 已更新至 1.0.4</b>（1.0.5？直接下载最新的那个就行 哈哈）"),
        ("- Fixed a bug that affected pixelated rendering during certain cutscenes.", "- 修复了影响部分过场动画中像素化渲染的 bug。"),
        ("- Fixed a bug that allowed Mercenary's Hollow stutter to apply to all talker lines.", "- 修复了导致 Mercenary 的空洞卡顿效果作用于所有台词的问题。"),
        ("<b>Gunsaw Genetics v1.7.5 changelog:</b>", "<b>Gunsaw Genetics v1.7.5 更新日志：</b>"),
        ("<b>Roza Overhaul:</b>", "<b>Roza 重做：</b>"),
        ("<i>Roza is not done. Dialogue and portrait art are still being worked on, alongside a few more things for the species itself.</i>", "<i>Roza 尚未完成。对话与立绘仍在制作中，该物种本身也还有几项内容待处理。</i>"),
        ("<b>Torpor:</b>", "<b>蛰伏：</b>"),
        ("- Active ability. Hold to actively lower own body temperature.", "- 主动能力。按住可主动降低自身体温。"),
        ("- - Lower limit of 29°C. You cannot cool yourself below this temp.", "- - 下限为 29°C。无法将自身体温降到该温度以下。"),
        ("- Works even at higher temperatures, but has reduced effectiveness the higher those temperatures are", "- 在体温较高时同样有效，但体温越高，效果越弱"),
        ("- - For reference, ~40°C is only ~56% as effective and ~42°C is only ~38% as effective at lowering temperature.", "- - 作为参考，约 40°C 时降温效果仅有约 56%，约 42°C 时仅有约 38%。"),
        ("- Thirst and energy get drained by using this.", "- 使用时会消耗口渴和体力。"),
        ("- - Thirst is 0.5/sec. Increases by 0.05/sec for each second held.", "- - 口渴为 0.5/秒。每多按住一秒，再增加 0.05/秒。"),
        ("- - Energy is 0.15/sec", "- - 体力为 0.15/秒"),
        ("- Scaling cooldown:", "- 递增冷却："),
        ("- - 5 seconds held = ~5 second cooldown (Bumped to minimum 6 seconds if it comes out lesser.)", "- - 按住 5 秒 = 约 5 秒冷却（若结算结果更低，则提升至最低 6 秒。）"),
        ("- - 10 seconds = ~13 seconds", "- - 10 秒 = 约 13 秒"),
        ("- - 20 seconds = ~35 seconds", "- - 20 秒 = 约 35 秒"),
        ("<b>Frozen:</b>", "<b>冻结：</b>"),
        ("- While Torpor is being used, items can sometimes freeze.", "- 使用蛰伏期间，物品有时会冻结。"),
        ("- To freeze:", "- 冻结条件："),
        ("- - Torpor needs to be active", "- - 蛰伏需要处于激活状态"),
        ("- - Body temp must be below 30°C", "- - 体温必须低于 30°C"),
        ("- - Food items need to be wet", "- - 食物需要处于潮湿状态"),
        ("- - Liquid containers need to contain liquid", "- - 液体容器需要装有液体"),
        ("- While frozen, items:", "- 冻结期间，物品："),
        ("- - Cannot be consumed", "- - 无法被食用"),
        ("- - Thaw overtime", "- - 会随时间解冻"),
        ("- - Decay is paused", "- - 腐坏暂停"),
        ("- Frozen items can also be used on the body as a pseudo-icepack.", "- 冻结的物品也可以当作简易冰敷包用在身体上。"),
        ("- - FAR less effective than a real icepack (Around 7% of the normal effect)", "- - 效果远低于真正的冰敷包（约为正常效果的 7%）"),
        ("- - Reduces frozen time and condition when used like this.", "- - 这样使用时，会减少冻结时间和冻结程度。"),
        ("- Frozen tooltip line added", "- 新增冻结提示行"),
        ("- Decay tooltip altered for frozen items.", "- 为冻结物品调整了腐坏提示。"),
        ("- Talker line added for attempting to consume frozen items.", "- 新增尝试食用冻结物品时的台词。"),
        ("<b>Temperature:</b>", "<b>温度：</b>"),
        ("- Movement slowdown from cold (below 34°C) is reduced by 70%.", "- 寒冷（低于 34°C）造成的移动减速降低 70%。"),
        ("- The frost screen effect is reduced by 70%.", "- 结霜屏幕效果降低 70%。"),
        ("- Cold no longer drains hunger between 30°C and 32°C.", "- 在 30°C 到 32°C 之间，寒冷不再消耗饥饿。"),
        ("- Roza's body doesn't take real cold damage until roughly 2°C colder than other species would.", "- Roza 的身体要到比其他物种再低约 2°C 时，才会受到真正的寒冷伤害。"),
        ("- - Just like Dune, the WoundView warnings are shifted to match.", "- - 与 Dune 一样，伤势视图的警告也相应延后。"),
        ("- Heartrate no longer drops as harshly in the cold. Cancels ~35% of the normal heart rate decrease while cold.", "- 寒冷时心率不再下降得那么剧烈。寒冷状态下可抵消约 35% 的正常心率下降。"),
        ("- - No effect during fibrillation. Roza can still die from being too cold, it's just harder.", "- - 心律失常期间无效。Roza 仍可能因过冷而死亡，只是更难。"),
        ("<b>Diet:</b>", "<b>饮食：</b>"),
        ("<i>This is a bit weird since we don't have a ton of info on what a Snow Strider actually is. Since Roza is directly from Experiment, I just left it be, for now.</i>", "<i>这有点奇怪，因为我们对雪行者究竟是什么了解得并不多。由于 Roza 直接来自 Experiment，目前我就先保持原样。</i>"),
        ("- Eating other Sawians (Yellow Flesh, Internal Organs) causes an additional -7.5 mood loss", "- 食用其他 Sawian（黄色肉块、内脏团）会额外造成 -7.5 的心情损失"),
        ("- - Unique talker line for Roza when resorting to cannibalism", "- - Roza 在被迫同类相食时有专属台词"),
        ("- Mood takes twice as long to naturally return to neutral. (Positive and negative)", "- 心情自然回归中性所需的时间翻倍。（无论正面还是负面）"),
        ("- Threatening a trader costs 2x the normal mood and trauma hit.", "- 威胁商人造成的心情与心理创伤代价为正常的 2 倍。"),
        ("- Killing a trader applies an additional -10 mood and +5 trauma", "- 杀死商人会额外造成 -10 心情和 +5 心理创伤"),
        ("- Seeing a corpse costs 1.75x the normal mood loss (Might be too oppressive)", "- 看到尸体造成的心情损失为正常的 1.75 倍（可能过于压抑）"),
        ("- Breaking a corpse costs 2x the normal mood loss", "- 破坏尸体造成的心情损失为正常的 2 倍"),
        ("- Hugging a trader now requires 25 less reputation", "- 现在拥抱商人所需的好感度降低 25"),
        ("- Successful hugs give 2x the normal mood and reputation gain", "- 成功拥抱获得的心情和好感度为正常的 2 倍"),
        ("- - Failed hugs are unaffected.", "- - 拥抱失败不受影响。"),
        ("<b>Dune Changes:</b>", "<b>Dune 改动：</b>"),
        ("- Changed heartrate during higher temps to give Dune a more stable bpm. Forgot to add this last update.", "- 调整了高温时的心率，使 Dune 的心率更加稳定。上次更新忘了加这一条。"),
        ("- - Same deal as Roza's heart changes above.", "- - 与上文 Roza 的心率改动同理。"),
        ("<b>Universal Diet Changes:</b>", "<b>通用饮食改动：</b>"),
        ("- Carnivores can now consume soup.", "- 食肉现在可以食用汤。"),
        ("<b>Species Config added:</b>", "<b>新增物种配置：</b>"),
        ("- Config button added to the mod's main menu.", "- 在模组主菜单中新增配置按钮。"),
        ("- Allows configuration of all built-in species in the mod.", "- 可对模组中所有内置物种进行配置。"),
        ("- Altered species <i>do</i> get marked as modified", "- 被修改过的物种<i>确实</i>会被标记为已修改"),
        ("- - This will be used in the future to block certain things", "- - 这将在未来用于屏蔽某些东西"),
        ("- - Unlock settings are never going to be removed, though. (And will continue to be added upon with any new additions that are gated)", "- - 不过解锁设置永远不会被移除。（并且今后任何有解锁门槛的新增内容都会继续加入其中）"),
        ("- Roza woundview sprites added (by ThePristineAnt!!!!)", "- 添加了 Roza 的伤势视图贴图（由 ThePristineAnt 制作！！！！）"),
        ("- Milky woundview sprite fixes", "- 修复 Milky 的伤势视图贴图"),
        ("<b>XP Multipliers:</b>", "<b>经验倍率：</b>"),
        ("- - STR: 70%", "- - 力量：70%"),
        ("- - RES: 80%", "- - 韧性：80%"),
        ("- - INT: 110%", "- - 智力：110%"),
        ("- - STR: 60%", "- - 力量：60%"),
        ("- - RES: 125%", "- - 韧性：125%"),
        ("- - INT: 115%", "- - 智力：115%"),
        ("- - STR: 120%", "- - 力量：120%"),
        ("- - RES: 115%", "- - 韧性：115%"),
        ("- - INT: 95%", "- - 智力：95%"),
        ("- - STR: 100% (Unchanged)", "- - 力量：100%（未改动）"),
        ("- - RES: 70%", "- - 韧性：70%"),
        ("- - STR: 90%", "- - 力量：90%"),
        ("- - RES: 130%", "- - 韧性：130%"),
        ("- - INT: 75%", "- - 智力：75%"),
        ("- - RES: 140%", "- - 韧性：140%"),
        ("- - INT: 70%", "- - 智力：70%"),
        ("- - INT: 90%", "- - 智力：90%"),
        ("- - STR: 110%", "- - 力量：110%"),
        ("- - INT: 100% (Unchanged)", "- - 智力：100%（未改动）"),
        ("- - RES: 90%", "- - 韧性：90%"),
        ("- - RES: 135%", "- - 韧性：135%"),
        ("- - STR: 50%", "- - 力量：50%"),
        ("- - RES: 55%", "- - 韧性：55%"),
        ("- - INT: 65%", "- - 智力：65%"),
        ("- Dune buff:", "- Dune 增强："),
        ("- - INT: 20% -> 35%", "- - 智力：20% -> 35%"),
        ("<b>Stat Changes:</b>", "<b>属性改动：</b>"),
        ("- - STR: 8", "- - 力量：8"),
        ("- - RES: 10", "- - 韧性：10"),
        ("- - INT: 9", "- - 智力：9"),
        ("- - STR: 9", "- - 力量：9"),
        ("- - RES: 6", "- - 韧性：6"),
        ("- - INT: 6 (Unchanged)", "- - 智力：6（未改动）"),
        ("- - RES: 11", "- - 韧性：11"),
        ("- - INT: 5 (Unchanged)", "- - 智力：5（未改动）"),
        ("- Trait text reformatted / rewritten", "- 特质文本已重新排版 / 重写"),
        ("- - This was annoying asf to do, so it's a little weird looking. I'm not touching it for a while.", "- - 做这个烦得要死，所以看起来有点怪。我暂时不会碰它。"),
        ("<b>Dune Overhaul:</b>", "<b>Dune 重做：</b>"),
        ("<i>Keep in mind that certain passive traits have already been added. Check previous changelogs.</i>", "<i>请记住，某些被动特质已经添加过了。查看之前的更新日志。</i>"),
        ("<b>Feeding:</b>", "<b>进食：</b>"),
        ("- Hug is entirely replaced with a bite.", "- 拥抱完全被替换为啃咬。"),
        ("- - The button icon will likely be replaced later. I just made something quickly so it wasn't blank.", "- - 按钮图标之后可能会替换。我只是快速做了个东西，免得空着。"),
        ("- With non-Dune traders, you need 150 rep to bite, and can only do so once per trader.", "- 对非 Dune 商人，你需要 150 好感度才能咬，且每个商人只能咬一次。"),
        ("- - Restores 20 hunger", "- - 恢复 20 点饥饿"),
        ("- - Drops reputation by 50", "- - 好感度下降 50"),
        ("- Dune traders have no reputation or once-only restriction, but won't allow it below 700 health.", "- Dune 商人没有好感度或仅限一次的限制，但生命值低于 700 时不允许。"),
        ("- - No reputation cost", "- - 无好感度消耗"),
        ("<b>Self-Cannibalization:</b>", "<b>自我同类相食：</b>"),
        ("- If hunger reaches 0 or below, a short countdown begins. Failing to eat in time results in Dune eating a piece of themself.", "- 如果饥饿降到 0 或以下，会开始一段短暂倒计时。没能在时限内进食，Dune 就会吃掉自己的一块肉。"),
        ("- - Restores a good chunk of hunger afterwards, so it isn't a death spiral", "- - 之后会恢复相当一部分饥饿度，所以不会陷入死亡螺旋"),
        ("- Moodle added", "- 已添加状态图标"),
        ("- Dune enjoys the heat. Between 40°C and 41°C, mood slowly improves (no bonus below or above this range).", "- Dune 喜欢高温。在 40°C 到 41°C 之间，心情会缓慢改善（低于或高于此范围都没有加成）。"),
        ("- Being hot no longer increases thirst drain for Dune specifically.", "- 对 Dune 而言，体温过高不再加快口渴消耗。"),
        ("- Movement slowdown from heat (above 38.5°C) is reduced by 70%.", "- 高温（38.5°C 以上）导致的移动减速降低 70%。"),
        ("- The heat screen effect is reduced by 70%.", "- 高温的屏幕效果降低 70%。"),
        ("- Dune's body doesn't take real heat damage (brain health / blood volume loss) until roughly 2°C hotter than other species would.", "- Dune 的身体要比其他物种高出大约 2°C 才会真正受到高温伤害（脑部健康 / 血量损失）。"),
        ("- - This means Dune's dying and critically dying states (used for on-screen warnings and such) are also adjusted to match. You won't see critical heat warnings unless something else is actually wrong.", "- - 这意味着 Dune 的濒死和危重状态（用于屏幕警告等）也相应调整。除非确实出了别的问题，否则你不会看到高温危重警告。"),
        ("- No longer can trigger Last Stand", "- 不再能触发背水一战"),
        ("- Mood cannot go below -30 or above 60 (Hard setting to 0 is removed)", "- 心情不能低于 -30 或高于 60（困难设置下的 0 限制已移除）"),
        ("- Sickness cap increased to 75 (Was 40)", "- 疾病上限提高到 75（原为 40）"),
        ("- Weight gain from eating food is reduced by 40%.", "- 进食导致的体重增加降低 40%。"),
        ("- Sickness from overeating (eating past being full) is reduced by 80%.", "- 暴食（吃饱后继续吃）导致的疾病降低 80%。"),
        ("- Healing rate increased from 0.5 to 0.75", "- 治疗速率从 0.5 提高到 0.75"),
        ("- Health increased from 0.9 to 0.95", "- 健康从 0.9 提高到 0.95"),
        ("<b>Diets added:</b>", "<b>已添加饮食：</b>"),
        ("- Dune is now properly a carnivore. Eating non-meat now has penalties.", "- Dune 现在正式是食肉动物。吃非肉类现在会有惩罚。"),
        ("- Penalties for eating outside of your species diet include:", "- 吃本物种饮食之外的食物会有以下惩罚："),
        ("- - 35% less hunger restored from eaten food", "- - 吃下的食物恢复的饥饿度减少 35%"),
        ("- - -3 Mood", "- - 心情 -3"),
        ("- - +8 Sickness", "- - 疾病 +8"),
        ("- Mindwipe does clear diets, but certain properties will still linger", "- 精神抹除剂确实会清除饮食，但某些属性仍会残留"),
        ("- - Such as Dune's weight gain reduction or overfeed sickness reduction", "- - 例如 Dune 的体重增加降低或暴食疾病降低"),
        ("- Other species will definitely be added to this system. Milky is a semi-herbivore, for example.", "- 其他物种肯定会加入这套系统。例如 Milky 是半食草动物。"),
        ("<b>XP Multipliers added:</b>", "<b>已添加经验倍率：</b>"),
        ("<i>100% is baseline. Higher is better.</i>", "<i>100% 为基准。越高越好。</i>"),
        ("- - STR: 115%", "- - 力量：115%"),
        ("- - RES: 110%", "- - 韧性：110%"),
        ("- - INT: 20%", "- - 智力：20%"),
        ("- - STR: 85%", "- - 力量：85%"),
        ("- - INT: 125%", "- - 智力：125%"),
        ("- - STR and RES are default", "- - 力量与韧性为默认值"),
        ("- - INT: 35%", "- - 智力：35%"),
        ("- Setting added to toggle this off (All stats revert to 1x / 100%). Default on.", "- 新增设置项可关闭此功能（所有属性恢复为 1x / 100%）。默认开启。"),
        ("- Menu text updated to show multipliers when changed.", "- 菜单文本已更新，改动时会显示倍率。"),
        ("- All species will eventually have these set. This is the first iteration and requires testing before full implementation.", "- 所有物种最终都会配置这些数值。这是第一轮迭代，全面实装前需要测试。"),
        ("<b>Localization:</b>", "<b>本地化：</b>"),
        ("- Old zh.json removed", "- 移除了旧的 zh.json"),
        ("- New zh.json added (This was made by lpoklpok!!!)", "- 新增了 zh.json（由 lpoklpok 制作！！！）"),
        ("<b>Info Panel:</b>", "<b>信息面板：</b>"),
        ("- Dune updated", "- Dune 已更新"),
        ("<b>Gunsaw Genetics v1.6.6 Changelog:</b>", "<b>Gunsaw Genetics v1.6.6 更新日志：</b>"),
        ("<i>A lot of the MP is being removed for now. It's just causing more issues than it fixes. MP support will be on hold until the MP mod itself updates to v5, sorry.", "<i>目前大量联机内容被移除。它造成的问题比解决的问题还多。联机支持将暂时搁置，直到联机模组本身更新到 v5，抱歉。"),
        ("I've kept what does work, though. Mostly visual stuff.", "不过我保留了确实能用的部分。主要是视觉方面的内容。"),
        ("If you notice that a bug report you made was deleted (On Nexus), that was intentional. They aren't applicable anymore with these changes.</i>", "如果你发现自己提交的 bug 报告被删除了（在 Nexus 上），那是故意的。这些报告在本次改动后已不再适用。</i>"),
        ("<b>Update Notifier added:</b>", "<b>新增更新提示：</b>"),
        ("- Popup that triggers when a new version of GG is uploaded to Nexus", "- 当 GG 有新版本上传到 Nexus 时触发的弹窗"),
        ("- Confirm and link button", "- 确认与链接按钮"),
        ("- Checkbox to disable", "- 可禁用的复选框"),
        ("- - Config (File, not in-game) entry to toggle as well", "- - 也可通过配置（文件，非游戏内）条目开关"),
        ("- Changelog attached", "- 附带更新日志"),
        ("- Since this is added in this update, you won't see it until the next update.", "- 由于这是本次更新才加入的，你要到下次更新才能看到它。"),
        ("<b>Changelogs added (In-game):</b>", "<b>新增更新日志（游戏内）：</b>"),
        ("- New button on the main screen of the mod", "- 模组主界面新增按钮"),
        ("- - ! in the top right", "- - 右上角的 !"),
        ("- Displays all of the changelogs for the mod, latest first", "- 显示该模组的所有更新日志，最新在前"),
        ("<b>Custom Death Screens:</b>", "<b>自定义死亡画面：</b>"),
        ("- Custom Death screens are now able to be added.", "- 现在可以添加自定义死亡画面。"),
        ("- - Currently, this doesn't have anything beyond a single test, which is disabled.", "- - 目前除了一项已禁用的测试外没有任何内容。"),
        ("- - Folder path is CustomBodySprites/CustomDeathScreens if you'd like to customize this yourself, just be sure to remove the !", "- - 如果你想自己自定义，文件夹路径是 CustomBodySprites/CustomDeathScreens，注意务必移除其中的 !"),
        ("- Fixed a bug that allowed Voyager to repeatedly steal the same item (If trade menu wasn't reopened)", "- 修复了 Voyager 可以反复偷取同一物品的 bug（交易菜单未重新打开时）"),
        ("<b>MP CHANGES:</b>", "<b>联机改动：</b>"),
        ("<b>Conversations:</b>", "<b>对话：</b>"),
        ("- Made conversations rarer between players", "- 降低了玩家之间对话的频率"),
        ("- Fixed a multiplayer bug where species selection could corrupt sync data for other players", "- 修复了一个联机 bug：选择物种可能会破坏其他玩家的同步数据"),
        ("- Removed several broken multiplayer systems (stat resync, vitals sync, save/load, etc.) that were causing more harm than good", "- 移除了若干损坏的联机系统（属性重同步、生命体征同步、存档/读档等），它们弊大于利"),
        ("- - This means that vanilla + MP systems are back in control of things, not my own stuff.", "- - 这意味着由原版 + 联机系统重新接管，而不是我自己的那套。"),
        ("- Various internal cleanup and stability fixes", "- 各项内部清理与稳定性修复"),
        ("<b>Mercenary Changes:</b>", "<b>Mercenary 改动：</b>"),
        ("- Charge now properly depletes (No more constant regen!)", "- 充能现在会正确耗尽（不再持续回复！）"),
        ("- - Doesn't regen while in-use", "- - 使用期间不会回复"),
        ("- - Regen is stopped upon hitting zero for a brief moment (Visual)", "- - 归零时会短暂停止回复（视觉表现）"),
        ("- - These were already in, they just couldn't be triggered with the constant regen", "- - 这些本来就有，只是持续回复导致它们无法触发"),
        ("- Shrapnel is now cleared on reform / swap", "- 弹片现在会在重塑 / 交换时清除"),
        ("- Overdose is now cleared on reform / swap", "- 药物过量现在会在重塑 / 交换时清除"),
        ("- Radiation is now cleared on reform / swap", "- 辐射现在会在重塑 / 交换时清除"),
        ("- Hollow text effects should scale better (Hardly showed at lower Hollow levels)", "- 空洞文本效果的表现应该更合理了（空洞等级较低时几乎不显示）"),
        ("- Hollow now properly clears post-death", "- 空洞现在会在死亡后正确清除"),
        ("- Lowered the volume of reform / swap", "- 降低了重塑 / 交换的音量"),
        ("<b>Velvet Changes:</b>", "<b>Velvet 改动：</b>"),
        ("- Web passive regen changed to 15s (Accidently left it very low, but this is still a buff from the original version)", "- 蛛网被动回复改为 15s（不小心把它设得太低了，但相对原版这仍然是增强）"),
        ("- No longer locked to 3 INT. My bad.", "- 不再锁定为 3 智力。是我的疏忽。"),
        ("<b>WoundView:</b>", "<b>伤势视图：</b>"),
        ("- Custom missing eye(s) sprites added:", "- 新增自定义缺眼贴图："),
        ("- - Velvet, Baron, Dune, and Milky", "- - Velvet、Baron、Dune 和 Milky"),
        ("- Custom disfigured sprites added:", "- 新增自定义面部缺损贴图："),
        ("- Baron WoundView alignment fixes", "- Baron 伤势视图对齐修复"),
        ("<b>Portraits:</b>", "<b>头像：</b>"),
        ("- Velvet Portrait added (by Toky!!!!)", "- 新增 Velvet 头像（由 Toky 制作！！！！）"),
        ("<b>Dialogue:</b>", "<b>对话：</b>"),
        ("- Voyager lines added (Trader + Self)", "- 新增 Voyager 台词（商人 + 自身）"),
        ("<b>Notes / E-PDA:</b>", "<b>笔记 / E-PDA：</b>"),
        ("- All of these below are written by ThePristineAnt!!!!!! Thank him!!!", "- 以下全部内容由 ThePristineAnt 撰写！！！！！！感谢他！！！"),
        ("- Random dialogue can now start between different players", "- 不同玩家之间现在可以随机开始对话"),
        ("- - Host config. You can turn this off entirely.", "- - 主机配置。你可以完全关闭它。"),
        ("- - Random chance + Cooldown (Might need tweaking)", "- - 随机概率 + 冷却（可能需要调整）"),
        ("- - Interrupted by certain events (Might need tweaking as well)", "- - 会被某些事件打断（同样可能需要调整）"),
        ("- Conversations depend on the species of each player, and how many times they have talked", "- 对话取决于每位玩家的物种，以及他们交谈过的次数"),
        ("- Current Convos:", "- 当前对话："),
        ("<b>CatPatch Compat:</b>", "<b>CatPatch 兼容：</b>"),
        ("- Voyager now refuses hugs from non-Voyagers", "- Voyager 现在会拒绝非 Voyager 的拥抱"),
        ("- Voyager now refuses kisses from non-Voyagers", "- Voyager 现在会拒绝非 Voyager 的亲吻"),
        ("- Dialogue added for each", "- 分别为两者添加了对话"),
        ("<b>Fixes (Hopefully...):</b>", "<b>修复（但愿如此）：</b>"),
        ("- Saving has been improved. Items are still weird, but the rest should be a lot more stable", "- 存档已得到改进。物品仍然有些奇怪，但其余部分应该稳定得多"),
        ("- - Stuff is still probably going to be wiped or loaded at the wrong time. It's a bunch of tangled bs that I can't bring myself to care about. Enjoy.", "- - 有些东西大概还是会被清空，或者在错误的时机加载。这堆烂摊子乱得我实在懒得管。玩得开心。"),
        ("- Natural healing shouldn't be stuck anymore. Whoops...", "- 自然愈合应该不会再卡住了。哎呀..."),
        ("- Sleeping no longer drains quickly for non-hosts", "- 非主机玩家睡觉时不再快速流失"),
        ("- Velvet can now cannibalize in MP", "- Velvet 现在可以在联机中同类相食"),
        ("- Voyager can now properly steal from traders", "- Voyager 现在可以正确地从商人处偷窃"),
        ("- Voyager can now properly stealth attack traders", "- Voyager 现在可以正确地对商人发动潜行攻击"),
        ("- Traders becoming hostile from stealing are now synced across the server", "- 因偷窃而变得敌对的商人现在会在整个服务器同步"),
        ("- Traders becoming hostile from stealth attacks are now synced across the server (Music / inventory might still be weird on non-host)", "- 因潜行攻击而变得敌对的商人现在会在整个服务器同步（非主机端的音乐 / 物品栏可能仍会有些异常）"),
        ("- Traders now properly drop inventory for all of the above", "- 以上所有情况下，商人现在都会正确掉落物品栏"),
        ("- Dialogue is now properly applied per-player. (Host doesn't determine the lines for the entire lobby anymore)", "- 对话现在会按玩家分别正确应用。（主机不再为整个房间决定台词）"),
        ("<i>This is the first version of MP support for Gunsaw Genetics.  Most issues still exist, and this is still going to be highly buggy. This is essentially a test of what I CAN fix, rather than complete MP support. If the changes listed here don't work, please let me know. That is far more important to know about than MP issues that aren't listed here.</i>", "<i>这是 Gunsaw Genetics 联机支持的第一个版本。大部分问题依然存在，而且这个版本仍然会有大量 bug。它本质上是对我能修好的部分的一次测试，而不是完整的联机支持。如果这里列出的改动没有生效，请告诉我。这比那些没在列表里的联机问题重要得多。</i>"),
        ("<b>SP CHANGES:</b>", "<b>单人改动：</b>"),
        ("<b>Custom Species:</b>", "<b>自定义物种：</b>"),
        ("- New tab on the mod's menu", "- 模组菜单新增标签页"),
        ("- Allows for the creation of custom species.", "- 可以创建自定义物种。"),
        ("- Abilites are not included, but base stats (Vanilla and mod) are avaliable", "- 不包含能力，但基础属性（原版与模组）都可以设置"),
        ("- G4-A custom species added for reference", "- 添加了 G4-A 自定义物种作为参考"),
        ("- Help section for further customization", "- 提供进一步自定义的帮助部分"),
        ("- - Specifically: Character sprites, WoundView sprites, and portrait art", "- - 具体为：角色贴图、伤势视图贴图与肖像美术"),
        ("- Species picking works independently for host and non-host", "- 物种选择对主机与非主机各自独立生效"),
        ("- Stats (STR/RES/INT) now apply correctly for non-hosts, including decreases (the exp-boundary bug)", "- 属性（力量/韧性/智力）现在对非主机玩家正确生效，包括属性下降（经验边界 bug）"),
        ("- Starting items (e.g. Voyager's cloak) now spawn correctly for non-hosts.", "- 初始物品（如 Voyager 的隐身装置）现在能正确发放给非主机玩家。"),
        ("- Custom sprite slots now render correctly for everyone", "- 自定义贴图槽位现在对所有人都能正确渲染"),
        ("- Late-join snapshot. A player joining mid-session immediately sees everyone's correct species/sprites, not just after the next change.", "- 中途加入快照。中途加入的玩家能立即看到所有人正确的物种/贴图，而不必等到下一次变更。"),
        ("- WoundView species name label no longer stuck on \"Experiment\".", "- 伤势视图的物种名称标签不再卡在“Experiment”。"),
        ("- Species identity is now queryable. I'll be doing special stuff for MP only, so this is necessary.", "- 物种身份现在可以被查询。我将只针对联机做一些特殊处理，所以这是必要的。"),
        ("<b>Visual effects:</b>", "<b>视觉效果：</b>"),
        ("- Voyager's Cloak", "- Voyager 的隐身装置"),
        ("- Crystal's grapple tongue", "- Crystal 的抓取舌"),
        ("- Velvet's webs (both line and point types) spawn, are climbable by everyone, and durability/breaking stays consistent across all clients, with proper per-player caps.", "- Velvet 的蛛网（线型与点型两种）现在会生成，所有人都能攀爬，耐久/断裂在所有客户端之间保持一致，并按玩家正确计算上限。"),
        ("- All Talker lines (custom and vanilla-replacements) now display for non-hosts, and are properly seen by everyone regardless of who's speaking.", "- 所有 Talker 台词（自定义与原版替换）现在都会向非主机玩家显示，无论说话者是谁，所有人都能正确看到。"),
        ("- Fixed a bug with RshLib that caused Voyager to bug out.", "- 修复了一个由 RshLib 引起、导致 Voyager 出错的 bug。"),
        ("- Added placeholder moodle for Mercenary's Hollow.", "- 为 Mercenary 的空洞添加了占位状态图标。"),
        ("Hopefully this fixes that issue. Works on my end... :voyager:", "但愿这能解决那个问题。在我这边是好的... :voyager:"),
        ("<b>Mercenary added:</b>", "<b>新增 Mercenary：</b>"),
        ("- Unlocked by changing the config setting for now. Will be given a proper obtainment later.", "- 目前通过修改配置项解锁。之后会给出正规的获取方式。"),
        ("- Once unlocked, Ctrl + Left click Experiment", "- 解锁后，Ctrl + 左键点击 Experiment"),
        ("- Three chip-based abilities:", "- 三个基于芯片的能力："),
        ("- - Levitation", "- - 悬浮"),
        ("- - - Grabs any loose object or creature at range", "- - - 远距离抓取任何散落物体或生物"),
        ("- - - Force is mass-dependent both ways.Heavy objects barely move but throw Mercenary back harder. Light objects fling easily.", "- - - 施力与质量相关，且双向作用。重物几乎纹丝不动，但会把 Mercenary 反推得更狠。轻物则轻易飞出。"),
        ("- - - Living targets resist much more than objects", "- - - 活体目标的抗性远高于普通物体"),
        ("- - - Drains charge while active.", "- - - 激活期间持续消耗储量。"),
        ("- - Reformation", "- - 重塑"),
        ("- - - On death, time slows and a short window opens to cheat it", "- - - 死亡时，时间会变慢，并短暂开启一个可以欺骗死亡的窗口"),
        ("- - - Reforms the body. Clears breaks, bleeding, and infection, regrows lost limbs, and restores vitals.", "- - - 重塑身体。清除骨折、出血与感染，再生失去的肢体，并恢复生命体征。"),
        ("- - - Letting the window expire is permanent death", "- - - 让窗口超时即为永久死亡"),
        ("- - - Increases Hollow on use.", "- - - 使用时增加空洞。"),
        ("- - - Consumes charge on use.", "- - - 使用时消耗储量。"),
        ("- - Mindswap", "- - 意识交换"),
        ("- - - An alternative to Reforming. Forces a nearby Sawian trader out of their body and takes it instead.", "- - - 重塑的替代方案。将附近一名 Sawian 商人的意识强行逐出躯体，并占据它。"),
        ("- - - Old body is left behind, INT, chips, scarf, and hyper-regeneration always carry over regardless of body.", "- - - 旧躯体被留在原地；智力、芯片、围巾与超速再生无论换到哪具身体都会保留。"),
        ("- - - Stats reset to the new body's baseline (with a small bonus).", "- - - 属性重置为新躯体的基准值（附带少量加成）。"),
        ("- Shared charge system powers Levitation, Reformation, and Mindswap, regenerating passively over time", "- 共用储量系统为悬浮、重塑与意识交换供能，并随时间被动恢复"),
        ("- Hollow: a permanent, worsening condition that builds up from using Reformation and (especially) Mindswap", "- 空洞：一种永久且不断恶化的状态，因使用重塑和（尤其是）意识交换而累积"),
        ("- - Gradually desaturates vision", "- - 逐渐降低视野的色彩饱和度"),
        ("- - Narrows how far mood can swing in either direction", "- - 缩小心情向任一方向波动的幅度"),
        ("- - Reduces trauma buildup", "- - 降低心理创伤的累积"),
        ("- - Increases speech stammering / cutting off mid-sentence", "- - 增加言语结巴 / 中途断句"),
        ("- - Increases trader reputation penalty", "- - 加重商人好感度惩罚"),
        ("- While wearing another Sawian's body via Mindswap, Mercenary gains access to that species' signature ability (currently just Milky's Hyper-Focus)", "- 通过意识交换穿戴另一名 Sawian 的身体时，Mercenary 可以使用该物种的标志性能力（目前只有 Milky 的超聚焦）"),
        ("- Portrait art by ThePristineAnt!!!!", "- 肖像美术由 ThePristineAnt 绘制！！！！"),
        ("- Cloak is now a wearable item", "- 隐身装置现在是一件可穿戴物品"),
        ("- - Active Equipment", "- - 主动装备"),
        ("- - Toggles cloaking state on / off", "- - 切换隐身状态的开 / 关"),
        ("- - While cloaked, crouching puts you in a special movement state", "- - 隐身期间蹲伏会进入一种特殊移动状态"),
        ("- - - Allows cloaking during movement", "- - - 允许在移动中保持隐身"),
        ("- - - Disables the effects of certain traps", "- - - 使某些陷阱的效果失效"),
        ("- - - Drains more power from the battery", "- - - 消耗更多电池电量"),
        ("- - Susceptible to radiation", "- - 易受辐射影响"),
        ("- - Susceptible to water / wetness", "- - 易受水 / 潮湿影响"),
        ("- - Battery powered", "- - 由电池驱动"),
        ("- Toughness slightly lowered (0.84 -> 0.8)", "- 坚韧略微降低（0.84 -> 0.8）"),
        ("- Dialogue added for:", "- 新增对话："),
        ("- - Low radiation", "- - 低辐射"),
        ("- - Mid radiation", "- - 中辐射"),
        ("- - High radiation", "- - 高辐射"),
        ("- - High radiation force decloaking", "- - 高辐射强制解除隐身"),
        ("- - Wetness force decloaking", "- - 潮湿强制解除隐身"),
        ("- - Trying to use cloak without it equipped", "- - 未装备隐身装置时尝试使用隐身"),
        ("- - Trying to use cloak while battery is drained", "- - 电池耗尽时尝试使用隐身"),
        ("- - Trying to use cloak while having high radiation", "- - 身处高辐射时尝试使用隐身"),
        ("- - Trying to use cloak while very wet", "- - 极度潮湿时尝试使用隐身"),
        ("- - Wet dialogue lines in general", "- - 通用的潮湿对话台词"),
        ("- - Self-harm and suicide lines", "- - 自残与自杀台词"),
        ("- Passive aspects added:", "- 新增被动特性："),
        ("- - Idolatry", "- - 崇物"),
        ("- - - Unique interactions based on items used, worn, and held", "- - - 根据使用、穿戴和手持的物品触发独特互动"),
        ("- - - Items include:", "- - - 物品包括："),
        ("- - - - Pistol, rifle, shotgun, trauma rig, riot helmet, wood sandals, tactical boots, machete, titanium machete, makeshift rifle, makeshift digging tool, ripped dressing, old rag, crude cleaver, makeshift wrench, makeshift headlamp, makeshift helmet, and sling bag", "- - - - 手枪、步枪、霰弹枪、战术胸挂、防暴头盔、木屐、战术靴、砍刀、钛合金砍刀、简易步枪、简易挖掘工具、撕裂的绷带、旧布条、粗制菜刀、简易扳手、简易头灯、简易头盔和植物纤维挎包"),
        ("- - Arrogance", "- - 傲慢"),
        ("- - - Two mood states. +30 and -30.", "- - - 两种心情状态。+30 与 -30。"),
        ("- - - +30 represents pride, giving reduced mood loss for corpses, allowing stealth attacks, improving preferred item damage, etc.", "- - - +30 代表自豪，减少看到尸体时的心情损失，允许潜行攻击，提升偏好物品的伤害等。"),
        ("- - - -30 represents desperation, preventing stealing, allowing hugging and resting with traders, and giving extra mood loss upon viewing corpses.", "- - - -30 代表绝望，禁止偷窃，允许与商人拥抱和休息，并会在看到尸体时造成额外心情损失。"),
        ("- Voyager has increased mood loss resistance as mood lowers, but that reverses upon going below -85, making Voyager far more susceptible to mood loss.", "- Voyager 会在心情降低时获得更高的心情损失抗性，但一旦低于 -85 就会反转，使 Voyager 变得更容易受到心情损失影响。"),
        ("- Voyager does increased damage (with claws) to enemies. Environment damage is unaffected.", "- Voyager 用爪对敌人造成更高伤害。环境伤害不受影响。"),
        ("- Stealth Attacks", "- 潜行攻击"),
        ("- - Available while cloaked and crouched near an unaware trader", "- - 在隐身且蹲伏靠近未察觉的商人时可用"),
        ("- - Unarmed attacks deal heavy damage and force combat", "- - 徒手攻击造成大量伤害并强制进入战斗"),
        ("- - Armed (non-firearm) attacks kill outright, at the cost of item durability and a small chance to break the weapon", "- - 持械（非枪械）攻击可直接击杀，代价是物品耐久度以及有较小几率损坏武器"),
        ("- Stealing", "- 偷窃"),
        ("- - Additional option to steal from traders", "- - 新增从商人处偷窃的选项"),
        ("- - Chance to succeed scales with item value and Voyager's INT", "- - 成功几率随物品价值和 Voyager 的智力提升"),
        ("- - Failure turns the trader hostile", "- - 失败会使商人转为敌对"),
        ("- Reworked self-harm", "- 重做自残"),
        ("- - Simple for now. Future mini-game", "- - 目前较为简单。后续会做成小游戏"),
        ("- Reworked suicide", "- 重做自杀"),
        ("- - Fully automated minigame sequence, escalating across multiple limbs with a chance for additional slashes", "- - 全自动的小游戏流程，会逐步升级并蔓延至多个肢体，还有几率造成额外割伤"),
        ("- - Visuals should hopefully be better once I start to properly add custom mini-games.", "- - 等我开始正式加入自定义小游戏后，视觉效果应该会更好。"),
        ("<b>Orange Changes:</b>", "<b>Orange 改动：</b>"),
        ("- Dialogue lines added by frigidFriend / DaryllDemo!!!", "- 由 frigidFriend / DaryllDemo 添加的对话台词！！！"),
        ("- Hand speed scales worse with strength. Clumsy.", "- 手部速度随力量提升的幅度降低。笨拙。"),
        ("- Claws hit harder, tools hit softer.", "- 爪击更重，工具攻击更轻。"),
        ("- Mood swings harder in every direction (150% more impactful, both positive and negative.)", "- 心情在各个方向上的波动都更剧烈（影响程度 +150%，正面和负面皆然。）"),
        ("- Trader reputation on first meeting reflects your current mood. Milky traders will ignore this and try to take advantage of you regardless.", "- 首次见面时的商人好感度会反映你当前的心情。Milky 商人会无视这一点，无论如何都会试图占你便宜。"),
        ("- Hugging traders has a stronger effect on reputation", "- 拥抱商人对好感度的影响更强"),
        ("- Letting Dunes bite you gives a bigger reputation boost", "- 让 Dune 咬你能获得更高的好感度加成"),
        ("- Bone fractures and dislocations heal twice as fast", "- 骨折和脱臼的愈合速度加倍"),
        ("- Recently injured limbs take reduced damage for a short time afterward", "- 近期受伤的肢体会在之后一小段时间内受到的伤害降低"),
        ("<b>Baron Changes:</b>", "<b>Baron 改动：</b>"),
        ("- Toughness reduced (6.0 -> 4.0)", "- 坚韧降低（6.0 -> 4.0）"),
        ("- Velvet note added (Written by ThePristineAnt!!)", "- 新增 Velvet 笔记（由 ThePristineAnt 撰写！！）"),
        ("- Voyager updated", "- Voyager 已更新"),
        ("- Orange updated", "- Orange 已更新"),
        ("- Mercenary added", "- 新增 Mercenary"),
        ("- Added a dedicated settings tab for the mod's own options (ability keybinds, WoundView recolor toggle, text effects toggle, tendril mode, language, etc)", "- 为模组自身的选项新增了专属设置页（技能按键、伤势视图配色开关、文字特效开关、触须模式、语言等）"),
        ("- - This will hopefully be positioned better later", "- - 之后希望能把它放到更合适的位置"),
        ("- WoundView panel borders are now properly recolored. I'll be adjusting these a bit, later on.", "- 伤势视图面板边框现在能正确重新着色了。之后我会再稍微调整一下。"),
        ("- <b>Added CUCoreLib as a dependency </b>", "- <b>新增 CUCoreLib 作为依赖项 </b>"),
        ("- zh.json added (C2H4F2 made this translation! Thank them!!!)", "- 新增 zh.json（该翻译由 C2H4F2 制作！感谢TA！！！）"),
        ("- Velvet lines added (by ThePristineAnt!!!!)", "- 新增 Velvet 台词（由 ThePristineAnt 撰写！！！！）"),
        ("- Dune lines added (by Dirasial!!)", "- 新增 Dune 台词（由 Dirasial 撰写！！）"),
        ("<b>Velvet Overhaul:</b>", "<b>Velvet 重做：</b>"),
        ("- Web Active Ability added", "- 新增蛛网主动技能"),
        ("- - Pressing shoots a small web", "- - 按下会射出小型蛛网"),
        ("- - - Costs 1", "- - - 消耗 1"),
        ("- - - Acts as a grab point, not a rope.", "- - - 作为抓握点，而非绳索。"),
        ("- - Holding shoots a long web", "- - 长按会射出大型蛛网"),
        ("- - - Costs 5", "- - - 消耗 5"),
        ("- - - Climbable. Can span over gaps.", "- - - 可攀爬。能跨越裂隙。"),
        ("- - - Unique interaction when directly hitting Salad (Big cooldown)", "- - - 直接命中 Salad 时有独特互动（长冷却）"),
        ("- - Web supply scales with INT", "- - 蛛网储量随智力提升"),
        ("- - Restored slowly overtime or by sleeping", "- - 随时间缓慢恢复，或通过睡眠恢复"),
        ("- - Max of 5 webs", "- - 最多 5 张蛛网"),
        ("- - Webs decay overtime", "- - 蛛网会随时间衰减"),
        ("- - Slows enemies that come into contact", "- - 减速接触到的敌人"),
        ("- - - Small web has 1 durability, Long has 5.", "- - - 小型蛛网有 1 点耐久，大型有 5 点。"),
        ("- - - Slowness %, duration, and durability damage change per-enemy", "- - - 减速百分比、持续时间和耐久度伤害因敌人而异"),
        ("- Trader Hug action replaced with cannibalization at 200 Rep.", "- 好感度达到 200 时，商人拥抱动作替换为同类相食。"),
        ("- Self-harm and Suicide replaced with self-cannibalization.", "- 自残和自杀替换为自我同类相食。"),
        ("- Woundview art by ThePristineAnt!!!", "- 伤势视图美术由 ThePristineAnt 制作！！！"),
        ("- Extra limbs added to Woundview", "- 伤势视图新增额外肢体"),
        ("- Toggle added to view / interact with extra limbs", "- 新增用于查看 / 互动额外肢体的开关"),
        ("- Immune to trauma", "- 免疫心理创伤"),
        ("- Increased positive mood gain.", "- 提升正面心情获取。"),
        ("- Sleeping resets mood to 0 if positive", "- 若心情为正，睡眠会将其重置为 0"),
        ("- Mood buff upon killing a trader", "- 杀死商人时获得心情增益"),
        ("- No mood loss upon threatening a trader", "- 威胁商人时没有心情损失"),
        ("- No mood loss upon harming a trader", "- 伤害商人时没有心情损失"),
        ("- No mood loss upon seeing corpses", "- 看到尸体时没有心情损失"),
        ("- No mood loss upon destroying corpses", "- 破坏尸体时没有心情损失"),
        ("- Eating Yellow flesh no longer gives sickness", "- 食用黄色肉块不再造成疾病"),
        ("- Eating Yellow flesh no longer has a mood drop", "- 食用黄色肉块不再掉落心情"),
        ("- Eating Internal Organs only gives half sickness", "- 食用内脏团只造成一半疾病"),
        ("- Eating Internal Organs no longer has a mood drop", "- 食用内脏团不再掉落心情"),
        ("<b>Milky Changes:</b>", "<b>Milky 改动：</b>"),
        ("- Woundview head redrawn by ThePristineAnt!", "- 伤势视图头部由 ThePristineAnt 重绘！"),
        ("- Toughness increased", "- 坚韧提升"),
        ("- Hyper-Focus cooldown scales with timescale now", "- 超聚焦冷却现在随游戏速度缩放"),
        ("- Eye adaptation scales with timescale now", "- 眼睛适应现在随游戏速度缩放"),
        ("- Eye adaptation radius increased", "- 眼睛适应半径提升"),
        ("- Eye adaptation brightness decreased (No more glowing Milky...)", "- 眼睛适应亮度降低（Milky 不再发光了...）"),
        ("- Eye glare effect now scales based on:", "- 眼睛眩光效果现在依据以下因素缩放："),
        ("- - Brightness of light source", "- - 光源亮度"),
        ("- - Level of adaptation", "- - 适应程度"),
        ("- Small mood buff upon seeing corpses (No mood drop)", "- 看到尸体时获得小幅心情增益（无心情掉落）"),
        ("- No mood loss upon killing a trader", "- 杀死商人时没有心情损失"),
        ("<b>Albino Changes:</b>", "<b>Albino 改动：</b>"),
        ("- Portrait art redrawn by ThePristineAnt! (Menu + Note)", "- 立绘由 ThePristineAnt 重绘！（菜单 + 笔记）"),
        ("- Portrait art redrawn by ThePristineAnt! (Menu)", "- 立绘由 ThePristineAnt 重绘！（菜单）"),
        ("- Cloaking no longer stacks.", "- 隐身不再叠加。"),
        ("- Cloaking no longer affects visibility outside of cloaking", "- 隐身不再影响隐身状态之外的可见度"),
        ("<b>Species info panel added:</b>", "<b>物种信息面板已添加：</b>"),
        ("- Arrow is located below the STR, RES, INT panel.", "- 箭头位于力量、韧性、智力面板下方。"),
        ("- Displays more detailed info about current species", "- 显示当前物种更详细的信息"),
        ("- Text effects for keywords", "- 关键词的文本特效"),
        ("- Keywords include tooltips for extra information", "- 关键词带有悬浮提示以提供额外信息"),
        ("- Albino info added", "- 添加了 Albino 信息"),
        ("- Milky info added", "- 添加了 Milky 信息"),
        ("- Velvet info added", "- 添加了 Velvet 信息"),
        ("- Baron Prideful entry added", "- 添加了 Baron 自豪条目"),
        ("- Unfinished entries added to species that haven't been overhauled", "- 为尚未重做的物种添加了未完成条目"),
        ("<b>Death screen:</b>", "<b>死亡界面：</b>"),
        ("- Each Sawian is given their proper ID (e.g. SAW-03)", "- 每个 Sawian 都会获得其对应的 ID（例如 SAW-03）"),
        ("- Albino is censored", "- Albino 被屏蔽处理"),
        ("- Icke and Chik use corrupted IDs", "- Icke 和 Chik 使用损坏的 ID"),
        ("- Removed Debug PDA (Whoops)", "- 移除了调试用 E-PDA（哎呀）"),
        ("<b>Localization added:</b>", "<b>已添加本地化：</b>"),
        ("- en.json added", "- 添加了 en.json"),
        ("- ru.json added", "- 添加了 ru.json"),
        ("- - Current Russian translation is just a machine translation of the menu and some of Albino's text. There is a translator working on this, it just takes a while to do stuff like this. This is a placeholder and will not be expanded upon until the proper translation is made.", "- - 当前的俄语翻译只是菜单和部分 Albino 文本的机器翻译。有一位译者正在处理这项工作，只是做这种事需要一些时间。这只是占位内容，在正式翻译完成前不会再扩充。"),
        ("- Config setting for language added", "- 添加了语言配置项"),
        ("<b>Milky changes:</b>", "<b>Milky 改动：</b>"),
        ("- Head Woundview sprite added", "- 添加了头部伤势视图贴图"),
        ("- Active ability Hyper-Focus added", "- 添加了主动技能超聚焦"),
        ("- Ability moodles added for active and cooldown states.", "- 为技能的激活与冷却添加了状态图标。"),
        ("- Blueprints now provide two random recipes when used.", "- 蓝图现在使用时提供两个随机配方。"),
        ("- Hand control strength scaling (In mini-games) improved.", "- 改进了手部控制的力度缩放（小游戏中）。"),
        ("- Better tool scaling", "- 工具缩放更优"),
        ("- Worse claw scaling", "- 爪缩放更差"),
        ("- Milky's eyes adapt to the darkness. This has an adverse effect when going back into a bright area without taking your time.", "- Milky 的眼睛会适应黑暗。如果不慢慢来就贸然回到明亮区域，会产生不良影响。"),
        ("- Self-harm is replaced with vomiting.", "- 自残被替换为呕吐。"),
        ("- Suicide is replaced with a custom event.", "- 自杀被替换为自定义事件。"),
        ("- Starting items removed", "- 移除了初始物品"),
        ("<b>Custom dialogue patch added:</b>", "<b>已添加自定义对话补丁：</b>"),
        ("- Milky lines added (ThePristineAnt wrote these, so thank him!!!)", "- 添加了 Milky 台词（这些是 ThePristineAnt 写的，所以要感谢他！！！）"),
        ("<b>Custom moodle text patch added </b> <i>(This isn't for new moodles. Those were handled in v1.2.0.)</i> <b>:</b>", "<b>已添加自定义状态图标文本补丁 </b> <i>（这不是用于新状态图标的。那些已在 v1.2.0 中处理。）</i> <b>：</b>"),
        ("- Some moodle lines changed for Milky.", "- 更改了 Milky 的部分状态图标文本。"),
        ("<b>Custom Notes and PDA entry system added:</b>", "<b>已添加自定义笔记与 E-PDA 条目系统：</b>"),
        ("- Albino1 note added", "- 添加了 Albino1 笔记"),
        ("- Albino2 note added", "- 添加了 Albino2 笔记"),
        ("- Dune Woundview sprites added", "- 添加了 Dune 伤势视图贴图"),
        ("- Woundview now properly displays species name", "- 伤势视图现在会正确显示物种名"),
        ("- Woundview now has different color palettes per-species.", "- 伤势视图现在按物种使用不同的配色。"),
        ("- Config setting for Woundview coloring added", "- 添加了伤势视图配色的配置项"),
        ("- Config setting for ability keybind added", "- 添加了技能快捷键的配置项"),
        ("- Button added to Woundview panel to toggle coloring in-game", "- 在伤势视图面板中添加了按钮，可在游戏内切换配色"),
        ("- Clicking during menu startup now skips it", "- 菜单启动期间点击现在会跳过它"),
        ("- Albino starting hoodie removed", "- 移除了 Albino 的初始连帽衫"),
        ("- Albino properly unlocks now", "- Albino 现在能正确解锁了"),
        ("- Voyager sprite bug fixes", "- 修复了 Voyager 贴图的 bug"),
        ("<i>Art is now mostly being handled by...</i>", "<i>美术现在主要由...负责</i>"),
        ("This guy is my goat. I couldn't do even a fraction of this myself.", "这家伙就是我的神。这些工作我一个人连一小部分都做不出来。"),
        ("(Specifically:", "（具体来说："),
        ("All custom moodle art.", "所有自定义状态图标美术。"),
        ("Baron WoundView sprites.", "Baron 伤势视图贴图。"),
        ("Orange Portrait art.", "Orange 立绘美术。"),
        ("Albino Portrait art.)", "Albino 立绘美术。）"),
        ("- <b>Custom Moodle System Created:</b>", "- <b>已创建自定义状态图标系统：</b>"),
        ("- - Icke moodles added", "- - 添加了 Icke 状态图标"),
        ("- - Baron moodle added", "- - 添加了 Baron 状态图标"),
        ("- - Albino moodles added", "- - 添加了 Albino 状态图标"),
        ("- <b>Custom Woundview System Created:</b>", "- <b>已创建自定义伤势视图系统：</b>"),
        ("- - Voyager Woundview sprites added", "- - 添加了 Voyager 伤势视图贴图"),
        ("- - Baron Woundview sprites added", "- - 添加了 Baron 伤势视图贴图"),
        ("- - Icke Woundview sprite (Head) added", "- - 添加了 Icke 伤势视图贴图（头部）"),
        ("- - Albino Woundview sprite (Head) added", "- - 添加了 Albino 伤势视图贴图（头部）"),
        ("- <b>Custom Music System Created:</b>", "- <b>已创建自定义音乐系统：</b>"),
        ("- - Albino ability music added (3 tracks)", "- - 添加了 Albino 技能音乐（3 首）"),
        ("- Orange portrait art added", "- 添加了 Orange 立绘美术"),
        ("- Albino portrait art added", "- 添加了 Albino 立绘美术"),
        ("- Chik obtainment added", "- 添加了 Chik 的获取方式"),
        ("- Chik menu page updated", "- 更新了 Chik 菜单页面"),
        ("- Baron passive ability (Prideful) added", "- 添加了 Baron 被动技能（自豪）"),
        ("- <b>Albino changes:</b>", "- <b>Albino 改动：</b>"),
        ("- - Starting stats (INT, etc.) are all set to 4 now", "- - 初始属性（智力等）现在全部设为 4"),
        ("- - Description + Trait text updated", "- - 更新了描述 + 特质文本"),
        ("- - Active Ability (Desync) added", "- - 添加了主动技能（解离）"),
        ("- - Albino is now more susceptible to temperature changes", "- - Albino 现在更容易受温度变化影响"),
        ("- - Enemies spot Albino easier (~2.5x)", "- - 敌人更容易发现 Albino（约 2.5 倍）"),
        ("- - Removed Immunity buff", "- - 移除了免疫力增强"),
        ("- - Albino starts without an eye", "- - Albino 初始缺少一只眼睛"),
        ("- - Albino starts with a single, random, fracture on their legs", "- - Albino 初始腿部带有一处随机骨折"),
        ("- All species (Except Expie) are locked by default", "- 所有物种（除 Expie 外）默认处于锁定状态"),
        ("- Obtainment methods added for each species.", "- 为每个物种添加了获取方式。"),
        ("- Unlock all checkbox added to menu", "- 在菜单中添加了全部解锁复选框"),
        ("- Random button added to menu", "- 在菜单中添加了随机按钮"),
        ("- Loading a save now properly loads sprites", "- 加载存档现在会正确加载贴图"),
        ("- Minor bug fixes", "- 次要 bug 修复"),
    };
}
