internal static class GunsawGeneticsTrTw
{
    public static readonly (string En, string Zh)[] Logs =
    {
        ("[ERROR] Species picker not yet initialized.", "[錯誤] 物種選擇器尚未初始化。"),
        ("[ERROR] You must be playing as Mercenary to use this command.", "[錯誤] 你必須以 Mercenary 身份進行遊戲才能使用此命令。"),
        ("[ERROR] You must be playing as Baron to use this command.", "[錯誤] 你必須以 Baron 身份進行遊戲才能使用此命令。"),
        ("[ERROR] PlayerCamera not found.", "[錯誤] 未找到 PlayerCamera。"),
        ("Running Last Stand visual/audio sequence.", "正在播放「背水一戰」的視覺/音頻序列。"),
        ("Forced post-mindwipe state (Hollow moodle + aftermath effects).", "已強制進入精神抹除後的狀態（空洞狀態圖標 + 後續效果）。"),
        ("Cleared forced mindwipe state and vignette.", "已清除強制精神抹除狀態與畫面暗角。"),
        ("Gunsaw Genetics debug commands:", "Gunsaw Genetics 調試命令 : "),
        ("[ERROR] Usage: GG switchspecies <species> <true/false> [keepStats true/false]", "[錯誤] 用法 : GG switchspecies <物種> <true/false> [keepStats true/false]"),
        ("[ERROR] Usage: GG merchollow <0-10>", "[錯誤] 用法 : GG merchollow <0-10>"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("Switched to {0}.", "已切換到 {0}。"),
        ("Mercenary Hollow level set to {0}.", "Mercenary 的空洞等級已設為 {0}。"),
        ("Baron horns broken set to {0}.", "Baron 已折斷的角數已設為 {0}。"),
        ("Cleared {0} cached sprite(s), refreshed WoundView, hands, and in-world sprites for {1}.", "已清除 {0} 份貼圖緩存，並刷新了 {1} 的傷勢視圖、手部與場景內貼圖。"),
        ("[ERROR] Usage: GG <subcommand> [args...]. Available: {0}", "[錯誤] 用法 : GG <子命令> [參數...]。可用 : {0}"),
        ("[ERROR] Unknown GG subcommand: {0}. Available: {1}", "[錯誤] 未知的 GG 子命令 : {0}。可用 : {1}"),
        ("[ERROR] Unknown species: {0}", "[錯誤] 未知物種 : {0}"),
        ("[ERROR] Invalid heal argument: {0} (expected true/false)", "[錯誤] heal 參數無效 : {0}（應為 true/false）"),
        ("[ERROR] Invalid keepStats argument: {0} (expected true/false)", "[錯誤] keepStats 參數無效 : {0}（應為 true/false）"),
        ("[ERROR] Usage: GG debugbaronhorns <0-{0}>", "[錯誤] 用法 : GG debugbaronhorns <0-{0}>"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("string subcommand", "子命令（文本）"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Gunsaw Genetics debug commands. Usage: GG <subcommand> [args...]", "Gunsaw Genetics 調試命令。用法 : GG <子命令> [參數...]"),
        ("Which Gunsaw Genetics command to run", "要運行的 Gunsaw Genetics 命令"),
        ("Remaining arguments depend on the subcommand", "其餘參數取決於具體子命令"),
    };
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Milky Bonus: {0}", "Milky 加成 : {0}"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Gunsaw Genetics", "Gunsaw基因"),
        ("Search", "搜索"),
        ("GUNSAW GENETICS UPDATE AVAILABLE", "GUNSAW 基因工程 有新版本"),
        ("CHANGELOG", "更新日誌"),
        ("[ BACK ]", "[ 返回 ]"),
        ("[ GOT IT ]", "[ 知道了 ]"),
        ("[ NEXUS PAGE ]", "[ Ｎ網頁面 ]"),
        ("[ VIEW CHANGELOG ]", "[ 查看更新日誌 ]"),
        ("[ ] Don't show this again", "[ ] 不再顯示此提示"),
        ("No notable ability.", "無顯著能力。"),
        ("No info added yet.", "尚未添加信息。"),
        ("Frail, but sharp. A steady hand.", "纖弱卻敏銳。一隻穩當的手。"),
        ("The baseline. Ordinary in every way.", "基準。各方面都平平無奇。"),
        ("Simple-minded. Built for the water.", "頭腦簡單。為水而生。"),
        ("<color=#4499ff>CLICK TO SWAP</color>", "<color=#4499ff>點擊交換</color>"),
        ("The arms are closer...", "手臂更近了..."),
        ("The legs are thicker...", "腿更粗了..."),
        ("STR", "力量"),
        ("RES", "韌性"),
        ("INT", "智力"),
        ("MOVE SPEED MULT", "移動速度倍率"),
        ("HEALTH MULT", "生命倍率"),
        ("JUMP SPEED MULT", "跳躍速度倍率"),
        ("SKIN HEAL MULT", "皮膚癒合倍率"),
        ("IMMUNITY BONUS", "免疫力加成"),
        ("MODIFIED", "已修改"),
        ("WOUNDVIEW COLOR", "傷勢視圖顏色"),
        ("TRAITS", "特質"),
        ("e.g. 1.0", "例如 1.0"),
        ("Species name...", "物種名稱..."),
        ("Flavor traits text...", "風味特質文本..."),
        ("Short description...", "簡短描述..."),
        ("Ctrl + Click", "Ctrl + 左鍵點擊"),
        ("Name can't be empty.", "名稱不能為空。"),
        ("That name is already taken.", "該名稱已被佔用。"),
        ("This can't be undone.", "此操作無法撤銷。"),
        ("Sprites folder created:", "已創建貼圖文件夾："),
        ("Nothing is generated automatically beyond the empty Body and Head folders. You'll need to add the sprites yourself.", "除空的 Body 與 Head 文件夾外不會自動生成任何內容，貼圖需要你自己添加。"),
        ("[NORMAL]", "[常規]"),
        ("- Unchanged", "- 無變化"),
        ("[WIP]", "[開發中]"),
        ("- Not properly implemented yet", "- 尚未完整實現"),
        ("NAME", "名稱"),
        ("DESCRIPTION", "描述"),
        ("[ DELETE ]", "[ 刪除 ]"),
        ("[ CLOSE ]", "[ 關閉 ]"),
        ("[HYPER-FOCUS]", "[超聚焦]"),
        ("- Slows time while aiming a loaded gun", "- 瞄準已裝填槍械時減緩時間"),
        ("[EYE ADAPT]", "[暗適應]"),
        ("- Sees clearly in darkness after adjusting", "- 適應後可在黑暗中看清"),
        ("[STEADY]", "[鎮定]"),
        ("- Self-harm shows as vomiting instead", "- 自殘表現為嘔吐"),
        ("[GENERAL]", "[通用]"),
        ("- Reads blueprints easily, better with tools than claws", "- 更易讀懂藍圖，工具使用強於爪擊"),
        ("[REGROWTH]", "[再生]"),
        ("- Hold to heal fast, mend bones, and regrow missing limbs, eyes, or jaw", "- 長按可快速治療、接骨，並再生缺失的肢體、眼睛或下頜"),
        ("[MOBILITY]", "[機動性]"),
        ("- Built to move fast and recover from it", "- 為高速移動而生，也擅長從高速移動中恢復"),
        ("[TORPOR]", "[蟄伏]"),
        ("- Self-cooling ability", "- 自我降溫能力"),
        ("[CHILL]", "[耐寒]"),
        ("- Adapted to the cold", "- 適應寒冷"),
        ("[CARING]", "[關懷]"),
        ("- Deeper mood swings, especially around others", "- 情緒波動更強烈，尤其在他人身邊時"),
        ("- No diet restriction, uneasy about cannibalism", "- 無飲食限制，但排斥同類相食"),
        ("[CLOAK]", "[隱身]"),
        ("- Toggleable invisibility while standing still", "- 站立不動時可開關的隱形"),
        ("[IDOLATRY]", "[崇物]"),
        ("- Reveres genuine gear, despises makeshift equipment", "- 尊崇正規裝備，蔑視自制器械"),
        ("[ARROGANCE]", "[傲慢]"),
        ("- Mood swings hard with pride and ego", "- 情緒隨自尊與自我劇烈波動"),
        ("[VOLATILE]", "[暴烈]"),
        ("- Self-harm and suicide escalate violently", "- 自殘與自殺行為急劇升級"),
        ("- Looks down on every other species", "- 瞧不起所有其他物種"),
        ("[PRIDEFUL]", "[充滿自豪]"),
        ("- Grows more prideful after a strong kill", "- 擊殺強敵後更加自豪"),
        ("[HORNS]", "[雙角]"),
        ("- Self-harm targets the horns", "- 自殘會攻擊雙角"),
        ("[TOUGH]", "[強健]"),
        ("- Enormous health pool, but no healing", "- 生命值極高，但無法治療"),
        ("- Strict herbivore", "- 嚴格食草"),
        ("[WEB]", "[蛛網]"),
        ("- Fires webs to bind, climb, and slow enemies", "- 發射蛛網束縛、攀爬並減速敵人"),
        ("[PSYCHOPATHY]", "[精神變態]"),
        ("- Nothing truly reaches. Not fear, nor guilt", "- 沒有任何東西能真正觸動它——恐懼與愧疚皆無"),
        ("[CANNIBAL]", "[同類相食]"),
        ("- Enough trust, and a hug turns deadly", "- 信任足夠時，擁抱會變得致命"),
        ("- Extra limbs aid mobility (cosmetic rn)", "- 額外的肢體有助於移動（目前僅為外觀）"),
        ("- Sawian flesh is just meat", "- Sawian 的血肉不過就是肉"),
        ("[SIMPLE MIND]", "[頭腦簡單]"),
        ("- Too simple to spiral... or to hope", "- 簡單到不會崩潰...也簡單到不會期望"),
        ("[WARMTH]", "[耐熱]"),
        ("- Adapted to the heat", "- 適應高溫"),
        ("- Strict carnivore, resists weight gain and sickness", "- 嚴格食肉，不易增重，抗病性強"),
        ("[DESYNC]", "[解離]"),
        ("- 3-stage active ability, escalating effects", "- 三階段主動能力，效果逐級增強"),
        ("[SCARS]", "[舊傷]"),
        ("- Old injuries", "- 陳年傷患"),
        ("- Temperature and stealth both work against them", "- 溫度與潛行都對它不利"),
        ("[███████]", "[████]"),
        ("- ██████████ chip installed ", "- 已安裝█████芯片 "),
        ("- ███████████ chip installed. ", "- 已安裝██████芯片。 "),
        ("PORTRAITS (menu picture)\nLocation: BepInEx/plugins/SpeciesPortraits/\nFilename: <yourspeciesname>.png (all lowercase)\n\nWOUNDVIEW SPRITES (limb outline/middle art)\nLocation: BepInEx/plugins/CustomBodySprites/\nFilenames: <YourSpeciesName>_Limb_0_Outline.png\n           <YourSpeciesName>_Limb_0_Middle.png\n(0 through 14, one Outline + one Middle pair per limb)\n\nIN-WORLD CHARACTER SPRITES (Body/Head)\nLocation: BepInEx/plugins/CustomSprites/st<slot>/Body/ and .../Head/\n(your slot number was shown when you created this species)\nFilenames must match the game's own internal sprite names exactly\n(e.g. experimentHead.png, experimentCrus.png, experimentEyeOpen.png, etc.)\n\nNothing here is generated for you beyond empty folders.\nAll sprites are placed manually.", "立繪（菜單圖片）\n位置：BepInEx/plugins/SpeciesPortraits/\n文件名：<你的物種名>.png（全小寫）\n\n傷勢視圖貼圖（肢體輪廓 / 中層圖）\n位置：BepInEx/plugins/CustomBodySprites/\n文件名：<你的物種名>_Limb_0_Outline.png\n           <你的物種名>_Limb_0_Middle.png\n（0 到 14，每個肢體一對 Outline + Middle）\n\n場景內角色貼圖（Body / Head）\n位置：BepInEx/plugins/CustomSprites/st<slot>/Body/ 與 .../Head/\n（創建該物種時會顯示你的槽位編號）\n文件名必須與遊戲內部貼圖名完全一致\n（例如 experimentHead.png、experimentCrus.png、experimentEyeOpen.png 等）\n\n除空文件夾外，這裡不會為你生成任何內容。\n所有貼圖都需手動放入。"),
        ("[██████]", "[███]"),
        ("- ████████ chip installed.", "- 已安裝████芯片。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Your version:  v{0}", "當前版本：  v{0}"),
        ("Latest version:  v{0}", "最新版本：  v{0}"),
        ("Delete \"{0}\"?", "刪除「{0}」？"),
    };
    public static readonly (string En, string Zh)[] Fallbacks =
    {
        ("Preferred", "偏好"),
        ("Not Preferred", "不偏好"),
        ("Preferred (Cannibal)", "偏好（同類相食）"),
        ("Preferred (Leapy)", "偏好（Leapy）"),
        ("Not Preferred (Semi)", "不偏好（半）"),
        ("Bite", "咬一口"),
        ("Take a piece for yourself.", "給自己拿一塊。"),
        ("Decays in: Never (frozen)", "腐敗時間：永不（已凍結）"),
        ("Freezing: ", "凍結："),
        ("Frozen for ", "已凍結 "),
        ("HEAL RATE", "治療速度"),
        ("HEALTH", "生命"),
        ("IMMUNITY", "免疫力"),
        ("JUMP", "跳躍"),
        ("MOVE", "移動"),
        ("No info added yet.", "尚未添加信息。"),
        ("Marred", "殘缺"),
        ("Both horns are gone. Something about this feels permanent.", "雙角都沒了。總覺得有些事就此成了定局。"),
        ("Regrowth", "再生"),
        ("Hyper-Regeneration. Highly taxing on the body.", "超速再生。對身體負擔極大。"),
        ("Hollow", "空洞"),
        ("Every reforged body and borrowed mind takes something with it. It doesn't come back.", "每一次重塑軀體、每一次借用他人的意識，都會帶走些什麼——而它再也回不來。"),
        ("Hyper-Focus", "超聚焦"),
        ("Adrenaline surging. Perception of time slowed. Weapon handling vastly improved.", "腎上腺素激增。時間感知變慢。槍械操控大幅提升。"),
        ("Sensory Overload", "感官過載"),
        ("Nervous system recovering from extreme strain. Cannot hyper-focus.", "神經系統正從極度緊繃中恢復，無法進入超聚焦。"),
        ("Recovering", "恢復中"),
        ("The body needs time until it can cool again...", "身體需要時間才能再次降溫..."),
        ("Torpor", "蟄伏"),
        ("The body is slowly cooling...", "身體正在緩慢降溫..."),
        ("Genetic profile corrupted. Fulfill requirement to unlock.", "基因檔案已損壞。滿足解鎖條件即可解鎖。"),
        ("[ BACK ]", "[ 返回 ]"),
        ("[ SAVE ]", "[ 保存 ]"),
        ("[ RESET ]", "[ 重置 ]"),
        ("[ CANCEL ]", "[ 取消 ]"),
        ("[ LOCKED ]", "[ 已鎖定 ]"),
        ("NEW", "新建"),
        ("EDIT", "編輯"),
        ("DEL", "刪除"),
        ("CUSTOM SPECIES", "自定義物種"),
        ("–CUSTOM SPECIES————————", "–自定義物種————————"),
        ("–SPECIES EDITOR————————", "–物種編輯器————————"),
        ("–BALANCE CONFIG————————", "–平衡配置————————"),
        ("–SPRITE GUIDE————————", "–貼圖指南————————"),
        ("–CHANGELOG————————", "–更新日誌————————"),
        ("No custom species yet.", "還沒有自定義物種。"),
        ("Freezing", "凍結中"),
        ("Frozen", "已凍結"),
        ("Steal", "偷竊"),
        ("Take it without paying. {0}% chance. Failure means combat.", "不付錢直接拿走。成功率 {0}%，失敗即進入戰鬥。"),
        ("[███████] - ██████████ chip installed \n[███████] - ███████████ chip installed. \n[██████] - ████████ chip installed.", "[████] - 已安裝█████芯片 \n[████] - 已安裝█████芯片。 \n[███] - 已安裝████芯片。"),
        ("Small Web", "小型蛛網"),
        ("Costs 1 web charge. Fires instantly and anchors on contact. A grab point, not a climbable line. Only 5 webs are able to exist at a time.", "消耗 1 點蛛網儲量，瞬間射出、接觸即固定。它只是抓握點，不能當作可攀爬的繩索。同時最多隻能存在 5 張蛛網。"),
        ("Long Web", "大型蛛網"),
        ("Costs 5 web charges. Considerably more than a small web. Requires holding the ability key briefly to charge before it fires. Produces a full climbable strand able to span gaps too wide to cross normally, climbable both up and down along its length. Only 5 webs are able to exist at a time.", "消耗 5 點蛛網儲量，遠多於小型蛛網。需要短按技能鍵蓄力後才能射出。能生成一條完整可攀爬的絲線，可跨越平時無法通過的寬大裂隙，並可沿其上下攀爬。同時最多隻能存在 5 張蛛網。"),
        ("Psychopathy", "精神變態"),
        ("Complete trauma immunity. Positive moods run stronger than they should, and outright killing a trader lifts mood rather than damaging it, on top of no mood loss from threatening, harming, or killing them at all. Corpses, whether found or made, cost nothing either. Sleep resets a good mood back to neutral, but only if it was already positive. Anything negative carries over untouched.", "完全免疫心理創傷。正面心情效果強於常態；直接殺死商人不減心情，反而會提升；威脅、傷害或殺死他們也不會造成任何心情損失。無論是發現還是造成的屍體，同樣不會帶來損失。睡眠會把良好的心情重置為中性，但僅限原本為正面的心情。任何負面狀態都會原樣保留。"),
        ("Cannibal", "同類相食"),
        ("At 200 reputation, trader hug actions are changed to cannibalization. Cannibalization gives you a large boost to mood, hunger, and thirst afterwards. If your own mood drops low enough on its own, that same hunger turns onto yourself. Eating Yellow Flesh costs nothing. No sickness, no mood loss. Internal Organs give reduced sickness and no longer have mood loss either.", "好感度達到 200 後，對商人的擁抱動作會變為同類相食。同類相食會在之後大幅提升你的心情、飢餓與口渴。若心情自行低落到一定程度，那份飢餓就會轉向自身。食用黃色血肉沒有任何代價——不會生病，也不會掉心情。內臟造成的疾病更輕，同樣不再有心情損失。"),
        ("Cloaking", "隱身"),
        ("Requires a charged battery and standing still to engage. Drains while active. Any movement breaks it, except while crouched. Crouching allows certain traps to be avoided entirely, but drains battery slightly faster. Radiation interferes with the cloak, and enough exposure prevents it from being used at all. Sneak cloaking also allows for stealth attacks on traders. Outcome can be improved with equipment, but could also cause damage to equipment.", "需要電量充足的電池並保持靜止才能啟動，激活期間持續耗電。任何移動都會解除隱身，蹲伏時除外。蹲伏可以完全避開某些陷阱，但耗電略快。輻射會干擾隱身，累積到一定程度後將完全無法使用。潛行隱身還允許對商人發動潛行攻擊。裝備可以改善結果，但也可能造成裝備損壞。"),
        ("Idolatry", "崇物"),
        ("Genuine human-made gear noticeably improves mood when equipped. Crude, makeshift, or scavenged gear does the opposite, and some items are refused outright. Others may have reduced effectiveness, refusal to fire, or an inability to use certain medical items, unless mood or pain has broken down resistance enough to allow it.", "裝備真正由人類製造的裝備會明顯提升心情。粗製、自制或拾荒得來的裝備則相反，有些物品會被直接拒絕；另一些則可能效果下降、拒絕開火，或無法使用某些醫療物品——除非心情或疼痛已把這種牴觸削弱到足以接受的程度。"),
        ("Arrogance", "傲慢"),
        ("Mood swings define this. At +30 and above, setbacks land softer. Corpses and killed traders cost far less mood than they would otherwise, and favored gear (certain tools and firearms) hits harder. At -30 and below, the opposite takes hold: those same losses cut twice as deep, and stealth attacks can no longer be used, though desperation loosens the usual refusal of ripped dressings and old rags. At -40 and below, pride collapses further still. Stealing from traders is no longer possible, but for the first time, a hug is accepted from them. Beyond mood swings, negative mood itself resists differently depending on how deep it is: from -30 to -50, 10% of further loss is shrugged off, 30% from -50 to -70, and 40% from -70 to -85, but past -85, whatever's left gives way entirely, and every further blow lands 20% harder.", "情緒波動是它的核心。心情在 +30 以上時，挫折的打擊更輕：屍體與被殺的商人造成的心情損失遠低於常態，偏愛的裝備（某些工具與槍械）傷害更高。心情在 -30 以下時則相反：同樣的損失會加倍刺痛，且無法再使用潛行攻擊，不過絕望會讓它不再拒絕破舊繃帶與舊布條。心情在 -40 以下時，自尊進一步崩塌：無法再從商人那裡偷竊，但也會第一次接受他們的擁抱。除情緒波動外，負面心情本身也會按深度產生不同的抵抗：-30 到 -50 時後續損失的 10% 被無視，-50 到 -70 為 30%，-70 到 -85 為 40%；但超過 -85 後剩餘部分會徹底失守，之後每一次打擊都加重 20%。"),
        ("Levitation", "懸浮"),
        ("Grabs any loose or movable object at range through a visible tether, redirecting force between it and its wielder based on relative mass. Heavy objects barely move but reflect force back; light objects move freely and resist little in return. Living targets are far harder to influence. Capable of flinging light objects with precision, or using something too heavy to lift as a launch point. Momentum from movement, jumps, and chained grabs all stack together.", "通過一條可見的牽引線隔空抓取任何鬆散或可移動的物體，並依據相對質量在物體與持有者之間轉移力。重物幾乎不動，卻會把力反彈回來；輕物可自由移動，反作用力也很小。對活體目標的影響要困難得多。它能精準拋擲輕物，也能把重到無法舉起的東西當作借力點。移動、跳躍與連續抓取產生的動量可以疊加。"),
        ("Reformation", "重塑"),
        ("On the verge of true death, time slows and a brief window opens to choose survival. Reforming rebuilds the body from what's left. Bleeding, breaks, and infection cleared. Blood and vitals restored. All at the cost of shared charge, and always a little something more.", "在瀕臨真正死亡之際，時間會變慢，並短暫開啟一個選擇生存的窗口。重塑會以殘留部分重建身體：止血、接骨、清除感染，恢復血液與生命體徵。代價是共用儲量，而且總要再多付出一點什麼。"),
        ("Mindswap", "意識交換"),
        ("During Reformation's window, an eligible Sawian can be selected instead of reforming. Their body becomes the new host. Stats reset to that species' baseline with a small (random) bonus. Vitals are mostly restored, while INT, hyper-regeneration, and every other chip persist regardless of the body worn. The one left behind does not survive the exchange.", "在重塑的窗口期內，可以改為選擇一名符合條件的 Sawian，其身體將成為新的宿主。屬性重置為該物種的基準值，並獲得少量（隨機）加成。生命體徵大體恢復；而智力、超速再生與其他所有芯片，無論換到哪具身體都依然保留。被留下的那一方無法在交換中存活。"),
        ("Hollow", "空洞"),
        ("Rises with every Reformation or Mindswap. Mindswap far more, since it means directly hearing another mind. As it climbs: color fades from sight, mood is held closer to neutral, trauma stops taking hold at all, speech grows halting and prone to cutting short, and trader reputation suffers further. None of it reverses. 'Reborn, Rebuilt, Reformed... but never the same again.'", "每次重塑或意識交換都會加深，其中意識交換尤甚——因為它意味著直接聽見另一個意識。隨著它累積：視野中的色彩逐漸褪去，心情被拉向中性，心理創傷不再留下影響，言語變得斷續、容易戛然而止，商人的好感度也會進一步受損。這一切都不可逆。「重生、重建、重塑...卻再也不是原來的自己。」"),
        ("Carnivore", "食肉"),
        ("Only meat-based food can be eaten without issue. Anything else reduces mood, increases sickness, and restores less hunger than it should. Mindwipe removes this restriction entirely.", "只有肉類食物可以正常食用。其他任何食物都會降低心情、增加疾病，並恢復更少的飢餓。精神抹除劑可完全解除這一限制。"),
        ("Feeding", "進食"),
        ("With enough trust, a trader can be bitten for hunger instead of trade. One-time offer per trader, and never available until trust is high enough. Another Dune, however, will allow it freely and always, with no trust required and no limit on how often. If hunger falls too far with nothing else to eat, that same instinct turns inward instead.", "信任足夠時，可以啃咬商人來充飢，而不必交易。每位商人僅限一次，且信任不足時絕不會開放。不過另一位 Dune 會無條件、不限次數地允許你這麼做。如果飢餓過度而再無他物可食，這份本能就會轉向自身。"),
        ("Torpor", "蟄伏"),
        ("Actively lowers body temperature while held, deepening the longer it's held, down to a hard limit near freezing. Holding through the heat helps too, though cooling grows harder the higher the temperature climbs. Costs thirst and energy while active, with thirst increasing the longer it's held. Releasing starts a cooldown based on how long it was held. The cooldown increases faster than the hold itself the longer it goes on.", "長按可主動降低體溫，按住越久降得越深，直至接近冰點的下限。在高溫中按住也有幫助，不過溫度越高越難降溫。激活期間消耗口渴與體力，按住越久口渴越快。鬆開後會產生一段與按住時長相關的冷卻，且拖得越久，冷卻增長得比按住本身更快。"),
        ("Frozen", "凍結"),
        ("Certain food and drink turn solid while held cold enough during {Torpor}. Decay pauses entirely, and neither can be eaten or drunk until they thaw. Frozen items can be used on the body, offering a brief burst of real healing and a little relief, at the cost of some of the item's condition and however long it has left frozen.", "在蟄伏期間保持足夠低溫時，某些食物與飲品會凝固。腐敗會完全暫停，且在解凍之前既不能吃也不能喝。凍結的物品可以用在身體上，帶來一次短暫的真實治療與些許緩解，代價是物品的部分耐久，以及它保持凍結的那段時間。"),
        ("Herbivore", "食草"),
        ("Only plant-based food can be eaten without issue. Anything else reduces mood, increases sickness, and restores less hunger than it should. Mindwipe removes this restriction entirely.", "只有植物類食物可以正常食用。其他任何食物都會降低心情、增加疾病，並恢復更少的飢餓。精神抹除劑可完全解除這一限制。"),
        ("Semi-Herbivore", "半食草"),
        ("Only plant-based food can be eaten without issue, but violations come with a lighter penalty than strict herbivores. Mindwipe removes this restriction entirely.", "只有植物類食物可以正常食用，但違規的懲罰比嚴格食草者更輕。精神抹除劑可完全解除這一限制。"),
        ("Semi-Carnivore", "半食肉"),
        ("Only meat-based food can be eaten without issue, but violations come with a lighter penalty than strict carnivores. Mindwipe removes this restriction entirely.", "只有肉類食物可以正常食用，但違規的懲罰比嚴格食肉者更輕。精神抹除劑可完全解除這一限制。"),
        ("Regrowth", "再生"),
        ("Actively accelerates healing while held: bleeding eases, skin and muscle recover quickly, fractures mend, and missing limbs, eyes, or disfigurement regrow in stages. Progress on regrowth stays in stages, though it's lost entirely if the parent limb is destroyed. Cannot be used while too hungry. Costs hunger and thirst while active, and grows harder to sustain the more is being regrown. Immunity and temperature drift, pain and heart rate climb, and the heart itself becomes considerably more vulnerable the longer it's pushed.", "長按可主動加速癒合：出血減輕，皮膚與肌肉快速恢復，骨折癒合，缺失的肢體、眼睛或面部缺損會分階段再生。再生進度以階段推進，但若母肢體被摧毀便會完全丟失。過於飢餓時無法使用。激活期間消耗飢餓與口渴，需要再生的部位越多越難維持。免疫力與體溫會波動，疼痛與心率上升，而心臟被逼得越久就越脆弱。"),
        ("{Carnivore}\n#VoyagerSupremancy", "{Carnivore}\n#VoyagerSupremacy"),
        ("Clumsy", "笨拙"),
        ("Sensitive", "敏感"),
        ("Eye Adaptation", "暗適應"),
        ("Desync", "解離"),
        ("Old Wounds", "舊傷"),
        ("Horns", "雙角"),
        ("Tough", "強健"),
        ("Mobility", "機動性"),
        ("Chill", "耐寒"),
        ("Caring", "關懷"),
        ("Cloak", "隱身"),
        ("Web", "蛛網"),
        ("Volatile", "暴烈"),
        ("Prideful", "充滿自豪"),
        ("Simple Mind", "頭腦簡單"),
        ("Steady", "鎮定"),
        ("Unfinished", "未完成"),
        ("General", "通用"),
        ("Warmth", "耐熱"),
        ("Levitation Chip", "懸浮芯片"),
        ("Reformation Chip", "重塑芯片"),
        ("Mindswap Chip", "意識交換芯片"),
        ("A last resort against death, at a cost.\n{Reformation} rebuilds what's broken, but never quite all the way.", "絕境中對抗死亡的最後手段，但代價不菲。\n{Reformation} 能重建破損之處，卻永遠無法完全復原。"),
        ("A side effect, not a chip of its own. Deepens with every use of the others.\n{Hollow} takes the color first. Then the edges. Then, quieter still, the words.", "它不是獨立的芯片，而是一種副作用，隨其他芯片的每次使用而加深。\n{Hollow} 先帶走色彩，然後是輪廓，最後在更深處，帶走言語。"),
        ("Active Ability. Hold to actively cool the body.\n{Torpor} helps with controlling the body's temperature, even helping against certain threats.\nCold enough, and objects begin to turn {Frozen} too.", "主動能力。長按可主動為身體降溫。\n{Torpor} 有助於控制體溫，甚至能抵禦某些威脅。\n溫度足夠低時，物品也會開始轉為 {Frozen}。"),
        ("Active Ability. Hold to heal, mend, and regrow. {Regrowth} comes with increasing costs the longer it's pushed.", "主動能力。長按可治療、接骨與再生。{Regrowth} 維持越久，代價越高。"),
        ("Active Ability. Slows time while you're aiming a loaded gun. Four shots max.", "主動能力。瞄準已裝填槍械時減緩時間。最多四發。"),
        ("Active Equipment. Toggle {cloaking} while standing still with charge remaining.\nCrouching while active allows slow movement without breaking it.", "主動裝備。在靜止且尚有電量時切換 {cloaking}。\n激活期間蹲伏可緩慢移動而不解除隱身。"),
        ("Active ability. 3 Stages. {Desync} effects scale with each use.", "主動能力。共三階段。{Desync} 的效果隨每次使用而增強。"),
        ("An enormous pool of health, paired with wounds that refuse to close on their own.\nBandages are harder to wrap around such a large body\nDoses meant for something smaller barely make a dent.", "生命值極厚，但傷口無法自行癒合。\n如此龐大的身軀更難纏上繃帶。\n按較小體型配製的劑量幾乎不起作用。"),
        ("Bones and dislocations mend twice as fast, and recent injuries hurt a little less the second time.", "骨骼與脫臼的癒合速度快一倍，舊傷復發時的疼痛也會略輕一些。"),
        ("Built for speed, and built to recover from pushing it too far.\nLosing the ability to move quickly will have negative effects, though.", "為速度而生，也擅長從過度衝刺中恢復。\n不過一旦失去快速移動的能力，後果會很糟糕。"),
        ("Cold is met with comfort, tolerated well past where others Sawians would start to suffer.", "寒冷對它而言反而舒適，耐受程度遠超其他 Sawian 開始受苦的界限。"),
        ("Enough trust in a trader, and a hug turns into something else entirely.\nThe same hunger turns inward too. {Cannibal} habits don't stop at other people.", "與商人建立起足夠信任後，擁抱會徹底變成另一回事。\n那份飢餓也會轉向自身。{Cannibal} 的習慣並不只針對他人。"),
        ("Forces another mind out. Takes the body that remains.\n{Mindswap} lets the user hear everything they were thinking. It doesn't quite stop afterwards.", "將另一個意識強行驅逐，佔據留下的軀體。\n{Mindswap} 會讓使用者聽見對方所有的想法，而此後它並不會真正停下。"),
        ("Heat and cold both catch up faster than they used to. The body doesn't push back like it should.\nSomething out there always seems to notice first. Staying unseen was never easy.\nAgain. Again. Again.", "冷熱對它的影響都比從前來得更快，身體也不再像該有的那樣抵抗。\n外面的什麼東西似乎總能先一步察覺它——不被看見，從來都不容易。\n又一次。又一次。又一次。"),
        ("Heat is welcomed rather than feared, tolerated well past where others would start to suffer.", "它不懼高溫反而歡迎它，耐受程度遠超他人開始受苦的界限。"),
        ("Looks down upon all other species.\n{Arrogance} swings with ego. Pride sharpens, ruin breaks.", "瞧不起所有其他物種。\n{Arrogance} 隨自尊起伏：驕傲使其銳利，破敗使其崩塌。"),
        ("Meat is all the same, Sawian or otherwise.\n{Feeding} doesn't always mean hunting.", "肉就是肉，Sawian 與否並無分別。\n{Feeding} 並不總是意味著狩獵。"),
        ("Minigames respond slower to strength. Arms hit harder than most, tools hit softer.", "小遊戲中力量的收益更慢。徒手攻擊比多數人更重，工具攻擊則更輕。"),
        ("Mood runs deeper in every direction, especially when others are hurt.\nHugs are easier and mean more.", "情緒的起伏在各方面都更深，尤其當他人受傷時。\n擁抱更容易達成，也更有意義。"),
        ("Mood swings harder in every direction, and colors first impressions with traders far more than usual.", "情緒在各方面波動更劇烈，也遠比常人更能左右商人初見時的觀感。"),
        ("No dietary restrictions, but eating another Sawian doesn't sit right.", "沒有飲食限制，但吃下另一名 Sawian 讓它很不自在。"),
        ("Press for a {small web}, hold for a {long web}.\nWeb supply scales with intelligence. Rebuilds slowly, or fully with sleep.", "輕按發射 {small web}，長按發射 {long web}。\n蛛網儲量隨智力提升，恢復緩慢，睡覺可完全恢復。"),
        ("Remote kinetic redirection. Force applied is mass-dependent, in both directions.\n{Levitation} was never rated for a body this light.", "隔空轉移動能，所施加的力與質量相關，且雙向作用。\n{Levitation} 從未針對如此輕的身體做過適配。"),
        ("Reveres genuine human-made gear above all else. Makeshift or scavenged equipment earns nothing but contempt.\n{Idolatry} colors mood around whatever's currently equipped.", "對真正出自人類之手的裝備推崇備至，而自制或拾荒得來的器械只會招致蔑視。\n{Idolatry} 會讓心情隨當前裝備的好壞而起伏。"),
        ("Self-harm presents as vomiting instead of the usual.\nSuicide attempts cause heavy vomiting, fibrillation, and a rapidly climbing heart rate.", "自殘表現為嘔吐，而非通常的方式。\n自殺嘗試會導致劇烈嘔吐、心室顫動，以及迅速攀升的心率。"),
        ("Self-harm targets the hands. Suicide escalates rapidly, and violently, across the whole body.\nNeither is quick. Neither is quiet.", "自殘會針對雙手。自殺則會迅速而猛烈地蔓延至全身。\n兩者都不快，兩者都不安靜。"),
        ("Self-harm targets the horns. Each one lost costs something lasting.\nThere are only two to give.", "自殘會針對雙角。每失去一隻，都會留下永久的代價。\n而它只有兩只可以交出。"),
        ("Semi-Active ability. Gain {Prideful} after killing an enemy. Scales with enemy killed.\nKept active, and death itself can be shrugged off once.", "半主動能力。擊殺敵人後獲得 {Prideful}，強度隨敵人強弱變化。\n保持激活時，就連死亡也能被硬扛過一次。"),
        ("Staying in darkness for a while lets you see in it clearly. Returning to light should be done carefully.", "在黑暗中待上一陣便能看清四周，但回到光亮處時須格外小心。"),
        ("That scar wasn't quiet. Something put it there, and it's remembered exactly how.\nThe legs are just another part. It'll heal again. It always does.", "那道疤來得並不平靜——有什麼東西留下了它，而它記得清清楚楚。\n腿不過是又一個部件，它還會再長好，向來如此。"),
        ("This species hasn't been properly made yet. Wait for it's update in the future!", "該物種尚未製作完成，請等待它日後的更新！"),
        ("Too simple to spiral, too simple to hope.\nNo Last Stand waiting at the end.", "簡單到不會崩潰，也簡單到不會期望。\n盡頭沒有「背水一戰」。"),
        ("Very little truly reaches. Not grief, guilt, or fear. {Psychopathy} runs deep.", "幾乎沒有什麼能真正觸動它——悲傷、愧疚或恐懼皆然。{Psychopathy} 根深蒂固。"),
        ("{Carnivore}\nExtra limbs help with mobility (Cosmetic currently)", "{Carnivore}\n額外的肢體有助於移動（目前僅為外觀）。"),
        ("{Carnivore}\nLess of what's eaten turns to weight, and overindulgence costs less than it should.\nSickness can only climb so far.", "{Carnivore}\n吃下的東西更少轉化為體重，暴食的代價也低於應有水平。\n疾病最多隻能累積到一定程度。"),
        ("{Herbivore}\nThreats land far easier coming from him. He never feels good about making them.", "{Herbivore}\n由他說出的威脅格外容易奏效，而他從不為此感到愉快。"),
        ("{Semi-Herbivore}\nFoliage, in every form, is able to be digested far easier.\nFood is needed more often than other Sawians.", "{Semi-Herbivore}\n任何形式的植物都更容易被消化。\n比其他的 Sawian 更頻繁地需要進食。"),
        ("{Semi-Herbivore}\nYou can understand blueprints more clearly.\nWorse Claw scaling. Better Tool scaling.", "{Semi-Herbivore}\n更容易讀懂藍圖。\n爪擊成長更差，工具成長更好。"),
    };
    public static readonly (string En, string Zh)[] HueNames =
    {
        ("Green (Default)", "綠色（默認）"),
        ("Red", "紅色"),
        ("Yellow", "黃色"),
        ("Teal", "青色"),
        ("Cyan", "青色（亮）"),
        ("Blue", "藍色"),
        ("Purple", "紫色"),
        ("Pink", "粉色"),
    };
    public static readonly (string En, string Zh)[] PickerStats =
    {
        ("STR", "力量"),
        ("RES", "韌性"),
        ("INT", "智力"),
        ("MOBILITY", "機動性"),
        ("LEAP POWER", "跳躍力"),
        ("TOUGHNESS", "堅韌"),
        ("REGEN RATE", "恢復速率"),
        ("IMMUNITY", "免疫力"),
    };
    public static readonly (string En, string Zh)[] LimbNames =
    {
        ("Torso Tendril L (Inner)", "軀幹觸鬚 左（內側）"),
        ("Torso Tendril L (Outer)", "軀幹觸鬚 左（外側）"),
        ("Torso Tendril R (Inner)", "軀幹觸鬚 右（內側）"),
        ("Torso Tendril R (Outer)", "軀幹觸鬚 右（外側）"),
        ("Abdomen Tendril L (Inner)", "腹部觸鬚 左（內側）"),
        ("Abdomen Tendril L (Outer)", "腹部觸鬚 左（外側）"),
        ("Abdomen Tendril R (Inner)", "腹部觸鬚 右（內側）"),
        ("Abdomen Tendril R (Outer)", "腹部觸鬚 右（外側）"),
    };
    public static readonly (string En, string Zh)[] Changelog =
    {
        ("<b>Gunsaw Genetics v1.9.0 changelog:</b>", "<b>Gunsaw Genetics v1.9.0 更新日誌：</b>"),
        ("<b>Baron Overhaul:</b>", "<b>Baron 重做：</b>"),
        ("<b>Prideful Changes:</b>", "<b>自豪改動：</b>"),
        ("- Prideful duration scaling changed:", "- 自豪持續時間成長規則改動："),
        ("- - Duration now scales with the strength of the enemy killed (25-120s), instead of being fixed", "- - 持續時間現在隨擊殺敵人的強度變化（25-120s），而不再是固定值"),
        ("- - Kills below 50 max health no longer grant Prideful at all (Cave ticks, etc.)", "- - 擊殺最大生命值低於 50 的敵人不再觸發自豪（洞穴蜱蟲等）"),
        ("- - Killing the Elder Thornback grants a flat 13-minute duration, regardless of the normal scaling", "- - 擊殺棘背獸長老固定獲得 13 分鐘持續時間，不受常規成長規則影響"),
        ("- Trader Prideful reputation scaling changed:", "- 商人自豪好感度成長規則改動："),
        ("- - Reputation bonus while Prideful now scales with the strength of the kill that triggered it (+12 to +55), instead of a flat bonus", "- - 自豪期間的好感度加成現在隨觸發它的擊殺強度變化（+12 至 +55），而不再是固定加成"),
        ("- - Killing the Elder Thornback grants a flat +95 reputation bonus, regardless of the normal scaling", "- - 擊殺棘背獸長老固定獲得 +95 好感度加成，不受常規成長規則影響"),
        ("- Baron's Last Stand no longer triggers the same way as other species:", "- Baron 的背水一戰不再與其他物種以相同方式觸發："),
        ("- - Last Stand is now tied to Prideful. While Prideful, Baron has a 95% chance to trigger Last Stand", "- - 背水一戰現在與自豪綁定。處於自豪狀態時，Baron 有 95% 幾率觸發背水一戰"),
        ("- - Still limited to once per run (unless Infinite Last Stand is enabled)", "- - 仍限制為每局一次（除非啟用了無限背水一戰）"),
        ("- - Triggering Last Stand this way clears Prideful", "- - 以此方式觸發背水一戰會清空自豪"),
        ("- Mood buff removed entirely", "- 完全移除心情加成"),
        ("- Prideful now tracks the strength of the enemy killed", "- 自豪現在會記錄擊殺敵人的強度"),
        ("- Traders now react to a Prideful Baron", "- 商人現在會對處於自豪狀態的 Baron 做出反應"),
        ("- New trader interaction added for returning to a known trader while Prideful.", "- 新增商人互動：在自豪狀態下回到已認識的商人處。"),
        ("<b>Self-Harm Overhaul:</b>", "<b>自殘重做：</b>"),
        ("- Baron's self-harm event is now a unique minigame instead of the standard vanilla one", "- Baron 的自殘事件現在改為專屬小遊戲，不再是原版標準玩法"),
        ("- - Grab one of Baron's horns and tug to break it free. Letting go and re-grabbing is safe, but resistance builds the longer you hold on", "- - 抓住 Baron 的一隻角用力拉扯將其掰斷。鬆手再抓是安全的，但握得越久阻力越大"),
        ("- - Once broken, the horn cannot regrow", "- - 角一旦掰斷便無法再生"),
        ("- - Breaking a horn causes heavy head bleeding, pain, and skin damage, and updates Baron's head sprite to reflect the damage", "- - 掰斷角會造成嚴重的頭部出血、疼痛和皮膚損傷，並更新 Baron 的頭部貼圖以體現損傷"),
        ("- - A second horn can be broken the same way. After that, self-harm reverts to vanilla's version", "- - 第二隻角也可以用同樣方式掰斷。此後自殘恢復為原版玩法"),
        ("- One horn broken:", "- 掰斷一隻角："),
        ("- - Prideful's duration and trader reputation bonus are both halved", "- - 自豪的持續時間和商人好感度加成均減半"),
        ("- - Baseline trader reputation bonus reduced (+10 -> +5)", "- - 基礎商人好感度加成降低（+10 -> +5）"),
        ("- - Threaten's success odds bonus is halved", "- - 威脅的成功率加成減半"),
        ("- Both horns broken:", "- 掰斷兩隻角："),
        ("- - Prideful is disabled entirely, meaning Last Stand can no longer be triggered through it", "- - 自豪被完全禁用，意味著無法再通過它觸發背水一戰"),
        ("- - Baseline trader reputation bonus removed, replaced with a flat -10", "- - 移除基礎商人好感度加成，改為固定 -10"),
        ("- - Threaten's success odds bonus is removed, reverting to vanilla odds", "- - 移除威脅的成功率加成，恢復為原版成功率"),
        ("- - Reputation and mood gained from hugging traders is permanently halved", "- - 擁抱商人獲得的好感度和心情永久減半"),
        ("- - Marred moodle is added (unimportant, hover to see)", "- - 新增殘缺狀態圖標（無關緊要，懸浮查看）"),
        ("<b>Healing Changes:</b>", "<b>治療改動：</b>"),
        ("- Wound-care item effectiveness reduced by 50% per use (bandages, dressings, sutures, bruise kits, bone welding tool, splints, etc.)", "- 傷口護理物品每次使用效果降低 50%（繃帶、敷料、縫合線、瘀傷包、骨焊接工具、夾板等）"),
        ("- - This does not affect how quickly items wear out, just how much they actually heal", "- - 這不會影響物品的損耗速度，隻影響其實際治療量"),
        ("- Drug potency and duration reduced by 50%", "- 藥物效力和持續時間降低 50%"),
        ("- - Blood bags, IV bags, and other blood-replenishing items unaffected. Volume is still 1:1 on the body, even with Baron's naturally higher blood volume.", "- - 血袋、輸液袋及其他補血物品不受影響。即使 Baron 天生血量更高，注入體內的量仍為 1:1。"),
        ("<b>Blood Changes:</b>", "<b>血液改動：</b>"),
        ("- Blood volume increased by 50% (5.00L -> 7.50L)", "- 血量提高 50%（5.00L -> 7.50L）"),
        ("- Blood loss thresholds (dying/critically dying) increased by 25%", "- 失血閾值（瀕死/危重瀕死）提高 25%"),
        ("- Losing a large amount of blood is more forgiving than it is for other species, but not by a full 1:1 margin. Baron can still bleed out, it just takes more.", "- 大量失血比其他物種更寬容，但並非完全 1:1 的比例。Baron 仍然會失血而死，只是需要失掉更多血。"),
        ("<b>General:</b>", "<b>通用：</b>"),
        ("- Threaten now has significantly better odds while playing as Baron, at the cost of a much harsher mood and trauma penalty on use", "- 扮演 Baron 時威脅的成功率顯著提高，代價是使用時承受更嚴厲的心情和創傷懲罰"),
        ("- Trauma gained from ongoing pain reduced by 35% (Does not apply to trauma from other sources, such as eye loss, disfigurement, or trader-related incidents)", "- 持續疼痛獲得的創傷降低 35%（不適用於其他來源的創傷，如失去眼睛、面部缺損或與商人相關的事件）"),
        ("- Energy regeneration while sleeping reduced by 35%", "- 睡眠時的體力恢復降低 35%"),
        ("- Baron now destroys a wider area of terrain when landing hard enough, scaling with impact force", "- Baron 重摔落地時現在會破壞更大範圍的地形，範圍隨衝擊力變化"),
        ("- Hunger and thirst caps increased by 50", "- 飢餓和口渴上限提高 50"),
        ("- Baron reputation buff baseline changed to +10 (Was +15)", "- Baron 好感度加成基礎值改為 +10（原為 +15）"),
        ("- Toughness changed from 4.0x to 2.25x", "- 堅韌從 4.0x 改為 2.25x"),
        ("<b>Voyager Changes:</b>", "<b>Voyager 改動：</b>"),
        ("- Cloaking now has sounds for cloaking, uncloaking, and forced decloaking.", "- 隱身在進入隱身、解除隱身和強制解除隱身時現在都有音效。"),
        ("- - All of these are made by Dirasial!", "- - 以上音效均由 Dirasial 製作！"),
        ("<b>Leapy Changes:</b>", "<b>Leapy 改動：</b>"),
        ("- Cannot be older than 20 anymore.", "- 年齡不能再超過 20 歲。"),
        ("<b>Custom Last Stands:</b>", "<b>自定義背水一戰：</b>"),
        ("<i>By ThePristineAnt!:</i>", "<i>由 ThePristineAnt 製作！：</i>"),
        ("- Baron Last Stand audio added", "- 新增 Baron 背水一戰音效"),
        ("- Baron Last Stand screen(s) added", "- 新增 Baron 背水一戰畫面"),
        ("- Milky Last Stand screen(s) added", "- 新增 Milky 背水一戰畫面"),
        ("- Orange Last Stand screen(s) added", "- 新增 Orange 背水一戰畫面"),
        ("- Roza Last Stand screen(s) added", "- 新增 Roza 背水一戰畫面"),
        ("- Voyager Last Stand screen(s) added", "- 新增 Voyager 背水一戰畫面"),
        ("- Velvet Last Stand screen(s) added", "- 新增 Velvet 背水一戰畫面"),
        ("<i>By Dirasial!:</i>", "<i>由 Dirasial 製作！：</i>"),
        ("- Albino Last Stand screen(s) added", "- 新增 Albino 背水一戰畫面"),
        ("- Albino Last Stand audio added", "- 新增 Albino 背水一戰音效"),
        ("- Roza Last Stand audio added", "- 新增 Roza 背水一戰音效"),
        ("<b>Custom Hand (Minigame) Sprites:</b>", "<b>自定義手部（小遊戲）貼圖：</b>"),
        ("<i>New system to alter the hand / arm visuals during minigames.</i>", "<i>新增系統，用於在小遊戲期間改變手部/手臂外觀。</i>"),
        ("- (Partial) Voyager hand sprites added", "- 新增（部分）Voyager 手部貼圖"),
        ("<b>Custom Dialogue:</b>", "<b>自定義對話：</b>"),
        ("- Roza dialogue added (By BountyXSnipe!!!!)", "- 新增 Roza 對話（由 BountyXSnipe 製作！！！！）"),
        ("- Baron dialogue added (By ThePristineAnt!!!!!)", "- 新增 Baron 對話（由 ThePristineAnt 製作！！！！！）"),
        ("<b>Custom Corpses:</b>", "<b>自定義屍體：</b>"),
        ("<i>Sawian corpses now have more variants, specifically those including other species not in the vanilla pool</i>", "<i>Sawian 屍體現在有更多變體，特別是包含原版池中沒有的其他物種的變體</i>"),
        ("<i>By Strag!:</i>", "<i>由 Strag 製作！：</i>"),
        ("- Leapy Corpse 1 added", "- 新增 Leapy 屍體 1"),
        ("- Leapy Corpse 2 added", "- 新增 Leapy 屍體 2"),
        ("- Leapy Corpse 3 added", "- 新增 Leapy 屍體 3"),
        ("- Chompy Corpse 1 added", "- 新增 Chompy 屍體 1"),
        ("- Chompy Corpse 2 added", "- 新增 Chompy 屍體 2"),
        ("<b>Custom Moodles:</b>", "<b>自定義狀態圖標：</b>"),
        ("- Albino Desync aftermath moodles redrawn by ThePristineAnt!!!!", "- Albino 解離後遺症的狀態圖標由 ThePristineAnt 重新繪製！！！！"),
        ("<b>Universal Weight:</b>", "<b>通用體重：</b>"),
        ("<i>Species now have different weight that (should) match them. This is purely cosmetic and has zero gameplay effect unless otherwise stated.</i>", "<i>各物種現在有不同的體重，（應該）與其相符。除非另有說明，這純粹是外觀性質，對玩法零影響。</i>"),
        ("- Orange weight is now +15kg higher", "- Orange 體重提高 +15kg"),
        ("- Milky weight is now -10kg lower", "- Milky 體重降低 -10kg"),
        ("- Leapy weight is now -5kg lower", "- Leapy 體重降低 -5kg"),
        ("- Chompy weight is now +10kg higher", "- Chompy 體重提高 +10kg"),
        ("- Roza weight is now +5kg higher", "- Roza 體重提高 +5kg"),
        ("- Voyager weight is now -5kg lower", "- Voyager 體重降低 -5kg"),
        ("- Baron weight is now +30kg higher", "- Baron 體重提高 +30kg"),
        ("- Chik weight is now -15kg lower", "- Chik 體重降低 15kg"),
        ("- Crystal weight is now +10kg higher", "- Crystal 體重提高 10kg"),
        ("- Velvet weight is now +5kg higher", "- Velvet 體重提高 5kg"),
        ("- Shelly weight is now +10kg higher", "- Shelly 體重提高 10kg"),
        ("- Dune weight is now +5kg higher", "- Dune 體重提高 5kg"),
        ("- Albino weight is now -5kg lower", "- Albino 體重降低 5kg"),
        ("<b>Universal Hunger / Thirst Caps:</b>", "<b>通用飢餓／口渴上限：</b>"),
        ("<i>Species now have different hunger and thirst caps that (should) match them. Unlike weight, this has a real gameplay effect. Species with higher caps can eat/drink further past \"full\" before facing the usual downsides, while species with lower caps hit those downsides sooner.</i>", "<i>現在各物種有不同的飢餓和口渴上限，（應該）與其自身相匹配。與體重不同，這會產生實際的玩法影響。上限更高的物種在超過“飽”之後還能繼續吃喝更久才會遭遇通常的負面效果，而上限更低的物種會更早遭遇這些負面效果。</i>"),
        ("- Orange caps are now 30 higher", "- Orange 上限提高 30"),
        ("- Milky caps are now 10 lower", "- Milky 上限降低 10"),
        ("- Leapy caps are now 5 lower", "- Leapy 上限降低 5"),
        ("- Chompy caps are now 15 higher", "- Chompy 上限提高 15"),
        ("- Voyager caps are now 5 lower", "- Voyager 上限降低 5"),
        ("- Baron caps are now 50 higher", "- Baron 上限提高 50"),
        ("- Chik caps are now 15 lower", "- Chik 上限降低 15"),
        ("- Velvet caps are now 5 higher", "- Velvet 上限提高 5"),
        ("- Dune caps are now 20 higher", "- Dune 上限提高 20"),
        ("- Albino caps are now 20 lower", "- Albino 上限降低 20"),
        ("<b>E-PDA:</b>", "<b>E-PDA：</b>"),
        ("- Albino E-PDA 2 added", "- 新增 Albino E-PDA 2"),
        ("- Albino E-PDA 3 added (This one is a <i>very</i> long read, so keep that in mind)", "- 新增 Albino E-PDA 3（這一篇<i>非常</i>長，請留意）"),
        ("<i>Written by ThePristineAnt!!:</i>", "<i>由 ThePristineAnt 撰寫！！：</i>"),
        ("- Chompy E-PDA 1 added", "- 新增 Chompy E-PDA 1"),
        ("- Icke E-PDA 1 added", "- 新增 Icke E-PDA 1"),
        ("<b>Notes:</b>", "<b>筆記：</b>"),
        ("- Albino Note 1 removed", "- 移除 Albino 筆記 1"),
        ("- - Albino E-PDA 1 is a superior version of this subject and this older note is now redundant.", "- - Albino E-PDA 1 是該對象的更優版本，這篇較舊的筆記現已多餘。"),
        ("- Chompy Note 1 added", "- 新增 Chompy 筆記 1"),
        ("- Chompy Note 2 added", "- 新增 Chompy 筆記 2"),
        ("- Icke Note 1 added", "- 新增 Icke 筆記 1"),
        ("- Icke Note 2 added", "- 新增 Icke 筆記 2"),
        ("<b>Woundview:</b>", "<b>傷勢視圖：</b>"),
        ("- Additional Baron Woundview head sprites added", "- 新增額外的 Baron 傷勢視圖頭部貼圖"),
        ("- Milky Woundview Sprites added (By ThePristineAnt!!)", "- 新增 Milky 傷勢視圖貼圖（由 ThePristineAnt 製作！！）"),
        ("- - Yes, Milky already had sprites. This is just the complete version of that.", "- - 是的，Milky 原本就有貼圖。這只是它的完整版本。"),
        ("<b>Quality of Life:</b>", "<b>體驗優化：</b>"),
        ("- Added a search bar to the settings menu, filtering the current tab's options as you type", "- 設置菜單新增搜索欄，輸入時即時篩選當前標籤頁的選項"),
        ("- Added two new keybinds to step up/down through sprite slots (defaults: [ and ])", "- 新增兩個用於在貼圖槽位間上／下切換的按鍵綁定（默認：[ 和 ]）"),
        ("- Added an \"Enable Diet Tooltips\" setting (off by default) that shows a colored tag in the extended item description indicating whether a food is preferred for your current species", "- 新增“啟用飲食提示”設置（默認關閉），會在擴展物品描述中顯示一個帶顏色的標籤，標明該食物是否為你當前物種所偏好"),
        ("- Added an additional argument to switchspecies command to toggle stat changes.", "- 為 switchspecies 命令新增一個額外參數，用於切換屬性變化。"),
        ("- - Full command is now: GG switchspecies <species> <true/false> <true/false>", "- - 完整命令現為：GG switchspecies <物種> <true/false> <true/false>"),
        ("- - The second true/false determines if stats are changed to the provided species.", "- - 第二個 true/false 決定是否將屬性變更為所指定的物種。"),
        ("- Added a new debug command, GG debugbaronhorns, to directly set how many of Baron's horns are broken.", "- 新增調試命令 GG debugbaronhorns，用於直接設置 Baron 有多少隻角被折斷。"),
        ("- Added a new debug command, GG reloadsprites, to force custom sprites (Woundview, minigame hands, and in-world) to reload from disk without restarting", "- 新增調試命令 GG reloadsprites，可在不重啟遊戲的情況下強制從磁盤重新加載自定義貼圖（傷勢視圖、小遊戲手部以及世界內貼圖）"),
        ("- Added new debug commands, GG forcehollow and GG unforcehollow, to force or clear a post-Mindwipe state for testing", "- 新增調試命令 GG forcehollow 與 GG unforcehollow，用於強制或清除精神抹除後的狀態以便測試"),
        ("- Added GG help, listing every available GG subcommand and its usage", "- 新增 GG help，列出所有可用的 GG 子命令及其用法"),
        ("<b>Bug Fixes:</b>", "<b>漏洞修復：</b>"),
        ("- Fixed GG switchspecies failing with a \"Species picker not yet initialized\" error on loaded saves", "- 修復了在已讀取的存檔中 GG switchspecies 因“Species picker not yet initialized”錯誤而失敗的問題"),
        ("- Fixed a vanilla bug where notes and E-PDAs wouldn't scroll correctly at some screen resolutions (By Dirasial!)", "- 修復了一個原版漏洞：在某些屏幕分辨率下筆記和 E-PDA 無法正確滾動（由 Dirasial 修復！）"),
        ("- - GG's loreslop exposed this. #BEASTMODE", "- - GG 的劇情長文暴露了這個問題。#BEASTMODE"),
        ("<b>Gunsaw Genetics v1.8.0 Changelog:</b>", "<b>Gunsaw Genetics v1.8.0 更新日誌：</b>"),
        ("<i>Like Roza, Leapy's dialogue is still being worked on. Leapy is also missing a few things, mostly because I'm waiting for CUCoreLib's animation support. That being said, I've been working on a lot of other things, so custom shaders/screen effects, custom mini-games, etc. may be coming in the future.</i>", "<i>和 Roza 一樣，Leapy 的對話仍在製作中。Leapy 還缺少一些內容，主要因為我在等 CUCoreLib 的動畫支持。話雖如此，我一直在做很多其他工作，所以自定義著色器／屏幕效果、自定義小遊戲等可能會在未來推出。</i>"),
        ("<b>Leapy Overhaul:</b>", "<b>Leapy 重做：</b>"),
        ("<b>Regrowth:</b>", "<b>再生：</b>"),
        ("- Active ability. Hold to use.", "- 主動技能。按住使用。"),
        ("- While active:", "- 激活期間："),
        ("- - Regenerates skin and muscle health across the entire body at around ~4.5/sec", "- - 以約 4.5/秒的速度再生全身的皮膚和肌肉生命值"),
        ("- - Reduces active bleeding", "- - 減少活動性出血"),
        ("- - Mends bone fractures (dislocations unaffected)", "- - 修復骨折（脫臼不受影響）"),
        ("- - Regrows missing limbs in stages.", "- - 分階段再生缺失的肢體。"),
        ("- - Regrows disfigurement and missing eyes in stages.", "- - 分階段再生面部缺損和缺失的眼睛。"),
        ("- - Cannot be activated below 20 hunger", "- - 飢餓低於 20 時無法激活"),
        ("- Regrowth progress (on limbs, eyes, and disfigurement) will regress if not held, but won't go below the last stage reached. This <i>does</i> get cleared if the parent segment gets dismembered, though.", "- 再生進度（肢體、眼睛和麵部缺損）在未按住時會回退，但不會低於已到達的最後階段。不過，如果上級部位被切斷，進度<i>確實</i>會被清空。"),
        ("- Costs, scaling with how much is currently being healed (fractures + heavily damaged limbs below 50/50 health + actively regrowing limbs):", "- 消耗會隨當前正在治療的內容量而增加（骨折 + 生命值低於 50/50 的嚴重受損肢體 + 正在再生的肢體）："),
        ("- - Drains hunger at 4.5/sec, and thirst at 1/3 that rate", "- - 以 4.5/秒的速度消耗飢餓，口渴的消耗速度為該值的 1/3"),
        ("- - Reduces immunity by 1/sec", "- - 每秒降低 1 點免疫力"),
        ("- - Raises body temperature by 0.1/sec", "- - 每秒提高 0.1 點體溫"),
        ("- - Increases pain by 1.2/sec per thing currently healing", "- - 每個正在治療的項目每秒增加 1.2 點疼痛"),
        ("- - Increases heart rate by 3/sec per thing currently healing", "- - 每個正在治療的項目每秒增加 3 點心率"),
        ("- - Drains energy by 0.5/sec per thing currently healing", "- - 每個正在治療的項目每秒消耗 0.5 點體力"),
        ("- - Considerably more susceptible to fibrillation while active, on top of the heart rate increase itself.", "- - 激活期間，除了心率本身的提升之外，還明顯更容易發生心室顫動。"),
        ("<b>Leapy's natural (non-Regrowth) healing has been reworked:</b>", "<b>Leapy 的自然（非再生）治療已重做：</b>"),
        ("- Still uses the game's normal healing formula, but its hunger-based scaling has been replaced with Leapy's own.", "- 仍使用遊戲的常規治療公式，但其基於飢餓的加成已替換為 Leapy 專屬的加成。"),
        ("- Scales with average hunger/thirst: full strength at 100/100, normal strength at 20/20, and progressively worse below that.", "- 隨飢餓／口渴的平均值縮放：100/100 時效果全滿，20/20 時為正常強度，低於該值則逐步變差。"),
        ("<b>Mood:</b>", "<b>心情：</b>"),
        ("- Injured legs now give a constant, but slow, mood drop.", "- 受傷的腿現在會帶來持續但緩慢的心情下降。"),
        ("- - -0.1/sec per-leg segment below 50/50 health.", "- - 每個生命值低於 50/50 的腿部部位每秒 -0.1。"),
        ("- Losing a leg segment gives -12 mood, on top of everything else.", "- 失去一個腿部部位會額外造成 -12 心情，且疊加在其他所有效果之上。"),
        ("- Using Regrowth to restore a leg segment gives +6 mood.", "- 使用再生恢復一個腿部部位會給予 +6 心情。"),
        ("<b>Wallslide changed:</b>", "<b>貼牆下滑已改動：</b>"),
        ("- Comes to a (almost) complete stop", "- 會（幾乎）完全停下"),
        ("- Drains slightly more stamina", "- 略微增加體力消耗"),
        ("<b>Walk / Run speed changed:</b>", "<b>行走／奔跑速度已改動：</b>"),
        ("- Starts slower, then ramps up in speed", "- 起步更慢，隨後速度逐漸提升"),
        ("- - This makes it easier for Leapy to make smaller movements while still retaining their high mobility stats.", "- - 這讓 Leapy 更容易做出小幅移動，同時仍保留其高機動屬性。"),
        ("- Hunger rate increased to 1.4x", "- 飢餓速度提高至 1.4 倍"),
        ("- Dash ability removed", "- 移除衝刺技能"),
        ("- MoveSpeed changed from 1.36 to 1.3", "- MoveSpeed 從 1.36 改為 1.3"),
        ("- JumpSpeed changed from 1.3 to 1.2", "- JumpSpeed 從 1.3 改為 1.2"),
        ("<b>Universal Diets:</b>", "<b>通用飲食：</b>"),
        ("<i>Processed food is still kinda in a weird spot. A future update might put them into a separate list for diets. For now, the system will use a more simplified format.</i>", "<i>加工食品目前仍處於一個比較尷尬的位置。未來的更新可能會把它們放進單獨的飲食列表。就目前而言，系統會採用更簡化的格式。</i>"),
        ("- Herbivore diet added", "- 新增食草動物飲食"),
        ("- Semi-Herbivore diet added", "- 新增半食草動物飲食"),
        ("- - Semi-Herbivores use the same list as herbivores, but have a lesser penalty for eating outside of their diet.", "- - 半食草動物使用與食草動物相同的列表，但食用飲食之外的食物時懲罰更輕。"),
        ("- Semi-Carnivore diet added", "- 新增半食肉動物飲食"),
        ("- - Semi-Carnivores use the same list as carnivores, but have a lesser penalty for eating outside of their diet.", "- - 半食肉使用與食肉相同的列表，但進食飲食範圍之外的食物時懲罰更輕。"),
        ("- Carnivores and Semi-Carnivores can now eat Animal Flesh without the sickness penalty. Missed this before.", "- 食肉與半食肉現在可以食用動物肉塊，且不會受到疾病懲罰。之前漏掉了這一點。"),
        ("- Sickness penalty for eating outside of diets reduced.", "- 進食飲食範圍之外的食物時，疾病懲罰已降低。"),
        ("- Leapy is now a Semi-Herbivore", "- Leapy 現在是半食草"),
        ("- - Additionally, Leapy can eat foliage, dried foliage, and foliage meals with less downsides.", "- - 此外，Leapy 可以食用植物纖維、乾燥植物纖維和植物纖維餐，負面影響更小。"),
        ("- Milky is now a Semi-Herbivore", "- Milky 現在是半食草"),
        ("- Chik is now a Semi-Herbivore", "- Chik 現在是半食草"),
        ("- Baron is now a Herbivore", "- Baron 現在是食草"),
        ("- Icke is now a Herbivore", "- Icke 現在是食草"),
        ("- Crystal is now a Semi-Carnivore", "- Crystal 現在是半食肉"),
        ("- Chompy is now a Carnivore", "- Chompy 現在是食肉"),
        ("- Voyager is now a Carnivore", "- Voyager 現在是食肉"),
        ("- Velvet is now a Carnivore", "- Velvet 現在是食肉"),
        ("- Setting toggle added to disable diets entirely. Species-specific food bonuses (like Leapy's foliage tolerance) still apply either way.", "- 新增設置開關，可完全禁用飲食系統。無論是否啟用，物種特有的食物加成（如 Leapy 的植物纖維耐受）依然生效。"),
        ("<b>Commands added:</b>", "<b>新增指令：</b>"),
        ("<i>GG will be the prefix for all current and future commands.</i>", "<i>GG 將作為當前及今後所有指令的前綴。</i>"),
        ("- Added switchspecies command", "- 新增 switchspecies 指令"),
        ("- - Example: GG switchspecies Leapy <true/false>", "- - 示例：GG switchspecies Leapy <true/false>"),
        ("- - True / false determines if you are healed when running the command. If not defined, you will be healed automatically.", "- - true / false 決定執行指令時是否為你治療。若不指定，將自動為你治療。"),
        ("- Added merchollow command", "- 新增 merchollow 指令"),
        ("- - Example: GG merchollow <0-10>", "- - 示例：GG merchollow <0-10>"),
        ("- - Need to be Mercenary to use this command. Sets hollow level to provided number.", "- - 需要是 Mercenary 才能使用此指令。將空洞等級設為指定的數值。"),
        ("<b>Tail Sprites added (ThePristineAnt drew all of these!!!!):</b>", "<b>新增尾部貼圖（全部由 ThePristineAnt 繪製！！！！）：</b>"),
        ("- Velvet tail sprite added", "- 新增 Velvet 尾部貼圖"),
        ("- Leapy tail sprite added", "- 新增 Leapy 尾部貼圖"),
        ("- Roza tail sprite added", "- 新增 Roza 尾部貼圖"),
        ("- Baron tail sprite added", "- 新增 Baron 尾部貼圖"),
        ("- Experiment tail sprite added", "- 新增 Experiment 尾部貼圖"),
        ("- Setting added to toggle these. Default on.", "- 新增設置開關，可切換這些貼圖。默認開啟。"),
        ("<b>Woundview Sprites:</b>", "<b>傷勢視圖貼圖：</b>"),
        ("- Leapy Regrowth sprites (75 of them!) added (by ThePristineAnt!!!!)", "- 新增 Leapy 再生貼圖（多達 75 張！）（由 ThePristineAnt 繪製！！！！）"),
        ("- Voyager resprite! (by ThePristineAnt!!!)", "- Voyager 貼圖重製！（由 ThePristineAnt 繪製！！！）"),
        ("- <b>CUCoreLib updated to 1.0.4</b> (1.0.5? Just download the most recent one lol)", "- <b>CUCoreLib 已更新至 1.0.4</b>（1.0.5？直接下載最新的那個就行 哈哈）"),
        ("- Fixed a bug that affected pixelated rendering during certain cutscenes.", "- 修復了影響部分過場動畫中像素化渲染的 bug。"),
        ("- Fixed a bug that allowed Mercenary's Hollow stutter to apply to all talker lines.", "- 修復了導致 Mercenary 的空洞卡頓效果作用於所有臺詞的問題。"),
        ("<b>Gunsaw Genetics v1.7.5 changelog:</b>", "<b>Gunsaw Genetics v1.7.5 更新日誌：</b>"),
        ("<b>Roza Overhaul:</b>", "<b>Roza 重做：</b>"),
        ("<i>Roza is not done. Dialogue and portrait art are still being worked on, alongside a few more things for the species itself.</i>", "<i>Roza 尚未完成。對話與立繪仍在製作中，該物種本身也還有幾項內容待處理。</i>"),
        ("<b>Torpor:</b>", "<b>蟄伏：</b>"),
        ("- Active ability. Hold to actively lower own body temperature.", "- 主動能力。按住可主動降低自身體溫。"),
        ("- - Lower limit of 29°C. You cannot cool yourself below this temp.", "- - 下限為 29°C。無法將自身體溫降到該溫度以下。"),
        ("- Works even at higher temperatures, but has reduced effectiveness the higher those temperatures are", "- 在體溫較高時同樣有效，但體溫越高，效果越弱"),
        ("- - For reference, ~40°C is only ~56% as effective and ~42°C is only ~38% as effective at lowering temperature.", "- - 作為參考，約 40°C 時降溫效果僅有約 56%，約 42°C 時僅有約 38%。"),
        ("- Thirst and energy get drained by using this.", "- 使用時會消耗口渴和體力。"),
        ("- - Thirst is 0.5/sec. Increases by 0.05/sec for each second held.", "- - 口渴為 0.5/秒。每多按住一秒，再增加 0.05/秒。"),
        ("- - Energy is 0.15/sec", "- - 體力為 0.15/秒"),
        ("- Scaling cooldown:", "- 遞增冷卻："),
        ("- - 5 seconds held = ~5 second cooldown (Bumped to minimum 6 seconds if it comes out lesser.)", "- - 按住 5 秒 = 約 5 秒冷卻（若結算結果更低，則提升至最低 6 秒。）"),
        ("- - 10 seconds = ~13 seconds", "- - 10 秒 = 約 13 秒"),
        ("- - 20 seconds = ~35 seconds", "- - 20 秒 = 約 35 秒"),
        ("<b>Frozen:</b>", "<b>凍結：</b>"),
        ("- While Torpor is being used, items can sometimes freeze.", "- 使用蟄伏期間，物品有時會凍結。"),
        ("- To freeze:", "- 凍結條件："),
        ("- - Torpor needs to be active", "- - 蟄伏需要處於激活狀態"),
        ("- - Body temp must be below 30°C", "- - 體溫必須低於 30°C"),
        ("- - Food items need to be wet", "- - 食物需要處於潮溼狀態"),
        ("- - Liquid containers need to contain liquid", "- - 液體容器需要裝有液體"),
        ("- While frozen, items:", "- 凍結期間，物品："),
        ("- - Cannot be consumed", "- - 無法被食用"),
        ("- - Thaw overtime", "- - 會隨時間解凍"),
        ("- - Decay is paused", "- - 腐壞暫停"),
        ("- Frozen items can also be used on the body as a pseudo-icepack.", "- 凍結的物品也可以當作簡易冰敷包用在身體上。"),
        ("- - FAR less effective than a real icepack (Around 7% of the normal effect)", "- - 效果遠低於真正的冰敷包（約為正常效果的 7%）"),
        ("- - Reduces frozen time and condition when used like this.", "- - 這樣使用時，會減少凍結時間和凍結程度。"),
        ("- Frozen tooltip line added", "- 新增凍結提示行"),
        ("- Decay tooltip altered for frozen items.", "- 為凍結物品調整了腐壞提示。"),
        ("- Talker line added for attempting to consume frozen items.", "- 新增嘗試食用凍結物品時的臺詞。"),
        ("<b>Temperature:</b>", "<b>溫度：</b>"),
        ("- Movement slowdown from cold (below 34°C) is reduced by 70%.", "- 寒冷（低於 34°C）造成的移動減速降低 70%。"),
        ("- The frost screen effect is reduced by 70%.", "- 結霜屏幕效果降低 70%。"),
        ("- Cold no longer drains hunger between 30°C and 32°C.", "- 在 30°C 到 32°C 之間，寒冷不再消耗飢餓。"),
        ("- Roza's body doesn't take real cold damage until roughly 2°C colder than other species would.", "- Roza 的身體要到比其他物種再低約 2°C 時，才會受到真正的寒冷傷害。"),
        ("- - Just like Dune, the WoundView warnings are shifted to match.", "- - 與 Dune 一樣，傷勢視圖的警告也相應延後。"),
        ("- Heartrate no longer drops as harshly in the cold. Cancels ~35% of the normal heart rate decrease while cold.", "- 寒冷時心率不再下降得那麼劇烈。寒冷狀態下可抵消約 35% 的正常心率下降。"),
        ("- - No effect during fibrillation. Roza can still die from being too cold, it's just harder.", "- - 心律失常期間無效。Roza 仍可能因過冷而死亡，只是更難。"),
        ("<b>Diet:</b>", "<b>飲食：</b>"),
        ("<i>This is a bit weird since we don't have a ton of info on what a Snow Strider actually is. Since Roza is directly from Experiment, I just left it be, for now.</i>", "<i>這有點奇怪，因為我們對雪行者究竟是什麼瞭解得並不多。由於 Roza 直接來自 Experiment，目前我就先保持原樣。</i>"),
        ("- Eating other Sawians (Yellow Flesh, Internal Organs) causes an additional -7.5 mood loss", "- 食用其他 Sawian（黃色肉塊、內臟團）會額外造成 -7.5 的心情損失"),
        ("- - Unique talker line for Roza when resorting to cannibalism", "- - Roza 在被迫同類相食時有專屬臺詞"),
        ("- Mood takes twice as long to naturally return to neutral. (Positive and negative)", "- 心情自然迴歸中性所需的時間翻倍。（無論正面還是負面）"),
        ("- Threatening a trader costs 2x the normal mood and trauma hit.", "- 威脅商人造成的心情與心理創傷代價為正常的 2 倍。"),
        ("- Killing a trader applies an additional -10 mood and +5 trauma", "- 殺死商人會額外造成 -10 心情和 +5 心理創傷"),
        ("- Seeing a corpse costs 1.75x the normal mood loss (Might be too oppressive)", "- 看到屍體造成的心情損失為正常的 1.75 倍（可能過於壓抑）"),
        ("- Breaking a corpse costs 2x the normal mood loss", "- 破壞屍體造成的心情損失為正常的 2 倍"),
        ("- Hugging a trader now requires 25 less reputation", "- 現在擁抱商人所需的好感度降低 25"),
        ("- Successful hugs give 2x the normal mood and reputation gain", "- 成功擁抱獲得的心情和好感度為正常的 2 倍"),
        ("- - Failed hugs are unaffected.", "- - 擁抱失敗不受影響。"),
        ("<b>Dune Changes:</b>", "<b>Dune 改動：</b>"),
        ("- Changed heartrate during higher temps to give Dune a more stable bpm. Forgot to add this last update.", "- 調整了高溫時的心率，使 Dune 的心率更加穩定。上次更新忘了加這一條。"),
        ("- - Same deal as Roza's heart changes above.", "- - 與上文 Roza 的心率改動同理。"),
        ("<b>Universal Diet Changes:</b>", "<b>通用飲食改動：</b>"),
        ("- Carnivores can now consume soup.", "- 食肉現在可以食用湯。"),
        ("<b>Species Config added:</b>", "<b>新增物種配置：</b>"),
        ("- Config button added to the mod's main menu.", "- 在模組主菜單中新增配置按鈕。"),
        ("- Allows configuration of all built-in species in the mod.", "- 可對模組中所有內置物種進行配置。"),
        ("- Altered species <i>do</i> get marked as modified", "- 被修改過的物種<i>確實</i>會被標記為已修改"),
        ("- - This will be used in the future to block certain things", "- - 這將在未來用於屏蔽某些東西"),
        ("- - Unlock settings are never going to be removed, though. (And will continue to be added upon with any new additions that are gated)", "- - 不過解鎖設置永遠不會被移除。（並且今後任何有解鎖門檻的新增內容都會繼續加入其中）"),
        ("- Roza woundview sprites added (by ThePristineAnt!!!!)", "- 添加了 Roza 的傷勢視圖貼圖（由 ThePristineAnt 製作！！！！）"),
        ("- Milky woundview sprite fixes", "- 修復 Milky 的傷勢視圖貼圖"),
        ("<b>XP Multipliers:</b>", "<b>經驗倍率：</b>"),
        ("- - STR: 70%", "- - 力量：70%"),
        ("- - RES: 80%", "- - 韌性：80%"),
        ("- - INT: 110%", "- - 智力：110%"),
        ("- - STR: 60%", "- - 力量：60%"),
        ("- - RES: 125%", "- - 韌性：125%"),
        ("- - INT: 115%", "- - 智力：115%"),
        ("- - STR: 120%", "- - 力量：120%"),
        ("- - RES: 115%", "- - 韌性：115%"),
        ("- - INT: 95%", "- - 智力：95%"),
        ("- - STR: 100% (Unchanged)", "- - 力量：100%（未改動）"),
        ("- - RES: 70%", "- - 韌性：70%"),
        ("- - STR: 90%", "- - 力量：90%"),
        ("- - RES: 130%", "- - 韌性：130%"),
        ("- - INT: 75%", "- - 智力：75%"),
        ("- - RES: 140%", "- - 韌性：140%"),
        ("- - INT: 70%", "- - 智力：70%"),
        ("- - INT: 90%", "- - 智力：90%"),
        ("- - STR: 110%", "- - 力量：110%"),
        ("- - INT: 100% (Unchanged)", "- - 智力：100%（未改動）"),
        ("- - RES: 90%", "- - 韌性：90%"),
        ("- - RES: 135%", "- - 韌性：135%"),
        ("- - STR: 50%", "- - 力量：50%"),
        ("- - RES: 55%", "- - 韌性：55%"),
        ("- - INT: 65%", "- - 智力：65%"),
        ("- Dune buff:", "- Dune 增強："),
        ("- - INT: 20% -> 35%", "- - 智力：20% -> 35%"),
        ("<b>Stat Changes:</b>", "<b>屬性改動：</b>"),
        ("- - STR: 8", "- - 力量：8"),
        ("- - RES: 10", "- - 韌性：10"),
        ("- - INT: 9", "- - 智力：9"),
        ("- - STR: 9", "- - 力量：9"),
        ("- - RES: 6", "- - 韌性：6"),
        ("- - INT: 6 (Unchanged)", "- - 智力：6（未改動）"),
        ("- - RES: 11", "- - 韌性：11"),
        ("- - INT: 5 (Unchanged)", "- - 智力：5（未改動）"),
        ("- Trait text reformatted / rewritten", "- 特質文本已重新排版 / 重寫"),
        ("- - This was annoying asf to do, so it's a little weird looking. I'm not touching it for a while.", "- - 做這個煩得要死，所以看起來有點怪。我暫時不會碰它。"),
        ("<b>Dune Overhaul:</b>", "<b>Dune 重做：</b>"),
        ("<i>Keep in mind that certain passive traits have already been added. Check previous changelogs.</i>", "<i>請記住，某些被動特質已經添加過了。查看之前的更新日誌。</i>"),
        ("<b>Feeding:</b>", "<b>進食：</b>"),
        ("- Hug is entirely replaced with a bite.", "- 擁抱完全被替換為啃咬。"),
        ("- - The button icon will likely be replaced later. I just made something quickly so it wasn't blank.", "- - 按鈕圖標之後可能會替換。我只是快速做了個東西，免得空著。"),
        ("- With non-Dune traders, you need 150 rep to bite, and can only do so once per trader.", "- 對非 Dune 商人，你需要 150 好感度才能咬，且每個商人只能咬一次。"),
        ("- - Restores 20 hunger", "- - 恢復 20 點飢餓"),
        ("- - Drops reputation by 50", "- - 好感度下降 50"),
        ("- Dune traders have no reputation or once-only restriction, but won't allow it below 700 health.", "- Dune 商人沒有好感度或僅限一次的限制，但生命值低於 700 時不允許。"),
        ("- - No reputation cost", "- - 無好感度消耗"),
        ("<b>Self-Cannibalization:</b>", "<b>自我同類相食：</b>"),
        ("- If hunger reaches 0 or below, a short countdown begins. Failing to eat in time results in Dune eating a piece of themself.", "- 如果飢餓降到 0 或以下，會開始一段短暫倒計時。沒能在時限內進食，Dune 就會吃掉自己的一塊肉。"),
        ("- - Restores a good chunk of hunger afterwards, so it isn't a death spiral", "- - 之後會恢復相當一部分飢餓度，所以不會陷入死亡螺旋"),
        ("- Moodle added", "- 已添加狀態圖標"),
        ("- Dune enjoys the heat. Between 40°C and 41°C, mood slowly improves (no bonus below or above this range).", "- Dune 喜歡高溫。在 40°C 到 41°C 之間，心情會緩慢改善（低於或高於此範圍都沒有加成）。"),
        ("- Being hot no longer increases thirst drain for Dune specifically.", "- 對 Dune 而言，體溫過高不再加快口渴消耗。"),
        ("- Movement slowdown from heat (above 38.5°C) is reduced by 70%.", "- 高溫（38.5°C 以上）導致的移動減速降低 70%。"),
        ("- The heat screen effect is reduced by 70%.", "- 高溫的屏幕效果降低 70%。"),
        ("- Dune's body doesn't take real heat damage (brain health / blood volume loss) until roughly 2°C hotter than other species would.", "- Dune 的身體要比其他物種高出大約 2°C 才會真正受到高溫傷害（腦部健康 / 血量損失）。"),
        ("- - This means Dune's dying and critically dying states (used for on-screen warnings and such) are also adjusted to match. You won't see critical heat warnings unless something else is actually wrong.", "- - 這意味著 Dune 的瀕死和危重狀態（用於屏幕警告等）也相應調整。除非確實出了別的問題，否則你不會看到高溫危重警告。"),
        ("- No longer can trigger Last Stand", "- 不再能觸發背水一戰"),
        ("- Mood cannot go below -30 or above 60 (Hard setting to 0 is removed)", "- 心情不能低於 -30 或高於 60（困難設置下的 0 限制已移除）"),
        ("- Sickness cap increased to 75 (Was 40)", "- 疾病上限提高到 75（原為 40）"),
        ("- Weight gain from eating food is reduced by 40%.", "- 進食導致的體重增加降低 40%。"),
        ("- Sickness from overeating (eating past being full) is reduced by 80%.", "- 暴食（吃飽後繼續吃）導致的疾病降低 80%。"),
        ("- Healing rate increased from 0.5 to 0.75", "- 治療速率從 0.5 提高到 0.75"),
        ("- Health increased from 0.9 to 0.95", "- 健康從 0.9 提高到 0.95"),
        ("<b>Diets added:</b>", "<b>已添加飲食：</b>"),
        ("- Dune is now properly a carnivore. Eating non-meat now has penalties.", "- Dune 現在正式是食肉動物。吃非肉類現在會有懲罰。"),
        ("- Penalties for eating outside of your species diet include:", "- 吃本物種飲食之外的食物會有以下懲罰："),
        ("- - 35% less hunger restored from eaten food", "- - 吃下的食物恢復的飢餓度減少 35%"),
        ("- - -3 Mood", "- - 心情 -3"),
        ("- - +8 Sickness", "- - 疾病 +8"),
        ("- Mindwipe does clear diets, but certain properties will still linger", "- 精神抹除劑確實會清除飲食，但某些屬性仍會殘留"),
        ("- - Such as Dune's weight gain reduction or overfeed sickness reduction", "- - 例如 Dune 的體重增加降低或暴食疾病降低"),
        ("- Other species will definitely be added to this system. Milky is a semi-herbivore, for example.", "- 其他物種肯定會加入這套系統。例如 Milky 是半食草動物。"),
        ("<b>XP Multipliers added:</b>", "<b>已添加經驗倍率：</b>"),
        ("<i>100% is baseline. Higher is better.</i>", "<i>100% 為基準。越高越好。</i>"),
        ("- - STR: 115%", "- - 力量：115%"),
        ("- - RES: 110%", "- - 韌性：110%"),
        ("- - INT: 20%", "- - 智力：20%"),
        ("- - STR: 85%", "- - 力量：85%"),
        ("- - INT: 125%", "- - 智力：125%"),
        ("- - STR and RES are default", "- - 力量與韌性為默認值"),
        ("- - INT: 35%", "- - 智力：35%"),
        ("- Setting added to toggle this off (All stats revert to 1x / 100%). Default on.", "- 新增設置項可關閉此功能（所有屬性恢復為 1x / 100%）。默認開啟。"),
        ("- Menu text updated to show multipliers when changed.", "- 菜單文本已更新，改動時會顯示倍率。"),
        ("- All species will eventually have these set. This is the first iteration and requires testing before full implementation.", "- 所有物種最終都會配置這些數值。這是第一輪迭代，全面實裝前需要測試。"),
        ("<b>Localization:</b>", "<b>本地化：</b>"),
        ("- Old zh.json removed", "- 移除了舊的 zh.json"),
        ("- New zh.json added (This was made by lpoklpok!!!)", "- 新增了 zh.json（由 lpoklpok 製作！！！）"),
        ("<b>Info Panel:</b>", "<b>信息面板：</b>"),
        ("- Dune updated", "- Dune 已更新"),
        ("<b>Gunsaw Genetics v1.6.6 Changelog:</b>", "<b>Gunsaw Genetics v1.6.6 更新日誌：</b>"),
        ("<i>A lot of the MP is being removed for now. It's just causing more issues than it fixes. MP support will be on hold until the MP mod itself updates to v5, sorry.", "<i>目前大量聯機內容被移除。它造成的問題比解決的問題還多。聯機支持將暫時擱置，直到聯機模組本身更新到 v5，抱歉。"),
        ("I've kept what does work, though. Mostly visual stuff.", "不過我保留了確實能用的部分。主要是視覺方面的內容。"),
        ("If you notice that a bug report you made was deleted (On Nexus), that was intentional. They aren't applicable anymore with these changes.</i>", "如果你發現自己提交的 bug 報告被刪除了（在 Nexus 上），那是故意的。這些報告在本次改動後已不再適用。</i>"),
        ("<b>Update Notifier added:</b>", "<b>新增更新提示：</b>"),
        ("- Popup that triggers when a new version of GG is uploaded to Nexus", "- 當 GG 有新版本上傳到 Nexus 時觸發的彈窗"),
        ("- Confirm and link button", "- 確認與鏈接按鈕"),
        ("- Checkbox to disable", "- 可禁用的複選框"),
        ("- - Config (File, not in-game) entry to toggle as well", "- - 也可通過配置（文件，非遊戲內）條目開關"),
        ("- Changelog attached", "- 附帶更新日誌"),
        ("- Since this is added in this update, you won't see it until the next update.", "- 由於這是本次更新才加入的，你要到下次更新才能看到它。"),
        ("<b>Changelogs added (In-game):</b>", "<b>新增更新日誌（遊戲內）：</b>"),
        ("- New button on the main screen of the mod", "- 模組主界面新增按鈕"),
        ("- - ! in the top right", "- - 右上角的 !"),
        ("- Displays all of the changelogs for the mod, latest first", "- 顯示該模組的所有更新日誌，最新在前"),
        ("<b>Custom Death Screens:</b>", "<b>自定義死亡畫面：</b>"),
        ("- Custom Death screens are now able to be added.", "- 現在可以添加自定義死亡畫面。"),
        ("- - Currently, this doesn't have anything beyond a single test, which is disabled.", "- - 目前除了一項已禁用的測試外沒有任何內容。"),
        ("- - Folder path is CustomBodySprites/CustomDeathScreens if you'd like to customize this yourself, just be sure to remove the !", "- - 如果你想自己自定義，文件夾路徑是 CustomBodySprites/CustomDeathScreens，注意務必移除其中的 !"),
        ("- Fixed a bug that allowed Voyager to repeatedly steal the same item (If trade menu wasn't reopened)", "- 修復了 Voyager 可以反覆偷取同一物品的 bug（交易菜單未重新打開時）"),
        ("<b>MP CHANGES:</b>", "<b>聯機改動：</b>"),
        ("<b>Conversations:</b>", "<b>對話：</b>"),
        ("- Made conversations rarer between players", "- 降低了玩家之間對話的頻率"),
        ("- Fixed a multiplayer bug where species selection could corrupt sync data for other players", "- 修復了一個聯機 bug：選擇物種可能會破壞其他玩家的同步數據"),
        ("- Removed several broken multiplayer systems (stat resync, vitals sync, save/load, etc.) that were causing more harm than good", "- 移除了若干損壞的聯機系統（屬性重同步、生命體徵同步、存檔/讀檔等），它們弊大於利"),
        ("- - This means that vanilla + MP systems are back in control of things, not my own stuff.", "- - 這意味著由原版 + 聯機系統重新接管，而不是我自己的那套。"),
        ("- Various internal cleanup and stability fixes", "- 各項內部清理與穩定性修復"),
        ("<b>Mercenary Changes:</b>", "<b>Mercenary 改動：</b>"),
        ("- Charge now properly depletes (No more constant regen!)", "- 充能現在會正確耗盡（不再持續回覆！）"),
        ("- - Doesn't regen while in-use", "- - 使用期間不會回覆"),
        ("- - Regen is stopped upon hitting zero for a brief moment (Visual)", "- - 歸零時會短暫停止回覆（視覺表現）"),
        ("- - These were already in, they just couldn't be triggered with the constant regen", "- - 這些本來就有，只是持續回覆導致它們無法觸發"),
        ("- Shrapnel is now cleared on reform / swap", "- 彈片現在會在重塑 / 交換時清除"),
        ("- Overdose is now cleared on reform / swap", "- 藥物過量現在會在重塑 / 交換時清除"),
        ("- Radiation is now cleared on reform / swap", "- 輻射現在會在重塑 / 交換時清除"),
        ("- Hollow text effects should scale better (Hardly showed at lower Hollow levels)", "- 空洞文本效果的表現應該更合理了（空洞等級較低時幾乎不顯示）"),
        ("- Hollow now properly clears post-death", "- 空洞現在會在死亡後正確清除"),
        ("- Lowered the volume of reform / swap", "- 降低了重塑 / 交換的音量"),
        ("<b>Velvet Changes:</b>", "<b>Velvet 改動：</b>"),
        ("- Web passive regen changed to 15s (Accidently left it very low, but this is still a buff from the original version)", "- 蛛網被動回覆改為 15s（不小心把它設得太低了，但相對原版這仍然是增強）"),
        ("- No longer locked to 3 INT. My bad.", "- 不再鎖定為 3 智力。是我的疏忽。"),
        ("<b>WoundView:</b>", "<b>傷勢視圖：</b>"),
        ("- Custom missing eye(s) sprites added:", "- 新增自定義缺眼貼圖："),
        ("- - Velvet, Baron, Dune, and Milky", "- - Velvet、Baron、Dune 和 Milky"),
        ("- Custom disfigured sprites added:", "- 新增自定義面部缺損貼圖："),
        ("- Baron WoundView alignment fixes", "- Baron 傷勢視圖對齊修復"),
        ("<b>Portraits:</b>", "<b>頭像：</b>"),
        ("- Velvet Portrait added (by Toky!!!!)", "- 新增 Velvet 頭像（由 Toky 製作！！！！）"),
        ("<b>Dialogue:</b>", "<b>對話：</b>"),
        ("- Voyager lines added (Trader + Self)", "- 新增 Voyager 臺詞（商人 + 自身）"),
        ("<b>Notes / E-PDA:</b>", "<b>筆記 / E-PDA：</b>"),
        ("- All of these below are written by ThePristineAnt!!!!!! Thank him!!!", "- 以下全部內容由 ThePristineAnt 撰寫！！！！！！感謝他！！！"),
        ("- Random dialogue can now start between different players", "- 不同玩家之間現在可以隨機開始對話"),
        ("- - Host config. You can turn this off entirely.", "- - 主機配置。你可以完全關閉它。"),
        ("- - Random chance + Cooldown (Might need tweaking)", "- - 隨機概率 + 冷卻（可能需要調整）"),
        ("- - Interrupted by certain events (Might need tweaking as well)", "- - 會被某些事件打斷（同樣可能需要調整）"),
        ("- Conversations depend on the species of each player, and how many times they have talked", "- 對話取決於每位玩家的物種，以及他們交談過的次數"),
        ("- Current Convos:", "- 當前對話："),
        ("<b>CatPatch Compat:</b>", "<b>CatPatch 兼容：</b>"),
        ("- Voyager now refuses hugs from non-Voyagers", "- Voyager 現在會拒絕非 Voyager 的擁抱"),
        ("- Voyager now refuses kisses from non-Voyagers", "- Voyager 現在會拒絕非 Voyager 的親吻"),
        ("- Dialogue added for each", "- 分別為兩者添加了對話"),
        ("<b>Fixes (Hopefully...):</b>", "<b>修復（但願如此）：</b>"),
        ("- Saving has been improved. Items are still weird, but the rest should be a lot more stable", "- 存檔已得到改進。物品仍然有些奇怪，但其餘部分應該穩定得多"),
        ("- - Stuff is still probably going to be wiped or loaded at the wrong time. It's a bunch of tangled bs that I can't bring myself to care about. Enjoy.", "- - 有些東西大概還是會被清空，或者在錯誤的時機加載。這堆爛攤子亂得我實在懶得管。玩得開心。"),
        ("- Natural healing shouldn't be stuck anymore. Whoops...", "- 自然癒合應該不會再卡住了。哎呀..."),
        ("- Sleeping no longer drains quickly for non-hosts", "- 非主機玩家睡覺時不再快速流失"),
        ("- Velvet can now cannibalize in MP", "- Velvet 現在可以在聯機中同類相食"),
        ("- Voyager can now properly steal from traders", "- Voyager 現在可以正確地從商人處偷竊"),
        ("- Voyager can now properly stealth attack traders", "- Voyager 現在可以正確地對商人發動潛行攻擊"),
        ("- Traders becoming hostile from stealing are now synced across the server", "- 因偷竊而變得敵對的商人現在會在整個服務器同步"),
        ("- Traders becoming hostile from stealth attacks are now synced across the server (Music / inventory might still be weird on non-host)", "- 因潛行攻擊而變得敵對的商人現在會在整個服務器同步（非主機端的音樂 / 物品欄可能仍會有些異常）"),
        ("- Traders now properly drop inventory for all of the above", "- 以上所有情況下，商人現在都會正確掉落物品欄"),
        ("- Dialogue is now properly applied per-player. (Host doesn't determine the lines for the entire lobby anymore)", "- 對話現在會按玩家分別正確應用。（主機不再為整個房間決定臺詞）"),
        ("<i>This is the first version of MP support for Gunsaw Genetics.  Most issues still exist, and this is still going to be highly buggy. This is essentially a test of what I CAN fix, rather than complete MP support. If the changes listed here don't work, please let me know. That is far more important to know about than MP issues that aren't listed here.</i>", "<i>這是 Gunsaw Genetics 聯機支持的第一個版本。大部分問題依然存在，而且這個版本仍然會有大量 bug。它本質上是對我能修好的部分的一次測試，而不是完整的聯機支持。如果這裡列出的改動沒有生效，請告訴我。這比那些沒在列表裡的聯機問題重要得多。</i>"),
        ("<b>SP CHANGES:</b>", "<b>單人改動：</b>"),
        ("<b>Custom Species:</b>", "<b>自定義物種：</b>"),
        ("- New tab on the mod's menu", "- 模組菜單新增標籤頁"),
        ("- Allows for the creation of custom species.", "- 可以創建自定義物種。"),
        ("- Abilites are not included, but base stats (Vanilla and mod) are avaliable", "- 不包含能力，但基礎屬性（原版與模組）都可以設置"),
        ("- G4-A custom species added for reference", "- 添加了 G4-A 自定義物種作為參考"),
        ("- Help section for further customization", "- 提供進一步自定義的幫助部分"),
        ("- - Specifically: Character sprites, WoundView sprites, and portrait art", "- - 具體為：角色貼圖、傷勢視圖貼圖與肖像美術"),
        ("- Species picking works independently for host and non-host", "- 物種選擇對主機與非主機各自獨立生效"),
        ("- Stats (STR/RES/INT) now apply correctly for non-hosts, including decreases (the exp-boundary bug)", "- 屬性（力量/韌性/智力）現在對非主機玩家正確生效，包括屬性下降（經驗邊界 bug）"),
        ("- Starting items (e.g. Voyager's cloak) now spawn correctly for non-hosts.", "- 初始物品（如 Voyager 的隱身裝置）現在能正確發放給非主機玩家。"),
        ("- Custom sprite slots now render correctly for everyone", "- 自定義貼圖槽位現在對所有人都能正確渲染"),
        ("- Late-join snapshot. A player joining mid-session immediately sees everyone's correct species/sprites, not just after the next change.", "- 中途加入快照。中途加入的玩家能立即看到所有人正確的物種/貼圖，而不必等到下一次變更。"),
        ("- WoundView species name label no longer stuck on \"Experiment\".", "- 傷勢視圖的物種名稱標籤不再卡在“Experiment”。"),
        ("- Species identity is now queryable. I'll be doing special stuff for MP only, so this is necessary.", "- 物種身份現在可以被查詢。我將只針對聯機做一些特殊處理，所以這是必要的。"),
        ("<b>Visual effects:</b>", "<b>視覺效果：</b>"),
        ("- Voyager's Cloak", "- Voyager 的隱身裝置"),
        ("- Crystal's grapple tongue", "- Crystal 的抓取舌"),
        ("- Velvet's webs (both line and point types) spawn, are climbable by everyone, and durability/breaking stays consistent across all clients, with proper per-player caps.", "- Velvet 的蛛網（線型與點型兩種）現在會生成，所有人都能攀爬，耐久/斷裂在所有客戶端之間保持一致，並按玩家正確計算上限。"),
        ("- All Talker lines (custom and vanilla-replacements) now display for non-hosts, and are properly seen by everyone regardless of who's speaking.", "- 所有 Talker 臺詞（自定義與原版替換）現在都會向非主機玩家顯示，無論說話者是誰，所有人都能正確看到。"),
        ("- Fixed a bug with RshLib that caused Voyager to bug out.", "- 修復了一個由 RshLib 引起、導致 Voyager 出錯的 bug。"),
        ("- Added placeholder moodle for Mercenary's Hollow.", "- 為 Mercenary 的空洞添加了佔位狀態圖標。"),
        ("Hopefully this fixes that issue. Works on my end... :voyager:", "但願這能解決那個問題。在我這邊是好的... :voyager:"),
        ("<b>Mercenary added:</b>", "<b>新增 Mercenary：</b>"),
        ("- Unlocked by changing the config setting for now. Will be given a proper obtainment later.", "- 目前通過修改配置項解鎖。之後會給出正規的獲取方式。"),
        ("- Once unlocked, Ctrl + Left click Experiment", "- 解鎖後，Ctrl + 左鍵點擊 Experiment"),
        ("- Three chip-based abilities:", "- 三個基於芯片的能力："),
        ("- - Levitation", "- - 懸浮"),
        ("- - - Grabs any loose object or creature at range", "- - - 遠距離抓取任何散落物體或生物"),
        ("- - - Force is mass-dependent both ways.Heavy objects barely move but throw Mercenary back harder. Light objects fling easily.", "- - - 施力與質量相關，且雙向作用。重物幾乎紋絲不動，但會把 Mercenary 反推得更狠。輕物則輕易飛出。"),
        ("- - - Living targets resist much more than objects", "- - - 活體目標的抗性遠高於普通物體"),
        ("- - - Drains charge while active.", "- - - 激活期間持續消耗儲量。"),
        ("- - Reformation", "- - 重塑"),
        ("- - - On death, time slows and a short window opens to cheat it", "- - - 死亡時，時間會變慢，並短暫開啟一個可以欺騙死亡的窗口"),
        ("- - - Reforms the body. Clears breaks, bleeding, and infection, regrows lost limbs, and restores vitals.", "- - - 重塑身體。清除骨折、出血與感染，再生失去的肢體，並恢復生命體徵。"),
        ("- - - Letting the window expire is permanent death", "- - - 讓窗口超時即為永久死亡"),
        ("- - - Increases Hollow on use.", "- - - 使用時增加空洞。"),
        ("- - - Consumes charge on use.", "- - - 使用時消耗儲量。"),
        ("- - Mindswap", "- - 意識交換"),
        ("- - - An alternative to Reforming. Forces a nearby Sawian trader out of their body and takes it instead.", "- - - 重塑的替代方案。將附近一名 Sawian 商人的意識強行逐出軀體，並佔據它。"),
        ("- - - Old body is left behind, INT, chips, scarf, and hyper-regeneration always carry over regardless of body.", "- - - 舊軀體被留在原地；智力、芯片、圍巾與超速再生無論換到哪具身體都會保留。"),
        ("- - - Stats reset to the new body's baseline (with a small bonus).", "- - - 屬性重置為新軀體的基準值（附帶少量加成）。"),
        ("- Shared charge system powers Levitation, Reformation, and Mindswap, regenerating passively over time", "- 共用儲量系統為懸浮、重塑與意識交換供能，並隨時間被動恢復"),
        ("- Hollow: a permanent, worsening condition that builds up from using Reformation and (especially) Mindswap", "- 空洞：一種永久且不斷惡化的狀態，因使用重塑和（尤其是）意識交換而累積"),
        ("- - Gradually desaturates vision", "- - 逐漸降低視野的色彩飽和度"),
        ("- - Narrows how far mood can swing in either direction", "- - 縮小心情向任一方向波動的幅度"),
        ("- - Reduces trauma buildup", "- - 降低心理創傷的累積"),
        ("- - Increases speech stammering / cutting off mid-sentence", "- - 增加言語結巴 / 中途斷句"),
        ("- - Increases trader reputation penalty", "- - 加重商人好感度懲罰"),
        ("- While wearing another Sawian's body via Mindswap, Mercenary gains access to that species' signature ability (currently just Milky's Hyper-Focus)", "- 通過意識交換穿戴另一名 Sawian 的身體時，Mercenary 可以使用該物種的標誌性能力（目前只有 Milky 的超聚焦）"),
        ("- Portrait art by ThePristineAnt!!!!", "- 肖像美術由 ThePristineAnt 繪製！！！！"),
        ("- Cloak is now a wearable item", "- 隱身裝置現在是一件可穿戴物品"),
        ("- - Active Equipment", "- - 主動裝備"),
        ("- - Toggles cloaking state on / off", "- - 切換隱身狀態的開 / 關"),
        ("- - While cloaked, crouching puts you in a special movement state", "- - 隱身期間蹲伏會進入一種特殊移動狀態"),
        ("- - - Allows cloaking during movement", "- - - 允許在移動中保持隱身"),
        ("- - - Disables the effects of certain traps", "- - - 使某些陷阱的效果失效"),
        ("- - - Drains more power from the battery", "- - - 消耗更多電池電量"),
        ("- - Susceptible to radiation", "- - 易受輻射影響"),
        ("- - Susceptible to water / wetness", "- - 易受水 / 潮溼影響"),
        ("- - Battery powered", "- - 由電池驅動"),
        ("- Toughness slightly lowered (0.84 -> 0.8)", "- 堅韌略微降低（0.84 -> 0.8）"),
        ("- Dialogue added for:", "- 新增對話："),
        ("- - Low radiation", "- - 低輻射"),
        ("- - Mid radiation", "- - 中輻射"),
        ("- - High radiation", "- - 高輻射"),
        ("- - High radiation force decloaking", "- - 高輻射強制解除隱身"),
        ("- - Wetness force decloaking", "- - 潮溼強制解除隱身"),
        ("- - Trying to use cloak without it equipped", "- - 未裝備隱身裝置時嘗試使用隱身"),
        ("- - Trying to use cloak while battery is drained", "- - 電池耗盡時嘗試使用隱身"),
        ("- - Trying to use cloak while having high radiation", "- - 身處高輻射時嘗試使用隱身"),
        ("- - Trying to use cloak while very wet", "- - 極度潮溼時嘗試使用隱身"),
        ("- - Wet dialogue lines in general", "- - 通用的潮溼對話臺詞"),
        ("- - Self-harm and suicide lines", "- - 自殘與自殺臺詞"),
        ("- Passive aspects added:", "- 新增被動特性："),
        ("- - Idolatry", "- - 崇物"),
        ("- - - Unique interactions based on items used, worn, and held", "- - - 根據使用、穿戴和手持的物品觸發獨特互動"),
        ("- - - Items include:", "- - - 物品包括："),
        ("- - - - Pistol, rifle, shotgun, trauma rig, riot helmet, wood sandals, tactical boots, machete, titanium machete, makeshift rifle, makeshift digging tool, ripped dressing, old rag, crude cleaver, makeshift wrench, makeshift headlamp, makeshift helmet, and sling bag", "- - - - 手槍、步槍、霰彈槍、戰術胸掛、防暴頭盔、木屐、戰術靴、砍刀、鈦合金砍刀、簡易步槍、簡易挖掘工具、撕裂的繃帶、舊布條、粗製菜刀、簡易扳手、簡易頭燈、簡易頭盔和植物纖維挎包"),
        ("- - Arrogance", "- - 傲慢"),
        ("- - - Two mood states. +30 and -30.", "- - - 兩種心情狀態。+30 與 -30。"),
        ("- - - +30 represents pride, giving reduced mood loss for corpses, allowing stealth attacks, improving preferred item damage, etc.", "- - - +30 代表自豪，減少看到屍體時的心情損失，允許潛行攻擊，提升偏好物品的傷害等。"),
        ("- - - -30 represents desperation, preventing stealing, allowing hugging and resting with traders, and giving extra mood loss upon viewing corpses.", "- - - -30 代表絕望，禁止偷竊，允許與商人擁抱和休息，並會在看到屍體時造成額外心情損失。"),
        ("- Voyager has increased mood loss resistance as mood lowers, but that reverses upon going below -85, making Voyager far more susceptible to mood loss.", "- Voyager 會在心情降低時獲得更高的心情損失抗性，但一旦低於 -85 就會反轉，使 Voyager 變得更容易受到心情損失影響。"),
        ("- Voyager does increased damage (with claws) to enemies. Environment damage is unaffected.", "- Voyager 用爪對敵人造成更高傷害。環境傷害不受影響。"),
        ("- Stealth Attacks", "- 潛行攻擊"),
        ("- - Available while cloaked and crouched near an unaware trader", "- - 在隱身且蹲伏靠近未察覺的商人時可用"),
        ("- - Unarmed attacks deal heavy damage and force combat", "- - 徒手攻擊造成大量傷害並強制進入戰鬥"),
        ("- - Armed (non-firearm) attacks kill outright, at the cost of item durability and a small chance to break the weapon", "- - 持械（非槍械）攻擊可直接擊殺，代價是物品耐久度以及有較小几率損壞武器"),
        ("- Stealing", "- 偷竊"),
        ("- - Additional option to steal from traders", "- - 新增從商人處偷竊的選項"),
        ("- - Chance to succeed scales with item value and Voyager's INT", "- - 成功幾率隨物品價值和 Voyager 的智力提升"),
        ("- - Failure turns the trader hostile", "- - 失敗會使商人轉為敵對"),
        ("- Reworked self-harm", "- 重做自殘"),
        ("- - Simple for now. Future mini-game", "- - 目前較為簡單。後續會做成小遊戲"),
        ("- Reworked suicide", "- 重做自殺"),
        ("- - Fully automated minigame sequence, escalating across multiple limbs with a chance for additional slashes", "- - 全自動的小遊戲流程，會逐步升級並蔓延至多個肢體，還有幾率造成額外割傷"),
        ("- - Visuals should hopefully be better once I start to properly add custom mini-games.", "- - 等我開始正式加入自定義小遊戲後，視覺效果應該會更好。"),
        ("<b>Orange Changes:</b>", "<b>Orange 改動：</b>"),
        ("- Dialogue lines added by frigidFriend / DaryllDemo!!!", "- 由 frigidFriend / DaryllDemo 添加的對話臺詞！！！"),
        ("- Hand speed scales worse with strength. Clumsy.", "- 手部速度隨力量提升的幅度降低。笨拙。"),
        ("- Claws hit harder, tools hit softer.", "- 爪擊更重，工具攻擊更輕。"),
        ("- Mood swings harder in every direction (150% more impactful, both positive and negative.)", "- 心情在各個方向上的波動都更劇烈（影響程度 +150%，正面和負面皆然。）"),
        ("- Trader reputation on first meeting reflects your current mood. Milky traders will ignore this and try to take advantage of you regardless.", "- 首次見面時的商人好感度會反映你當前的心情。Milky 商人會無視這一點，無論如何都會試圖佔你便宜。"),
        ("- Hugging traders has a stronger effect on reputation", "- 擁抱商人對好感度的影響更強"),
        ("- Letting Dunes bite you gives a bigger reputation boost", "- 讓 Dune 咬你能獲得更高的好感度加成"),
        ("- Bone fractures and dislocations heal twice as fast", "- 骨折和脫臼的癒合速度加倍"),
        ("- Recently injured limbs take reduced damage for a short time afterward", "- 近期受傷的肢體會在之後一小段時間內受到的傷害降低"),
        ("<b>Baron Changes:</b>", "<b>Baron 改動：</b>"),
        ("- Toughness reduced (6.0 -> 4.0)", "- 堅韌降低（6.0 -> 4.0）"),
        ("- Velvet note added (Written by ThePristineAnt!!)", "- 新增 Velvet 筆記（由 ThePristineAnt 撰寫！！）"),
        ("- Voyager updated", "- Voyager 已更新"),
        ("- Orange updated", "- Orange 已更新"),
        ("- Mercenary added", "- 新增 Mercenary"),
        ("- Added a dedicated settings tab for the mod's own options (ability keybinds, WoundView recolor toggle, text effects toggle, tendril mode, language, etc)", "- 為模組自身的選項新增了專屬設置頁（技能按鍵、傷勢視圖配色開關、文字特效開關、觸鬚模式、語言等）"),
        ("- - This will hopefully be positioned better later", "- - 之後希望能把它放到更合適的位置"),
        ("- WoundView panel borders are now properly recolored. I'll be adjusting these a bit, later on.", "- 傷勢視圖面板邊框現在能正確重新著色了。之後我會再稍微調整一下。"),
        ("- <b>Added CUCoreLib as a dependency </b>", "- <b>新增 CUCoreLib 作為依賴項 </b>"),
        ("- zh.json added (C2H4F2 made this translation! Thank them!!!)", "- 新增 zh.json（該翻譯由 C2H4F2 製作！感謝TA！！！）"),
        ("- Velvet lines added (by ThePristineAnt!!!!)", "- 新增 Velvet 臺詞（由 ThePristineAnt 撰寫！！！！）"),
        ("- Dune lines added (by Dirasial!!)", "- 新增 Dune 臺詞（由 Dirasial 撰寫！！）"),
        ("<b>Velvet Overhaul:</b>", "<b>Velvet 重做：</b>"),
        ("- Web Active Ability added", "- 新增蛛網主動技能"),
        ("- - Pressing shoots a small web", "- - 按下會射出小型蛛網"),
        ("- - - Costs 1", "- - - 消耗 1"),
        ("- - - Acts as a grab point, not a rope.", "- - - 作為抓握點，而非繩索。"),
        ("- - Holding shoots a long web", "- - 長按會射出大型蛛網"),
        ("- - - Costs 5", "- - - 消耗 5"),
        ("- - - Climbable. Can span over gaps.", "- - - 可攀爬。能跨越裂隙。"),
        ("- - - Unique interaction when directly hitting Salad (Big cooldown)", "- - - 直接命中 Salad 時有獨特互動（長冷卻）"),
        ("- - Web supply scales with INT", "- - 蛛網儲量隨智力提升"),
        ("- - Restored slowly overtime or by sleeping", "- - 隨時間緩慢恢復，或通過睡眠恢復"),
        ("- - Max of 5 webs", "- - 最多 5 張蛛網"),
        ("- - Webs decay overtime", "- - 蛛網會隨時間衰減"),
        ("- - Slows enemies that come into contact", "- - 減速接觸到的敵人"),
        ("- - - Small web has 1 durability, Long has 5.", "- - - 小型蛛網有 1 點耐久，大型有 5 點。"),
        ("- - - Slowness %, duration, and durability damage change per-enemy", "- - - 減速百分比、持續時間和耐久度傷害因敵人而異"),
        ("- Trader Hug action replaced with cannibalization at 200 Rep.", "- 好感度達到 200 時，商人擁抱動作替換為同類相食。"),
        ("- Self-harm and Suicide replaced with self-cannibalization.", "- 自殘和自殺替換為自我同類相食。"),
        ("- Woundview art by ThePristineAnt!!!", "- 傷勢視圖美術由 ThePristineAnt 製作！！！"),
        ("- Extra limbs added to Woundview", "- 傷勢視圖新增額外肢體"),
        ("- Toggle added to view / interact with extra limbs", "- 新增用於查看 / 互動額外肢體的開關"),
        ("- Immune to trauma", "- 免疫心理創傷"),
        ("- Increased positive mood gain.", "- 提升正面心情獲取。"),
        ("- Sleeping resets mood to 0 if positive", "- 若心情為正，睡眠會將其重置為 0"),
        ("- Mood buff upon killing a trader", "- 殺死商人時獲得心情增益"),
        ("- No mood loss upon threatening a trader", "- 威脅商人時沒有心情損失"),
        ("- No mood loss upon harming a trader", "- 傷害商人時沒有心情損失"),
        ("- No mood loss upon seeing corpses", "- 看到屍體時沒有心情損失"),
        ("- No mood loss upon destroying corpses", "- 破壞屍體時沒有心情損失"),
        ("- Eating Yellow flesh no longer gives sickness", "- 食用黃色肉塊不再造成疾病"),
        ("- Eating Yellow flesh no longer has a mood drop", "- 食用黃色肉塊不再掉落心情"),
        ("- Eating Internal Organs only gives half sickness", "- 食用內臟團只造成一半疾病"),
        ("- Eating Internal Organs no longer has a mood drop", "- 食用內臟團不再掉落心情"),
        ("<b>Milky Changes:</b>", "<b>Milky 改動：</b>"),
        ("- Woundview head redrawn by ThePristineAnt!", "- 傷勢視圖頭部由 ThePristineAnt 重繪！"),
        ("- Toughness increased", "- 堅韌提升"),
        ("- Hyper-Focus cooldown scales with timescale now", "- 超聚焦冷卻現在隨遊戲速度縮放"),
        ("- Eye adaptation scales with timescale now", "- 眼睛適應現在隨遊戲速度縮放"),
        ("- Eye adaptation radius increased", "- 眼睛適應半徑提升"),
        ("- Eye adaptation brightness decreased (No more glowing Milky...)", "- 眼睛適應亮度降低（Milky 不再發光了...）"),
        ("- Eye glare effect now scales based on:", "- 眼睛眩光效果現在依據以下因素縮放："),
        ("- - Brightness of light source", "- - 光源亮度"),
        ("- - Level of adaptation", "- - 適應程度"),
        ("- Small mood buff upon seeing corpses (No mood drop)", "- 看到屍體時獲得小幅心情增益（無心情掉落）"),
        ("- No mood loss upon killing a trader", "- 殺死商人時沒有心情損失"),
        ("<b>Albino Changes:</b>", "<b>Albino 改動：</b>"),
        ("- Portrait art redrawn by ThePristineAnt! (Menu + Note)", "- 立繪由 ThePristineAnt 重繪！（菜單 + 筆記）"),
        ("- Portrait art redrawn by ThePristineAnt! (Menu)", "- 立繪由 ThePristineAnt 重繪！（菜單）"),
        ("- Cloaking no longer stacks.", "- 隱身不再疊加。"),
        ("- Cloaking no longer affects visibility outside of cloaking", "- 隱身不再影響隱身狀態之外的可見度"),
        ("<b>Species info panel added:</b>", "<b>物種信息面板已添加：</b>"),
        ("- Arrow is located below the STR, RES, INT panel.", "- 箭頭位於力量、韌性、智力面板下方。"),
        ("- Displays more detailed info about current species", "- 顯示當前物種更詳細的信息"),
        ("- Text effects for keywords", "- 關鍵詞的文本特效"),
        ("- Keywords include tooltips for extra information", "- 關鍵詞帶有懸浮提示以提供額外信息"),
        ("- Albino info added", "- 添加了 Albino 信息"),
        ("- Milky info added", "- 添加了 Milky 信息"),
        ("- Velvet info added", "- 添加了 Velvet 信息"),
        ("- Baron Prideful entry added", "- 添加了 Baron 自豪條目"),
        ("- Unfinished entries added to species that haven't been overhauled", "- 為尚未重做的物種添加了未完成條目"),
        ("<b>Death screen:</b>", "<b>死亡界面：</b>"),
        ("- Each Sawian is given their proper ID (e.g. SAW-03)", "- 每個 Sawian 都會獲得其對應的 ID（例如 SAW-03）"),
        ("- Albino is censored", "- Albino 被屏蔽處理"),
        ("- Icke and Chik use corrupted IDs", "- Icke 和 Chik 使用損壞的 ID"),
        ("- Removed Debug PDA (Whoops)", "- 移除了調試用 E-PDA（哎呀）"),
        ("<b>Localization added:</b>", "<b>已添加本地化：</b>"),
        ("- en.json added", "- 添加了 en.json"),
        ("- ru.json added", "- 添加了 ru.json"),
        ("- - Current Russian translation is just a machine translation of the menu and some of Albino's text. There is a translator working on this, it just takes a while to do stuff like this. This is a placeholder and will not be expanded upon until the proper translation is made.", "- - 當前的俄語翻譯只是菜單和部分 Albino 文本的機器翻譯。有一位譯者正在處理這項工作，只是做這種事需要一些時間。這只是佔位內容，在正式翻譯完成前不會再擴充。"),
        ("- Config setting for language added", "- 添加了語言配置項"),
        ("<b>Milky changes:</b>", "<b>Milky 改動：</b>"),
        ("- Head Woundview sprite added", "- 添加了頭部傷勢視圖貼圖"),
        ("- Active ability Hyper-Focus added", "- 添加了主動技能超聚焦"),
        ("- Ability moodles added for active and cooldown states.", "- 為技能的激活與冷卻添加了狀態圖標。"),
        ("- Blueprints now provide two random recipes when used.", "- 藍圖現在使用時提供兩個隨機配方。"),
        ("- Hand control strength scaling (In mini-games) improved.", "- 改進了手部控制的力度縮放（小遊戲中）。"),
        ("- Better tool scaling", "- 工具縮放更優"),
        ("- Worse claw scaling", "- 爪縮放更差"),
        ("- Milky's eyes adapt to the darkness. This has an adverse effect when going back into a bright area without taking your time.", "- Milky 的眼睛會適應黑暗。如果不慢慢來就貿然回到明亮區域，會產生不良影響。"),
        ("- Self-harm is replaced with vomiting.", "- 自殘被替換為嘔吐。"),
        ("- Suicide is replaced with a custom event.", "- 自殺被替換為自定義事件。"),
        ("- Starting items removed", "- 移除了初始物品"),
        ("<b>Custom dialogue patch added:</b>", "<b>已添加自定義對話補丁：</b>"),
        ("- Milky lines added (ThePristineAnt wrote these, so thank him!!!)", "- 添加了 Milky 臺詞（這些是 ThePristineAnt 寫的，所以要感謝他！！！）"),
        ("<b>Custom moodle text patch added </b> <i>(This isn't for new moodles. Those were handled in v1.2.0.)</i> <b>:</b>", "<b>已添加自定義狀態圖標文本補丁 </b> <i>（這不是用於新狀態圖標的。那些已在 v1.2.0 中處理。）</i> <b>：</b>"),
        ("- Some moodle lines changed for Milky.", "- 更改了 Milky 的部分狀態圖標文本。"),
        ("<b>Custom Notes and PDA entry system added:</b>", "<b>已添加自定義筆記與 E-PDA 條目系統：</b>"),
        ("- Albino1 note added", "- 添加了 Albino1 筆記"),
        ("- Albino2 note added", "- 添加了 Albino2 筆記"),
        ("- Dune Woundview sprites added", "- 添加了 Dune 傷勢視圖貼圖"),
        ("- Woundview now properly displays species name", "- 傷勢視圖現在會正確顯示物種名"),
        ("- Woundview now has different color palettes per-species.", "- 傷勢視圖現在按物種使用不同的配色。"),
        ("- Config setting for Woundview coloring added", "- 添加了傷勢視圖配色的配置項"),
        ("- Config setting for ability keybind added", "- 添加了技能快捷鍵的配置項"),
        ("- Button added to Woundview panel to toggle coloring in-game", "- 在傷勢視圖面板中添加了按鈕，可在遊戲內切換配色"),
        ("- Clicking during menu startup now skips it", "- 菜單啟動期間點擊現在會跳過它"),
        ("- Albino starting hoodie removed", "- 移除了 Albino 的初始連帽衫"),
        ("- Albino properly unlocks now", "- Albino 現在能正確解鎖了"),
        ("- Voyager sprite bug fixes", "- 修復了 Voyager 貼圖的 bug"),
        ("<i>Art is now mostly being handled by...</i>", "<i>美術現在主要由...負責</i>"),
        ("This guy is my goat. I couldn't do even a fraction of this myself.", "這傢伙就是我的神。這些工作我一個人連一小部分都做不出來。"),
        ("(Specifically:", "（具體來說："),
        ("All custom moodle art.", "所有自定義狀態圖標美術。"),
        ("Baron WoundView sprites.", "Baron 傷勢視圖貼圖。"),
        ("Orange Portrait art.", "Orange 立繪美術。"),
        ("Albino Portrait art.)", "Albino 立繪美術。）"),
        ("- <b>Custom Moodle System Created:</b>", "- <b>已創建自定義狀態圖標系統：</b>"),
        ("- - Icke moodles added", "- - 添加了 Icke 狀態圖標"),
        ("- - Baron moodle added", "- - 添加了 Baron 狀態圖標"),
        ("- - Albino moodles added", "- - 添加了 Albino 狀態圖標"),
        ("- <b>Custom Woundview System Created:</b>", "- <b>已創建自定義傷勢視圖系統：</b>"),
        ("- - Voyager Woundview sprites added", "- - 添加了 Voyager 傷勢視圖貼圖"),
        ("- - Baron Woundview sprites added", "- - 添加了 Baron 傷勢視圖貼圖"),
        ("- - Icke Woundview sprite (Head) added", "- - 添加了 Icke 傷勢視圖貼圖（頭部）"),
        ("- - Albino Woundview sprite (Head) added", "- - 添加了 Albino 傷勢視圖貼圖（頭部）"),
        ("- <b>Custom Music System Created:</b>", "- <b>已創建自定義音樂系統：</b>"),
        ("- - Albino ability music added (3 tracks)", "- - 添加了 Albino 技能音樂（3 首）"),
        ("- Orange portrait art added", "- 添加了 Orange 立繪美術"),
        ("- Albino portrait art added", "- 添加了 Albino 立繪美術"),
        ("- Chik obtainment added", "- 添加了 Chik 的獲取方式"),
        ("- Chik menu page updated", "- 更新了 Chik 菜單頁面"),
        ("- Baron passive ability (Prideful) added", "- 添加了 Baron 被動技能（自豪）"),
        ("- <b>Albino changes:</b>", "- <b>Albino 改動：</b>"),
        ("- - Starting stats (INT, etc.) are all set to 4 now", "- - 初始屬性（智力等）現在全部設為 4"),
        ("- - Description + Trait text updated", "- - 更新了描述 + 特質文本"),
        ("- - Active Ability (Desync) added", "- - 添加了主動技能（解離）"),
        ("- - Albino is now more susceptible to temperature changes", "- - Albino 現在更容易受溫度變化影響"),
        ("- - Enemies spot Albino easier (~2.5x)", "- - 敵人更容易發現 Albino（約 2.5 倍）"),
        ("- - Removed Immunity buff", "- - 移除了免疫力增強"),
        ("- - Albino starts without an eye", "- - Albino 初始缺少一隻眼睛"),
        ("- - Albino starts with a single, random, fracture on their legs", "- - Albino 初始腿部帶有一處隨機骨折"),
        ("- All species (Except Expie) are locked by default", "- 所有物種（除 Expie 外）默認處於鎖定狀態"),
        ("- Obtainment methods added for each species.", "- 為每個物種添加了獲取方式。"),
        ("- Unlock all checkbox added to menu", "- 在菜單中添加了全部解鎖複選框"),
        ("- Random button added to menu", "- 在菜單中添加了隨機按鈕"),
        ("- Loading a save now properly loads sprites", "- 加載存檔現在會正確加載貼圖"),
        ("- Minor bug fixes", "- 次要 bug 修復"),
    };
}
