[概要]
"GUID" = "com.rushellxyz.thighhighs"
"翻译版本" = "v1.0.0"
"模组版本" = "v3.0.0"
[Locale]
# Original: White thigh highs
"thighhighs.thighhighwhite" = "白色过膝袜"
# Original: A pair of white thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighwhitedsc" = "一双白色过膝袜，保暖效果不错。"
# Original: Black thigh highs
"thighhighs.thighhighblack" = "黑色过膝袜"
# Original: A pair of black thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighblackdsc" = "一双黑色过膝袜，保暖效果不错。"
# Original: Pink-white thigh highs
"thighhighs.thighhighpinkwhite" = "粉白过膝袜"
# Original: A pair of pink-white thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighpinkwhitedsc" = "一双粉白过膝袜，保暖效果不错。"
# Original: Blue-black thigh highs
"thighhighs.thighhighblueblack" = "蓝黑过膝袜"
# Original: A pair of blue-black thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighblueblackdsc" = "一双蓝黑过膝袜，保暖效果不错。"
