internal static class KrokMPTr
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("MP- force to show and log all chat messages", "【MP】强制显示并记录所有聊天消息"),
        ("MP - Hijack object's Talker component.", "【MP】劫持目标物体的 Talker 组件。"),
        ("MP - control earthquake", "【MP】控制地震"),
        ("DELETEME", "【MP】删除我"),
        ("MP - respawn a player", "【MP】重生一名玩家"),
        ("MP - clear inventory of a player", "【MP】清空一名玩家的物品栏"),
        ("MP - revive every player and keep resetting their health", "【MP】复活所有玩家并持续重置其生命值"),
        ("MP - zoom camera", "【MP】缩放视角"),
        ("MP - spectator mode", "【MP】旁观模式"),
        ("MP- Call a vote.", "【MP】发起投票。"),
        ("MP-SERVER- Call a custom vote.", "【MP 服务器】发起自定义投票。"),
        ("MP-SERVER- Forcefully disconnect player.", "【MP 服务器】强制断开玩家连接。"),
        ("MP-SERVER- Ban player.", "【MP 服务器】封禁玩家。"),
        ("MP-SERVER- IP Ban player. (Non-steam only)", "【MP 服务器】IP 封禁玩家。（仅限非 Steam 连接）"),
        ("MP- Show all players you've banned. Local.", "【MP】显示你已封禁的所有玩家（本地）。"),
        ("MP- Remove a player from your ban list.", "【MP】将玩家从封禁列表中移除。"),
        ("MP - say something in chat", "【MP】在聊天中发送消息"),
        ("MP - Activate/Deactivate radline", "【MP】激活/停用辐射线"),
        ("MP - vc test", "【MP】语音聊天测试"),
        ("MP - mute or change volume of a specific player, local", "【MP】静音或调整特定玩家的语音音量（本地）"),
        ("MP-SERVER- force reload all custom music right now", "【MP 服务器】立即强制重新加载所有自定义音乐"),
        ("MP-SERVER- set admin password (ANYONE CAN USE THIS PASSWORD)", "【MP 服务器】设置管理员密码（任何人都可使用此密码）"),
        ("MP-SERVER- give or remove admin privileges", "【MP 服务器】授予或移除管理员权限"),
        ("MP-CLIENT- toggle admin mode, run commands on the server and see its log", "【MP 客户端】切换管理员模式，在服务器上执行命令并查看其日志"),
        ("MP- delete blast marks, block damages, casings, blood", "【MP】清除爆炸痕迹、方块损坏、弹壳和血迹"),
        ("MP-SERVER- force rename a player", "【MP 服务器】强制重命名玩家"),
        ("MP-SERVER- force recolor a player", "【MP 服务器】强制更改玩家颜色"),
        ("MP - dump locale of multiplayer mod", "【MP】转储多人模组的本地化数据"),
        ("MP dev - Enable verbose logging and debug screens", "【MP 开发】启用详细日志记录和调试画面"),
        ("MP dev - Show debug sync info on objects. (DEPRECATED)", "【MP 开发】显示物体的调试同步信息（已废弃）"),
        ("MP-SERVER- mute player chat or voice", "【MP 服务器】禁言玩家文字聊天或语音"),
        ("MP dev - Queue force-sync for a object netId", "【MP 开发】对指定 netId 对象排队强制同步"),
        ("MP dev - Unregister all objects. (IT CAN CAUSE MORE DESYNC)", "【MP 开发】注销所有对象（可能导致更多不同步）"),
        ("MP dev - Register all objects in the world. (IT LAGS !!!!!)", "【MP 开发】注册世界中所有对象（会导致卡顿！！！！！）"),
        ("MP - SERVER - Set player limit", "【MP 服务器】设置玩家数量上限"),
        ("MP - set position and size of chat box (everything is a scale in float (0-1)) (OBSOLETE)", "【MP】设置聊天框的位置和大小（所有参数为 0-1 浮点比例）（已废弃）"),
        ("MP dev - toggle chat text preview (OBSOLETE)", "【MP 开发】切换聊天文字预览（已废弃）"),
        ("MP - go to main menu", "【MP】返回主菜单"),
        ("MP - show all multiplayer game rules", "【MP】显示所有多人游戏规则"),
        ("MP - reset all multiplayer game rules to default values", "【MP】将所有多人游戏规则重置为默认值"),
        ("MP - set multiplayer game rule", "【MP】设置多人游戏规则"),
        ("MP - Set your multiplayer username.", "【MP】设置你的多人联机用户名。"),
        ("MP - Set your multiplayer password.", "【MP】设置房间加入密码。"),
        ("MP - Client Connect to an active steam lobby.", "【MP】客户端连接到活跃的 Steam 大厅。"),
        ("MP - Host steam lobby.", "【MP】创建 Steam 大厅。"),
        ("MP - Log info about your steam lobby.", "【MP】记录 Steam 大厅信息。"),
        ("MP - Start a dedicated server. (you'll have no player character)", "【MP】启动专用服务器（你将没有玩家角色）"),
        ("MP - Client Connect to an active server.", "【MP】客户端连接到活跃的服务器。"),
        ("MP - Host the game.", "【MP】主持游戏。"),
        ("MP - Send a bug report.", "【MP】发送错误报告。"),
        ("MP - Disconnect from server or shutdown server.", "【MP】断开与服务器的连接或关闭服务器。"),
        ("MP dev - set game window resolution", "【MP 开发】设置游戏窗口分辨率"),
        ("MP - dump all fields of a body (for easy health desync debugging)", "【MP】转储身体的所有字段（用于生命值不同步调试）"),
        ("MP - give an item to a player", "【MP】给予玩家一件物品"),
        ("optional", "可选"),
        ("string item_id", "文本 物品 ID"),
        ("string rule", "文本 规则名"),
        ("string name", "文本 用户名"),
        ("string command", "文本 命令"),
        ("string reason", "文本 原因"),
        ("string password", "文本 密码"),
        ("string ip:port", "文本 IP:端口"),
        ("string text", "字符 文本"),
        ("float zoom", "浮点 缩放"),
        ("float time", "浮点 时长"),
        ("float percent", "浮点 百分比"),
        ("int port", "整数 端口"),
        ("SteamId", "SteamID"),
        ("gamemode", "游戏模式"),
        ("password", "密码"),
        ("optional, Who to teleport", "（可选）要传送的玩家"),
        ("optional, name of a player to mess with", "（可选）要操作的玩家名称"),
        ("optional, name of a player to heal", "（可选）要治疗的玩家名称"),
        ("optional, name of a player to addliquid", "（可选）要添加液体的玩家"),
        ("to dumpbodyvars to", "要转储身体变量的玩家"),
        ("to give to", "要给予物品的玩家"),
        ("Item resource ID, multiple is allowed", "物品资源 ID（允许多个）"),
        ("to respawn to", "要重生的玩家"),
        ("delete items", "删除物品"),
        ("the bigger the number, the closer you see", "数值越大，看得越近"),
        ("kick/mutevc/mutetc", "kick踢出、mutevc禁言语音、mutetc禁言文字"),
        ("Command to run if vote is accepted.", "投票通过后要执行的命令。"),
        ("Time for vote. (Default: 10)", "投票时长（默认 : 10）"),
        ("Percentage of votes required. (Default: 50)", "所需投票百分比（默认 : 50）"),
        ("skyColor", "天空颜色"),
        ("rainIntensity", "降雨强度"),
        ("Activate/Deactivate radline", "激活/停用辐射线"),
        ("volume level 0-1", "音量级别 0-1"),
        ("choose strong password", "请选择强密码"),
        ("optional (u dont need password if ur whitelisted)", "可选（已加入白名单则无需密码）"),
        ("new name", "新名称"),
        ("new color", "新颜色"),
        ("tc/vc/all", "tc文字、vc语音、all全部"),
        ("1 for unsafe, 0 for simple", "1=不安全方式、0=简单方式"),
        ("Rule Name", "规则名称"),
        ("New value", "新值"),
        ("Your new name", "你的新用户名"),
        ("Lobby type (2 = public, 1 = friends only, 0 = private)", "大厅类型（2=公开、1=仅好友、0=私人）"),
        ("dedicated", "专用服务器"),
        ("filtered", "已过滤"),
        ("optional, IP and PORT of target server", "（可选）目标服务器的 IP 和端口"),
        ("SteamID or IP or Name", "SteamID 或 IP 或名称"),
        ("message", "消息"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Killed the player.", "已杀死玩家。"),
        ("Killed everyone :) ", "杀死了所有人 :)"),
        ("Healed the player.", "已治疗玩家。"),
        ("Healed everyone.", "已治疗所有人。"),
        ("Reset all player skills.", "已重置所有玩家技能。"),
        ("Started earthquake right now.", "已立即开始地震。"),
        ("No talker was found at cursor.", "光标位置未找到说话者。"),
        ("Chatbox: Reset chatbox location.", "聊天框 : 已重置聊天框位置。"),
        ("Chatbox: SETTING NEW PARAMETERS:", "聊天框 : 设置新参数 : "),
        ("Reset all rules to default.", "已将所有规则恢复为默认值。"),
        ("Set server admin password.", "已设置服务器管理员密码。"),
        ("Disconnect.", "正在断开连接。"),
        ("Local player already has this privilege.", "本地玩家已拥有此权限。"),
        ("Message is invalid.", "消息无效。"),
        ("Thats not a nubmer bro", "这不是一个数字，老哥"),
        ("addliquided everyone.", "已为所有人添加液体。"),
        ("Announced display alert \"", "已广播显示提醒 \""),
        ("Displayed alert \"", "已显示提醒 \""),
        ("Server denied server console access.", "服务器拒绝了服务器控制台访问。"),
        ("Chat message sent: ", "聊天消息已发送 : "),
        ("Patched the console!", "已修补控制台！"),
        ("all og commands: \n", "所有原始命令 : \n"),
        ("Loading debug world", "正在加载调试世界"),
        ("Loading tutorial world", "正在加载教程世界"),
        ("Loading vanilla world", "正在加载原始世界"),
        ("CLIENT: received command from server to enable spectator mode", "客户端 : 收到服务器命令，启用旁观模式"),
        ("Sending command to server: \"", "正在向服务器发送命令 : \""),
        ("SERVER: Invalid chat message.", "服务器 : 聊天消息无效。"),
        ("Network system is already running!", "网络系统已在运行！"),
        ("Network system is not running!", "网络系统未在运行！"),
        ("You can do that only in a Steam lobby!", "只能在 Steam 大厅中进行此操作！"),
        ("Network system is not running or not connected!", "网络系统未运行或未连接！"),
        ("Local player not found!", "未找到本地玩家！"),
        ("Client can't do that.", "客户端无法执行此操作。"),
        ("Server can't do that.", "服务器无法执行此操作。"),
        ("This can only be done in main menu.", "此操作只能在主菜单中完成。"),
        ("Name can only be set in main menu.", "名称只能在主菜单中设置。"),
        ("Password can only be set in main menu.", "房间密码只能在主菜单中设置。"),
        ("Not holding an item in the main hand!", "主手未持有物品！"),
        ("Only available for direct IP connection mode.", "仅适用于直连 IP 模式。"),
        ("Unknown chat type: ", "未知的聊天类型 : "),
        ("Server rule 'sv_cheats' is disabled", "服务器规则「sv_cheats」已禁用"),
        ("Server rule 'AllowClientCheatCommands' is disabled", "服务器规则「AllowClientCheatCommands」已禁用"),
        ("Zoom can't be 0 or your perception of reality will shatter.", "不能为 0，否则你对现实的感知将崩塌。"),
        ("Unknown resource: ", "未知资源 : "),
        ("STEAM: Lobby Created :)", "STEAM : 大厅已创建。"),
        ("Steam: OnLobbyEnter", "Steam : 已进入大厅。"),
        ("STEAM: Lobby Enter Rejected: Lobby does not exist!", "STEAM : 进入大厅被拒绝 : 大厅不存在！"),
        ("Steam: Create Lobby FAILED: No internet connection.", "Steam : 创建大厅失败 : 无网络连接。"),
        ("CREATED LOBBY BUT THERES NO STEAMWORKS TRASNPORT WHAAAAT??!?!?!!??", "已创建大厅，但没有 Steamworks 传输层。什么？？！？！？！！？？"),
        ("I got removed from the lobby. But im the owner!\nAttempting to recreate lobby in a sec...", "我被移出了大厅，但我是房主！\n正在尝试重新创建大厅..."),
        ("I got removed from the lobby.", "你已被移出大厅。"),
        ("LOBBY OWNER LEFT, LEAVING", "大厅房主已离开，正在退出大厅。"),
        ("GameLobbyJoinRequested: Nah, Already in a game.", "收到加入大厅请求 : 当前已在游戏中，无法加入。"),
        ("### STARTING GAME ###", "### 正在开始游戏 ###"),
        ("### STARTING GAME (RECEIVED ANNOUNCEMENT FROM SERVER) ###", "### 正在开始游戏（已收到服务器通知）###"),
        ("Host is starting the tutorial.", "主机正在开始教程。"),
        ("Host is starting game.", "主机正在开始游戏。"),
        ("Received announcement to go to main menu.", "已收到返回主菜单的广播。"),
        ("GenerateWorld_SeedAnnounce, received worldgen seed.", "已收到世界生成种子。"),
        ("Received RegenerateWorld announcement.", "已收到重新生成世界广播。"),
        ("Received RegenerateWorld announcement. (CANCELLING GenerateWorld !!!)", "已收到重新生成世界广播（正在取消世界生成！！！）"),
        ("Went back to main menu because disconnected.", "由于连接已断开，已返回主菜单。"),
        ("Disconnecting because im going to main menu on my own!", "正在断开连接，因为你主动返回主菜单。"),
        ("PLAYER CHARACTER NOT FOUND!!!!!!!!!!!!!!!! RESTART THE GAME! RESTART !!!!!!!!!!!!!!!!!!!!", "未找到玩家角色！！！！！！！！！！！！！！！！请重启游戏！！！！！！！！！！！！！！！！！！！！"),
        ("SetTimeScale: Received SetTimeScale from server.", "时间缩放 : 已收到服务器的时间缩放设置。"),
        ("STEAM: Creating Lobby...", "STEAM : 正在创建大厅..."),
        ("NETWORK SHUTDOWNRESET IS SHUTTING IT !!!!!!!!!!!", "网络正在执行关闭重置！！！！！！！！！！！"),
        ("Disconnected by the user.", "用户已断开连接。"),
        ("WorldGeneration.GenerateWorld", "世界生成 : 开始生成世界"),
        ("WorldGeneration.WorldPlacePlayer", "世界生成 : 放置玩家"),
        ("WorldGeneration.FinishWorldGeneration", "世界生成 : 完成世界生成"),
        ("SCENE CHANGE: Is In World,  No world?", "场景切换 : 进入世界，但没有世界？"),
        ("SCENE CHANGE: Is In Main Menu ", "场景切换 : 进入主菜单"),
        ("LOBBY INFO:", "大厅信息 : "),
        ("WrongVersionNotifier:", "版本不符提示 : "),
        ("!!!!! FAILED TO LOAD GAME FONT !!!!!!!!!", "！！！！！游戏字体加载失败！！！！！！！！！"),
        ("!!!!! animatedgradient FAILED TO LOAD !!!!!!!!!!!!", "！！！！！动画渐变加载失败！！！！！！！！！！！！"),
        ("MainMenuPatcher: Could not find version wanning ui element!", "主菜单补丁 : 找不到版本警告 UI 元素！"),
        ("Received StartGameAnnouncement but theres no PreRunScript, what???", "收到开始游戏广播，但没有 PreRunScript？？？"),
        ("You can't play singleplayer with MP mod active.", "启用 MP 模组时无法游玩单人模式。"),
        ("To play singleplayer go to \"MP Mod Menu > Settings > General > Deactivate Multiplayer Mod\"", "要游玩单人模式，请前往「MP 模组菜单 > 设置 > 通用 > 停用多人联机模组」"),
        ("Or start an empty server.", "或启动一个空服务器。"),
        ("Cheats disabled. Server rule 'sv_cheats' is disabled", "作弊已禁用：服务器规则「sv_cheats」已禁用"),
        ("Cheats disabled. Server rule 'AllowClientCheatCommands' is disabled", "作弊已禁用：服务器规则「AllowClientCheatCommands」已禁用"),
        ("Announcing GoBackToMainMenu.", "正在广播返回主菜单。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("Teleported player to {0}.", "已将玩家传送至 {0}。"),
        ("Teleported: {0} to {1}", "已传送 : {0} 至 {1}"),
        ("Failed to teleport: {0}", "传送失败 : {0}"),
        ("Failed to teleport: {0} {1}", "传送失败 : {0} {1}"),
        ("Gave {0} {1} strength experience.", "给予 {0} {1} 点力量经验。"),
        ("Gave {0} {1} resilience experience.", "给予 {0} {1} 点抗性经验。"),
        ("Gave {0} {1} intelligence experience.", "给予 {0} {1} 点智力经验。"),
        ("Gave the player {0} strength experience.", "已给予玩家 {0} 点力量经验。"),
        ("Gave the player {0} resilience experience.", "已给予玩家 {0} 点韧性经验。"),
        ("Gave the player {0} intelligence experience.", "已给予玩家 {0} 点智力经验。"),
        ("Added {0}mL of {1} to {2} ({3}mL/{4}mL).", "已将 {0}mL 的 {1} 添加到 {2}（{3}mL/{4}mL）。"),
        ("Earthquake active: {0}", "地震已激活 : {0}"),
        ("godmode {0}", "上帝模式 {0}"),
        ("zoom {0} orthographicSize={1} PPU={2}", "缩放 {0} 正交大小={1} PPU={2}"),
        ("Spectator mode: {0}", "旁观模式 : {0}"),
        ("skybg {0} ", "天空背景 {0}"),
        ("snowbg {0} ", "雪景背景 {0}"),
        ("telekinesis {0}", "意念控物 {0}"),
        ("audio_only_on_focus {0}", "仅在聚焦时播放音频 : {0}"),
        ("custom_music_volume {0}", "自定义音乐音量 : {0}"),
        ("Radiation line active: {0}", "辐射线已激活 : {0}"),
        ("Set player count limit to: {0}", "已将玩家数量上限设置为 : {0}"),
        ("Succesfully set rule '{0}' to '{1}'.", "已成功将规则「{0}」设置为「{1}」。"),
        ("Set tile {0} {1} id to {2} ({3})", "已将方块 {0} {1} 的 ID 设置为 {2}（{3}）"),
        ("Set fluid {0} {1} id to {2} ({3})", "已将流体 {0} {1} 的 ID 设置为 {2}（{3}）"),
        ("Rule '{0}' does not exist!", "规则「{0}」不存在！"),
        ("Failed to set rule '{0}': {1}", "设置规则「{0}」失败 : {1}"),
        ("Set vc volume {0} to {1}", "已将 {0} 的语音音量设置为 {1}"),
        ("Player does not exist: {0}", "玩家不存在 : {0}"),
        ("Renamed {0} to {1}", "已将 {0} 重命名为 {1}"),
        ("Rename error: {0}", "重命名错误 : {0}"),
        ("Recolored {0} to {1}", "已将 {0} 重新着色为 {1}"),
        ("Recolor error: {0}", "更改颜色错误 : {0}"),
        ("Set local color to {0}", "已将本地颜色设置为 {0}"),
        ("Hosting Steam Lobby: {0}, {1}", "正在创建 Steam 大厅 : {0}，{1}"),
        ("Starting client and attempting join: {0}", "正在启动客户端并尝试加入 : {0}"),
        ("Starting client and attempting connection: {0}", "正在启动客户端并尝试连接 : {0}"),
        ("Starting Host: {0}", "正在启动主机 : {0}"),
        ("Starting Server: {0}", "正在启动服务器 : {0}"),
        ("Set your username to: {0}", "已将用户名设置为 : {0}"),
        ("Set your password to: {0}", "已将密码设置为 : {0}"),
        ("Chatbox: setting_posX  = {0}%", "聊天框 : X 位置={0}%"),
        ("Chatbox: setting_posY  = {0}%", "聊天框 : Y 位置={0}%"),
        ("Chatbox: setting_sizeX = {0}%", "聊天框 : X 大小={0}%"),
        ("Chatbox: setting_sizeY = {0}%", "聊天框 : Y 大小={0}%"),
        ("Chatbox: setting_scale = {0}%", "聊天框 : 缩放比例={0}%"),
        ("Chat._DEV_ENABLE_PREVIEW = {0}", "聊天预览模式 Chat._DEV_ENABLE_PREVIEW={0}"),
        ("UIMainMenu.SetOpen({0});", "主菜单打开 : {0}"),
        ("Reset all {0} skills.", "已重置 {0} 的所有技能。"),
        ("Cleared inventory: {0}", "已清空物品栏 : {0}"),
        ("Failed to clear inventory: {0}", "清空物品栏失败 : {0}"),
        ("Failed to clear inventory: {0} {1}", "清空物品栏失败 : {0} {1}"),
        ("Respawned: {0}", "已重生 : {0}"),
        ("Failed to respawn: {0}", "重生失败 : {0}"),
        ("Failed to respawn: {0} {1}", "重生失败 : {0} {1}"),
        ("Killed: {0} ", "已杀死 : {0}"),
        ("{0} not found. ", "未找到 {0}"),
        ("Healed: {0}", "已治疗 : {0}"),
        ("Made {0} say \"{1}\"", "已让 {0} 说出「{1}」"),
        ("Failed to make {0} say \"{1}\"", "让 {0} 说出「{1}」失败"),
        ("{0} got the {1}", "{0} 获得了 {1}"),
        ("{0} is not an item.", "{0} 不是一件物品。"),
        ("{0} -> body not found. ", "{0} → 未找到身体。"),
        ("Kicked: {0} - {1}", "已踢出 : {0} - {1}"),
        ("Failed to kick: {0} {1}", "踢出失败 : {0} {1}"),
        ("Banned: {0} - {1}", "已封禁 : {0} - {1}"),
        ("Banned Steam ID: {0} ", "已封禁 Steam ID : {0}"),
        ("Banned IP: {0} ", "已封禁 IP : {0}"),
        ("Failed to Ban: {0} {1}", "封禁失败 : {0} {1}"),
        ("Unbanned: {0}", "已解封 : {0}"),
        ("\"{0}\" was not found in your ban list.", "「{0}」未在你的封禁列表中找到。"),
        ("{0} -> player does not exist", "{0} → 玩家不存在"),
        ("{0} -> it should be \"add\" or  \"remove\"", "{0} → 应为「add」或「remove」"),
        ("{0} - Not holding an item in the main hand!", "{0} - 主手未持有物品！"),
        ("\"{0}\" is not a liquid container!", "「{0}」不是液体容器！"),
        ("\"{0}\" is not a valid liquid id!", "「{0}」不是有效的液体 ID！"),
        ("\"{0}\" is not a valid skill type!", "「{0}」不是有效的技能类型！"),
        ("servermute fail: {0}", "服务器静音失败 : {0}"),
        ("Gave admin privilege to: {0}", "已将管理员权限授予 : {0}"),
        ("Removed admin privilege from: {0}", "已从 {0} 移除管理员权限"),
        ("Requesting admin console: {0}", "正在请求管理员控制台 : {0}"),
        ("DEV : verbose = {0} ", "开发 : 详细日志={0}"),
        ("NetObjectRegistry._DEV_ENABLE_SYNCINFO_SNITCHING = {0} ", "同步信息监控已启用 : {0}"),
        ("BANLIST: {0}\n{1} ", "封禁列表 : {0}\n{1}"),
        ("{0} tried to execute a local-only command: {1}", "{0} 尝试执行本地命令 : {1}"),
        ("{0} tried to execute a banned admin command: {1}", "{0} 尝试执行被禁止的管理员命令 : {1}"),
        ("{0} is a banned admin command.", "{0} 是被禁止的管理员命令。"),
        ("{0} is not a valid boolean value! (true/false)", "{0} 不是有效的真假值！（true/false）"),
        ("{0} is not a valid limb!", "{0} 不是有效的部位！"),
        ("Cheats disabled. {0}", "作弊已禁用 : {0}"),
        ("SAVING TO FILE: {0}", "正在保存到文件 : {0}"),
        ("Steamworks initialized!\n{0} - {1}", "Steamworks 已初始化！\n{0} - {1}"),
        ("FAILED TO INIT STEAM:\n{0}", "Steam 初始化失败 : \n{0}"),
        ("OnLobbyEnter failed! response: {0}", "加入大厅失败！响应 : {0}"),
        ("STEAM: Lobby Enter Rejected: {0}", "STEAM : 进入大厅被拒绝 : {0}"),
        ("Steam: Create Lobby FAILED: {0}", "Steam : 创建大厅失败 : {0}"),
        ("STEAM: OnLobbyCreated encountered an IOFailure due to: {0}", "STEAM : 创建大厅时发生 IO 失败 : {0}"),
        ("STEAM: Kicked: {0}", "Steam : 已被踢出 : {0}"),
        ("GameLobbyJoinRequested: lobbyID:{0}", "收到加入大厅请求 : lobbyID : {0}"),
        ("SERVER: REQUEST FROM {0} TO TryExecuteCommand \n{1}", "服务器 : {0} 请求执行命令 \n{1}"),
        ("User pressed Create Lobby! {0} -> {1}", "用户点击创建大厅 : {0} → {1}"),
        ("STEAM: LeaveLobby called! lobbyID:{0}", "STEAM : 已调用离开大厅，lobbyID : {0}"),
        ("STEAM: LeaveLobby called! lobbyID:{0} - STACK: {1}", "STEAM : 已调用离开大厅！lobbyID : {0} - 堆栈 : {1}"),
        ("Lang: Failed to get {0} translation for \"{1}\"", "语言 : 未找到 {0} 翻译 : 「{1}」"),
        ("Lang: Failed to get {0} translation for \"{1}\" -> OG: \"{2}\"", "语言 : 未找到 {0} 翻译 : 「{1}」 -> 原文 : 「{2}」"),
        ("SCENE CHANGE: Is In World,  Layer: {0}", "场景切换 : 进入世界，层级 : {0}"),
        ("rgblights {0}", "RGB 灯光 : {0}"),
        ("Earthquake active: {0}", "地震已激活 : {0}"),
        ("{0}.mute_vc = {1}", "已设置 {0} 的语音静音 : {1}"),
        ("{0}.mute_tc = {1}", "已设置 {0} 的聊天静音 : {1}"),
        ("Gamemode \"{0}\" was not found.", "未找到游戏模式「{0}」。"),
        ("{0} -> it should be \"add\" or  \"remove\"", "{0} → 参数应为「add」或「remove」"),
        ("[<color=red>ADMIN</color>] {0} executes \"{1}\"", "[<color=red>管理员</color>] {0} 执行了「{1}」"),
        ("[<color=red>ADMIN</color>] {0} <color=green><b>ENTERS</b></color> server console! (Entered correct password)", "[<color=red>管理员</color>] {0} <color=green><b>进入</b></color>服务器控制台！（已输入正确密码）"),
        ("[<color=red>ADMIN</color>] {0} <color=green><b>ENTERS</b></color> server console!", "[<color=red>管理员</color>] {0} <color=green><b>进入</b></color>服务器控制台！"),
        ("[<color=red>ADMIN</color>] {0} <color=red><b>EXITS</b></color> server console!", "[<color=red>管理员</color>] {0} <color=red><b>退出</b></color>服务器控制台！"),
        ("AED CHARGE for {0} -> {1}: ran out of battery", "AED 充电（{0} → {1}） : 电池耗尽"),
        ("{0} CANCELLED AED ???", "{0} 取消了 AED？？？"),
        ("Denied amputation cutting for {0} -> {1}", "已拒绝 {0}（{1}）的截肢切割"),
        ("MANUALDEFIB CHARGE for {0} -> {1}: ran out of battery", "手动除颤充电（{0} → {1}） : 电池耗尽"),
        ("DrillPod:  Local player tries to use DrillPod but not everyone is inside. count: {0}/{1}", "钻舱 : 本地玩家尝试使用钻舱，但并非所有人都已进入。人数 : {0}/{1}"),
        ("{0}.CreateServerSocket : Socket already exists !!!!!!!!! {1}", "{0} 的 CreateServerSocket : Socket 已存在 ！！！！！！！！！！！！ {1}"),
        ("{0}.CreateClientSocket : Socket already exists !!!!!!!!! {1}", "{0} 的 CreateClientSocket : Socket 已存在 ！！！！！！！！！！！！ {1}"),
        ("{0}.CreateClientSocket : Client could not be started !! {1}", "{0} 的 CreateClientSocket : 客户端无法启动 ！！ {1}"),
        ("Steam is not loaded!", "Steam 尚未加载！"),
        ("STEAM: IsInitialized is false!", "STEAM : IsInitialized 为 false！"),
        ("Invalid Server name.", "服务器名称无效。"),
        ("Steam: Connection closed: {0}", "Steam : 连接已关闭 : {0}"),
        ("Lobby member {0} timed out!", "大厅成员 {0} 已超时！"),
        ("{0}: Accepted connection for: {1}  color:{2}", "{0} : 已接受 {1} 的连接，颜色 : {2}"),
        ("Tried to kick {0} as a non-host????", "尝试以非主机身份踢出 {0}？？？？"),
    };
    public static readonly (string En, string Zh)[] Prefixes =
    {
        ("<color=red>KrokMP ERROR: ", "<color=red>KrokMP 错误 : "),
        ("<color=yellow>KrokMP WARN: ", "<color=yellow>KrokMP 警告 : "),
        ("Multiplayer ERROR: ", "多人联机错误 : "),
        ("Multiplayer: ", "多人联机 : "),
        ("[<color=red>SERVER</color>] ", "[<color=red>服务器</color>] "),
    };
    public static readonly (string En, string Zh)[] Credits =
    {
        ("Krokosha666 - OG MP Mod Developer, owner", "Krokosha666 - MP 模组原作者，所有者"),
        ("Creature - MP Mod Developer", "Creature - MP 模组开发者"),
        ("dannad - Auto-updater module, Installer tool, C:T ds Staff", "dannad - 自动更新模块、安装工具，C:T ds 员工"),
        ("Gary the cat - playtester, Bug report module, past servers, C:T ds Staff", "Gary the cat - 测试玩家、错误报告模块、前服务器，C:T ds 员工"),
        ("Todd - external mod \"ChangeSkin\", C:T ds Staff", "Todd - 外部模组“ChangeSkin”，C:T ds 员工"),
        ("ItsVoidSK - playtester, some sprites", "ItsVoidSK - 测试玩家、部分精灵"),
        ("dawn - TimeManipulation patch", "dawn - 时间操控补丁"),
        ("Jilu-tin - playtester", "Jilu-tin - 测试玩家"),
        ("NyaruQwQ - playtester", "NyaruQwQ - 测试玩家"),
        ("X0men0X - playtester", "X0men0X - 测试玩家"),
        ("{Pixel} - playtester", "{Pixel} - 测试玩家"),
        ("avr - playtester", "avr - 测试玩家"),
        ("gordocats - self-heal sprite", "gordocats - 自愈精灵"),
        ("notamoron - playtester", "notamoron - 测试玩家"),
        ("Devactor - playtester", "Devactor - 测试玩家"),
        ("Dictator - playtester", "Dictator - 测试玩家"),
        ("Мрак 2.0 - playtester", "Мрак 2.0 - 测试玩家"),
        ("Dmonya - playtester", "Dmonya - 测试玩家"),
        ("Shiro - playtester", "Shiro - 测试玩家"),
        ("Charu - playtester", "Charu - 测试玩家"),
        ("kipish - playtester", "kipish - 测试玩家"),
        ("Orsoniks - Developer of Casualties: Unknown", "Orsoniks - 《未知伤亡》开发者"),
        ("...and the rest of bug reporters, suggestions and regular players", "...以及其余的 bug 报告者、建议者和普通玩家"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("MP", "【MP】"),
        ("MP dev", "【MP 开发】"),
        ("string", "文本"),
        ("bool", "真假"),
        ("float", "浮点"),
        ("int", "整数"),
        ("color", "颜色"),
        ("action", "操作"),
        ("type", "类型"),
        ("user", "用户"),
        ("value", "值"),
        ("arg", "参数"),
        ("Title", "标题"),
        ("Text", "文本"),
        ("netId", "netId"),
        ("X pos", "X 位置"),
        ("Y pos", "Y 位置"),
        ("X size", "X 尺寸"),
        ("Y size", "Y 尺寸"),
        ("scale", "缩放比例"),
        ("Action", "操作"),
    };
}
