internal static class KrokMPTrTw
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("MP- force to show and log all chat messages", "【MP】強制顯示並記錄所有聊天消息"),
        ("MP - Hijack object's Talker component.", "【MP】劫持目標物體的 Talker 組件。"),
        ("MP - control earthquake", "【MP】控制地震"),
        ("DELETEME", "【MP】刪除我"),
        ("MP - respawn a player", "【MP】重生一名玩家"),
        ("MP - clear inventory of a player", "【MP】清空一名玩家的物品欄"),
        ("MP - revive every player and keep resetting their health", "【MP】復活所有玩家並持續重置其生命值"),
        ("MP - zoom camera", "【MP】縮放視角"),
        ("MP - spectator mode", "【MP】旁觀模式"),
        ("MP- Call a vote.", "【MP】發起投票。"),
        ("MP-SERVER- Call a custom vote.", "【MP 服務器】發起自定義投票。"),
        ("MP-SERVER- Forcefully disconnect player.", "【MP 服務器】強制斷開玩家連接。"),
        ("MP-SERVER- Ban player.", "【MP 服務器】封禁玩家。"),
        ("MP-SERVER- IP Ban player. (Non-steam only)", "【MP 服務器】IP 封禁玩家。（僅限非 Steam 連接）"),
        ("MP- Show all players you've banned. Local.", "【MP】顯示你已封禁的所有玩家（本地）。"),
        ("MP- Remove a player from your ban list.", "【MP】將玩家從封禁列表中移除。"),
        ("MP - say something in chat", "【MP】在聊天中發送消息"),
        ("MP - Activate/Deactivate radline", "【MP】激活/停用輻射線"),
        ("MP - vc test", "【MP】語音聊天測試"),
        ("MP - mute or change volume of a specific player, local", "【MP】靜音或調整特定玩家的語音音量（本地）"),
        ("MP-SERVER- force reload all custom music right now", "【MP 服務器】立即強制重新加載所有自定義音樂"),
        ("MP-SERVER- set admin password (ANYONE CAN USE THIS PASSWORD)", "【MP 服務器】設置管理員密碼（任何人都可使用此密碼）"),
        ("MP-SERVER- give or remove admin privileges", "【MP 服務器】授予或移除管理員權限"),
        ("MP-CLIENT- toggle admin mode, run commands on the server and see its log", "【MP 客戶端】切換管理員模式，在服務器上執行命令並查看其日誌"),
        ("MP- delete blast marks, block damages, casings, blood", "【MP】清除爆炸痕跡、方塊損壞、彈殼和血跡"),
        ("MP-SERVER- force rename a player", "【MP 服務器】強制重命名玩家"),
        ("MP-SERVER- force recolor a player", "【MP 服務器】強制更改玩家顏色"),
        ("MP - dump locale of multiplayer mod", "【MP】轉儲多人模組的本地化數據"),
        ("MP dev - Enable verbose logging and debug screens", "【MP 開發】啟用詳細日誌記錄和調試畫面"),
        ("MP dev - Show debug sync info on objects. (DEPRECATED)", "【MP 開發】顯示物體的調試同步信息（已廢棄）"),
        ("MP-SERVER- mute player chat or voice", "【MP 服務器】禁言玩家文字聊天或語音"),
        ("MP dev - Queue force-sync for a object netId", "【MP 開發】對指定 netId 對象排隊強制同步"),
        ("MP dev - Unregister all objects. (IT CAN CAUSE MORE DESYNC)", "【MP 開發】註銷所有對象（可能導致更多不同步）"),
        ("MP dev - Register all objects in the world. (IT LAGS !!!!!)", "【MP 開發】註冊世界中所有對象（會導致卡頓！！！！！）"),
        ("MP - SERVER - Set player limit", "【MP 服務器】設置玩家數量上限"),
        ("MP - set position and size of chat box (everything is a scale in float (0-1)) (OBSOLETE)", "【MP】設置聊天框的位置和大小（所有參數為 0-1 浮點比例）（已廢棄）"),
        ("MP dev - toggle chat text preview (OBSOLETE)", "【MP 開發】切換聊天文字預覽（已廢棄）"),
        ("MP - go to main menu", "【MP】返回主菜單"),
        ("MP - show all multiplayer game rules", "【MP】顯示所有多人遊戲規則"),
        ("MP - reset all multiplayer game rules to default values", "【MP】將所有多人遊戲規則重置為默認值"),
        ("MP - set multiplayer game rule", "【MP】設置多人遊戲規則"),
        ("MP - Set your multiplayer username.", "【MP】設置你的多人聯機用戶名。"),
        ("MP - Set your multiplayer password.", "【MP】設置房間加入密碼。"),
        ("MP - Client Connect to an active steam lobby.", "【MP】客戶端連接到活躍的 Steam 大廳。"),
        ("MP - Host steam lobby.", "【MP】創建 Steam 大廳。"),
        ("MP - Log info about your steam lobby.", "【MP】記錄 Steam 大廳信息。"),
        ("MP - Start a dedicated server. (you'll have no player character)", "【MP】啟動專用服務器（你將沒有玩家角色）"),
        ("MP - Client Connect to an active server.", "【MP】客戶端連接到活躍的服務器。"),
        ("MP - Host the game.", "【MP】主持遊戲。"),
        ("MP - Send a bug report.", "【MP】發送錯誤報告。"),
        ("MP - Disconnect from server or shutdown server.", "【MP】斷開與服務器的連接或關閉服務器。"),
        ("MP dev - set game window resolution", "【MP 開發】設置遊戲窗口分辨率"),
        ("MP - dump all fields of a body (for easy health desync debugging)", "【MP】轉儲身體的所有字段（用於生命值不同步調試）"),
        ("MP - give an item to a player", "【MP】給予玩家一件物品"),
        ("optional", "可選"),
        ("string item_id", "文本 物品 ID"),
        ("string rule", "文本 規則名"),
        ("string name", "文本 用戶名"),
        ("string command", "文本 命令"),
        ("string reason", "文本 原因"),
        ("string password", "文本 密碼"),
        ("string ip:port", "文本 IP:端口"),
        ("string text", "字符 文本"),
        ("float zoom", "浮點 縮放"),
        ("float time", "浮點 時長"),
        ("float percent", "浮點 百分比"),
        ("int port", "整數 端口"),
        ("SteamId", "SteamID"),
        ("gamemode", "遊戲模式"),
        ("password", "密碼"),
        ("optional, Who to teleport", "（可選）要傳送的玩家"),
        ("optional, name of a player to mess with", "（可選）要操作的玩家名稱"),
        ("optional, name of a player to heal", "（可選）要治療的玩家名稱"),
        ("optional, name of a player to addliquid", "（可選）要添加液體的玩家"),
        ("to dumpbodyvars to", "要轉儲身體變量的玩家"),
        ("to give to", "要給予物品的玩家"),
        ("Item resource ID, multiple is allowed", "物品資源 ID（允許多個）"),
        ("to respawn to", "要重生的玩家"),
        ("delete items", "刪除物品"),
        ("the bigger the number, the closer you see", "數值越大，看得越近"),
        ("kick/mutevc/mutetc", "kick踢出、mutevc禁言語音、mutetc禁言文字"),
        ("Command to run if vote is accepted.", "投票通過後要執行的命令。"),
        ("Time for vote. (Default: 10)", "投票時長（默認 : 10）"),
        ("Percentage of votes required. (Default: 50)", "所需投票百分比（默認 : 50）"),
        ("skyColor", "天空顏色"),
        ("rainIntensity", "降雨強度"),
        ("Activate/Deactivate radline", "激活/停用輻射線"),
        ("volume level 0-1", "音量級別 0-1"),
        ("choose strong password", "請選擇強密碼"),
        ("optional (u dont need password if ur whitelisted)", "可選（已加入白名單則無需密碼）"),
        ("new name", "新名稱"),
        ("new color", "新顏色"),
        ("tc/vc/all", "tc文字、vc語音、all全部"),
        ("1 for unsafe, 0 for simple", "1=不安全方式、0=簡單方式"),
        ("Rule Name", "規則名稱"),
        ("New value", "新值"),
        ("Your new name", "你的新用戶名"),
        ("Lobby type (2 = public, 1 = friends only, 0 = private)", "大廳類型（2=公開、1=僅好友、0=私人）"),
        ("dedicated", "專用服務器"),
        ("filtered", "已過濾"),
        ("optional, IP and PORT of target server", "（可選）目標服務器的 IP 和端口"),
        ("SteamID or IP or Name", "SteamID 或 IP 或名稱"),
        ("message", "消息"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("Killed the player.", "已殺死玩家。"),
        ("Killed everyone :) ", "殺死了所有人 :)"),
        ("Healed the player.", "已治療玩家。"),
        ("Healed everyone.", "已治療所有人。"),
        ("Reset all player skills.", "已重置所有玩家技能。"),
        ("Started earthquake right now.", "已立即開始地震。"),
        ("No talker was found at cursor.", "光標位置未找到說話者。"),
        ("Chatbox: Reset chatbox location.", "聊天框 : 已重置聊天框位置。"),
        ("Chatbox: SETTING NEW PARAMETERS:", "聊天框 : 設置新參數 : "),
        ("Reset all rules to default.", "已將所有規則恢復為默認值。"),
        ("Set server admin password.", "已設置服務器管理員密碼。"),
        ("Disconnect.", "正在斷開連接。"),
        ("Local player already has this privilege.", "本地玩家已擁有此權限。"),
        ("Message is invalid.", "消息無效。"),
        ("Thats not a nubmer bro", "這不是一個數字，老哥"),
        ("addliquided everyone.", "已為所有人添加液體。"),
        ("Announced display alert \"", "已廣播顯示提醒 \""),
        ("Displayed alert \"", "已顯示提醒 \""),
        ("Server denied server console access.", "服務器拒絕了服務器控制檯訪問。"),
        ("Chat message sent: ", "聊天消息已發送 : "),
        ("Patched the console!", "已修補控制檯！"),
        ("all og commands: \n", "所有原始命令 : \n"),
        ("Loading debug world", "正在加載調試世界"),
        ("Loading tutorial world", "正在加載教程世界"),
        ("Loading vanilla world", "正在加載原始世界"),
        ("CLIENT: received command from server to enable spectator mode", "客戶端 : 收到服務器命令，啟用旁觀模式"),
        ("Sending command to server: \"", "正在向服務器發送命令 : \""),
        ("SERVER: Invalid chat message.", "服務器 : 聊天消息無效。"),
        ("Network system is already running!", "網絡系統已在運行！"),
        ("Network system is not running!", "網絡系統未在運行！"),
        ("You can do that only in a Steam lobby!", "只能在 Steam 大廳中進行此操作！"),
        ("Network system is not running or not connected!", "網絡系統未運行或未連接！"),
        ("Local player not found!", "未找到本地玩家！"),
        ("Client can't do that.", "客戶端無法執行此操作。"),
        ("Server can't do that.", "服務器無法執行此操作。"),
        ("This can only be done in main menu.", "此操作只能在主菜單中完成。"),
        ("Name can only be set in main menu.", "名稱只能在主菜單中設置。"),
        ("Password can only be set in main menu.", "房間密碼只能在主菜單中設置。"),
        ("Not holding an item in the main hand!", "主手未持有物品！"),
        ("Only available for direct IP connection mode.", "僅適用於直連 IP 模式。"),
        ("Unknown chat type: ", "未知的聊天類型 : "),
        ("Server rule 'sv_cheats' is disabled", "服務器規則「sv_cheats」已禁用"),
        ("Server rule 'AllowClientCheatCommands' is disabled", "服務器規則「AllowClientCheatCommands」已禁用"),
        ("Zoom can't be 0 or your perception of reality will shatter.", "不能為 0，否則你對現實的感知將崩塌。"),
        ("Unknown resource: ", "未知資源 : "),
        ("STEAM: Lobby Created :)", "STEAM : 大廳已創建。"),
        ("Steam: OnLobbyEnter", "Steam : 已進入大廳。"),
        ("STEAM: Lobby Enter Rejected: Lobby does not exist!", "STEAM : 進入大廳被拒絕 : 大廳不存在！"),
        ("Steam: Create Lobby FAILED: No internet connection.", "Steam : 創建大廳失敗 : 無網絡連接。"),
        ("CREATED LOBBY BUT THERES NO STEAMWORKS TRASNPORT WHAAAAT??!?!?!!??", "已創建大廳，但沒有 Steamworks 傳輸層。什麼？？！？！？！！？？"),
        ("I got removed from the lobby. But im the owner!\nAttempting to recreate lobby in a sec...", "我被移出了大廳，但我是房主！\n正在嘗試重新創建大廳..."),
        ("I got removed from the lobby.", "你已被移出大廳。"),
        ("LOBBY OWNER LEFT, LEAVING", "大廳房主已離開，正在退出大廳。"),
        ("GameLobbyJoinRequested: Nah, Already in a game.", "收到加入大廳請求 : 當前已在遊戲中，無法加入。"),
        ("### STARTING GAME ###", "### 正在開始遊戲 ###"),
        ("### STARTING GAME (RECEIVED ANNOUNCEMENT FROM SERVER) ###", "### 正在開始遊戲（已收到服務器通知）###"),
        ("Host is starting the tutorial.", "主機正在開始教程。"),
        ("Host is starting game.", "主機正在開始遊戲。"),
        ("Received announcement to go to main menu.", "已收到返回主菜單的廣播。"),
        ("GenerateWorld_SeedAnnounce, received worldgen seed.", "已收到世界生成種子。"),
        ("Received RegenerateWorld announcement.", "已收到重新生成世界廣播。"),
        ("Received RegenerateWorld announcement. (CANCELLING GenerateWorld !!!)", "已收到重新生成世界廣播（正在取消世界生成！！！）"),
        ("Went back to main menu because disconnected.", "由於連接已斷開，已返回主菜單。"),
        ("Disconnecting because im going to main menu on my own!", "正在斷開連接，因為你主動返回主菜單。"),
        ("PLAYER CHARACTER NOT FOUND!!!!!!!!!!!!!!!! RESTART THE GAME! RESTART !!!!!!!!!!!!!!!!!!!!", "未找到玩家角色！！！！！！！！！！！！！！！！請重啟遊戲！！！！！！！！！！！！！！！！！！！！"),
        ("SetTimeScale: Received SetTimeScale from server.", "時間縮放 : 已收到服務器的時間縮放設置。"),
        ("STEAM: Creating Lobby...", "STEAM : 正在創建大廳..."),
        ("NETWORK SHUTDOWNRESET IS SHUTTING IT !!!!!!!!!!!", "網絡正在執行關閉重置！！！！！！！！！！！"),
        ("Disconnected by the user.", "用戶已斷開連接。"),
        ("WorldGeneration.GenerateWorld", "世界生成 : 開始生成世界"),
        ("WorldGeneration.WorldPlacePlayer", "世界生成 : 放置玩家"),
        ("WorldGeneration.FinishWorldGeneration", "世界生成 : 完成世界生成"),
        ("SCENE CHANGE: Is In World,  No world?", "場景切換 : 進入世界，但沒有世界？"),
        ("SCENE CHANGE: Is In Main Menu ", "場景切換 : 進入主菜單"),
        ("LOBBY INFO:", "大廳信息 : "),
        ("WrongVersionNotifier:", "版本不符提示 : "),
        ("!!!!! FAILED TO LOAD GAME FONT !!!!!!!!!", "！！！！！遊戲字體加載失敗！！！！！！！！！"),
        ("!!!!! animatedgradient FAILED TO LOAD !!!!!!!!!!!!", "！！！！！動畫漸變加載失敗！！！！！！！！！！！！"),
        ("MainMenuPatcher: Could not find version wanning ui element!", "主菜單補丁 : 找不到版本警告 UI 元素！"),
        ("Received StartGameAnnouncement but theres no PreRunScript, what???", "收到開始遊戲廣播，但沒有 PreRunScript？？？"),
        ("You can't play singleplayer with MP mod active.", "啟用 MP 模組時無法遊玩單人模式。"),
        ("To play singleplayer go to \"MP Mod Menu > Settings > General > Deactivate Multiplayer Mod\"", "要遊玩單人模式，請前往「MP 模組菜單 > 設置 > 通用 > 停用多人聯機模組」"),
        ("Or start an empty server.", "或啟動一個空服務器。"),
        ("Cheats disabled. Server rule 'sv_cheats' is disabled", "作弊已禁用：服務器規則「sv_cheats」已禁用"),
        ("Cheats disabled. Server rule 'AllowClientCheatCommands' is disabled", "作弊已禁用：服務器規則「AllowClientCheatCommands」已禁用"),
        ("Announcing GoBackToMainMenu.", "正在廣播返回主菜單。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("Teleported player to {0}.", "已將玩家傳送至 {0}。"),
        ("Teleported: {0} to {1}", "已傳送 : {0} 至 {1}"),
        ("Failed to teleport: {0}", "傳送失敗 : {0}"),
        ("Failed to teleport: {0} {1}", "傳送失敗 : {0} {1}"),
        ("Gave {0} {1} strength experience.", "給予 {0} {1} 點力量經驗。"),
        ("Gave {0} {1} resilience experience.", "給予 {0} {1} 點抗性經驗。"),
        ("Gave {0} {1} intelligence experience.", "給予 {0} {1} 點智力經驗。"),
        ("Gave the player {0} strength experience.", "已給予玩家 {0} 點力量經驗。"),
        ("Gave the player {0} resilience experience.", "已給予玩家 {0} 點韌性經驗。"),
        ("Gave the player {0} intelligence experience.", "已給予玩家 {0} 點智力經驗。"),
        ("Added {0}mL of {1} to {2} ({3}mL/{4}mL).", "已將 {0}mL 的 {1} 添加到 {2}（{3}mL/{4}mL）。"),
        ("Earthquake active: {0}", "地震已激活 : {0}"),
        ("godmode {0}", "上帝模式 {0}"),
        ("zoom {0} orthographicSize={1} PPU={2}", "縮放 {0} 正交大小={1} PPU={2}"),
        ("Spectator mode: {0}", "旁觀模式 : {0}"),
        ("skybg {0} ", "天空背景 {0}"),
        ("snowbg {0} ", "雪景背景 {0}"),
        ("telekinesis {0}", "意念控物 {0}"),
        ("audio_only_on_focus {0}", "僅在聚焦時播放音頻 : {0}"),
        ("custom_music_volume {0}", "自定義音樂音量 : {0}"),
        ("Radiation line active: {0}", "輻射線已激活 : {0}"),
        ("Set player count limit to: {0}", "已將玩家數量上限設置為 : {0}"),
        ("Succesfully set rule '{0}' to '{1}'.", "已成功將規則「{0}」設置為「{1}」。"),
        ("Set tile {0} {1} id to {2} ({3})", "已將方塊 {0} {1} 的 ID 設置為 {2}（{3}）"),
        ("Set fluid {0} {1} id to {2} ({3})", "已將流體 {0} {1} 的 ID 設置為 {2}（{3}）"),
        ("Rule '{0}' does not exist!", "規則「{0}」不存在！"),
        ("Failed to set rule '{0}': {1}", "設置規則「{0}」失敗 : {1}"),
        ("Set vc volume {0} to {1}", "已將 {0} 的語音音量設置為 {1}"),
        ("Player does not exist: {0}", "玩家不存在 : {0}"),
        ("Renamed {0} to {1}", "已將 {0} 重命名為 {1}"),
        ("Rename error: {0}", "重命名錯誤 : {0}"),
        ("Recolored {0} to {1}", "已將 {0} 重新著色為 {1}"),
        ("Recolor error: {0}", "更改顏色錯誤 : {0}"),
        ("Set local color to {0}", "已將本地顏色設置為 {0}"),
        ("Hosting Steam Lobby: {0}, {1}", "正在創建 Steam 大廳 : {0}，{1}"),
        ("Starting client and attempting join: {0}", "正在啟動客戶端並嘗試加入 : {0}"),
        ("Starting client and attempting connection: {0}", "正在啟動客戶端並嘗試連接 : {0}"),
        ("Starting Host: {0}", "正在啟動主機 : {0}"),
        ("Starting Server: {0}", "正在啟動服務器 : {0}"),
        ("Set your username to: {0}", "已將用戶名設置為 : {0}"),
        ("Set your password to: {0}", "已將密碼設置為 : {0}"),
        ("Chatbox: setting_posX  = {0}%", "聊天框 : X 位置={0}%"),
        ("Chatbox: setting_posY  = {0}%", "聊天框 : Y 位置={0}%"),
        ("Chatbox: setting_sizeX = {0}%", "聊天框 : X 大小={0}%"),
        ("Chatbox: setting_sizeY = {0}%", "聊天框 : Y 大小={0}%"),
        ("Chatbox: setting_scale = {0}%", "聊天框 : 縮放比例={0}%"),
        ("Chat._DEV_ENABLE_PREVIEW = {0}", "聊天預覽模式 Chat._DEV_ENABLE_PREVIEW={0}"),
        ("UIMainMenu.SetOpen({0});", "主菜單打開 : {0}"),
        ("Reset all {0} skills.", "已重置 {0} 的所有技能。"),
        ("Cleared inventory: {0}", "已清空物品欄 : {0}"),
        ("Failed to clear inventory: {0}", "清空物品欄失敗 : {0}"),
        ("Failed to clear inventory: {0} {1}", "清空物品欄失敗 : {0} {1}"),
        ("Respawned: {0}", "已重生 : {0}"),
        ("Failed to respawn: {0}", "重生失敗 : {0}"),
        ("Failed to respawn: {0} {1}", "重生失敗 : {0} {1}"),
        ("Killed: {0} ", "已殺死 : {0}"),
        ("{0} not found. ", "未找到 {0}"),
        ("Healed: {0}", "已治療 : {0}"),
        ("Made {0} say \"{1}\"", "已讓 {0} 說出「{1}」"),
        ("Failed to make {0} say \"{1}\"", "讓 {0} 說出「{1}」失敗"),
        ("{0} got the {1}", "{0} 獲得了 {1}"),
        ("{0} is not an item.", "{0} 不是一件物品。"),
        ("{0} -> body not found. ", "{0} → 未找到身體。"),
        ("Kicked: {0} - {1}", "已踢出 : {0} - {1}"),
        ("Failed to kick: {0} {1}", "踢出失敗 : {0} {1}"),
        ("Banned: {0} - {1}", "已封禁 : {0} - {1}"),
        ("Banned Steam ID: {0} ", "已封禁 Steam ID : {0}"),
        ("Banned IP: {0} ", "已封禁 IP : {0}"),
        ("Failed to Ban: {0} {1}", "封禁失敗 : {0} {1}"),
        ("Unbanned: {0}", "已解封 : {0}"),
        ("\"{0}\" was not found in your ban list.", "「{0}」未在你的封禁列表中找到。"),
        ("{0} -> player does not exist", "{0} → 玩家不存在"),
        ("{0} -> it should be \"add\" or  \"remove\"", "{0} → 應為「add」或「remove」"),
        ("{0} - Not holding an item in the main hand!", "{0} - 主手未持有物品！"),
        ("\"{0}\" is not a liquid container!", "「{0}」不是液體容器！"),
        ("\"{0}\" is not a valid liquid id!", "「{0}」不是有效的液體 ID！"),
        ("\"{0}\" is not a valid skill type!", "「{0}」不是有效的技能類型！"),
        ("servermute fail: {0}", "服務器靜音失敗 : {0}"),
        ("Gave admin privilege to: {0}", "已將管理員權限授予 : {0}"),
        ("Removed admin privilege from: {0}", "已從 {0} 移除管理員權限"),
        ("Requesting admin console: {0}", "正在請求管理員控制檯 : {0}"),
        ("DEV : verbose = {0} ", "開發 : 詳細日誌={0}"),
        ("NetObjectRegistry._DEV_ENABLE_SYNCINFO_SNITCHING = {0} ", "同步信息監控已啟用 : {0}"),
        ("BANLIST: {0}\n{1} ", "封禁列表 : {0}\n{1}"),
        ("{0} tried to execute a local-only command: {1}", "{0} 嘗試執行本地命令 : {1}"),
        ("{0} tried to execute a banned admin command: {1}", "{0} 嘗試執行被禁止的管理員命令 : {1}"),
        ("{0} is a banned admin command.", "{0} 是被禁止的管理員命令。"),
        ("{0} is not a valid boolean value! (true/false)", "{0} 不是有效的真假值！（true/false）"),
        ("{0} is not a valid limb!", "{0} 不是有效的部位！"),
        ("Cheats disabled. {0}", "作弊已禁用 : {0}"),
        ("SAVING TO FILE: {0}", "正在保存到文件 : {0}"),
        ("Steamworks initialized!\n{0} - {1}", "Steamworks 已初始化！\n{0} - {1}"),
        ("FAILED TO INIT STEAM:\n{0}", "Steam 初始化失敗 : \n{0}"),
        ("OnLobbyEnter failed! response: {0}", "加入大廳失敗！響應 : {0}"),
        ("STEAM: Lobby Enter Rejected: {0}", "STEAM : 進入大廳被拒絕 : {0}"),
        ("Steam: Create Lobby FAILED: {0}", "Steam : 創建大廳失敗 : {0}"),
        ("STEAM: OnLobbyCreated encountered an IOFailure due to: {0}", "STEAM : 創建大廳時發生 IO 失敗 : {0}"),
        ("STEAM: Kicked: {0}", "Steam : 已被踢出 : {0}"),
        ("GameLobbyJoinRequested: lobbyID:{0}", "收到加入大廳請求 : lobbyID : {0}"),
        ("SERVER: REQUEST FROM {0} TO TryExecuteCommand \n{1}", "服務器 : {0} 請求執行命令 \n{1}"),
        ("User pressed Create Lobby! {0} -> {1}", "用戶點擊創建大廳 : {0} → {1}"),
        ("STEAM: LeaveLobby called! lobbyID:{0}", "STEAM : 已調用離開大廳，lobbyID : {0}"),
        ("STEAM: LeaveLobby called! lobbyID:{0} - STACK: {1}", "STEAM : 已調用離開大廳！lobbyID : {0} - 堆棧 : {1}"),
        ("Lang: Failed to get {0} translation for \"{1}\"", "語言 : 未找到 {0} 翻譯 : 「{1}」"),
        ("Lang: Failed to get {0} translation for \"{1}\" -> OG: \"{2}\"", "語言 : 未找到 {0} 翻譯 : 「{1}」 -> 原文 : 「{2}」"),
        ("SCENE CHANGE: Is In World,  Layer: {0}", "場景切換 : 進入世界，層級 : {0}"),
        ("rgblights {0}", "RGB 燈光 : {0}"),
        ("Earthquake active: {0}", "地震已激活 : {0}"),
        ("{0}.mute_vc = {1}", "已設置 {0} 的語音靜音 : {1}"),
        ("{0}.mute_tc = {1}", "已設置 {0} 的聊天靜音 : {1}"),
        ("Gamemode \"{0}\" was not found.", "未找到遊戲模式「{0}」。"),
        ("{0} -> it should be \"add\" or  \"remove\"", "{0} → 參數應為「add」或「remove」"),
        ("[<color=red>ADMIN</color>] {0} executes \"{1}\"", "[<color=red>管理員</color>] {0} 執行了「{1}」"),
        ("[<color=red>ADMIN</color>] {0} <color=green><b>ENTERS</b></color> server console! (Entered correct password)", "[<color=red>管理員</color>] {0} <color=green><b>進入</b></color>服務器控制檯！（已輸入正確密碼）"),
        ("[<color=red>ADMIN</color>] {0} <color=green><b>ENTERS</b></color> server console!", "[<color=red>管理員</color>] {0} <color=green><b>進入</b></color>服務器控制檯！"),
        ("[<color=red>ADMIN</color>] {0} <color=red><b>EXITS</b></color> server console!", "[<color=red>管理員</color>] {0} <color=red><b>退出</b></color>服務器控制檯！"),
        ("AED CHARGE for {0} -> {1}: ran out of battery", "AED 充電（{0} → {1}） : 電池耗盡"),
        ("{0} CANCELLED AED ???", "{0} 取消了 AED？？？"),
        ("Denied amputation cutting for {0} -> {1}", "已拒絕 {0}（{1}）的截肢切割"),
        ("MANUALDEFIB CHARGE for {0} -> {1}: ran out of battery", "手動除顫充電（{0} → {1}） : 電池耗盡"),
        ("DrillPod:  Local player tries to use DrillPod but not everyone is inside. count: {0}/{1}", "鑽艙 : 本地玩家嘗試使用鑽艙，但並非所有人都已進入。人數 : {0}/{1}"),
        ("{0}.CreateServerSocket : Socket already exists !!!!!!!!! {1}", "{0} 的 CreateServerSocket : Socket 已存在 ！！！！！！！！！！！！ {1}"),
        ("{0}.CreateClientSocket : Socket already exists !!!!!!!!! {1}", "{0} 的 CreateClientSocket : Socket 已存在 ！！！！！！！！！！！！ {1}"),
        ("{0}.CreateClientSocket : Client could not be started !! {1}", "{0} 的 CreateClientSocket : 客戶端無法啟動 ！！ {1}"),
        ("Steam is not loaded!", "Steam 尚未加載！"),
        ("STEAM: IsInitialized is false!", "STEAM : IsInitialized 為 false！"),
        ("Invalid Server name.", "服務器名稱無效。"),
        ("Steam: Connection closed: {0}", "Steam : 連接已關閉 : {0}"),
        ("Lobby member {0} timed out!", "大廳成員 {0} 已超時！"),
        ("{0}: Accepted connection for: {1}  color:{2}", "{0} : 已接受 {1} 的連接，顏色 : {2}"),
        ("Tried to kick {0} as a non-host????", "嘗試以非主機身份踢出 {0}？？？？"),
    };
    public static readonly (string En, string Zh)[] Prefixes =
    {
        ("<color=red>KrokMP ERROR: ", "<color=red>KrokMP 錯誤 : "),
        ("<color=yellow>KrokMP WARN: ", "<color=yellow>KrokMP 警告 : "),
        ("Multiplayer ERROR: ", "多人聯機錯誤 : "),
        ("Multiplayer: ", "多人聯機 : "),
        ("[<color=red>SERVER</color>] ", "[<color=red>服務器</color>] "),
    };
    public static readonly (string En, string Zh)[] Credits =
    {
        ("Krokosha666 - OG MP Mod Developer, owner", "Krokosha666 - MP 模組原作者，所有者"),
        ("Creature - MP Mod Developer", "Creature - MP 模組開發者"),
        ("dannad - Auto-updater module, Installer tool, C:T ds Staff", "dannad - 自動更新模塊、安裝工具，C:T ds 員工"),
        ("Gary the cat - playtester, Bug report module, past servers, C:T ds Staff", "Gary the cat - 測試玩家、錯誤報告模塊、前服務器，C:T ds 員工"),
        ("Todd - external mod \"ChangeSkin\", C:T ds Staff", "Todd - 外部模組“ChangeSkin”，C:T ds 員工"),
        ("ItsVoidSK - playtester, some sprites", "ItsVoidSK - 測試玩家、部分精靈"),
        ("dawn - TimeManipulation patch", "dawn - 時間操控補丁"),
        ("Jilu-tin - playtester", "Jilu-tin - 測試玩家"),
        ("NyaruQwQ - playtester", "NyaruQwQ - 測試玩家"),
        ("X0men0X - playtester", "X0men0X - 測試玩家"),
        ("{Pixel} - playtester", "{Pixel} - 測試玩家"),
        ("avr - playtester", "avr - 測試玩家"),
        ("gordocats - self-heal sprite", "gordocats - 自愈精靈"),
        ("notamoron - playtester", "notamoron - 測試玩家"),
        ("Devactor - playtester", "Devactor - 測試玩家"),
        ("Dictator - playtester", "Dictator - 測試玩家"),
        ("Мрак 2.0 - playtester", "Мрак 2.0 - 測試玩家"),
        ("Dmonya - playtester", "Dmonya - 測試玩家"),
        ("Shiro - playtester", "Shiro - 測試玩家"),
        ("Charu - playtester", "Charu - 測試玩家"),
        ("kipish - playtester", "kipish - 測試玩家"),
        ("Orsoniks - Developer of Casualties: Unknown", "Orsoniks - 《未知傷亡》開發者"),
        ("...and the rest of bug reporters, suggestions and regular players", "...以及其餘的 bug 報告者、建議者和普通玩家"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("MP", "【MP】"),
        ("MP dev", "【MP 開發】"),
        ("string", "文本"),
        ("bool", "真假"),
        ("float", "浮點"),
        ("int", "整數"),
        ("color", "顏色"),
        ("action", "操作"),
        ("type", "類型"),
        ("user", "用戶"),
        ("value", "值"),
        ("arg", "參數"),
        ("Title", "標題"),
        ("Text", "文本"),
        ("netId", "netId"),
        ("X pos", "X 位置"),
        ("Y pos", "Y 位置"),
        ("X size", "X 尺寸"),
        ("Y size", "Y 尺寸"),
        ("scale", "縮放比例"),
        ("Action", "操作"),
    };
}
