internal static class CatPatchTr
{
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Someone else is already helping that player.", "已经有别人在帮助这位玩家了。"),
        ("That rescue window has closed.", "救援窗口已经关闭。"),
        ("That rescue attempt was not accepted by the host.", "主机没有接受这次救援尝试。"),
        ("Rescue target is no longer valid.", "救援目标已失效。"),
        ("Cannot rescue right now.", "现在无法救援。"),
        ("Need close range and clear line of sight.", "需要近距离且视线清晰。"),
        ("You stopped the self-harm.", "你制止了自残行为。"),
        ("Rescue failed.", "救援失败。"),
        ("The gun was knocked away.", "枪被踢飞了。"),
        ("Self-harm stopped.", "自残行为已制止。"),
        ("Target is invalid.", "目标无效。"),
        ("Too slow.", "太慢了。"),
        ("Rescue canceled.", "救援已取消。"),
        ("Swipe faster and more sideways.", "滑得更快、更偏向侧面一些。"),
        ("Hug accepted.", "拥抱请求已接受。"),
        ("Hug rejected.", "拥抱请求被拒绝。"),
        ("This server uses a newer CatPatch version. Please update CatPatch to use hugs here.", "该服务器使用更新版本的 CatPatch。请更新 CatPatch 以在这里使用拥抱功能。"),
        ("Dogpile sleep boost activated. Sleep quality: Good.", "叠罗汉睡眠加成已激活。睡眠质量：良好。"),
        ("Some clients did not acknowledge your spray. They may not have CatPatch installed or updated.", "部分客户端未确认你的喷漆。他们可能没有安装或更新 CatPatch。"),
        ("Spray failed to upload.", "喷漆上传失败。"),
        ("Spray failed: backend unreachable. Check DNS, VPN, firewall, or internet.", "喷漆失败：无法连接后端。请检查 DNS、VPN、防火墙或网络。"),
        ("Spray does not have local or downloaded GIF data.", "该喷漆没有本地或已下载的 GIF 数据。"),
        ("No spray selected.", "未选择喷漆。"),
        ("The source spray file is empty.", "源喷漆文件为空。"),
        ("This spray has no image bytes available to save.", "该喷漆没有可保存的图像数据。"),
        ("Mr CatPatch has joined.", "CatPatch 先生加入了。"),
        ("Cannot request hug: local body not found.", "无法发起拥抱请求：未找到本地身体。"),
        ("Cannot request hug: local body is not huggable.", "无法发起拥抱请求：本地身体无法被拥抱。"),
        ("Cannot request hug: no nearby huggable target found.", "无法发起拥抱请求：附近没有可拥抱的目标。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("Sending hug request to {0}...", "正在向 {0} 发送拥抱请求..."),
        ("{0} wants to hug. Press {1} to accept or {2} to reject.", "{0} 想拥抱你。按 {1} 接受，按 {2} 拒绝。"),
        ("{0} wants to kiss. Press {1} to accept or {2} to reject.", "{0} 想亲吻你。按 {1} 接受，按 {2} 拒绝。"),
        ("Host spray cooldown: {0}s remaining.", "主机喷漆冷却中：剩余 {0} 秒。"),
        ("Your sprays are muted by the host for {0}s.", "你的喷漆被主机禁用了 {0} 秒。"),
        ("Spray failed: {0}", "喷漆失败：{0}"),
        ("Saved spray to {0}.", "喷漆已保存到 {0}。"),
        ("Host does not appear to have CatPatch. {0} is disabled on this server.", "主机似乎没有安装 CatPatch。本服务器已禁用 {0}。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("CatPatch is loaded!", "CatPatch 已加载！"),
        ("CatPatch Host Moderation is only available in a world for the multiplayer host or in singleplayer.", "CatPatch 主机管理仅在多人主机所在的世界或单人模式中可用。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("No players matched {0}.", "没有玩家匹配 {0}。"),
        ("Could not act on players matching {0}.", "无法对匹配 {0} 的玩家执行操作。"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Opens or closes the CatPatch Host Moderation menu.", "【CatPatch】打开或关闭 CatPatch 主机管理菜单。"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("Checking for CatPatch updates...", "正在检查 CatPatch 更新..."),
        ("Downloading CatPatch {0}...", "正在下载 CatPatch {0}..."),
        ("CatPatch {0} is available :)", "CatPatch {0} 有新版本可用 :)"),
        ("CatPatch is up to date.", "CatPatch 已是最新版本。"),
        ("CatPatch update check unavailable. :( all my hard work", "无法检查 CatPatch 更新。:( 我所有的辛苦"),
        ("CatPatch update downloaded. Click Apply & Quit to replace the DLL after the game closes.", "CatPatch 更新已下载。点击“应用＆退出”，游戏关闭后将替换 DLL。"),
        ("CatPatch update downloaded. Close the game, then extract the BepInEx folder from the zip into your game folder.", "CatPatch 更新已下载。关闭游戏，然后把压缩包里的 BepInEx 文件夹解压到你的游戏目录。"),
        ("CatPatch update download failed.", "CatPatch 更新下载失败。"),
        ("Automatic replacement only supports direct CatPatch.dll downloads.", "自动替换仅支持直接下载 CatPatch.dll 的方式。"),
        ("Starting CatPatch update helper...", "正在启动 CatPatch 更新助手..."),
        ("CatPatch update helper started. Quitting game...", "CatPatch 更新助手已启动。正在退出游戏..."),
        ("Failed to start CatPatch update helper. All my hard work :(", "无法启动 CatPatch 更新助手。我所有的辛苦 :("),
        ("CatPatch Update Available", "CatPatch 更新可用"),
        ("CatPatch {0} is available. You currently have {1}.", "CatPatch {0} 有新版本可用。你当前版本为 {1}。"),
        ("Changelog", "更新日志"),
        ("Downloaded to:", "已下载到："),
        ("Download", "下载"),
        ("Apply & Quit", "应用＆退出"),
        ("Later", "稍后"),
        ("Update manifest URL is empty. Meow failed, kill him with sticks", "更新清单 URL 为空。Meow 搞砸了，拿棍子揍他"),
        ("Update manifest was empty. Uh i dunno lol", "更新清单为空。呃，我也不知道，哈哈"),
        ("Update manifest is missing latest_version. thats weird", "更新清单缺少 latest_version。真奇怪"),
        ("Update manifest is missing download_url. :blush:", "更新清单缺少 download_url。:blush:"),
        ("Update manifest is missing sha256. hmmmmm", "更新清单缺少 sha256。呃呃呃呃"),
        ("Downloaded update failed SHA-256 verification.", "下载的更新未通过 SHA-256 校验。"),
        ("Cat\nPatch", "Cat\nPatch"),
        ("CatPatch Client Settings", "CatPatch 客户端设置"),
        ("Client Preferences", "客户端偏好"),
        ("Show sprays", "显示喷漆"),
        ("Updates", "更新"),
        ("Check Now for Update", "立即检查更新"),
        ("Installed: 1.0.4", "已安装：1.0.4"),
        ("Latest: ", "最新版本："),
        ("Error: {0}", "错误：{0}"),
        ("Suggest a feature, join the discord", "提建议？加入 Discord"),
        ("Host settings moved. Open server and click Host Moderation on the left.\n\n\nDEFAULT KEYBINDS:\n\nH: Hug\nG: Spray\nI: Inspect Spray", "“主机设置”已移动。打开服务器，点击左侧的“主机管理”。\n\n\n默认按键：\n\nH：拥抱\nG：喷漆\nI：检查喷漆"),
        ("Host Moderation", "主机管理"),
        ("Sections", "栏目"),
        ("Player Actions", "玩家操作"),
        ("Banned Steam IDs", "已封禁的 Steam ID"),
        ("Spray Moderation", "喷漆管理"),
        ("Server Mutes", "服务器禁言"),
        ("MFC Presets", "MFC 预设"),
        ("status", "状态"),
        ("Actions", "操作"),
        ("Players", "玩家"),
        ("Sprays", "喷漆"),
        ("Bans", "封禁"),
        ("Run Settings", "运行设置"),
        ("Connected players: ", "已连接玩家："),
        ("Singleplayer: actions affect the local player only.", "单人模式：操作仅影响本地玩家。"),
        ("Host a lobby to use moderation actions.", "创建大厅才能使用管理操作。"),
        ("No access. Host a lobby to use this menu.", "无权限。创建大厅才能使用此菜单。"),
        ("This section will be rebuilt without the old backend dependencies.", "该部分将在不依赖旧有后端组件的情况下重建。"),
        ("No players connected.", "没有玩家连接。"),
        ("Singleplayer", "单人模式"),
        ("Working", "运行中"),
        ("Host only", "仅主机"),
        ("players: ", "玩家："),
        ("THE VOICES ARE WINNING TODAY!!!!!!!1", "今天胜利属于声音们！！！！！！1"),
        ("Target", "目标"),
        ("host command target", "主机命令目标"),
        ("Ban list is unavailable. Host a lobby first.", "封禁列表不可用。请先创建大厅。"),
        ("Ban list is unavailable.", "封禁列表不可用。"),
        ("None", "无"),
        ("IP/name fallback ban", "IP/名称兜底封禁"),
        ("Steam ban", "Steam 封禁"),
        ("You can mute annoying people here", "你可以在这里禁言讨厌的人"),
        ("Sleeping on others gives good quality sleep?", "睡在别人身上能获得高质量睡眠？"),
        ("Shove key throws the player on your back", "按推键将玩家背起"),
        ("This makes for any vile combo of traps.", "这能组合出各种恶毒的陷阱。"),
        ("Enable challenge mode", "启用挑战模式"),
        ("Allow floating landmines", "允许浮空地雷"),
        ("Random spike trap orientation", "随机尖刺陷阱朝向"),
        ("Hazard categories", "危险分类"),
        ("Starter kit item IDs", "初始套件物品 ID"),
        ("Export a setup or paste one here to import it.", "导出配置或在此粘贴以导入。"),
        ("Elder thornbacks", "长老棘背兽"),
        ("Tp To You", "传送到你"),
        ("Tp To Them", "传送到Ta"),
        ("Heal/Revive", "治疗/复活"),
        ("Kill", "杀死"),
        ("Knock Out", "击晕"),
        ("Drop Inventory", "丢弃全部物品"),
        ("Explode", "爆炸"),
        ("Obliterate", "抹除"),
        ("Mindwipe", "精神抹除"),
        ("Skin", "剥皮"),
        ("Stub toe", "绊脚趾"),
        ("Fling", "抛飞"),
        ("Last Stand", "背水一战"),
        ("Kick, Ban, Admin", "踢出、封禁、管理员"),
        ("Admin", "管理员"),
        ("Unadmin", "取消管理员"),
        ("Kick", "踢出"),
        ("Ban", "封禁"),
        ("Unban", "解除封禁"),
        ("Mute", "禁言"),
        ("Unmute", "解除禁言"),
        ("Clear", "清除"),
        ("Clear all", "全部清除"),
        ("Enabled", "已启用"),
        ("Disabled", "已禁用"),
        ("Enable", "启用"),
        ("Disable", "禁用"),
        ("Hide", "隐藏"),
        ("Show", "显示"),
        ("Export", "导出"),
        ("Copy", "复制"),
        ("Import", "导入"),
        ("Chat On", "开启聊天"),
        ("Chat Off", "关闭聊天"),
        ("VC On", "开启语音"),
        ("VC Off", "关闭语音"),
        ("Mute All", "全部禁言"),
        ("Unmute All", "全部解除"),
        ("Muted (", "已禁言（"),
        ("s)", "秒）"),
        ("Allowed", "已允许"),
        ("Mute minutes:", "禁言分钟："),
        ("Cooldown", "冷却"),
        ("Throw strength", "抛掷力度"),
        ("Trap amount", "陷阱数量"),
        ("Dogpile Sleep", "叠罗汉睡眠"),
        ("Piggyback Throw", "背人抛掷"),
        ("Meow's final challenge", "Meow 的终极挑战"),
        ("  |  ping ", "  |  延迟 "),
        (" (ping ", "（延迟 "),
        ("chat: ", "聊天："),
        ("   vc: ", "   语音："),
        ("muted", "已禁言"),
        ("ok", "正常"),
        ("Host only action.", "仅主机操作。"),
        ("Host only.", "仅主机。"),
        ("Host cannot kick themselves.", "主机不能踢自己。"),
        ("Kicked by host.", "已被主机踢出。"),
        ("Kicked ", "已踢出 "),
        ("Host cannot ban themselves.", "主机不能封禁自己。"),
        ("Cannot ban ", "无法封禁 "),
        (": Steam ID unavailable.", "：Steam ID 不可用。"),
        ("Banned by host.", "已被主机封禁。"),
        ("Banned ", "已封禁 "),
        ("Unbanned: ", "已解除封禁："),
        ("Failed to unban: ", "解除封禁失败："),
        ("Clear failed: ", "清除失败："),
        ("Spray mute failed: ", "喷漆禁言失败："),
        ("Spray clear failed: ", "喷漆清除失败："),
        ("Spray muted client {0} for {1:0.##} minute(s).", "已将客户端 {0} 喷漆禁言 {1:0.##} 分钟。"),
        ("Spray unmuted client ", "喷漆未禁言客户端 "),
        (" is not spray muted.", " 未被喷漆禁言。"),
        ("Client ", "客户端 "),
        ("Muted chat and voice for client ", "已禁聊天和语音客户端 "),
        ("Unmuted chat and voice for client ", "已解聊天和语音客户端 "),
        ("Host cannot be muted.", "主机不能被禁言。"),
        (" muted client ", " 禁言了客户端 "),
        (" unmuted client ", " 解除了客户端 "),
        ("Chat", "聊天"),
        ("Voice", "语音"),
        ("Local player body not found.", "未找到本地玩家身体。"),
        ("Local host player not found.", "未找到本地主机玩家。"),
        ("Local host player id not found.", "未找到本地主机玩家 ID。"),
        ("Player not found.", "未找到玩家。"),
        ("Player id is out of range.", "玩家 ID 超出范围。"),
        ("Player body not found.", "未找到玩家身体。"),
        ("Left foot limb not found.", "未找到左脚肢体。"),
        ("Only host can change admin.", "只有主机能更改管理员。"),
        ("Host admin cannot be changed.", "主机管理员不可更改。"),
        ("Admin toggle failed: ", "管理员切换失败："),
        ("Granted admin to ", "已将管理员授予 "),
        ("Removed admin from ", "已移除管理员 "),
        ("Teleported ", "已传送 "),
        (" to you.", " 到你身边。"),
        ("Teleported you to ", "已将你传送到 "),
        ("Revived ", "已复活 "),
        ("Killed ", "已击杀 "),
        ("Knocked out ", "已击晕 "),
        ("Dropped inventory for ", "已丢弃 "),
        ("Boom on ", "爆炸了 "),
        ("head", "头部"),
        ("arm", "手臂"),
        ("hand", "手"),
        ("leg", "腿"),
        ("foot", "脚"),
        ("Obliterated ", "已抹除 "),
        (" limbs).", " 个肢体）。"),
        ("Mindwiped ", "已精神抹除"),
        ("Skinned ", "已剥皮 "),
        ("Stubbed toe for ", "绊了 "),
        ("Flung ", "已抛飞 "),
        (" cannot Last Stand right now.", " 现在无法背水一战。"),
        ("Forced Last Stand for ", "已强制背水一战 "),
        ("Last Stand is disabled by the multiplayer rules.", "多人模式规则禁用了背水一战。"),
        ("Mute action failed.", "禁言操作失败。"),
        ("Voice mute action failed.", "语音禁言操作失败。"),
        ("Exported MFC preset.", "已导出 MFC 预设。"),
        ("Copied MFC preset.", "已复制 MFC 预设。"),
        ("Preset text is empty.", "预设文本为空。"),
        ("Player ", "玩家 "),
        (".", "。"),
        ("Regular Traps", "普通陷阱"),
        ("Enemies", "敌人"),
        ("Environmental Hazards", "环境危害"),
        ("Radioactive Hazards", "放射性危害"),
        ("Hazards", "危害"),
        ("Spike stabber", "尖刺陷阱"),
        ("Barbed wire", "铁丝网"),
        ("Bear trap", "捕兽夹"),
        ("Jump pad", "弹射陷阱"),
        ("Landmine", "地雷"),
        ("Gunmine", "枪地雷"),
        ("Sawblade", "圆锯片"),
        ("Sound cannon", "音波炮"),
        ("Coil", "线圈"),
        ("Turret", "自动炮塔"),
        ("Tick swarm", "蜱虫群"),
        ("Wall biter", "咬墙虫"),
        ("Shade crawler", "暗影爬行者"),
        ("Thornback", "棘背兽"),
        ("Overgrown tick", "巨型蜱虫"),
        ("Grabber plant", "抓缠草"),
        ("Skull crusher", "碎颅者"),
        ("Geyser", "间歇泉"),
        ("Oil pipe", "废液管"),
        ("Glass shards", "玻璃碎片"),
        ("Rad barrel", "辐射桶"),
        ("Spent fuel", "乏燃料"),
        (" wants to hug.", " 想拥抱你。"),
        (" wants to kiss.", " 想亲吻你。"),
        (" to accept, or ", " 接受、按 "),
        (" to reject.", " 拒绝。"),
        ("Emotes", "表情"),
        ("Sit", "坐下"),
        ("Lay", "躺下"),
        ("Sleep", "睡觉"),
        ("Spray Preview", "喷漆预览"),
        ("Close", "关闭"),
        ("Download", "下载"),
        ("GET THE FUCK AWAY FROM ME!!!", "给劳资滚开！！！"),
        ("Oh no, you're not leaving me yet.", "噢不，你还不能走。"),
        ("Stay with me. We're getting through this.", "留在我身边。我们会挺过去的。"),
        ("Not today. I've got you.", "今天不行。有我在。"),
        ("Hey, look at me. You're still here.", "嘿，看着我。你还在这里。"),
        ("Nope. You're not in this alone.", "不行。你不是一个人。"),
        ("You're okay. You're fine.", "你没事的。你很好。"),
        ("Don't! It's- It's okay!", "别！没-没事的！"),
        ("It'll be alright. Breathe.", "会没事的。呼吸。"),
        ("Take a deep breath, okay?", "深呼吸，好吗？"),
        ("You'll be okay. Look at me.", "你会没事的。看着我。"),
        ("Not on my watch.", "有我在，别想。"),
        ("I've got you. Come here.", "我接住你了。过来。"),
        ("Stay with me, okay?", "待在我身边，好吗？"),
        ("You're still here. I'm here.", "你还在这里。我在这里。"),
        ("I'm here for you, buddy.", "我在这里陪着你，伙计。"),
        ("You're stuck with me for now.", "你现在甩不掉我了。"),
        ("Okay, okay... let's sit down, alright?", "好了，好了...我们坐下来，好吗？"),
        ("Well... that happened.", "嗯...刚才的事就这样吧。"),
        ("Tactical kiss.", "战术性亲吻。"),
        ("We are never explaining this.", "我们永远解释不清这件事。"),
        ("Worth it.", "值了。"),
        ("This is how rumors start.", "谣言就是这么来的。"),
        ("Absolutely normal workplace behavior.", "完全正常的工作场所行为。"),
        ("Okay, back to surviving.", "好了，回到求生正题。"),
        ("Mwah!", "啵！"),
        ("Charge me, doctor!", "给我充电，医生！"),
        ("I've always wanted to do this...", "我一直想这么做..."),
        ("They would never let us do this back on Earth.", "在地球上他们绝不会让我们这么做。"),
        ("Only on the Grey planet.", "只有在这颗灰色星球上。"),
        ("I hope no one saw that.", "希望没人看见。"),
        ("Cutie.", "小可爱。"),
        ("I don't know how to kiss, but I hope that was good enough.", "我不知道怎么接吻，但希望刚才够好。"),
        ("I don't know what to say, but I hope that was good enough.", "我不知道该说什么，但希望刚才够好。"),
        ("I hope that was good enough.", "希望刚才够好。"),
        ("My rival, my idol, you got me suicidal, my love, your rage, our dying claim to fame...", "我的对手，我的偶像，你让我痴狂，吾爱，你的怒火，我们垂死的成名之作..."),
        ("You taste really good.", "你尝起来真不错。"),
        ("*Slurping noises*", "*吸溜*"),
        ("Maybe let's stick to hugging for now.", "也许我们还是先拥抱吧。"),
        ("I learned from my handler.", "我是跟我的管理员学的。"),
        ("Last time I tried this, a Dune nearly ripped my jaw off.", "上次我这么干，一只沙丘差点把我下巴扯下来。"),
        ("Uh... no homo?", "呃...不是那种意思？"),
        ("Oh... we are so gay.", "噢...我们太基佬了。"),
        ("Congrats! You're gay now.", "恭喜！你现在是基佬了。"),
        ("I'm sorry, Gary.", "对不起，Gary。"),
        ("I hope I don't catch the gay!", "希望我不会被传染基佬病！"),
        ("MmmmMMhghgf-", "嗯嗯嗯嗯嗯嗯-"),
        ("That... wasn't a hug...", "那...不是拥抱..."),
        ("I hope they got this on record!", "希望他们把这录下来了！"),
        ("Platonically kissing you was the best thing ever!", "柏拉图式地亲你是有史以来最棒的事！"),
        ("You better write about this in your pod tonight.", "你今晚最好在维生舱里把这事写下来。"),
        ("We could always just let another group find the cargo.", "我们大可以就让别的队伍找到那批货物。"),
        ("Our captors can suck my wiggly dick.", "那些抓我们的人去吃屎吧。"),
        ("My handler had a bit too much of a  approach to teaching...", "我的管理员教我的方式有点太..."),
        ("Boop!", "戳！"),
        ("What's this, I got it, how could I have forgotten, the physical touch of another, it makes me feel so warm...", "这是什么，我明白了，我怎么忘了呢，另一个人的肢体接触，让我感觉如此温暖..."),
        ("My mango, is to blow up, and act like I don't know nobody... what's a mango?", "我的主要目标是爆红，然后装作谁也不认识..."),
        ("I just drank fent, by the way.", "顺便说一句，我刚喝了芬太尼。"),
        ("The 10 hour expie kissing scene is plot relevant, I swear!", "十小时恐怖片的接吻戏是剧情相关的，我发誓！"),
        ("With the power of yaoi, we shall prevail!", "凭借基腐之力，我们终将胜利！"),
        ("With the power of yuri, we shall prevail!", "凭借百合之力，我们终将胜利！"),
        ("Wanna share a syringe after this?", "完事后想共享一支注射器吗？"),
        ("I saw this on a blueprint once.", "我在蓝图上看过这个。"),
        ("I don't know if we should take this any further...", "我不知道我们该不该继续深入..."),
        ("We should stop at this...", "我们应该到此为止..."),
        ("This is like that one gif.", "这就像那个动图。"),
        ("What's my gender? kiss me again and find out.", "我的性别是什么？再亲我一次就知道了。"),
        ("I assume this means you'll be treat me to dinner.", "我猜这意味着你会请我吃晚饭。"),
        ("A little less tongue next time, yeah?", "下次少点舌头，好吗？"),
        ("If anyone asks, yes, we're a thing now.", "如果有人问，是的，我们现在是一对了。"),
        ("Fine... I guess I'll be your little pog champ.", "好吧...我勉强当你的小冠军宝贝。"),
        ("I KNEW YOU WERE GAY ALL ALONG!", "我 就 知 道 你 是 基 佬 ！"),
        ("I guess I'll endure your affection just this once.", "我就勉强忍受你的爱意这一次。"),
        ("LESS TEETH, YOU BUGGY FUCK!", "少 用 点 牙 ，你 这 虫 豸 ！"),
        ("Yummers.", "好耶。"),
        ("34 rules about to be violated tonight!", "今晚要违反 34 规则了！"),
        ("Call me a spike stabber the way I... Fuck, I forgot, nevermind.", "像叫尖刺陷阱那样叫我...操，我忘了，算了。"),
        ("They're gonna have to rename this to the freakpatch.", "他们得把这模组改名叫怪人补丁了。"),
        ("vaporeonx5 was here :3c", "vaporeonx5 到此一游 :3c"),
        ("I guess I'm trans now..?", "我想我现在是变性人了...？"),
        ("Oh yeah, keep jorking me, oh yeah ong ong", "噢耶，继续逗我，噢耶，真的真的"),
        ("Orsoniks approved mod!", "Orsoniks 认证模组！"),
        ("I think... I liked that.", "我想...我喜欢刚才。"),
        ("...oh?", "...哦？"),
        ("Last time I tried this, they nearly ripped my jaw off.", "上次我这么干，他们差点把我下巴扯下来。"),
        ("Uhh...", "呃..."),
        ("That's... nice?", "这...不错？"),
        ("Are you, um...", "你是，嗯..."),
        ("Is this okay..?", "这样可以吗...？"),
        ("Mmmh...", "嗯..."),
        ("How affectionate...", "多有爱意啊..."),
        ("What a display of affection...", "多么深情的表现..."),
        ("Ah! Mmhh... Thank you...", "啊！嗯...谢谢你..."),
        ("Aw! You're so nice!", "啊！你真好！"),
        ("Less- teeth, gosh.", "少—少用点牙，天哪。"),
        ("Still platonic, right?", "还是柏拉图式的，对吧？"),
        ("I hope there aren't any cameras around here.", "希望这附近没有摄像头。"),
        ("I think I skipped the kissing course...", "我想我跳过了接吻课程..."),
        ("You're cute...", "你真可爱..."),
        ("You're warm...", "你真暖和..."),
        ("You're soft...", "你真柔软..."),
        ("Oh, uh..! Is this alright?-", "噢，呃...！这样可以吗？—"),
        ("Did you just eat something..?", "你刚才是不是吃了什么东西...？"),
        ("Is this relevant to the mission..?", "这跟任务有关吗...？"),
        ("I feel better...", "我感觉好多了..."),
        ("Wanna share a burger after this?", "完事后想共享一个汉堡吗？"),
        ("Are we a thing now..?", "我们现在算是一对了吗...？"),
        ("Your tail is wagging.", "你的尾巴在摇。"),
        ("Haha- is my tail wagging?", "哈哈—我的尾巴在摇吗？"),
        ("You're just licking my face... okay...", "你只是在舔我的脸...好吧..."),
        ("Uh- what rule did we violate with this?", "呃—我们这样违反了哪条规则？"),
        ("Haha, you okay?", "哈哈，你还好吗？"),
        ("My heart is gonna jump out of my chest...", "我的心要从胸口跳出来了..."),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("Hahahaha... FUCK yeah... That's good...", "哈哈哈...真 他 妈 爽...这感觉可以..."),
        ("Thaaatttt's better... Ahahaha... Fucking amazing...", "这这这这就对了...啊哈哈哈...真他妈带劲..."),
        ("Oh yeah... Fuck yeah... FUCK yeah...", "哦耶...真他妈爽...真他妈爽..."),
        ("Mmhh... Fuck... Hahahaha... This is good...", "嗯嗯...妈的...哈哈哈...这感觉真好..."),
        ("How do yoouuuu like that... Fucker... Ahaha... FUCK you... Fuck you... Good...", "你你你感觉很爽吗...傻逼...啊哈哈...操...妈的...真不错..."),
        ("Fuck me, hahah... That feels amazing...", "我操，哈哈...那感觉真美妙..."),
        ("AAGH! FUCK YEAH! Fucking amazing...", "啊啊！爽翻了！太棒了..."),
        ("FUCK! HAHAHAHA! HELL FUCKING YEAH..!", "操！哈哈哈哈！真他妈爽...！"),
        ("Just a little cut... More... Ahahah... Fuck...", "只是一点小伤口...再来几次...啊哈哈...妈的..."),
        ("Ouch-... T-that's good... Fuck... That's great...", "哎哟—...这—这感觉不错...操...太棒了..."),
        ("FUCK! Hahaha! FUCK yeah! Hahahaha...", "操！哈哈哈！真他妈爽！哈哈哈..."),
        ("That's what... you get... Dickhead... Fuck you... Hahahaha...", "这是...你...你活该...白痴...去死吧...哈哈哈哈..."),
        ("There... we go... hahah... good...", "好...了...哈哈哈...不错..."),
        ("That'll.. fuck... Yeaaahhh... That'll do it... Haha...", "就这样...妈的...对...这样就对了...哈哈..."),
        ("Y-Yeah... take that... Fucker... That'll hurt good...", "对—对...尝尝这个...妈的...真痛快..."),
        ("You deserve this... Haha... That hurts greeatt...", "你活该...哈哈...这痛感爽翻了..."),
        ("AAHHAHA!! FUCK yeah... Fuck yeah. Hahaha... Hurts...", "啊啊哈哈！！真他妈爽...真他妈爽。哈哈哈...好痛..."),
        ("Hahah... that's better... yeah... Much better...", "哈哈...这样就对了...是的...好多了..."),
        ("Theeeree we go... That hurts gooooood...", "来来来吧...这疼得真爽..."),
        ("Hehhehheh... that fucking hurts... hurts good...", "嘿嘿嘿...真他妈的痛...痛得真爽..."),
        ("That... hahah... hurts good... Great...", "这...哈哈...痛得爽...太棒了..."),
        ("Let's not end this juuuussst yet... F-fuck... That's good...", "先别别别这么着急...操—操了...这感觉好棒..."),
        ("I don't need that flesh... Ggrhh... Haha... More of this...", "我不缺这点肉...呃呃...哈...再来几次..."),
        ("F-fuck... Ahahaha... Feels great...", "操—他妈的...啊哈哈哈...真他妈绝了..."),
        ("Goooooodd.... Mmmh... Finally... Finally... Fucking amazing... Mmmhh...", "太太太棒了...嗯嗯...终于...终于...真他妈解压...嗯嗯..."),
        ("M-maybe... Maybe I'll end it next time... Hahaha...", "也—也许...下次我就戒了吧...哈哈哈..."),
        ("Goodbye. Good FUCKING BYE. I am DONE!!! FUCK ALL OF THIS!", "再见。再 他 妈 的 见。就这样了！！去 你 妈 的！"),
        ("I'm done. Fuck this, fuck me and FUCK you.", "操你妈的，我不干了，去他妈的。"),
        ("I fucking told you. I TOLD you, you piece of shit. I'm DONE!", "我他妈早跟你说过。我 警 告 过你，我受够了！"),
        ("I'm leaving this shitty world once and for all.", "终于能永远逃离这垃圾地方了。"),
        ("Peace. Bye. Fuck this. I'm fucking leaving. I'm going to hell for this.", "可以清静了。再他妈的见，老子不伺候了。下地狱就下地狱吧。"),
        ("I have FUCKING had it with all of this. I am DONE! FUCK OFF!!!", "我他妈早就忍到 极 限 了。到 此 为 止！！！"),
        ("End of the line, fucker. End of the fucking line. I'M OUT!!!", "到此为止了，他妈的，老 子 不 干 了！！！"),
        ("That should do it... Bye-bye... Sorry for this... I hope there's an afterlife for me...", "这样应该就结束了吧...再见...对不起...希望还有来生等着我..."),
        ("This is the end. I hope whoever finds my corpse makes good use of me. I can't handle this anymore. I'm sorry.", "结束了。谁要是发现我的尸体，能用上的东西就拿去吧。我已经扛不住了。对不起。"),
        ("There's no point to this anymore. There NEVER fucking was. I'm ending it all. Fuck me... Fuck ALL of this.", "没意义了，从来就 没 有 过 他妈的意义。到此为止吧。操...通通去死吧。"),
        ("If slitting my wrists doesn't kill me, I'm going to gouge my own fucking eyes out, so I never have to see this horrible land ever again.", "如果割腕弄不死我，我就把我这双眼珠子抠出来，至少这样我就看不到这垃圾地方了。"),
        ("I don't know what comes after, but I can finally rest... Let's relax now... There is no need for emotions anymore...", "虽然不知道死后会怎样，但至少终于能解脱了...放松点...再也不用去感受那些痛苦了..."),
        ("AHHHH! FUCK THIS! ALL OF THIS! I CAN'T TAKE IT ANYMORE! LET ME OUT OF HERE! I'M DONE!", "啊！！！去 他 妈 的！都 去 死 吧！我 受 够 了！到 此 为 止 了！"),
        ("That's it. I've FUCKING had it. I'm finally doing this... Peace. Fucking PEACE. I'm OUT.", "够了，我 他 妈 受够了，终于到动手的时候了...清静了，真他妈 清 静，再见。"),
        ("I have made the conscious decision to end my life, right here and right now. Farewell, dipshits.", "我已经决定了，在这里、就现在，结束我的生命。永别了，傻逼们。"),
        ("I told you... I TOLD YOU. Piece of shit... Fuck... Burn in the fucking depths of hell.", "我警告过你，我他妈的 警 告 过 你，妈的...一起在无间地狱里烧成灰吧。"),
        ("I'll do better as a rotting corpse. My life ended the moment I was sent here. Goodbye.", "变成一具腐烂的尸体都比现在强。从我被送到这里的那一刻起，我就已经死了。再见。"),
        ("This is for fucking EVERYTHING! I'M DONE! AAAHHHH! FUCK ALL OF THIS!", "这都是你们逼的！！！老子 不 干 了！啊！！！都给我去死！！！"),
        ("I'm. I'm just... I'm done. No time for suicide notes. I'm so tired of all of this. Goodbye.", "我...我累了。没心思写什么遗言。我累了。再见。"),
        ("N... no hard feelings... right?.. hah... I'm... I'm so tired... G-goodnight...", "别...别恨我...好吗...呵...我好累...晚安..."),
        ("I'm not doing this anymore. I'm not. It's over. Bye. Ello. Fuck this.", "我熬不下去了，熬不下去了，结束了。再见，去他妈的。"),
        ("There never was any hope. FUCK. This. I'm OUT! LEAVE ME ALONE! I'M NOT LETTING THIS PLACE TAKE MY LIFE!", "根本就没有过希望。去你妈的。老子不玩了！我不会再让这傻逼地方折磨我了！！！"),
        ("Looooook at that... Hahahah... I'm saying goodbye to this fucking universe... Leaving this world behind... It's... Relieving...", "看啊...哈哈哈...我要跟 他 妈 的 这个世界说再见了...把这个世界抛在脑后...感觉...真是轻松啊..."),
        ("There... There it goes... Let's enjoy my last few moments now... Relax and... Fall asleep... One last time...", "好了...享受我最后的几分钟吧...放松...然后睡过去...最后一觉..."),
        ("I hope you're happy with what you've done. Dipshit. Fuck you. FUCK YOU. Go to hell.", "看到我这样你满意了吧？人渣。去你妈的。去死吧。下地狱去吧。"),
        ("There goes my wrist... It's all going to be over soon... Haha...", "手腕割开了...马上一切就要结束了...哈哈..."),
        ("Fuck you. FUCK you. I'm DONE. I'M FUCKING DONE!", "操你妈的，去死吧，我受够了，我 他 妈 真 的 受 够 了！！"),
        ("I am LEAVING this fucking place, whether I'm able to or NOT. FUCK YOU.", "无论成不成，我今天都必须 离 开 这垃圾地方。去 你 妈 的。"),
        ("FUCK this. It's fucking OVER. To hell with my life.", "去他妈的。彻底 结 束 了。这破烂生活不要也罢。"),
        ("To hell with this. I'm out. Piece of shit. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done.", "毁灭吧，我不干了。他妈的。我不干了。我不干了。我不干了。我不干了。我不干了。我不干了。我不干了。"),
        ("Piece of shit... I'm fucking done... Fuck this...", "妈的...我彻底放弃了，他妈的..."),
        ("I'm leaving. I hope I'm not going to hell for this.", "我要走了。希望我不会因此而下地狱。"),
        ("They can find me as a desiccated corpse in a ditch. Like it fucking matters.", "让他们在哪个臭水沟里找我干瘪的尸体去吧。无所谓了。"),
        ("None of this matters. This is a suicide mission. I'm not fucking going through any more of this.", "这一切都没意义。这他妈就是个自杀任务。我死也不想再经历这些了。"),
        ("I've failed. I give up. Fuck this.", "我放弃了，任务失败。去他妈的。"),
        ("Good fucking luck to anyone that comes here after me. Maybe my corpse will be of use to someone. I'm done.", "祝后面来这个鬼地方的人好运吧。也许我的尸体还能对谁有点用。我走了。"),
        ("There never was any fucking point to this. I was sent here to die.", "这事情他妈的从一开始就没有任何意义。我就是来送死的。"),
        ("They're getting what they fucking wanted.", "这下他们如愿以偿了。"),
        ("I didn't think I was ever actually going to do this... Haha... Ahahahaha... Cathartic...", "我没想到我真的会亲手了结自己...哈哈...啊哈哈哈...解脱了..."),
        ("I'm taking my life. Sorry. I can't. I fucking can't take it anymore. I'm so fucking sorry.", "我要自我了结了。对不起。我做不到了。我真你妈受不了了。真他妈抱歉了。"),
        ("I hope I end up in hell. Gonna be better than this fucking place. I can't. I'm out. Sorry. Fuck all of this.", "我希望我会进地狱。反正比这傻逼地方强得多。我受不了了。不干了。对不起。真他妈傻逼。"),
        ("Bye. I'm out. I'll see everyone on the other side, down in the pits of hell.", "再见。我走了。另一边见吧，在那地狱的深渊里。"),
        ("Fuck this. Fuck this. FUCK. This. I'M DONE! ENOUGH OF THIS.", "妈的。妈的。操 你 妈。我受够了！够了！！！"),
        ("Sorry. I'm out. Bye. I'm sorry. I'm so fucking sorry. I can't.", "对不起。我不干了。再见。对不起。我很他妈抱歉。我做不到。"),
        ("Thanks... I needed that.", "谢谢...我正需要这个。"),
        ("Can we stay like this for a second?", "我们能这样待一会儿吗？"),
        ("I'm not doing great.", "我现在不太好。"),
        ("I'm so tired...", "我好累..."),
        ("I don't think I've felt okay for a while.", "我好像很久没有好受过了。"),
        ("I don't want to... I can't be alone right now.", "我不想...我现在不能一个人待着。"),
        ("I'm not a burden, am I?", "我不是个累赘吧？"),
        ("This helps... a little...", "这有点用...一点点..."),
        ("I want to cry...", "我想哭..."),
        ("Everything feels wrong lately.", "最近一切都感觉不对劲。"),
        ("I needed a reminder that somebody still cares.", "我需要有人提醒我还有人关心我。"),
        ("I've been holding everything in.", "我一直把所有情绪憋在心里。"),
        ("I was starting to spiral again.", "我又开始胡思乱想了。"),
        ("Our captors will get what they fucking deserve.", "那些抓我们的人会得到他们应得的报应。"),
        ("I think I might consider a mindwipe.", "我想我可能要考虑洗脑了。"),
        ("I dreamt about our captors again last night... it was so vivid...", "昨晚我又梦到那些抓我们的人了...太清晰了..."),
        ("What did we do to deserve this?", "我们到底做错了什么要受这种罪？"),
        ("I hate how much this place affects me.", "我讨厌这个地方对我影响这么大。"),
        ("I'm scared of what I'm becoming in here.", "我害怕自己在这里变成的样子。"),
        ("When I get my claws on them, they will know pain.", "等我抓住他们，他们会知道什么叫痛苦。"),
        ("I don't even recognize myself anymore.", "我都不认识自己了。"),
        ("I'm really scared...", "我真的好害怕..."),
        ("I can't lose you, too...", "我不能再失去你了..."),
        ("Please don't leave me...", "求你别离开我..."),
        ("I've lost so many... I can't lose you too.", "我已经失去太多人了...不能再失去你。"),
        ("I'm trying really hard to keep going.", "我在很努力地撑下去。"),
        ("There is no honest way out, huh.", "没有体面的出路，是吧。"),
        ("...", "..."),
        ("If something happens, please don’t forget about me.", "如果发生什么，请别忘了我。"),
        ("Will I even make it out..?", "我真的能活着出去吗..？"),
        ("I hate this... I really do...", "我讨厌这一切...真的讨厌..."),
        ("They don't know what I'm going through down here...", "他们不知道我在下面经历了什么..."),
        ("Is this what we are to them..?", "我们对他们来说就是这样吗？"),
        ("This only delays the inevitable...", "这只是在拖延注定的结局"),
        ("I can't die like this...", "我不能就这样死"),
        ("Are... Are we going to make it out..?", "我们我们能活着出去吗？"),
        ("Please tell me we going to be okay...", "请告诉我我们会没事的"),
        ("Their salvation will be rotten...", "他们的救赎会烂掉"),
        ("I don't think this is enough.. but thank you.", "我知道这不够但谢谢你。"),
        ("Please don't leave my side... at least until I'm okay.", "请别离开我身边至少等我好起来。"),
        ("Will they toss us aside if we make it out? What will they do to us..?", "如果我们出去了，他们会不会把我们丢到一边？他们会对我们做什么？"),
        ("I... I don't want to do this anymore...", "我我不想再这样下去了"),
        ("I want to go somewhere else... anywhere but here...", "我想去别的地方哪里都行，就是别在这"),
        ("I... Won't end up like the rest, right..?", "我不会变得和那些尸体一样吧？"),
        ("Their bodies... mangled... stabbed... cold... why..?", "他们的尸体残缺被刺穿冰冷为什么？"),
        ("I can't... keep going...", "我撑不下去了"),
        ("I don't want to end up like them...", "我不想变得和他们一样"),
        ("Why are there so many of us down here..? So many... all dead.", "为什么这里有这么多我们的人？这么多全都死了。"),
        ("I can't stop crying...", "我止不住地哭"),
        ("I can't stop looking at the ground...", "我一直盯着地面"),
        ("I'm scared of this place...", "我害怕这个地方"),
        ("They won't get away with this.. I'll... I don't know...", "他们不会逍遥法外的我会我不知道"),
        ("What will we do once this is all over..?", "这一切结束后我们该怎么办？"),
        ("I hate that I'm actually adapting to this place...", "我讨厌自己居然在适应这个地方"),
        ("The traps... the lights... the corpses...", "那些陷阱灯光尸体"),
        ("Why can't they just get it themselves instead of commiting a genocide..?", "为什么他们不能自己来拿，非要搞种族灭绝？"),
        ("I'm sick of this place... I'm sick of it all.", "我受够了这个地方受够了一切。"),
        ("I feel like I'm not going to make it...", "我觉得我可能活不下去了"),
        ("I won't fall victim like the rest, right..?", "我不会像其他人那样成为受害者吧？"),
        ("I want to wake up...", "我想醒来"),
        ("This is all a bad dream, right..?", "这一切都是个噩梦，对吧？"),
        ("Why would they... why...", "他们为什么要为什么"),
        ("I... please don't watch if I scratch myself...", "我如果我自己抓伤自己，请不要看"),
        ("You shouldn't care about someone as useless as me...", "你不该关心像我这样没用的人"),
        ("I'm just dead weight, aren't I..?", "我只是个累赘，对吧？"),
        ("I'm not smart like a Milky and I'm not strong like a Dune... why bother...", "我不像奶白那样聪明，也不像沙丘那样强壮何必呢"),
        ("I hate this place... why here of all places...", "我讨厌这个地方为什么偏偏是这里"),
        ("If this keeps up I might have to resort to my own way out of this place...", "再这样下去，我可能不得不用我自己的方式离开这里了"),
        ("...I wish we could have stayed...", "真希望我们能留在那里"),
        ("Just this once...", "就这一次"),
        ("I can't even look up...", "我连头都抬不起来"),
        ("I'm not smart and I'm not strong... why bother...", "我不聪明也不强壮何必呢"),
        ("If this keeps up I might have to...", "再这样下去我可能不得不"),
        ("I'm exhausted.", "我精疲力尽了。"),
        ("I'm so sick of this place.", "我受够这个地方了。"),
        ("I hate this place.", "我讨厌这个地方。"),
        ("I hate myself...", "我讨厌我自己"),
        ("Please tell me we're going to be okay.", "请告诉我我们会没事的。"),
        ("I'm trying... I'm trying so hard...", "我在努力我非常努力"),
        ("I'm trying not to cry, okay..?", "我在努力不哭出来，好吗？"),
        ("I don't want to die...", "我不想死"),
        ("I couldn't care less about the cargo.", "我一点也不在乎那批货物。"),
        ("Thank you... Thank you...", "谢谢谢谢"),
        ("...Okay...", "好吧"),
        ("You looked like you needed this.", "你看上去需要这个。"),
        ("It's okay, even thought it's not, just know I'll be here for you.", "虽然现在不好，但没关系，我会陪着你。"),
        ("You've been carrying too much alone.", "你一个人扛得太多了。"),
        ("You know I care about you.", "你知道我在乎你。"),
        ("Hey, hey, it's okay. I'm here.", "嘿，嘿，没事的。我在这里。"),
        ("Come here...", "过来"),
        ("If you need to cry, I understand. I'm here for you.", "想哭就哭吧，我理解。我在这里陪着你。"),
        ("I'll be here for you, no matter what.", "无论发生什么，我都会陪着你。"),
        ("If you need a shoulder to cry on, I'm here.", "需要靠一靠肩膀的话，我在这里。"),
        ("Don't worry, I've got you.", "别担心，有我在。"),
        ("I know that look. I've had it too.", "我懂那种眼神。我也经历过。"),
        ("Just rest your head for a second.", "把头靠过来休息一下。"),
        ("I hope our captors are burning in hell for this.", "我希望那些抓我们的人在地狱里被火烧。"),
        ("Our captors can go fuck themselves.", "那些抓我们的人去死吧。"),
        ("Our captors can go to hell.", "那些抓我们的人下地狱去吧。"),
        ("Fuck 'em.", "去他妈的。"),
        ("When we get back, we will make them pay, don't worry.", "等我们回去，会让他们付出代价的，别担心。"),
        ("You don't have to handle this alone.", "你不需要一个人扛。"),
        ("Don't let this place win.", "别让这个地方得逞。"),
        ("You shouldn't have to go through this alone.", "你不该独自经历这些。"),
        ("Hey... breathe, alright? I'm here now.", "嘿深呼吸，好吗？我现在在这里。"),
        ("Smoke 'em if you got 'em...", "有烟抽就抽吧"),
        ("I’m not gonna leave you. I’m right here.", "我不会离开你的。我就在这里。"),
        ("We are in this together, remember?", "我们是一起的，记得吗？"),
        ("I know it’s hard, but we can get through this. Together.", "我知道很难，但我们可以挺过去。一起。"),
        ("I’m not going anywhere. I’ve got you.", "我哪儿也不去。有我在。"),
        ("I know you're scared, but we'll make it through this. I promise.", "我知道你害怕，但我们会挺过去的。我保证。"),
        ("I wish I could make it all better, but I can’t. I care about you and I’m here for you.", "我希望我能让一切变好，但我不能。我在乎你，我在这里陪着你。"),
        ("I know this place is awful, but you’re not alone. I’m here with you.", "我知道这地方很糟，但你不是一个人。我在这里。"),
        ("You’re doing the best you can, and that’s all anyone can ask of you. I’m proud of you.", "你已经尽力了，这就够了。我为你骄傲。"),
        ("You are so strong, I'm so proud of you.", "你太坚强了，我为你骄傲。"),
        ("I know it feels hopeless, but we have to keep going.", "我知道感觉没有希望，但我们必须继续走下去。"),
        ("You are the strongest one here.", "你是这里最坚强的人。"),
        ("I'm so proud of you.", "我为你骄傲。"),
        ("Shh... Just hold on...", "嘘再撑一下"),
        ("I’m by your side, buddy, it’s gonna be okay...", "我就在你身边，伙计，会没事的"),
        ("None of this is your fault. Not any of this.", "这一切都不是你的错。一点都不是。"),
        ("Just keep breathing, slowly. You’re doing good...", "慢慢呼吸。你做得很好"),
        ("It’s going to be okay... everything's going to be okay...", "会好起来的一切都会好起来的"),
        ("Let's not give up just yet.", "先别放弃。"),
        ("Despite everything we’re still here, right?", "尽管经历了这一切，我们还在这里，对吧？"),
        ("I won’t let you get hurt again.", "我不会再让你受伤了。"),
        ("You're okay.", "你没事的。"),
        ("You'll be fine...", "你会没事的"),
        ("Come here.", "过来。"),
        ("It's gonna be okay...", "会好起来的"),
        ("I'm proud of you.", "我为你骄傲。"),
        ("You're gonna make it out.", "你会活着出去的。"),
        ("I love you, it'll be okay.", "我爱你，一切都会好的。"),
        ("You're not alone.", "你不是一个人。"),
        ("I'll stay near.", "我会待在附近。"),
        ("Here, you're okay...", "来，你没事的"),
        ("It's all good...", "一切都好"),
        ("I'm here, it'll be okay...", "我在这里，会好起来的"),
        ("Hug time!", "拥抱时间到！"),
        ("Charge me, doctor!", "给我充电，医生！"),
        ("Come here!", "过来！"),
        ("This is nice.", "这感觉真好。"),
        ("There are so many cool things here! I will never go back to the lab!", "这里有趣的东西太多了！我再也不回实验室了！"),
        ("You deserve a hug.", "你值得一个拥抱。"),
        ("I think you are amazing!", "我觉得你太棒了！"),
        ("You are like, so totally awesome.", "你简直酷毙了。"),
        ("I hope things stay like this.", "我希望日子能一直这样。"),
        ("Wasn't this supposed to be hard and depressing?", "这不该是又难又压抑的吗？"),
        ("We got this in the bag.", "我们胜券在握。"),
        ("Yippee!", "耶！"),
        ("Physical touch makes me feel all tingly.", "肢体接触让我浑身酥麻。"),
        ("I'm gonna touch you >:3", "我要摸你了 >:3"),
        ("So like... wanna make out?", "所以想亲一个吗？"),
        ("We are doing SO good.", "我们做得太棒了。"),
        ("I like your fur.", "我喜欢你的毛。"),
        ("This is WAY better than dying alone.", "这可比孤独地死去好太多了。"),
        ("Okay maybe life IS worth living.", "好吧，也许生活确实值得活下去。"),
        ("We're gonna make it. Probably.", "我们会出去的。大概吧。"),
        ("This almost makes me forget the horrors.", "这几乎让我忘了那些恐怖的事。"),
        ("You are officially my emotional support survivor.", "你正式成为我的情绪支持幸存者了。"),
        ("I cast emotional support!", "我施放情绪支持！"),
        ("We're doing great, sweetie!", "我们做得很好，亲爱的！"),
        ("Let's do this again later!", "我们待会儿再来一次！"),
        ("This place can't stop me from being silly!", "这地方阻止不了我犯傻！"),
        ("Wanna go blow up a life pod later?", "待会儿想去炸个维生舱吗？"),
        ("When we get back, let's escape and go on a roadtrip!", "等我们回去，一起逃出去来场公路旅行吧！"),
        ("The horrors persist but so do we!", "恐怖还在，但我们也在！"),
        ("We're doing amazing, sweetie.", "我们做得超棒，亲爱的。"),
        ("We're so back.", "我们回来了。"),
        ("Are you a blood bag? Because I feel empty without you.", "你是血袋吗？因为没有你我觉得空落落的。"),
        ("...!!!", "...！！！"),
        ("I think we deserve a little whimsy.", "我觉得我们值得一点小小的奇思妙想。"),
        ("We should do this before every near-death experience.", "我们应该在每次濒死体验前来一次这个。"),
        ("If we die horribly later, this was still worth it.", "就算之后死得很惨，这也值了。"),
        ("Wow. Serotonin. Haven't felt that since my handler passed away.", "哇。血清素。自从我的管理员去世后就没感受过了。"),
        ("I'm resisting the urge to start spinning in circles.", "我在努力忍住原地转圈的冲动。"),
        ("I'm choosing to believe everything will be okay.", "我选择相信一切都会好起来。"),
        ("Look at us. Surviving and everything.", "看看我们。活着，而且啥都有。"),
        ("I'm full of dangerous amounts of optimism.", "我充满了危险剂量的乐观。"),
        ("We are absolutely crushing this apocalypse thing.", "我们绝对是在末日里混得风生水起。"),
        ("Morale has increased by approximately five hundred percent.", "士气大约提升了百分之五百。"),
        ("Your fur is SO soft, wow.", "你的毛好软，哇。"),
        ("happy_responce_dialogie_option_27", "*开心的声音*"),
        ("*Happiness noises*", "*开心的声音*"),
        ("I wonder if I could suplex you.", "我在想我能不能把你过肩摔。"),
        ("Can you not crush me? Thanks.", "你能不能别压扁我？谢谢。"),
        ("Your breath stinks.", "你嘴巴好臭。"),
        ("...You smell like steak. Maybe I’m just hungry.", "你闻起来像牛排。可能我只是饿了。"),
        ("So... Come here often?", "所以常来吗？"),
        ("I wasn’t expecting that. I didn’t mean stop!", "我没料到这个。我不是让你停的意思！"),
        ("Oh nooooo, please don’t hug me agaiinnnnnnnn...", "噢不不不不，请别再抱我了啊啊啊啊..."),
        ("I’m proud of who we’ve become. Let’s be even better!", "我为我们现在的样子骄傲。让我们变得更好！"),
        ("Imagine if we could just LIVE after this, no experiments, no tests.", "想象一下这一切结束后我们能好好活着，没有实验，没有测试。"),
        ("We should totally cuddle.", "我们应该好好抱一抱。"),
        ("I love this... wait a minute-", "我喜欢这样等等—"),
        ("We're gonna make it!", "我们会成功的！"),
        ("Oh, I love this place!", "噢，我爱这个地方！"),
        ("Yawn... you're really warm, y'know?", "哈欠你真暖和，知道吗？"),
        ("Oof- didn't expect this, haha!", "哦—没想到会这样，哈哈！"),
        ("We should do this more!", "我们应该多这样做！"),
        ("Awwh...", "啊呜..."),
        ("We're doing amazing!", "我们干得太棒了！"),
        ("Doing great so far!", "到目前为止都很好！"),
        ("C'mere, you!", "过来，你！"),
        ("There, there.", "好啦，好啦。"),
        ("Oof- hey, you're crushing me! Haha!", "哦—嘿，你要把我压扁了！哈哈！"),
        ("Wanna share some food later?", "待会儿要一起吃点东西吗？"),
        ("You're so fluffy!", "你真毛茸茸！"),
        ("You're really soft...", "你真柔软"),
        ("Thank you!", "谢谢你！"),
        ("Thanks...", "谢谢..."),
        ("Wow, this is nice...", "哇，真不错"),
        ("Let's do this more often.", "我们以后多这样。"),
        ("There you go.", "这就对了。"),
        ("Alright, bring it in.", "好，来吧。"),
        ("Our captors would be so mad at us right now.", "抓我们的人现在肯定气坏了。"),
        ("No wonder this was agianst the rules.", "难怪这违反规则。"),
        ("Thanks.", "谢谢。"),
        ("Could be worse, right?", "还不算太糟，对吧？"),
        ("Can't wait to fuck up our captors!", "等不及要干翻那些抓我们的人了！"),
        ("This makes me feel a little less alone.", "这让我感觉没那么孤单了。"),
        ("Hope you are doing well.", "希望你还好。"),
        ("Is this how you thought we were going to end up?", "你想到过我们会落到这步田地吗？"),
        ("Crazy times we're living in.", "我们活着的时代真疯狂。"),
        ("I like this.", "我喜欢这样。"),
        ("Don't make it weird.", "别搞得太奇怪。"),
        ("You're warmer than I expected.", "你比我想象的暖和。"),
        ("This almost feels normal.", "这几乎感觉像正常日子了。"),
        ("This place really wears us down, huh.", "这地方真把我们耗得够呛，是吧。"),
        ("So, what did they put you through back on Earth?", "那么，他们在地球上对你做了什么？"),
        ("We keep going.", "我们继续前进。"),
        ("One step at a time.", "一步一步来。"),
        ("We got this.", "我们能行。"),
        ("If I lose you too, I might go insane.", "如果我也失去你，我可能会疯掉。"),
        ("I ever tell you about the time my buddy Keith told me he was picked up by some little green men and they--", "我跟你说过我哥们 Keith 被小绿人抓走的事吗，他们—"),
        ("Not too bad, right?", "还不赖，对吧？"),
        ("I really do not miss being beaten...", "我真的很怀念不被殴打的时光"),
        ("Our captors are probably really upset at us.", "抓我们的人现在大概很生我们的气。"),
        ("I watched my buddy get sawed in half on Earth, so somehow this is a step up.", "我在地球上亲眼看着哥们被锯成两半，所以这里反而算升级了。"),
        ("I don't know about you, but I needed that.", "我不知道你怎么样，但我需要这个。"),
        ("I ever tell you about the time my buddy Keith fell down an open manhole? He was unconscious down there for like a week. During that time, unbeknownst to Keith, they paved over him. Keith had to--", "我跟你说过我哥们基思掉进敞开的窨井的事吗？他在下面昏迷了大概一周。那期间，Keith 不知道，他们把他上面铺了路。Keith 不得不—"),
        ("Can't hurt to slow down for a second.", "慢下来一会儿也没坏处。"),
        ("I enjoy your company.", "我喜欢有你陪着。"),
        ("Just making sure you're still with me.", "只是想确认你还跟我在一起。"),
        ("Don't get used to this.", "别习惯这个。"),
        ("You're tougher than you look.", "你比看起来更结实。"),
        ("One decent moment in this mess.", "这团糟里难得的好时刻。"),
        ("Just be careful, stick together, and don't die.", "小心点，抱团，别死。"),
        ("Could be worse, honestly.", "说实话，本可以更糟。"),
        ("I'd miss you if you died, so don't do that.", "你要是死了我会想你的，所以别死。"),
        ("Being alone would suck down here.", "在这里独自一人会很糟。"),
        ("Better than dying alone, right?", "总比孤独地死好，对吧？"),
        ("Not dead yet.", "还没死。"),
        ("I'm glad you're alive.", "很高兴你还活着。"),
        ("Hang in there.", "撑住。"),
        ("Don't give up.", "别放弃。"),
        ("You're softer than the others.", "你比其他人都软。"),
        ("Just trying to keep morale up.", "只是想提振一下士气。"),
        ("You're doing alright.", "你做得还行。"),
        ("This place gets lonely fast. I appreciate you.", "这地方很快就让人感到孤独。感谢有你。"),
        ("I appreciate you.", "感谢有你。"),
        ("What do you think Earth is like?", "你觉得地球现在是什么样？"),
        ("Two can be one...", "两个人可以合为一体"),
        ("Well, now we both need a shower.", "好吧，现在我们俩都得洗个澡。"),
        ("Yeah, okay. Bring it in.", "行，来吧。抱一下。"),
        ("I kind of expected something else...", "我本来以为会是别的什么"),
        ("Let me get that for you.", "让我帮你弄那个。"),
        ("We’ve got places to be, but that can wait.", "我们还有地方要去，但那个可以等。"),
        ("Just making sure.", "只是想确认一下。"),
        ("Uh... I slipped?", "呃我滑了一下？"),
        ("Soft...", "软..."),
        ("You're fluffy.", "你真毛茸茸。"),
        ("Thanks... I feel better.", "谢谢...我感觉好多了。"),
        ("Cute...", "可爱..."),
        ("Warm...", "暖和..."),
        ("Hey, this is nice...", "嘿，真不错"),
        ("I feel better.", "我感觉好多了。"),
        ("Thank you!", "谢谢你！"),
        ("Lovely.", "真舒服。"),
        ("Nice!", "不错！"),
        ("Hug time!", "拥抱时间到！"),
        ("Oh, this feels amazing...", "噢，这感觉太棒了..."),
        ("Do you think the others are okay?", "你觉得其他人还好吗？"),
        ("I'd miss you if you died, y'know?", "你要是死了我会想你的，知道吗？"),
        ("We're doing okay.", "我们做得还行。"),
        ("Doing well so far...", "到目前为止还不错"),
        ("Not too bad.", "还不算太糟。"),
        ("We're okay, aren't we?", "我们还好，对吧？"),
        ("You okay?", "你还好吗？"),
        ("All good?", "都好吗？"),
    };
    public static readonly (string En, string Zh)[] CharacterLines =
    {
        ("selfharm", "Hahahaha... FUCK yeah... That's good..."),
        ("selfharm", "Thaaatttt's better... Ahahaha... Fucking amazing..."),
        ("selfharm", "Oh yeah... Fuck yeah... FUCK yeah..."),
        ("selfharm", "Mmhh... Fuck... Hahahaha... This is good..."),
        ("selfharm", "How do yoouuuu like that... Fucker... Ahaha... FUCK you... Fuck you... Good..."),
        ("selfharm", "Fuck me, hahah... That feels amazing..."),
        ("selfharm", "AAGH! FUCK YEAH! Fucking amazing..."),
        ("selfharm", "FUCK! HAHAHAHA! HELL FUCKING YEAH..!"),
        ("selfharm", "Just a little cut... More... Ahahah... Fuck..."),
        ("selfharm", "Ouch-... T-that's good... Fuck... That's great..."),
        ("selfharm", "FUCK! Hahaha! FUCK yeah! Hahahaha..."),
        ("selfharm", "That's what... you get... Dickhead... Fuck you... Hahahaha..."),
        ("selfharm", "There... we go... hahah... good..."),
        ("selfharm", "That'll.. fuck... Yeaaahhh... That'll do it... Haha..."),
        ("selfharm", "Y-Yeah... take that... Fucker... That'll hurt good..."),
        ("selfharm", "You deserve this... Haha... That hurts greeatt..."),
        ("selfharm", "AAHHAHA!! FUCK yeah... Fuck yeah. Hahaha... Hurts..."),
        ("selfharm", "Hahah... that's better... yeah... Much better..."),
        ("selfharm", "Theeeree we go... That hurts gooooood..."),
        ("selfharm", "Hehhehheh... that fucking hurts... hurts good..."),
        ("selfharm", "That... hahah... hurts good... Great..."),
        ("selfharm", "Let's not end this juuuussst yet... F-fuck... That's good..."),
        ("selfharm", "I don't need that flesh... Ggrhh... Haha... More of this..."),
        ("selfharm", "F-fuck... Ahahaha... Feels great..."),
        ("selfharm", "Goooooodd.... Mmmh... Finally... Finally... Fucking amazing... Mmmhh..."),
        ("selfharm", "M-maybe... Maybe I'll end it next time... Hahaha..."),
        ("suicide", "Goodbye. Good FUCKING BYE. I am DONE!!! FUCK ALL OF THIS!"),
        ("suicide", "I'm done. Fuck this, fuck me and FUCK you."),
        ("suicide", "I fucking told you. I TOLD you, you piece of shit. I'm DONE!"),
        ("suicide", "I'm leaving this shitty world once and for all."),
        ("suicide", "Peace. Bye. Fuck this. I'm fucking leaving. I'm going to hell for this."),
        ("suicide", "I have FUCKING had it with all of this. I am DONE! FUCK OFF!!!"),
        ("suicide", "End of the line, fucker. End of the fucking line. I'M OUT!!!"),
        ("suicide", "That should do it... Bye-bye... Sorry for this... I hope there's an afterlife for me..."),
        ("suicide", "This is the end. I hope whoever finds my corpse makes good use of me. I can't handle this anymore. I'm sorry."),
        ("suicide", "There's no point to this anymore. There NEVER fucking was. I'm ending it all. Fuck me... Fuck ALL of this."),
        ("suicide", "If slitting my wrists doesn't kill me, I'm going to gouge my own fucking eyes out, so I never have to see this horrible land ever again."),
        ("suicide", "I don't know what comes after, but I can finally rest... Let's relax now... There is no need for emotions anymore..."),
        ("suicide", "AHHHH! FUCK THIS! ALL OF THIS! I CAN'T TAKE IT ANYMORE! LET ME OUT OF HERE! I'M DONE!"),
        ("suicide", "That's it. I've FUCKING had it. I'm finally doing this... Peace. Fucking PEACE. I'm OUT."),
        ("suicide", "I have made the conscious decision to end my life, right here and right now. Farewell, dipshits."),
        ("suicide", "I told you... I TOLD YOU. Piece of shit... Fuck... Burn in the fucking depths of hell."),
        ("suicide", "I'll do better as a rotting corpse. My life ended the moment I was sent here. Goodbye."),
        ("suicide", "This is for fucking EVERYTHING! I'M DONE! AAAHHHH! FUCK ALL OF THIS!"),
        ("suicide", "I'm. I'm just... I'm done. No time for suicide notes. I'm so tired of all of this. Goodbye."),
        ("suicide", "N... no hard feelings... right?.. hah... I'm... I'm so tired... G-goodnight..."),
        ("suicide", "I'm not doing this anymore. I'm not. It's over. Bye. Ello. Fuck this."),
        ("suicide", "There never was any hope. FUCK. This. I'm OUT! LEAVE ME ALONE! I'M NOT LETTING THIS PLACE TAKE MY LIFE!"),
        ("suicide", "Looooook at that... Hahahah... I'm saying goodbye to this fucking universe... Leaving this world behind... It's... Relieving..."),
        ("suicide", "There... There it goes... Let's enjoy my last few moments now... Relax and... Fall asleep... One last time..."),
        ("suicide", "I hope you're happy with what you've done. Dipshit. Fuck you. FUCK YOU. Go to hell."),
        ("suicide", "There goes my wrist... It's all going to be over soon... Haha..."),
        ("suicide", "Fuck you. FUCK you. I'm DONE. I'M FUCKING DONE!"),
        ("suicide", "I am LEAVING this fucking place, whether I'm able to or NOT. FUCK YOU."),
        ("suicide", "FUCK this. It's fucking OVER. To hell with my life."),
        ("suicide", "To hell with this. I'm out. Piece of shit. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done."),
        ("suicide", "Piece of shit... I'm fucking done... Fuck this..."),
        ("suicide", "I'm leaving. I hope I'm not going to hell for this."),
        ("suicide", "They can find me as a desiccated corpse in a ditch. Like it fucking matters."),
        ("suicide", "None of this matters. This is a suicide mission. I'm not fucking going through any more of this."),
        ("suicide", "I've failed. I give up. Fuck this."),
        ("suicide", "Good fucking luck to anyone that comes here after me. Maybe my corpse will be of use to someone. I'm done."),
        ("suicide", "There never was any fucking point to this. I was sent here to die."),
        ("suicide", "They're getting what they fucking wanted."),
        ("suicide", "I didn't think I was ever actually going to do this... Haha... Ahahahaha... Cathartic..."),
        ("suicide", "I'm taking my life. Sorry. I can't. I fucking can't take it anymore. I'm so fucking sorry."),
        ("suicide", "I hope I end up in hell. Gonna be better than this fucking place. I can't. I'm out. Sorry. Fuck all of this."),
        ("suicide", "Bye. I'm out. I'll see everyone on the other side, down in the pits of hell."),
        ("suicide", "Fuck this. Fuck this. FUCK. This. I'M DONE! ENOUGH OF THIS."),
        ("suicide", "Sorry. I'm out. Bye. I'm sorry. I'm so fucking sorry. I can't."),
        ("catpatch_hug_vulnerable", "Thanks... I needed that."),
        ("catpatch_hug_vulnerable", "Can we stay like this for a second?"),
        ("catpatch_hug_vulnerable", "I'm not doing great."),
        ("catpatch_hug_vulnerable", "I'm so tired..."),
        ("catpatch_hug_vulnerable", "I don't think I've felt okay for a while."),
        ("catpatch_hug_vulnerable", "I don't want to... I can't be alone right now."),
        ("catpatch_hug_vulnerable", "I'm not a burden, am I?"),
        ("catpatch_hug_vulnerable", "This helps... a little..."),
        ("catpatch_hug_vulnerable", "I want to cry..."),
        ("catpatch_hug_vulnerable", "Everything feels wrong lately."),
        ("catpatch_hug_vulnerable", "I needed a reminder that somebody still cares."),
        ("catpatch_hug_vulnerable", "I've been holding everything in."),
        ("catpatch_hug_vulnerable", "I was starting to spiral again."),
        ("catpatch_hug_vulnerable", "Our captors will get what they fucking deserve."),
        ("catpatch_hug_vulnerable", "I think I might consider a mindwipe."),
        ("catpatch_hug_vulnerable", "I dreamt about our captors again last night... it was so vivid..."),
        ("catpatch_hug_vulnerable", "What did we do to deserve this?"),
        ("catpatch_hug_vulnerable", "I hate how much this place affects me."),
        ("catpatch_hug_vulnerable", "I'm scared of what I'm becoming in here."),
        ("catpatch_hug_vulnerable", "When I get my claws on them, they will know pain."),
        ("catpatch_hug_vulnerable", "I don't even recognize myself anymore."),
        ("catpatch_hug_vulnerable", "I'm really scared..."),
        ("catpatch_hug_vulnerable", "I can't lose you, too..."),
        ("catpatch_hug_vulnerable", "Please don't leave me..."),
        ("catpatch_hug_vulnerable", "I've lost so many... I can't lose you too."),
        ("catpatch_hug_vulnerable", "I'm trying really hard to keep going."),
        ("catpatch_hug_vulnerable", "There is no honest way out, huh."),
        ("catpatch_hug_vulnerable", "..."),
        ("catpatch_hug_vulnerable", "If something happens, please don’t forget about me."),
        ("catpatch_hug_vulnerable", "Will I even make it out..?"),
        ("catpatch_hug_vulnerable", "I hate this... I really do..."),
        ("catpatch_hug_vulnerable", "They don't know what I'm going through down here..."),
        ("catpatch_hug_vulnerable", "Is this what we are to them..?"),
        ("catpatch_hug_vulnerable", "This only delays the inevitable..."),
        ("catpatch_hug_vulnerable", "I can't die like this..."),
        ("catpatch_hug_vulnerable", "Are... Are we going to make it out..?"),
        ("catpatch_hug_vulnerable", "Please tell me we going to be okay..."),
        ("catpatch_hug_vulnerable", "Their salvation will be rotten..."),
        ("catpatch_hug_vulnerable", "I don't think this is enough.. but thank you."),
        ("catpatch_hug_vulnerable", "Please don't leave my side... at least until I'm okay."),
        ("catpatch_hug_vulnerable", "Will they toss us aside if we make it out? What will they do to us..?"),
        ("catpatch_hug_vulnerable", "I... I don't want to do this anymore..."),
        ("catpatch_hug_vulnerable", "I want to go somewhere else... anywhere but here..."),
        ("catpatch_hug_vulnerable", "I... Won't end up like the rest, right..?"),
        ("catpatch_hug_vulnerable", "Their bodies... mangled... stabbed... cold... why..?"),
        ("catpatch_hug_vulnerable", "I can't... keep going..."),
        ("catpatch_hug_vulnerable", "I don't want to end up like them..."),
        ("catpatch_hug_vulnerable", "Why are there so many of us down here..? So many... all dead."),
        ("catpatch_hug_vulnerable", "I can't stop crying..."),
        ("catpatch_hug_vulnerable", "I can't stop looking at the ground..."),
        ("catpatch_hug_vulnerable", "I'm scared of this place..."),
        ("catpatch_hug_vulnerable", "They won't get away with this.. I'll... I don't know..."),
        ("catpatch_hug_vulnerable", "What will we do once this is all over..?"),
        ("catpatch_hug_vulnerable", "I hate that I'm actually adapting to this place..."),
        ("catpatch_hug_vulnerable", "The traps... the lights... the corpses..."),
        ("catpatch_hug_vulnerable", "Why can't they just get it themselves instead of commiting a genocide..?"),
        ("catpatch_hug_vulnerable", "I'm sick of this place... I'm sick of it all."),
        ("catpatch_hug_vulnerable", "I feel like I'm not going to make it..."),
        ("catpatch_hug_vulnerable", "I won't fall victim like the rest, right..?"),
        ("catpatch_hug_vulnerable", "I want to wake up..."),
        ("catpatch_hug_vulnerable", "This is all a bad dream, right..?"),
        ("catpatch_hug_vulnerable", "Why would they... why..."),
        ("catpatch_hug_vulnerable", "I... please don't watch if I scratch myself..."),
        ("catpatch_hug_vulnerable", "You shouldn't care about someone as useless as me..."),
        ("catpatch_hug_vulnerable", "I'm just dead weight, aren't I..?"),
        ("catpatch_hug_vulnerable", "I'm not smart like a Milky and I'm not strong like a Dune... why bother..."),
        ("catpatch_hug_vulnerable", "I hate this place... why here of all places..."),
        ("catpatch_hug_vulnerable", "If this keeps up I might have to resort to my own way out of this place..."),
        ("catpatch_hug_vulnerable", "...I wish we could have stayed..."),
        ("catpatch_hug_vulnerable", "Just this once..."),
        ("catpatch_hug_vulnerable", "I can't even look up..."),
        ("catpatch_hug_vulnerable", "I'm not smart and I'm not strong... why bother..."),
        ("catpatch_hug_vulnerable", "If this keeps up I might have to..."),
        ("catpatch_hug_vulnerable", "I'm exhausted."),
        ("catpatch_hug_vulnerable", "I'm so sick of this place."),
        ("catpatch_hug_vulnerable", "I hate this place."),
        ("catpatch_hug_vulnerable", "I hate myself..."),
        ("catpatch_hug_vulnerable", "Please tell me we're going to be okay."),
        ("catpatch_hug_vulnerable", "I'm trying... I'm trying so hard..."),
        ("catpatch_hug_vulnerable", "I'm trying not to cry, okay..?"),
        ("catpatch_hug_vulnerable", "I don't want to die..."),
        ("catpatch_hug_vulnerable", "I couldn't care less about the cargo."),
        ("catpatch_hug_vulnerable", "Thank you... Thank you..."),
        ("catpatch_hug_vulnerable", "...Okay..."),
        ("catpatch_hug_comfort", "You looked like you needed this."),
        ("catpatch_hug_comfort", "It's okay, even thought it's not, just know I'll be here for you."),
        ("catpatch_hug_comfort", "You've been carrying too much alone."),
        ("catpatch_hug_comfort", "You know I care about you."),
        ("catpatch_hug_comfort", "Hey, hey, it's okay. I'm here."),
        ("catpatch_hug_comfort", "Come here..."),
        ("catpatch_hug_comfort", "If you need to cry, I understand. I'm here for you."),
        ("catpatch_hug_comfort", "I'll be here for you, no matter what."),
        ("catpatch_hug_comfort", "If you need a shoulder to cry on, I'm here."),
        ("catpatch_hug_comfort", "Don't worry, I've got you."),
        ("catpatch_hug_comfort", "I know that look. I've had it too."),
        ("catpatch_hug_comfort", "Just rest your head for a second."),
        ("catpatch_hug_comfort", "I hope our captors are burning in hell for this."),
        ("catpatch_hug_comfort", "Our captors can go fuck themselves."),
        ("catpatch_hug_comfort", "Our captors can go to hell."),
        ("catpatch_hug_comfort", "Fuck 'em."),
        ("catpatch_hug_comfort", "When we get back, we will make them pay, don't worry."),
        ("catpatch_hug_comfort", "You don't have to handle this alone."),
        ("catpatch_hug_comfort", "Don't let this place win."),
        ("catpatch_hug_comfort", "You shouldn't have to go through this alone."),
        ("catpatch_hug_comfort", "Hey... breathe, alright? I'm here now."),
        ("catpatch_hug_comfort", "Smoke 'em if you got 'em..."),
        ("catpatch_hug_comfort", "I’m not gonna leave you. I’m right here."),
        ("catpatch_hug_comfort", "We are in this together, remember?"),
        ("catpatch_hug_comfort", "I know it’s hard, but we can get through this. Together."),
        ("catpatch_hug_comfort", "I’m not going anywhere. I’ve got you."),
        ("catpatch_hug_comfort", "I know you're scared, but we'll make it through this. I promise."),
        ("catpatch_hug_comfort", "I wish I could make it all better, but I can’t. I care about you and I’m here for you."),
        ("catpatch_hug_comfort", "I know this place is awful, but you’re not alone. I’m here with you."),
        ("catpatch_hug_comfort", "You’re doing the best you can, and that’s all anyone can ask of you. I’m proud of you."),
        ("catpatch_hug_comfort", "You are so strong, I'm so proud of you."),
        ("catpatch_hug_comfort", "I know it feels hopeless, but we have to keep going."),
        ("catpatch_hug_comfort", "You are the strongest one here."),
        ("catpatch_hug_comfort", "I'm so proud of you."),
        ("catpatch_hug_comfort", "Shh... Just hold on..."),
        ("catpatch_hug_comfort", "I’m by your side, buddy, it’s gonna be okay..."),
        ("catpatch_hug_comfort", "None of this is your fault. Not any of this."),
        ("catpatch_hug_comfort", "Just keep breathing, slowly. You’re doing good..."),
        ("catpatch_hug_comfort", "It’s going to be okay... everything's going to be okay..."),
        ("catpatch_hug_comfort", "Let's not give up just yet."),
        ("catpatch_hug_comfort", "Despite everything we’re still here, right?"),
        ("catpatch_hug_comfort", "I won’t let you get hurt again."),
        ("catpatch_hug_comfort", "You're okay."),
        ("catpatch_hug_comfort", "You'll be fine..."),
        ("catpatch_hug_comfort", "Come here."),
        ("catpatch_hug_comfort", "It's gonna be okay..."),
        ("catpatch_hug_comfort", "I'm proud of you."),
        ("catpatch_hug_comfort", "You're gonna make it out."),
        ("catpatch_hug_comfort", "I love you, it'll be okay."),
        ("catpatch_hug_comfort", "You're not alone."),
        ("catpatch_hug_comfort", "I'll stay near."),
        ("catpatch_hug_comfort", "Here, you're okay..."),
        ("catpatch_hug_comfort", "It's all good..."),
        ("catpatch_hug_comfort", "I'm here, it'll be okay..."),
        ("catpatch_hug_cheerful", "Hug time!"),
        ("catpatch_hug_cheerful", "Charge me, doctor!"),
        ("catpatch_hug_cheerful", "Come here!"),
        ("catpatch_hug_cheerful", "This is nice."),
        ("catpatch_hug_cheerful", "There are so many cool things here! I will never go back to the lab!"),
        ("catpatch_hug_cheerful", "You deserve a hug."),
        ("catpatch_hug_cheerful", "I think you are amazing!"),
        ("catpatch_hug_cheerful", "You are like, so totally awesome."),
        ("catpatch_hug_cheerful", "I hope things stay like this."),
        ("catpatch_hug_cheerful", "Wasn't this supposed to be hard and depressing?"),
        ("catpatch_hug_cheerful", "We got this in the bag."),
        ("catpatch_hug_cheerful", "Yippee!"),
        ("catpatch_hug_cheerful", "Physical touch makes me feel all tingly."),
        ("catpatch_hug_cheerful", "I'm gonna touch you >:3"),
        ("catpatch_hug_cheerful", "So like... wanna make out?"),
        ("catpatch_hug_cheerful", "We are doing SO good."),
        ("catpatch_hug_cheerful", "I like your fur."),
        ("catpatch_hug_cheerful", "This is WAY better than dying alone."),
        ("catpatch_hug_cheerful", "Okay maybe life IS worth living."),
        ("catpatch_hug_cheerful", "We're gonna make it. Probably."),
        ("catpatch_hug_cheerful", "This almost makes me forget the horrors."),
        ("catpatch_hug_cheerful", "You are officially my emotional support survivor."),
        ("catpatch_hug_cheerful", "I cast emotional support!"),
        ("catpatch_hug_cheerful", "We're doing great, sweetie!"),
        ("catpatch_hug_cheerful", "Let's do this again later!"),
        ("catpatch_hug_cheerful", "This place can't stop me from being silly!"),
        ("catpatch_hug_cheerful", "Wanna go blow up a life pod later?"),
        ("catpatch_hug_cheerful", "When we get back, let's escape and go on a roadtrip!"),
        ("catpatch_hug_cheerful", "The horrors persist but so do we!"),
        ("catpatch_hug_cheerful", "We're doing amazing, sweetie."),
        ("catpatch_hug_cheerful", "We're so back."),
        ("catpatch_hug_cheerful", "Are you a blood bag? Because I feel empty without you."),
        ("catpatch_hug_cheerful", "...!!!"),
        ("catpatch_hug_cheerful", "I think we deserve a little whimsy."),
        ("catpatch_hug_cheerful", "We should do this before every near-death experience."),
        ("catpatch_hug_cheerful", "If we die horribly later, this was still worth it."),
        ("catpatch_hug_cheerful", "Wow. Serotonin. Haven't felt that since my handler passed away."),
        ("catpatch_hug_cheerful", "I'm resisting the urge to start spinning in circles."),
        ("catpatch_hug_cheerful", "I'm choosing to believe everything will be okay."),
        ("catpatch_hug_cheerful", "Look at us. Surviving and everything."),
        ("catpatch_hug_cheerful", "I'm full of dangerous amounts of optimism."),
        ("catpatch_hug_cheerful", "We are absolutely crushing this apocalypse thing."),
        ("catpatch_hug_cheerful", "Morale has increased by approximately five hundred percent."),
        ("catpatch_hug_cheerful", "Your fur is SO soft, wow."),
        ("catpatch_hug_cheerful", "happy_responce_dialogie_option_27"),
        ("catpatch_hug_cheerful", "*Happiness noises*"),
        ("catpatch_hug_cheerful", "I wonder if I could suplex you."),
        ("catpatch_hug_cheerful", "Can you not crush me? Thanks."),
        ("catpatch_hug_cheerful", "Your breath stinks."),
        ("catpatch_hug_cheerful", "...You smell like steak. Maybe I’m just hungry."),
        ("catpatch_hug_cheerful", "So... Come here often?"),
        ("catpatch_hug_cheerful", "I wasn’t expecting that. I didn’t mean stop!"),
        ("catpatch_hug_cheerful", "Oh nooooo, please don’t hug me agaiinnnnnnnn..."),
        ("catpatch_hug_cheerful", "I’m proud of who we’ve become. Let’s be even better!"),
        ("catpatch_hug_cheerful", "Imagine if we could just LIVE after this, no experiments, no tests."),
        ("catpatch_hug_cheerful", "We should totally cuddle."),
        ("catpatch_hug_cheerful", "I love this... wait a minute-"),
        ("catpatch_hug_cheerful", "We're gonna make it!"),
        ("catpatch_hug_cheerful", "Oh, I love this place!"),
        ("catpatch_hug_cheerful", "Yawn... you're really warm, y'know?"),
        ("catpatch_hug_cheerful", "Oof- didn't expect this, haha!"),
        ("catpatch_hug_cheerful", "We should do this more!"),
        ("catpatch_hug_cheerful", "Awwh..."),
        ("catpatch_hug_cheerful", "We're doing amazing!"),
        ("catpatch_hug_cheerful", "Doing great so far!"),
        ("catpatch_hug_cheerful", "C'mere, you!"),
        ("catpatch_hug_cheerful", "There, there."),
        ("catpatch_hug_cheerful", "Oof- hey, you're crushing me! Haha!"),
        ("catpatch_hug_cheerful", "Wanna share some food later?"),
        ("catpatch_hug_cheerful", "You're so fluffy!"),
        ("catpatch_hug_cheerful", "You're really soft..."),
        ("catpatch_hug_cheerful", "Thank you!"),
        ("catpatch_hug_cheerful", "Thanks..."),
        ("catpatch_hug_cheerful", "Wow, this is nice..."),
        ("catpatch_hug_cheerful", "Let's do this more often."),
        ("catpatch_hug_neutral", "There you go."),
        ("catpatch_hug_neutral", "Alright, bring it in."),
        ("catpatch_hug_neutral", "Our captors would be so mad at us right now."),
        ("catpatch_hug_neutral", "No wonder this was agianst the rules."),
        ("catpatch_hug_neutral", "This is nice."),
        ("catpatch_hug_neutral", "Thanks."),
        ("catpatch_hug_neutral", "Could be worse, right?"),
        ("catpatch_hug_neutral", "Can't wait to fuck up our captors!"),
        ("catpatch_hug_neutral", "This makes me feel a little less alone."),
        ("catpatch_hug_neutral", "Hope you are doing well."),
        ("catpatch_hug_neutral", "Is this how you thought we were going to end up?"),
        ("catpatch_hug_neutral", "Crazy times we're living in."),
        ("catpatch_hug_neutral", "I like this."),
        ("catpatch_hug_neutral", "Don't make it weird."),
        ("catpatch_hug_neutral", "You're warmer than I expected."),
        ("catpatch_hug_neutral", "This almost feels normal."),
        ("catpatch_hug_neutral", "This place really wears us down, huh."),
        ("catpatch_hug_neutral", "So, what did they put you through back on Earth?"),
        ("catpatch_hug_neutral", "We keep going."),
        ("catpatch_hug_neutral", "One step at a time."),
        ("catpatch_hug_neutral", "We got this."),
        ("catpatch_hug_neutral", "If I lose you too, I might go insane."),
        ("catpatch_hug_neutral", "I ever tell you about the time my buddy Keith told me he was picked up by some little green men and they--"),
        ("catpatch_hug_neutral", "Not too bad, right?"),
        ("catpatch_hug_neutral", "I really do not miss being beaten..."),
        ("catpatch_hug_neutral", "Our captors are probably really upset at us."),
        ("catpatch_hug_neutral", "I watched my buddy get sawed in half on Earth, so somehow this is a step up."),
        ("catpatch_hug_neutral", "I don't know about you, but I needed that."),
        ("catpatch_hug_neutral", "I ever tell you about the time my buddy Keith fell down an open manhole? He was unconscious down there for like a week. During that time, unbeknownst to Keith, they paved over him. Keith had to--"),
        ("catpatch_hug_neutral", "Can't hurt to slow down for a second."),
        ("catpatch_hug_neutral", "I enjoy your company."),
        ("catpatch_hug_neutral", "Just making sure you're still with me."),
        ("catpatch_hug_neutral", "Don't get used to this."),
        ("catpatch_hug_neutral", "You're tougher than you look."),
        ("catpatch_hug_neutral", "One decent moment in this mess."),
        ("catpatch_hug_neutral", "Just be careful, stick together, and don't die."),
        ("catpatch_hug_neutral", "Could be worse, honestly."),
        ("catpatch_hug_neutral", "I'd miss you if you died, so don't do that."),
        ("catpatch_hug_neutral", "Being alone would suck down here."),
        ("catpatch_hug_neutral", "Better than dying alone, right?"),
        ("catpatch_hug_neutral", "Not dead yet."),
        ("catpatch_hug_neutral", "I'm glad you're alive."),
        ("catpatch_hug_neutral", "Hang in there."),
        ("catpatch_hug_neutral", "Don't give up."),
        ("catpatch_hug_neutral", "You're softer than the others."),
        ("catpatch_hug_neutral", "Just trying to keep morale up."),
        ("catpatch_hug_neutral", "You're doing alright."),
        ("catpatch_hug_neutral", "This place gets lonely fast. I appreciate you."),
        ("catpatch_hug_neutral", "I appreciate you."),
        ("catpatch_hug_neutral", "What do you think Earth is like?"),
        ("catpatch_hug_neutral", "Two can be one..."),
        ("catpatch_hug_neutral", "Well, now we both need a shower."),
        ("catpatch_hug_neutral", "Yeah, okay. Bring it in."),
        ("catpatch_hug_neutral", "I kind of expected something else..."),
        ("catpatch_hug_neutral", "Let me get that for you."),
        ("catpatch_hug_neutral", "We’ve got places to be, but that can wait."),
        ("catpatch_hug_neutral", "Just making sure."),
        ("catpatch_hug_neutral", "Uh... I slipped?"),
        ("catpatch_hug_neutral", "Soft..."),
        ("catpatch_hug_neutral", "You're fluffy."),
        ("catpatch_hug_neutral", "Thanks... I feel better."),
        ("catpatch_hug_neutral", "Cute..."),
        ("catpatch_hug_neutral", "Warm..."),
        ("catpatch_hug_neutral", "Hey, this is nice..."),
        ("catpatch_hug_neutral", "I feel better."),
        ("catpatch_hug_neutral", "Thank you!"),
        ("catpatch_hug_neutral", "Lovely."),
        ("catpatch_hug_neutral", "Nice!"),
        ("catpatch_hug_neutral", "Hug time!"),
        ("catpatch_hug_neutral", "Oh, this feels amazing..."),
        ("catpatch_hug_neutral", "Do you think the others are okay?"),
        ("catpatch_hug_neutral", "I'd miss you if you died, y'know?"),
        ("catpatch_hug_neutral", "We're doing okay."),
        ("catpatch_hug_neutral", "Doing well so far..."),
        ("catpatch_hug_neutral", "Not too bad."),
        ("catpatch_hug_neutral", "We're okay, aren't we?"),
        ("catpatch_hug_neutral", "You okay?"),
        ("catpatch_hug_neutral", "All good?"),
    };
}
