internal static class CatPatchTrTw
{
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Someone else is already helping that player.", "已經有別人在幫助這位玩家了。"),
        ("That rescue window has closed.", "救援窗口已經關閉。"),
        ("That rescue attempt was not accepted by the host.", "主機沒有接受這次救援嘗試。"),
        ("Rescue target is no longer valid.", "救援目標已失效。"),
        ("Cannot rescue right now.", "現在無法救援。"),
        ("Need close range and clear line of sight.", "需要近距離且視線清晰。"),
        ("You stopped the self-harm.", "你制止了自殘行為。"),
        ("Rescue failed.", "救援失敗。"),
        ("The gun was knocked away.", "槍被踢飛了。"),
        ("Self-harm stopped.", "自殘行為已制止。"),
        ("Target is invalid.", "目標無效。"),
        ("Too slow.", "太慢了。"),
        ("Rescue canceled.", "救援已取消。"),
        ("Swipe faster and more sideways.", "滑得更快、更偏向側面一些。"),
        ("Hug accepted.", "擁抱請求已接受。"),
        ("Hug rejected.", "擁抱請求被拒絕。"),
        ("This server uses a newer CatPatch version. Please update CatPatch to use hugs here.", "該服務器使用更新版本的 CatPatch。請更新 CatPatch 以在這裡使用擁抱功能。"),
        ("Dogpile sleep boost activated. Sleep quality: Good.", "疊羅漢睡眠加成已激活。睡眠質量：良好。"),
        ("Some clients did not acknowledge your spray. They may not have CatPatch installed or updated.", "部分客戶端未確認你的噴漆。他們可能沒有安裝或更新 CatPatch。"),
        ("Spray failed to upload.", "噴漆上傳失敗。"),
        ("Spray failed: backend unreachable. Check DNS, VPN, firewall, or internet.", "噴漆失敗：無法連接後端。請檢查 DNS、VPN、防火牆或網絡。"),
        ("Spray does not have local or downloaded GIF data.", "該噴漆沒有本地或已下載的 GIF 數據。"),
        ("No spray selected.", "未選擇噴漆。"),
        ("The source spray file is empty.", "源噴漆文件為空。"),
        ("This spray has no image bytes available to save.", "該噴漆沒有可保存的圖像數據。"),
        ("Mr CatPatch has joined.", "CatPatch 先生加入了。"),
        ("Cannot request hug: local body not found.", "無法發起擁抱請求：未找到本地身體。"),
        ("Cannot request hug: local body is not huggable.", "無法發起擁抱請求：本地身體無法被擁抱。"),
        ("Cannot request hug: no nearby huggable target found.", "無法發起擁抱請求：附近沒有可擁抱的目標。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("Sending hug request to {0}...", "正在向 {0} 發送擁抱請求..."),
        ("{0} wants to hug. Press {1} to accept or {2} to reject.", "{0} 想擁抱你。按 {1} 接受，按 {2} 拒絕。"),
        ("{0} wants to kiss. Press {1} to accept or {2} to reject.", "{0} 想親吻你。按 {1} 接受，按 {2} 拒絕。"),
        ("Host spray cooldown: {0}s remaining.", "主機噴漆冷卻中：剩餘 {0} 秒。"),
        ("Your sprays are muted by the host for {0}s.", "你的噴漆被主機禁用了 {0} 秒。"),
        ("Spray failed: {0}", "噴漆失敗：{0}"),
        ("Saved spray to {0}.", "噴漆已保存到 {0}。"),
        ("Host does not appear to have CatPatch. {0} is disabled on this server.", "主機似乎沒有安裝 CatPatch。本服務器已禁用 {0}。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("CatPatch is loaded!", "CatPatch 已加載！"),
        ("CatPatch Host Moderation is only available in a world for the multiplayer host or in singleplayer.", "CatPatch 主機管理僅在多人主機所在的世界或單人模式中可用。"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("No players matched {0}.", "沒有玩家匹配 {0}。"),
        ("Could not act on players matching {0}.", "無法對匹配 {0} 的玩家執行操作。"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Opens or closes the CatPatch Host Moderation menu.", "【CatPatch】打開或關閉 CatPatch 主機管理菜單。"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("Checking for CatPatch updates...", "正在檢查 CatPatch 更新..."),
        ("Downloading CatPatch {0}...", "正在下載 CatPatch {0}..."),
        ("CatPatch {0} is available :)", "CatPatch {0} 有新版本可用 :)"),
        ("CatPatch is up to date.", "CatPatch 已是最新版本。"),
        ("CatPatch update check unavailable. :( all my hard work", "無法檢查 CatPatch 更新。:( 我所有的辛苦"),
        ("CatPatch update downloaded. Click Apply & Quit to replace the DLL after the game closes.", "CatPatch 更新已下載。點擊“應用＆退出”，遊戲關閉後將替換 DLL。"),
        ("CatPatch update downloaded. Close the game, then extract the BepInEx folder from the zip into your game folder.", "CatPatch 更新已下載。關閉遊戲，然後把壓縮包裡的 BepInEx 文件夾解壓到你的遊戲目錄。"),
        ("CatPatch update download failed.", "CatPatch 更新下載失敗。"),
        ("Automatic replacement only supports direct CatPatch.dll downloads.", "自動替換僅支持直接下載 CatPatch.dll 的方式。"),
        ("Starting CatPatch update helper...", "正在啟動 CatPatch 更新助手..."),
        ("CatPatch update helper started. Quitting game...", "CatPatch 更新助手已啟動。正在退出遊戲..."),
        ("Failed to start CatPatch update helper. All my hard work :(", "無法啟動 CatPatch 更新助手。我所有的辛苦 :("),
        ("CatPatch Update Available", "CatPatch 更新可用"),
        ("CatPatch {0} is available. You currently have {1}.", "CatPatch {0} 有新版本可用。你當前版本為 {1}。"),
        ("Changelog", "更新日誌"),
        ("Downloaded to:", "已下載到："),
        ("Download", "下載"),
        ("Apply & Quit", "應用＆退出"),
        ("Later", "稍後"),
        ("Update manifest URL is empty. Meow failed, kill him with sticks", "更新清單 URL 為空。Meow 搞砸了，拿棍子揍他"),
        ("Update manifest was empty. Uh i dunno lol", "更新清單為空。呃，我也不知道，哈哈"),
        ("Update manifest is missing latest_version. thats weird", "更新清單缺少 latest_version。真奇怪"),
        ("Update manifest is missing download_url. :blush:", "更新清單缺少 download_url。:blush:"),
        ("Update manifest is missing sha256. hmmmmm", "更新清單缺少 sha256。呃呃呃呃"),
        ("Downloaded update failed SHA-256 verification.", "下載的更新未通過 SHA-256 校驗。"),
        ("Cat\nPatch", "Cat\nPatch"),
        ("CatPatch Client Settings", "CatPatch 客戶端設置"),
        ("Client Preferences", "客戶端偏好"),
        ("Show sprays", "顯示噴漆"),
        ("Updates", "更新"),
        ("Check Now for Update", "立即檢查更新"),
        ("Installed: 1.0.4", "已安裝：1.0.4"),
        ("Latest: ", "最新版本："),
        ("Error: {0}", "錯誤：{0}"),
        ("Suggest a feature, join the discord", "提建議？加入 Discord"),
        ("Host settings moved. Open server and click Host Moderation on the left.\n\n\nDEFAULT KEYBINDS:\n\nH: Hug\nG: Spray\nI: Inspect Spray", "“主機設置”已移動。打開服務器，點擊左側的“主機管理”。\n\n\n默認按鍵：\n\nH：擁抱\nG：噴漆\nI：檢查噴漆"),
        ("Host Moderation", "主機管理"),
        ("Sections", "欄目"),
        ("Player Actions", "玩家操作"),
        ("Banned Steam IDs", "已封禁的 Steam ID"),
        ("Spray Moderation", "噴漆管理"),
        ("Server Mutes", "服務器禁言"),
        ("MFC Presets", "MFC 預設"),
        ("status", "狀態"),
        ("Actions", "操作"),
        ("Players", "玩家"),
        ("Sprays", "噴漆"),
        ("Bans", "封禁"),
        ("Run Settings", "運行設置"),
        ("Connected players: ", "已連接玩家："),
        ("Singleplayer: actions affect the local player only.", "單人模式：操作僅影響本地玩家。"),
        ("Host a lobby to use moderation actions.", "創建大廳才能使用管理操作。"),
        ("No access. Host a lobby to use this menu.", "無權限。創建大廳才能使用此菜單。"),
        ("This section will be rebuilt without the old backend dependencies.", "該部分將在不依賴舊有後端組件的情況下重建。"),
        ("No players connected.", "沒有玩家連接。"),
        ("Singleplayer", "單人模式"),
        ("Working", "運行中"),
        ("Host only", "僅主機"),
        ("players: ", "玩家："),
        ("THE VOICES ARE WINNING TODAY!!!!!!!1", "今天勝利屬於聲音們！！！！！！1"),
        ("Target", "目標"),
        ("host command target", "主機命令目標"),
        ("Ban list is unavailable. Host a lobby first.", "封禁列表不可用。請先創建大廳。"),
        ("Ban list is unavailable.", "封禁列表不可用。"),
        ("None", "無"),
        ("IP/name fallback ban", "IP/名稱兜底封禁"),
        ("Steam ban", "Steam 封禁"),
        ("You can mute annoying people here", "你可以在這裡禁言討厭的人"),
        ("Sleeping on others gives good quality sleep?", "睡在別人身上能獲得高質量睡眠？"),
        ("Shove key throws the player on your back", "按推鍵將玩家背起"),
        ("This makes for any vile combo of traps.", "這能組合出各種惡毒的陷阱。"),
        ("Enable challenge mode", "啟用挑戰模式"),
        ("Allow floating landmines", "允許浮空地雷"),
        ("Random spike trap orientation", "隨機尖刺陷阱朝向"),
        ("Hazard categories", "危險分類"),
        ("Starter kit item IDs", "初始套件物品 ID"),
        ("Export a setup or paste one here to import it.", "導出配置或在此粘貼以導入。"),
        ("Elder thornbacks", "長老棘背獸"),
        ("Tp To You", "傳送到你"),
        ("Tp To Them", "傳送到Ta"),
        ("Heal/Revive", "治療/復活"),
        ("Kill", "殺死"),
        ("Knock Out", "擊暈"),
        ("Drop Inventory", "丟棄全部物品"),
        ("Explode", "爆炸"),
        ("Obliterate", "抹除"),
        ("Mindwipe", "精神抹除"),
        ("Skin", "剝皮"),
        ("Stub toe", "絆腳趾"),
        ("Fling", "拋飛"),
        ("Last Stand", "背水一戰"),
        ("Kick, Ban, Admin", "踢出、封禁、管理員"),
        ("Admin", "管理員"),
        ("Unadmin", "取消管理員"),
        ("Kick", "踢出"),
        ("Ban", "封禁"),
        ("Unban", "解除封禁"),
        ("Mute", "禁言"),
        ("Unmute", "解除禁言"),
        ("Clear", "清除"),
        ("Clear all", "全部清除"),
        ("Enabled", "已啟用"),
        ("Disabled", "已禁用"),
        ("Enable", "啟用"),
        ("Disable", "禁用"),
        ("Hide", "隱藏"),
        ("Show", "顯示"),
        ("Export", "導出"),
        ("Copy", "複製"),
        ("Import", "導入"),
        ("Chat On", "開啟聊天"),
        ("Chat Off", "關閉聊天"),
        ("VC On", "開啟語音"),
        ("VC Off", "關閉語音"),
        ("Mute All", "全部禁言"),
        ("Unmute All", "全部解除"),
        ("Muted (", "已禁言（"),
        ("s)", "秒）"),
        ("Allowed", "已允許"),
        ("Mute minutes:", "禁言分鐘："),
        ("Cooldown", "冷卻"),
        ("Throw strength", "拋擲力度"),
        ("Trap amount", "陷阱數量"),
        ("Dogpile Sleep", "疊羅漢睡眠"),
        ("Piggyback Throw", "揹人拋擲"),
        ("Meow's final challenge", "Meow 的終極挑戰"),
        ("  |  ping ", "  |  延遲 "),
        (" (ping ", "（延遲 "),
        ("chat: ", "聊天："),
        ("   vc: ", "   語音："),
        ("muted", "已禁言"),
        ("ok", "正常"),
        ("Host only action.", "僅主機操作。"),
        ("Host only.", "僅主機。"),
        ("Host cannot kick themselves.", "主機不能踢自己。"),
        ("Kicked by host.", "已被主機踢出。"),
        ("Kicked ", "已踢出 "),
        ("Host cannot ban themselves.", "主機不能封禁自己。"),
        ("Cannot ban ", "無法封禁 "),
        (": Steam ID unavailable.", "：Steam ID 不可用。"),
        ("Banned by host.", "已被主機封禁。"),
        ("Banned ", "已封禁 "),
        ("Unbanned: ", "已解除封禁："),
        ("Failed to unban: ", "解除封禁失敗："),
        ("Clear failed: ", "清除失敗："),
        ("Spray mute failed: ", "噴漆禁言失敗："),
        ("Spray clear failed: ", "噴漆清除失敗："),
        ("Spray muted client {0} for {1:0.##} minute(s).", "已將客戶端 {0} 噴漆禁言 {1:0.##} 分鐘。"),
        ("Spray unmuted client ", "噴漆未禁言客戶端 "),
        (" is not spray muted.", " 未被噴漆禁言。"),
        ("Client ", "客戶端 "),
        ("Muted chat and voice for client ", "已禁聊天和語音客戶端 "),
        ("Unmuted chat and voice for client ", "已解聊天和語音客戶端 "),
        ("Host cannot be muted.", "主機不能被禁言。"),
        (" muted client ", " 禁言了客戶端 "),
        (" unmuted client ", " 解除了客戶端 "),
        ("Chat", "聊天"),
        ("Voice", "語音"),
        ("Local player body not found.", "未找到本地玩家身體。"),
        ("Local host player not found.", "未找到本地主機玩家。"),
        ("Local host player id not found.", "未找到本地主機玩家 ID。"),
        ("Player not found.", "未找到玩家。"),
        ("Player id is out of range.", "玩家 ID 超出範圍。"),
        ("Player body not found.", "未找到玩家身體。"),
        ("Left foot limb not found.", "未找到左腳肢體。"),
        ("Only host can change admin.", "只有主機能更改管理員。"),
        ("Host admin cannot be changed.", "主機管理員不可更改。"),
        ("Admin toggle failed: ", "管理員切換失敗："),
        ("Granted admin to ", "已將管理員授予 "),
        ("Removed admin from ", "已移除管理員 "),
        ("Teleported ", "已傳送 "),
        (" to you.", " 到你身邊。"),
        ("Teleported you to ", "已將你傳送到 "),
        ("Revived ", "已復活 "),
        ("Killed ", "已擊殺 "),
        ("Knocked out ", "已擊暈 "),
        ("Dropped inventory for ", "已丟棄 "),
        ("Boom on ", "爆炸了 "),
        ("head", "頭部"),
        ("arm", "手臂"),
        ("hand", "手"),
        ("leg", "腿"),
        ("foot", "腳"),
        ("Obliterated ", "已抹除 "),
        (" limbs).", " 個肢體）。"),
        ("Mindwiped ", "已精神抹除"),
        ("Skinned ", "已剝皮 "),
        ("Stubbed toe for ", "絆了 "),
        ("Flung ", "已拋飛 "),
        (" cannot Last Stand right now.", " 現在無法背水一戰。"),
        ("Forced Last Stand for ", "已強制背水一戰 "),
        ("Last Stand is disabled by the multiplayer rules.", "多人模式規則禁用了背水一戰。"),
        ("Mute action failed.", "禁言操作失敗。"),
        ("Voice mute action failed.", "語音禁言操作失敗。"),
        ("Exported MFC preset.", "已導出 MFC 預設。"),
        ("Copied MFC preset.", "已複製 MFC 預設。"),
        ("Preset text is empty.", "預設文本為空。"),
        ("Player ", "玩家 "),
        (".", "。"),
        ("Regular Traps", "普通陷阱"),
        ("Enemies", "敵人"),
        ("Environmental Hazards", "環境危害"),
        ("Radioactive Hazards", "放射性危害"),
        ("Hazards", "危害"),
        ("Spike stabber", "尖刺陷阱"),
        ("Barbed wire", "鐵絲網"),
        ("Bear trap", "捕獸夾"),
        ("Jump pad", "彈射陷阱"),
        ("Landmine", "地雷"),
        ("Gunmine", "槍地雷"),
        ("Sawblade", "圓鋸片"),
        ("Sound cannon", "音波炮"),
        ("Coil", "線圈"),
        ("Turret", "自動炮塔"),
        ("Tick swarm", "蜱蟲群"),
        ("Wall biter", "咬牆蟲"),
        ("Shade crawler", "暗影爬行者"),
        ("Thornback", "棘背獸"),
        ("Overgrown tick", "巨型蜱蟲"),
        ("Grabber plant", "抓纏草"),
        ("Skull crusher", "碎顱者"),
        ("Geyser", "間歇泉"),
        ("Oil pipe", "廢液管"),
        ("Glass shards", "玻璃碎片"),
        ("Rad barrel", "輻射桶"),
        ("Spent fuel", "乏燃料"),
        (" wants to hug.", " 想擁抱你。"),
        (" wants to kiss.", " 想親吻你。"),
        (" to accept, or ", " 接受、按 "),
        (" to reject.", " 拒絕。"),
        ("Emotes", "表情"),
        ("Sit", "坐下"),
        ("Lay", "躺下"),
        ("Sleep", "睡覺"),
        ("Spray Preview", "噴漆預覽"),
        ("Close", "關閉"),
        ("Download", "下載"),
        ("GET THE FUCK AWAY FROM ME!!!", "給勞資滾開！！！"),
        ("Oh no, you're not leaving me yet.", "噢不，你還不能走。"),
        ("Stay with me. We're getting through this.", "留在我身邊。我們會挺過去的。"),
        ("Not today. I've got you.", "今天不行。有我在。"),
        ("Hey, look at me. You're still here.", "嘿，看著我。你還在這裡。"),
        ("Nope. You're not in this alone.", "不行。你不是一個人。"),
        ("You're okay. You're fine.", "你沒事的。你很好。"),
        ("Don't! It's- It's okay!", "別！沒-沒事的！"),
        ("It'll be alright. Breathe.", "會沒事的。呼吸。"),
        ("Take a deep breath, okay?", "深呼吸，好嗎？"),
        ("You'll be okay. Look at me.", "你會沒事的。看著我。"),
        ("Not on my watch.", "有我在，別想。"),
        ("I've got you. Come here.", "我接住你了。過來。"),
        ("Stay with me, okay?", "待在我身邊，好嗎？"),
        ("You're still here. I'm here.", "你還在這裡。我在這裡。"),
        ("I'm here for you, buddy.", "我在這裡陪著你，夥計。"),
        ("You're stuck with me for now.", "你現在甩不掉我了。"),
        ("Okay, okay... let's sit down, alright?", "好了，好了...我們坐下來，好嗎？"),
        ("Well... that happened.", "嗯...剛才的事就這樣吧。"),
        ("Tactical kiss.", "戰術性親吻。"),
        ("We are never explaining this.", "我們永遠解釋不清這件事。"),
        ("Worth it.", "值了。"),
        ("This is how rumors start.", "謠言就是這麼來的。"),
        ("Absolutely normal workplace behavior.", "完全正常的工作場所行為。"),
        ("Okay, back to surviving.", "好了，回到求生正題。"),
        ("Mwah!", "啵！"),
        ("Charge me, doctor!", "給我充電，醫生！"),
        ("I've always wanted to do this...", "我一直想這麼做..."),
        ("They would never let us do this back on Earth.", "在地球上他們絕不會讓我們這麼做。"),
        ("Only on the Grey planet.", "只有在這顆灰色星球上。"),
        ("I hope no one saw that.", "希望沒人看見。"),
        ("Cutie.", "小可愛。"),
        ("I don't know how to kiss, but I hope that was good enough.", "我不知道怎麼接吻，但希望剛才夠好。"),
        ("I don't know what to say, but I hope that was good enough.", "我不知道該說什麼，但希望剛才夠好。"),
        ("I hope that was good enough.", "希望剛才夠好。"),
        ("My rival, my idol, you got me suicidal, my love, your rage, our dying claim to fame...", "我的對手，我的偶像，你讓我痴狂，吾愛，你的怒火，我們垂死的成名之作..."),
        ("You taste really good.", "你嚐起來真不錯。"),
        ("*Slurping noises*", "*吸溜*"),
        ("Maybe let's stick to hugging for now.", "也許我們還是先擁抱吧。"),
        ("I learned from my handler.", "我是跟我的管理員學的。"),
        ("Last time I tried this, a Dune nearly ripped my jaw off.", "上次我這麼幹，一隻沙丘差點把我下巴扯下來。"),
        ("Uh... no homo?", "呃...不是那種意思？"),
        ("Oh... we are so gay.", "噢...我們太基佬了。"),
        ("Congrats! You're gay now.", "恭喜！你現在是基佬了。"),
        ("I'm sorry, Gary.", "對不起，Gary。"),
        ("I hope I don't catch the gay!", "希望我不會被傳染基佬病！"),
        ("MmmmMMhghgf-", "嗯嗯嗯嗯嗯嗯-"),
        ("That... wasn't a hug...", "那...不是擁抱..."),
        ("I hope they got this on record!", "希望他們把這錄下來了！"),
        ("Platonically kissing you was the best thing ever!", "柏拉圖式地親你是有史以來最棒的事！"),
        ("You better write about this in your pod tonight.", "你今晚最好在維生艙裡把這事寫下來。"),
        ("We could always just let another group find the cargo.", "我們大可以就讓別的隊伍找到那批貨物。"),
        ("Our captors can suck my wiggly dick.", "那些抓我們的人去吃屎吧。"),
        ("My handler had a bit too much of a  approach to teaching...", "我的管理員教我的方式有點太..."),
        ("Boop!", "戳！"),
        ("What's this, I got it, how could I have forgotten, the physical touch of another, it makes me feel so warm...", "這是什麼，我明白了，我怎麼忘了呢，另一個人的肢體接觸，讓我感覺如此溫暖..."),
        ("My mango, is to blow up, and act like I don't know nobody... what's a mango?", "我的主要目標是爆紅，然後裝作誰也不認識..."),
        ("I just drank fent, by the way.", "順便說一句，我剛喝了芬太尼。"),
        ("The 10 hour expie kissing scene is plot relevant, I swear!", "十小時恐怖片的接吻戲是劇情相關的，我發誓！"),
        ("With the power of yaoi, we shall prevail!", "憑藉基腐之力，我們終將勝利！"),
        ("With the power of yuri, we shall prevail!", "憑藉百合之力，我們終將勝利！"),
        ("Wanna share a syringe after this?", "完事後想共享一支注射器嗎？"),
        ("I saw this on a blueprint once.", "我在藍圖上看過這個。"),
        ("I don't know if we should take this any further...", "我不知道我們該不該繼續深入..."),
        ("We should stop at this...", "我們應該到此為止..."),
        ("This is like that one gif.", "這就像那個動圖。"),
        ("What's my gender? kiss me again and find out.", "我的性別是什麼？再親我一次就知道了。"),
        ("I assume this means you'll be treat me to dinner.", "我猜這意味著你會請我吃晚飯。"),
        ("A little less tongue next time, yeah?", "下次少點舌頭，好嗎？"),
        ("If anyone asks, yes, we're a thing now.", "如果有人問，是的，我們現在是一對了。"),
        ("Fine... I guess I'll be your little pog champ.", "好吧...我勉強當你的小冠軍寶貝。"),
        ("I KNEW YOU WERE GAY ALL ALONG!", "我 就 知 道 你 是 基 佬 ！"),
        ("I guess I'll endure your affection just this once.", "我就勉強忍受你的愛意這一次。"),
        ("LESS TEETH, YOU BUGGY FUCK!", "少 用 點 牙 ，你 這 蟲 豸 ！"),
        ("Yummers.", "好耶。"),
        ("34 rules about to be violated tonight!", "今晚要違反 34 規則了！"),
        ("Call me a spike stabber the way I... Fuck, I forgot, nevermind.", "像叫尖刺陷阱那樣叫我...操，我忘了，算了。"),
        ("They're gonna have to rename this to the freakpatch.", "他們得把這模組改名叫怪人補丁了。"),
        ("vaporeonx5 was here :3c", "vaporeonx5 到此一遊 :3c"),
        ("I guess I'm trans now..?", "我想我現在是變性人了...？"),
        ("Oh yeah, keep jorking me, oh yeah ong ong", "噢耶，繼續逗我，噢耶，真的真的"),
        ("Orsoniks approved mod!", "Orsoniks 認證模組！"),
        ("I think... I liked that.", "我想...我喜歡剛才。"),
        ("...oh?", "...哦？"),
        ("Last time I tried this, they nearly ripped my jaw off.", "上次我這麼幹，他們差點把我下巴扯下來。"),
        ("Uhh...", "呃..."),
        ("That's... nice?", "這...不錯？"),
        ("Are you, um...", "你是，嗯..."),
        ("Is this okay..?", "這樣可以嗎...？"),
        ("Mmmh...", "嗯..."),
        ("How affectionate...", "多有愛意啊..."),
        ("What a display of affection...", "多麼深情的表現..."),
        ("Ah! Mmhh... Thank you...", "啊！嗯...謝謝你..."),
        ("Aw! You're so nice!", "啊！你真好！"),
        ("Less- teeth, gosh.", "少—少用點牙，天哪。"),
        ("Still platonic, right?", "還是柏拉圖式的，對吧？"),
        ("I hope there aren't any cameras around here.", "希望這附近沒有攝像頭。"),
        ("I think I skipped the kissing course...", "我想我跳過了接吻課程..."),
        ("You're cute...", "你真可愛..."),
        ("You're warm...", "你真暖和..."),
        ("You're soft...", "你真柔軟..."),
        ("Oh, uh..! Is this alright?-", "噢，呃...！這樣可以嗎？—"),
        ("Did you just eat something..?", "你剛才是不是吃了什麼東西...？"),
        ("Is this relevant to the mission..?", "這跟任務有關嗎...？"),
        ("I feel better...", "我感覺好多了..."),
        ("Wanna share a burger after this?", "完事後想共享一個漢堡嗎？"),
        ("Are we a thing now..?", "我們現在算是一對了嗎...？"),
        ("Your tail is wagging.", "你的尾巴在搖。"),
        ("Haha- is my tail wagging?", "哈哈—我的尾巴在搖嗎？"),
        ("You're just licking my face... okay...", "你只是在舔我的臉...好吧..."),
        ("Uh- what rule did we violate with this?", "呃—我們這樣違反了哪條規則？"),
        ("Haha, you okay?", "哈哈，你還好嗎？"),
        ("My heart is gonna jump out of my chest...", "我的心要從胸口跳出來了..."),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("Hahahaha... FUCK yeah... That's good...", "哈哈哈...真 他 媽 爽...這感覺可以..."),
        ("Thaaatttt's better... Ahahaha... Fucking amazing...", "這這這這就對了...啊哈哈哈...真他媽帶勁..."),
        ("Oh yeah... Fuck yeah... FUCK yeah...", "哦耶...真他媽爽...真他媽爽..."),
        ("Mmhh... Fuck... Hahahaha... This is good...", "嗯嗯...媽的...哈哈哈...這感覺真好..."),
        ("How do yoouuuu like that... Fucker... Ahaha... FUCK you... Fuck you... Good...", "你你你感覺很爽嗎...傻逼...啊哈哈...操...媽的...真不錯..."),
        ("Fuck me, hahah... That feels amazing...", "我操，哈哈...那感覺真美妙..."),
        ("AAGH! FUCK YEAH! Fucking amazing...", "啊啊！爽翻了！太棒了..."),
        ("FUCK! HAHAHAHA! HELL FUCKING YEAH..!", "操！哈哈哈哈！真他媽爽...！"),
        ("Just a little cut... More... Ahahah... Fuck...", "只是一點小傷口...再來幾次...啊哈哈...媽的..."),
        ("Ouch-... T-that's good... Fuck... That's great...", "哎喲—...這—這感覺不錯...操...太棒了..."),
        ("FUCK! Hahaha! FUCK yeah! Hahahaha...", "操！哈哈哈！真他媽爽！哈哈哈..."),
        ("That's what... you get... Dickhead... Fuck you... Hahahaha...", "這是...你...你活該...白痴...去死吧...哈哈哈哈..."),
        ("There... we go... hahah... good...", "好...了...哈哈哈...不錯..."),
        ("That'll.. fuck... Yeaaahhh... That'll do it... Haha...", "就這樣...媽的...對...這樣就對了...哈哈..."),
        ("Y-Yeah... take that... Fucker... That'll hurt good...", "對—對...嚐嚐這個...媽的...真痛快..."),
        ("You deserve this... Haha... That hurts greeatt...", "你活該...哈哈...這痛感爽翻了..."),
        ("AAHHAHA!! FUCK yeah... Fuck yeah. Hahaha... Hurts...", "啊啊哈哈！！真他媽爽...真他媽爽。哈哈哈...好痛..."),
        ("Hahah... that's better... yeah... Much better...", "哈哈...這樣就對了...是的...好多了..."),
        ("Theeeree we go... That hurts gooooood...", "來來來吧...這疼得真爽..."),
        ("Hehhehheh... that fucking hurts... hurts good...", "嘿嘿嘿...真他媽的痛...痛得真爽..."),
        ("That... hahah... hurts good... Great...", "這...哈哈...痛得爽...太棒了..."),
        ("Let's not end this juuuussst yet... F-fuck... That's good...", "先別別別這麼著急...操—操了...這感覺好棒..."),
        ("I don't need that flesh... Ggrhh... Haha... More of this...", "我不缺這點肉...呃呃...哈...再來幾次..."),
        ("F-fuck... Ahahaha... Feels great...", "操—他媽的...啊哈哈哈...真他媽絕了..."),
        ("Goooooodd.... Mmmh... Finally... Finally... Fucking amazing... Mmmhh...", "太太太棒了...嗯嗯...終於...終於...真他媽解壓...嗯嗯..."),
        ("M-maybe... Maybe I'll end it next time... Hahaha...", "也—也許...下次我就戒了吧...哈哈哈..."),
        ("Goodbye. Good FUCKING BYE. I am DONE!!! FUCK ALL OF THIS!", "再見。再 他 媽 的 見。就這樣了！！去 你 媽 的！"),
        ("I'm done. Fuck this, fuck me and FUCK you.", "操你媽的，我不幹了，去他媽的。"),
        ("I fucking told you. I TOLD you, you piece of shit. I'm DONE!", "我他媽早跟你說過。我 警 告 過你，我受夠了！"),
        ("I'm leaving this shitty world once and for all.", "終於能永遠逃離這垃圾地方了。"),
        ("Peace. Bye. Fuck this. I'm fucking leaving. I'm going to hell for this.", "可以清靜了。再他媽的見，老子不伺候了。下地獄就下地獄吧。"),
        ("I have FUCKING had it with all of this. I am DONE! FUCK OFF!!!", "我他媽早就忍到 極 限 了。到 此 為 止！！！"),
        ("End of the line, fucker. End of the fucking line. I'M OUT!!!", "到此為止了，他媽的，老 子 不 幹 了！！！"),
        ("That should do it... Bye-bye... Sorry for this... I hope there's an afterlife for me...", "這樣應該就結束了吧...再見...對不起...希望還有來生等著我..."),
        ("This is the end. I hope whoever finds my corpse makes good use of me. I can't handle this anymore. I'm sorry.", "結束了。誰要是發現我的屍體，能用上的東西就拿去吧。我已經扛不住了。對不起。"),
        ("There's no point to this anymore. There NEVER fucking was. I'm ending it all. Fuck me... Fuck ALL of this.", "沒意義了，從來就 沒 有 過 他媽的意義。到此為止吧。操...通通去死吧。"),
        ("If slitting my wrists doesn't kill me, I'm going to gouge my own fucking eyes out, so I never have to see this horrible land ever again.", "如果割腕弄不死我，我就把我這雙眼珠子摳出來，至少這樣我就看不到這垃圾地方了。"),
        ("I don't know what comes after, but I can finally rest... Let's relax now... There is no need for emotions anymore...", "雖然不知道死後會怎樣，但至少終於能解脫了...放鬆點...再也不用去感受那些痛苦了..."),
        ("AHHHH! FUCK THIS! ALL OF THIS! I CAN'T TAKE IT ANYMORE! LET ME OUT OF HERE! I'M DONE!", "啊！！！去 他 媽 的！都 去 死 吧！我 受 夠 了！到 此 為 止 了！"),
        ("That's it. I've FUCKING had it. I'm finally doing this... Peace. Fucking PEACE. I'm OUT.", "夠了，我 他 媽 受夠了，終於到動手的時候了...清靜了，真他媽 清 靜，再見。"),
        ("I have made the conscious decision to end my life, right here and right now. Farewell, dipshits.", "我已經決定了，在這裡、就現在，結束我的生命。永別了，傻逼們。"),
        ("I told you... I TOLD YOU. Piece of shit... Fuck... Burn in the fucking depths of hell.", "我警告過你，我他媽的 警 告 過 你，媽的...一起在無間地獄裡燒成灰吧。"),
        ("I'll do better as a rotting corpse. My life ended the moment I was sent here. Goodbye.", "變成一具腐爛的屍體都比現在強。從我被送到這裡的那一刻起，我就已經死了。再見。"),
        ("This is for fucking EVERYTHING! I'M DONE! AAAHHHH! FUCK ALL OF THIS!", "這都是你們逼的！！！老子 不 幹 了！啊！！！都給我去死！！！"),
        ("I'm. I'm just... I'm done. No time for suicide notes. I'm so tired of all of this. Goodbye.", "我...我累了。沒心思寫什麼遺言。我累了。再見。"),
        ("N... no hard feelings... right?.. hah... I'm... I'm so tired... G-goodnight...", "別...別恨我...好嗎...呵...我好累...晚安..."),
        ("I'm not doing this anymore. I'm not. It's over. Bye. Ello. Fuck this.", "我熬不下去了，熬不下去了，結束了。再見，去他媽的。"),
        ("There never was any hope. FUCK. This. I'm OUT! LEAVE ME ALONE! I'M NOT LETTING THIS PLACE TAKE MY LIFE!", "根本就沒有過希望。去你媽的。老子不玩了！我不會再讓這傻逼地方折磨我了！！！"),
        ("Looooook at that... Hahahah... I'm saying goodbye to this fucking universe... Leaving this world behind... It's... Relieving...", "看啊...哈哈哈...我要跟 他 媽 的 這個世界說再見了...把這個世界拋在腦後...感覺...真是輕鬆啊..."),
        ("There... There it goes... Let's enjoy my last few moments now... Relax and... Fall asleep... One last time...", "好了...享受我最後的幾分鐘吧...放鬆...然後睡過去...最後一覺..."),
        ("I hope you're happy with what you've done. Dipshit. Fuck you. FUCK YOU. Go to hell.", "看到我這樣你滿意了吧？人渣。去你媽的。去死吧。下地獄去吧。"),
        ("There goes my wrist... It's all going to be over soon... Haha...", "手腕割開了...馬上一切就要結束了...哈哈..."),
        ("Fuck you. FUCK you. I'm DONE. I'M FUCKING DONE!", "操你媽的，去死吧，我受夠了，我 他 媽 真 的 受 夠 了！！"),
        ("I am LEAVING this fucking place, whether I'm able to or NOT. FUCK YOU.", "無論成不成，我今天都必須 離 開 這垃圾地方。去 你 媽 的。"),
        ("FUCK this. It's fucking OVER. To hell with my life.", "去他媽的。徹底 結 束 了。這破爛生活不要也罷。"),
        ("To hell with this. I'm out. Piece of shit. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done.", "毀滅吧，我不幹了。他媽的。我不幹了。我不幹了。我不幹了。我不幹了。我不幹了。我不幹了。我不幹了。"),
        ("Piece of shit... I'm fucking done... Fuck this...", "媽的...我徹底放棄了，他媽的..."),
        ("I'm leaving. I hope I'm not going to hell for this.", "我要走了。希望我不會因此而下地獄。"),
        ("They can find me as a desiccated corpse in a ditch. Like it fucking matters.", "讓他們在哪個臭水溝裡找我乾癟的屍體去吧。無所謂了。"),
        ("None of this matters. This is a suicide mission. I'm not fucking going through any more of this.", "這一切都沒意義。這他媽就是個自殺任務。我死也不想再經歷這些了。"),
        ("I've failed. I give up. Fuck this.", "我放棄了，任務失敗。去他媽的。"),
        ("Good fucking luck to anyone that comes here after me. Maybe my corpse will be of use to someone. I'm done.", "祝後面來這個鬼地方的人好運吧。也許我的屍體還能對誰有點用。我走了。"),
        ("There never was any fucking point to this. I was sent here to die.", "這事情他媽的從一開始就沒有任何意義。我就是來送死的。"),
        ("They're getting what they fucking wanted.", "這下他們如願以償了。"),
        ("I didn't think I was ever actually going to do this... Haha... Ahahahaha... Cathartic...", "我沒想到我真的會親手了結自己...哈哈...啊哈哈哈...解脫了..."),
        ("I'm taking my life. Sorry. I can't. I fucking can't take it anymore. I'm so fucking sorry.", "我要自我了結了。對不起。我做不到了。我真你媽受不了了。真他媽抱歉了。"),
        ("I hope I end up in hell. Gonna be better than this fucking place. I can't. I'm out. Sorry. Fuck all of this.", "我希望我會進地獄。反正比這傻逼地方強得多。我受不了了。不幹了。對不起。真他媽傻逼。"),
        ("Bye. I'm out. I'll see everyone on the other side, down in the pits of hell.", "再見。我走了。另一邊見吧，在那地獄的深淵裡。"),
        ("Fuck this. Fuck this. FUCK. This. I'M DONE! ENOUGH OF THIS.", "媽的。媽的。操 你 媽。我受夠了！夠了！！！"),
        ("Sorry. I'm out. Bye. I'm sorry. I'm so fucking sorry. I can't.", "對不起。我不幹了。再見。對不起。我很他媽抱歉。我做不到。"),
        ("Thanks... I needed that.", "謝謝...我正需要這個。"),
        ("Can we stay like this for a second?", "我們能這樣待一會兒嗎？"),
        ("I'm not doing great.", "我現在不太好。"),
        ("I'm so tired...", "我好累..."),
        ("I don't think I've felt okay for a while.", "我好像很久沒有好受過了。"),
        ("I don't want to... I can't be alone right now.", "我不想...我現在不能一個人待著。"),
        ("I'm not a burden, am I?", "我不是個累贅吧？"),
        ("This helps... a little...", "這有點用...一點點..."),
        ("I want to cry...", "我想哭..."),
        ("Everything feels wrong lately.", "最近一切都感覺不對勁。"),
        ("I needed a reminder that somebody still cares.", "我需要有人提醒我還有人關心我。"),
        ("I've been holding everything in.", "我一直把所有情緒憋在心裡。"),
        ("I was starting to spiral again.", "我又開始胡思亂想了。"),
        ("Our captors will get what they fucking deserve.", "那些抓我們的人會得到他們應得的報應。"),
        ("I think I might consider a mindwipe.", "我想我可能要考慮洗腦了。"),
        ("I dreamt about our captors again last night... it was so vivid...", "昨晚我又夢到那些抓我們的人了...太清晰了..."),
        ("What did we do to deserve this?", "我們到底做錯了什麼要受這種罪？"),
        ("I hate how much this place affects me.", "我討厭這個地方對我影響這麼大。"),
        ("I'm scared of what I'm becoming in here.", "我害怕自己在這裡變成的樣子。"),
        ("When I get my claws on them, they will know pain.", "等我抓住他們，他們會知道什麼叫痛苦。"),
        ("I don't even recognize myself anymore.", "我都不認識自己了。"),
        ("I'm really scared...", "我真的好害怕..."),
        ("I can't lose you, too...", "我不能再失去你了..."),
        ("Please don't leave me...", "求你別離開我..."),
        ("I've lost so many... I can't lose you too.", "我已經失去太多人了...不能再失去你。"),
        ("I'm trying really hard to keep going.", "我在很努力地撐下去。"),
        ("There is no honest way out, huh.", "沒有體面的出路，是吧。"),
        ("...", "..."),
        ("If something happens, please don’t forget about me.", "如果發生什麼，請別忘了我。"),
        ("Will I even make it out..?", "我真的能活著出去嗎..？"),
        ("I hate this... I really do...", "我討厭這一切...真的討厭..."),
        ("They don't know what I'm going through down here...", "他們不知道我在下面經歷了什麼..."),
        ("Is this what we are to them..?", "我們對他們來說就是這樣嗎？"),
        ("This only delays the inevitable...", "這只是在拖延註定的結局"),
        ("I can't die like this...", "我不能就這樣死"),
        ("Are... Are we going to make it out..?", "我們我們能活著出去嗎？"),
        ("Please tell me we going to be okay...", "請告訴我我們會沒事的"),
        ("Their salvation will be rotten...", "他們的救贖會爛掉"),
        ("I don't think this is enough.. but thank you.", "我知道這不夠但謝謝你。"),
        ("Please don't leave my side... at least until I'm okay.", "請別離開我身邊至少等我好起來。"),
        ("Will they toss us aside if we make it out? What will they do to us..?", "如果我們出去了，他們會不會把我們丟到一邊？他們會對我們做什麼？"),
        ("I... I don't want to do this anymore...", "我我不想再這樣下去了"),
        ("I want to go somewhere else... anywhere but here...", "我想去別的地方哪裡都行，就是別在這"),
        ("I... Won't end up like the rest, right..?", "我不會變得和那些屍體一樣吧？"),
        ("Their bodies... mangled... stabbed... cold... why..?", "他們的屍體殘缺被刺穿冰冷為什麼？"),
        ("I can't... keep going...", "我撐不下去了"),
        ("I don't want to end up like them...", "我不想變得和他們一樣"),
        ("Why are there so many of us down here..? So many... all dead.", "為什麼這裡有這麼多我們的人？這麼多全都死了。"),
        ("I can't stop crying...", "我止不住地哭"),
        ("I can't stop looking at the ground...", "我一直盯著地面"),
        ("I'm scared of this place...", "我害怕這個地方"),
        ("They won't get away with this.. I'll... I don't know...", "他們不會逍遙法外的我會我不知道"),
        ("What will we do once this is all over..?", "這一切結束後我們該怎麼辦？"),
        ("I hate that I'm actually adapting to this place...", "我討厭自己居然在適應這個地方"),
        ("The traps... the lights... the corpses...", "那些陷阱燈光屍體"),
        ("Why can't they just get it themselves instead of commiting a genocide..?", "為什麼他們不能自己來拿，非要搞種族滅絕？"),
        ("I'm sick of this place... I'm sick of it all.", "我受夠了這個地方受夠了一切。"),
        ("I feel like I'm not going to make it...", "我覺得我可能活不下去了"),
        ("I won't fall victim like the rest, right..?", "我不會像其他人那樣成為受害者吧？"),
        ("I want to wake up...", "我想醒來"),
        ("This is all a bad dream, right..?", "這一切都是個噩夢，對吧？"),
        ("Why would they... why...", "他們為什麼要為什麼"),
        ("I... please don't watch if I scratch myself...", "我如果我自己抓傷自己，請不要看"),
        ("You shouldn't care about someone as useless as me...", "你不該關心像我這樣沒用的人"),
        ("I'm just dead weight, aren't I..?", "我只是個累贅，對吧？"),
        ("I'm not smart like a Milky and I'm not strong like a Dune... why bother...", "我不像奶白那樣聰明，也不像沙丘那樣強壯何必呢"),
        ("I hate this place... why here of all places...", "我討厭這個地方為什麼偏偏是這裡"),
        ("If this keeps up I might have to resort to my own way out of this place...", "再這樣下去，我可能不得不用我自己的方式離開這裡了"),
        ("...I wish we could have stayed...", "真希望我們能留在那裡"),
        ("Just this once...", "就這一次"),
        ("I can't even look up...", "我連頭都抬不起來"),
        ("I'm not smart and I'm not strong... why bother...", "我不聰明也不強壯何必呢"),
        ("If this keeps up I might have to...", "再這樣下去我可能不得不"),
        ("I'm exhausted.", "我精疲力盡了。"),
        ("I'm so sick of this place.", "我受夠這個地方了。"),
        ("I hate this place.", "我討厭這個地方。"),
        ("I hate myself...", "我討厭我自己"),
        ("Please tell me we're going to be okay.", "請告訴我我們會沒事的。"),
        ("I'm trying... I'm trying so hard...", "我在努力我非常努力"),
        ("I'm trying not to cry, okay..?", "我在努力不哭出來，好嗎？"),
        ("I don't want to die...", "我不想死"),
        ("I couldn't care less about the cargo.", "我一點也不在乎那批貨物。"),
        ("Thank you... Thank you...", "謝謝謝謝"),
        ("...Okay...", "好吧"),
        ("You looked like you needed this.", "你看上去需要這個。"),
        ("It's okay, even thought it's not, just know I'll be here for you.", "雖然現在不好，但沒關係，我會陪著你。"),
        ("You've been carrying too much alone.", "你一個人扛得太多了。"),
        ("You know I care about you.", "你知道我在乎你。"),
        ("Hey, hey, it's okay. I'm here.", "嘿，嘿，沒事的。我在這裡。"),
        ("Come here...", "過來"),
        ("If you need to cry, I understand. I'm here for you.", "想哭就哭吧，我理解。我在這裡陪著你。"),
        ("I'll be here for you, no matter what.", "無論發生什麼，我都會陪著你。"),
        ("If you need a shoulder to cry on, I'm here.", "需要靠一靠肩膀的話，我在這裡。"),
        ("Don't worry, I've got you.", "別擔心，有我在。"),
        ("I know that look. I've had it too.", "我懂那種眼神。我也經歷過。"),
        ("Just rest your head for a second.", "把頭靠過來休息一下。"),
        ("I hope our captors are burning in hell for this.", "我希望那些抓我們的人在地獄裡被火燒。"),
        ("Our captors can go fuck themselves.", "那些抓我們的人去死吧。"),
        ("Our captors can go to hell.", "那些抓我們的人下地獄去吧。"),
        ("Fuck 'em.", "去他媽的。"),
        ("When we get back, we will make them pay, don't worry.", "等我們回去，會讓他們付出代價的，別擔心。"),
        ("You don't have to handle this alone.", "你不需要一個人扛。"),
        ("Don't let this place win.", "別讓這個地方得逞。"),
        ("You shouldn't have to go through this alone.", "你不該獨自經歷這些。"),
        ("Hey... breathe, alright? I'm here now.", "嘿深呼吸，好嗎？我現在在這裡。"),
        ("Smoke 'em if you got 'em...", "有煙抽就抽吧"),
        ("I’m not gonna leave you. I’m right here.", "我不會離開你的。我就在這裡。"),
        ("We are in this together, remember?", "我們是一起的，記得嗎？"),
        ("I know it’s hard, but we can get through this. Together.", "我知道很難，但我們可以挺過去。一起。"),
        ("I’m not going anywhere. I’ve got you.", "我哪兒也不去。有我在。"),
        ("I know you're scared, but we'll make it through this. I promise.", "我知道你害怕，但我們會挺過去的。我保證。"),
        ("I wish I could make it all better, but I can’t. I care about you and I’m here for you.", "我希望我能讓一切變好，但我不能。我在乎你，我在這裡陪著你。"),
        ("I know this place is awful, but you’re not alone. I’m here with you.", "我知道這地方很糟，但你不是一個人。我在這裡。"),
        ("You’re doing the best you can, and that’s all anyone can ask of you. I’m proud of you.", "你已經盡力了，這就夠了。我為你驕傲。"),
        ("You are so strong, I'm so proud of you.", "你太堅強了，我為你驕傲。"),
        ("I know it feels hopeless, but we have to keep going.", "我知道感覺沒有希望，但我們必須繼續走下去。"),
        ("You are the strongest one here.", "你是這裡最堅強的人。"),
        ("I'm so proud of you.", "我為你驕傲。"),
        ("Shh... Just hold on...", "噓再撐一下"),
        ("I’m by your side, buddy, it’s gonna be okay...", "我就在你身邊，夥計，會沒事的"),
        ("None of this is your fault. Not any of this.", "這一切都不是你的錯。一點都不是。"),
        ("Just keep breathing, slowly. You’re doing good...", "慢慢呼吸。你做得很好"),
        ("It’s going to be okay... everything's going to be okay...", "會好起來的一切都會好起來的"),
        ("Let's not give up just yet.", "先別放棄。"),
        ("Despite everything we’re still here, right?", "儘管經歷了這一切，我們還在這裡，對吧？"),
        ("I won’t let you get hurt again.", "我不會再讓你受傷了。"),
        ("You're okay.", "你沒事的。"),
        ("You'll be fine...", "你會沒事的"),
        ("Come here.", "過來。"),
        ("It's gonna be okay...", "會好起來的"),
        ("I'm proud of you.", "我為你驕傲。"),
        ("You're gonna make it out.", "你會活著出去的。"),
        ("I love you, it'll be okay.", "我愛你，一切都會好的。"),
        ("You're not alone.", "你不是一個人。"),
        ("I'll stay near.", "我會待在附近。"),
        ("Here, you're okay...", "來，你沒事的"),
        ("It's all good...", "一切都好"),
        ("I'm here, it'll be okay...", "我在這裡，會好起來的"),
        ("Hug time!", "擁抱時間到！"),
        ("Charge me, doctor!", "給我充電，醫生！"),
        ("Come here!", "過來！"),
        ("This is nice.", "這感覺真好。"),
        ("There are so many cool things here! I will never go back to the lab!", "這裡有趣的東西太多了！我再也不回實驗室了！"),
        ("You deserve a hug.", "你值得一個擁抱。"),
        ("I think you are amazing!", "我覺得你太棒了！"),
        ("You are like, so totally awesome.", "你簡直酷斃了。"),
        ("I hope things stay like this.", "我希望日子能一直這樣。"),
        ("Wasn't this supposed to be hard and depressing?", "這不該是又難又壓抑的嗎？"),
        ("We got this in the bag.", "我們勝券在握。"),
        ("Yippee!", "耶！"),
        ("Physical touch makes me feel all tingly.", "肢體接觸讓我渾身酥麻。"),
        ("I'm gonna touch you >:3", "我要摸你了 >:3"),
        ("So like... wanna make out?", "所以想親一個嗎？"),
        ("We are doing SO good.", "我們做得太棒了。"),
        ("I like your fur.", "我喜歡你的毛。"),
        ("This is WAY better than dying alone.", "這可比孤獨地死去好太多了。"),
        ("Okay maybe life IS worth living.", "好吧，也許生活確實值得活下去。"),
        ("We're gonna make it. Probably.", "我們會出去的。大概吧。"),
        ("This almost makes me forget the horrors.", "這幾乎讓我忘了那些恐怖的事。"),
        ("You are officially my emotional support survivor.", "你正式成為我的情緒支持倖存者了。"),
        ("I cast emotional support!", "我施放情緒支持！"),
        ("We're doing great, sweetie!", "我們做得很好，親愛的！"),
        ("Let's do this again later!", "我們待會兒再來一次！"),
        ("This place can't stop me from being silly!", "這地方阻止不了我犯傻！"),
        ("Wanna go blow up a life pod later?", "待會兒想去炸個維生艙嗎？"),
        ("When we get back, let's escape and go on a roadtrip!", "等我們回去，一起逃出去來場公路旅行吧！"),
        ("The horrors persist but so do we!", "恐怖還在，但我們也在！"),
        ("We're doing amazing, sweetie.", "我們做得超棒，親愛的。"),
        ("We're so back.", "我們回來了。"),
        ("Are you a blood bag? Because I feel empty without you.", "你是血袋嗎？因為沒有你我覺得空落落的。"),
        ("...!!!", "...！！！"),
        ("I think we deserve a little whimsy.", "我覺得我們值得一點小小的奇思妙想。"),
        ("We should do this before every near-death experience.", "我們應該在每次瀕死體驗前來一次這個。"),
        ("If we die horribly later, this was still worth it.", "就算之後死得很慘，這也值了。"),
        ("Wow. Serotonin. Haven't felt that since my handler passed away.", "哇。血清素。自從我的管理員去世後就沒感受過了。"),
        ("I'm resisting the urge to start spinning in circles.", "我在努力忍住原地轉圈的衝動。"),
        ("I'm choosing to believe everything will be okay.", "我選擇相信一切都會好起來。"),
        ("Look at us. Surviving and everything.", "看看我們。活著，而且啥都有。"),
        ("I'm full of dangerous amounts of optimism.", "我充滿了危險劑量的樂觀。"),
        ("We are absolutely crushing this apocalypse thing.", "我們絕對是在末日裡混得風生水起。"),
        ("Morale has increased by approximately five hundred percent.", "士氣大約提升了百分之五百。"),
        ("Your fur is SO soft, wow.", "你的毛好軟，哇。"),
        ("happy_responce_dialogie_option_27", "*開心的聲音*"),
        ("*Happiness noises*", "*開心的聲音*"),
        ("I wonder if I could suplex you.", "我在想我能不能把你過肩摔。"),
        ("Can you not crush me? Thanks.", "你能不能別壓扁我？謝謝。"),
        ("Your breath stinks.", "你嘴巴好臭。"),
        ("...You smell like steak. Maybe I’m just hungry.", "你聞起來像牛排。可能我只是餓了。"),
        ("So... Come here often?", "所以常來嗎？"),
        ("I wasn’t expecting that. I didn’t mean stop!", "我沒料到這個。我不是讓你停的意思！"),
        ("Oh nooooo, please don’t hug me agaiinnnnnnnn...", "噢不不不不，請別再抱我了啊啊啊啊..."),
        ("I’m proud of who we’ve become. Let’s be even better!", "我為我們現在的樣子驕傲。讓我們變得更好！"),
        ("Imagine if we could just LIVE after this, no experiments, no tests.", "想象一下這一切結束後我們能好好活著，沒有實驗，沒有測試。"),
        ("We should totally cuddle.", "我們應該好好抱一抱。"),
        ("I love this... wait a minute-", "我喜歡這樣等等—"),
        ("We're gonna make it!", "我們會成功的！"),
        ("Oh, I love this place!", "噢，我愛這個地方！"),
        ("Yawn... you're really warm, y'know?", "哈欠你真暖和，知道嗎？"),
        ("Oof- didn't expect this, haha!", "哦—沒想到會這樣，哈哈！"),
        ("We should do this more!", "我們應該多這樣做！"),
        ("Awwh...", "啊嗚..."),
        ("We're doing amazing!", "我們幹得太棒了！"),
        ("Doing great so far!", "到目前為止都很好！"),
        ("C'mere, you!", "過來，你！"),
        ("There, there.", "好啦，好啦。"),
        ("Oof- hey, you're crushing me! Haha!", "哦—嘿，你要把我壓扁了！哈哈！"),
        ("Wanna share some food later?", "待會兒要一起吃點東西嗎？"),
        ("You're so fluffy!", "你真毛茸茸！"),
        ("You're really soft...", "你真柔軟"),
        ("Thank you!", "謝謝你！"),
        ("Thanks...", "謝謝..."),
        ("Wow, this is nice...", "哇，真不錯"),
        ("Let's do this more often.", "我們以後多這樣。"),
        ("There you go.", "這就對了。"),
        ("Alright, bring it in.", "好，來吧。"),
        ("Our captors would be so mad at us right now.", "抓我們的人現在肯定氣壞了。"),
        ("No wonder this was agianst the rules.", "難怪這違反規則。"),
        ("Thanks.", "謝謝。"),
        ("Could be worse, right?", "還不算太糟，對吧？"),
        ("Can't wait to fuck up our captors!", "等不及要幹翻那些抓我們的人了！"),
        ("This makes me feel a little less alone.", "這讓我感覺沒那麼孤單了。"),
        ("Hope you are doing well.", "希望你還好。"),
        ("Is this how you thought we were going to end up?", "你想到過我們會落到這步田地嗎？"),
        ("Crazy times we're living in.", "我們活著的時代真瘋狂。"),
        ("I like this.", "我喜歡這樣。"),
        ("Don't make it weird.", "別搞得太奇怪。"),
        ("You're warmer than I expected.", "你比我想象的暖和。"),
        ("This almost feels normal.", "這幾乎感覺像正常日子了。"),
        ("This place really wears us down, huh.", "這地方真把我們耗得夠嗆，是吧。"),
        ("So, what did they put you through back on Earth?", "那麼，他們在地球上對你做了什麼？"),
        ("We keep going.", "我們繼續前進。"),
        ("One step at a time.", "一步一步來。"),
        ("We got this.", "我們能行。"),
        ("If I lose you too, I might go insane.", "如果我也失去你，我可能會瘋掉。"),
        ("I ever tell you about the time my buddy Keith told me he was picked up by some little green men and they--", "我跟你說過我哥們 Keith 被小綠人抓走的事嗎，他們—"),
        ("Not too bad, right?", "還不賴，對吧？"),
        ("I really do not miss being beaten...", "我真的很懷念不被毆打的時光"),
        ("Our captors are probably really upset at us.", "抓我們的人現在大概很生我們的氣。"),
        ("I watched my buddy get sawed in half on Earth, so somehow this is a step up.", "我在地球上親眼看著哥們被鋸成兩半，所以這裡反而算升級了。"),
        ("I don't know about you, but I needed that.", "我不知道你怎麼樣，但我需要這個。"),
        ("I ever tell you about the time my buddy Keith fell down an open manhole? He was unconscious down there for like a week. During that time, unbeknownst to Keith, they paved over him. Keith had to--", "我跟你說過我哥們基思掉進敞開的窨井的事嗎？他在下面昏迷了大概一週。那期間，Keith 不知道，他們把他上面鋪了路。Keith 不得不—"),
        ("Can't hurt to slow down for a second.", "慢下來一會兒也沒壞處。"),
        ("I enjoy your company.", "我喜歡有你陪著。"),
        ("Just making sure you're still with me.", "只是想確認你還跟我在一起。"),
        ("Don't get used to this.", "別習慣這個。"),
        ("You're tougher than you look.", "你比看起來更結實。"),
        ("One decent moment in this mess.", "這團糟裡難得的好時刻。"),
        ("Just be careful, stick together, and don't die.", "小心點，抱團，別死。"),
        ("Could be worse, honestly.", "說實話，本可以更糟。"),
        ("I'd miss you if you died, so don't do that.", "你要是死了我會想你的，所以別死。"),
        ("Being alone would suck down here.", "在這裡獨自一人會很糟。"),
        ("Better than dying alone, right?", "總比孤獨地死好，對吧？"),
        ("Not dead yet.", "還沒死。"),
        ("I'm glad you're alive.", "很高興你還活著。"),
        ("Hang in there.", "撐住。"),
        ("Don't give up.", "別放棄。"),
        ("You're softer than the others.", "你比其他人都軟。"),
        ("Just trying to keep morale up.", "只是想提振一下士氣。"),
        ("You're doing alright.", "你做得還行。"),
        ("This place gets lonely fast. I appreciate you.", "這地方很快就讓人感到孤獨。感謝有你。"),
        ("I appreciate you.", "感謝有你。"),
        ("What do you think Earth is like?", "你覺得地球現在是什麼樣？"),
        ("Two can be one...", "兩個人可以合為一體"),
        ("Well, now we both need a shower.", "好吧，現在我們倆都得洗個澡。"),
        ("Yeah, okay. Bring it in.", "行，來吧。抱一下。"),
        ("I kind of expected something else...", "我本來以為會是別的什麼"),
        ("Let me get that for you.", "讓我幫你弄那個。"),
        ("We’ve got places to be, but that can wait.", "我們還有地方要去，但那個可以等。"),
        ("Just making sure.", "只是想確認一下。"),
        ("Uh... I slipped?", "呃我滑了一下？"),
        ("Soft...", "軟..."),
        ("You're fluffy.", "你真毛茸茸。"),
        ("Thanks... I feel better.", "謝謝...我感覺好多了。"),
        ("Cute...", "可愛..."),
        ("Warm...", "暖和..."),
        ("Hey, this is nice...", "嘿，真不錯"),
        ("I feel better.", "我感覺好多了。"),
        ("Thank you!", "謝謝你！"),
        ("Lovely.", "真舒服。"),
        ("Nice!", "不錯！"),
        ("Hug time!", "擁抱時間到！"),
        ("Oh, this feels amazing...", "噢，這感覺太棒了..."),
        ("Do you think the others are okay?", "你覺得其他人還好嗎？"),
        ("I'd miss you if you died, y'know?", "你要是死了我會想你的，知道嗎？"),
        ("We're doing okay.", "我們做得還行。"),
        ("Doing well so far...", "到目前為止還不錯"),
        ("Not too bad.", "還不算太糟。"),
        ("We're okay, aren't we?", "我們還好，對吧？"),
        ("You okay?", "你還好嗎？"),
        ("All good?", "都好嗎？"),
    };
    public static readonly (string En, string Zh)[] CharacterLines =
    {
        ("selfharm", "Hahahaha... FUCK yeah... That's good..."),
        ("selfharm", "Thaaatttt's better... Ahahaha... Fucking amazing..."),
        ("selfharm", "Oh yeah... Fuck yeah... FUCK yeah..."),
        ("selfharm", "Mmhh... Fuck... Hahahaha... This is good..."),
        ("selfharm", "How do yoouuuu like that... Fucker... Ahaha... FUCK you... Fuck you... Good..."),
        ("selfharm", "Fuck me, hahah... That feels amazing..."),
        ("selfharm", "AAGH! FUCK YEAH! Fucking amazing..."),
        ("selfharm", "FUCK! HAHAHAHA! HELL FUCKING YEAH..!"),
        ("selfharm", "Just a little cut... More... Ahahah... Fuck..."),
        ("selfharm", "Ouch-... T-that's good... Fuck... That's great..."),
        ("selfharm", "FUCK! Hahaha! FUCK yeah! Hahahaha..."),
        ("selfharm", "That's what... you get... Dickhead... Fuck you... Hahahaha..."),
        ("selfharm", "There... we go... hahah... good..."),
        ("selfharm", "That'll.. fuck... Yeaaahhh... That'll do it... Haha..."),
        ("selfharm", "Y-Yeah... take that... Fucker... That'll hurt good..."),
        ("selfharm", "You deserve this... Haha... That hurts greeatt..."),
        ("selfharm", "AAHHAHA!! FUCK yeah... Fuck yeah. Hahaha... Hurts..."),
        ("selfharm", "Hahah... that's better... yeah... Much better..."),
        ("selfharm", "Theeeree we go... That hurts gooooood..."),
        ("selfharm", "Hehhehheh... that fucking hurts... hurts good..."),
        ("selfharm", "That... hahah... hurts good... Great..."),
        ("selfharm", "Let's not end this juuuussst yet... F-fuck... That's good..."),
        ("selfharm", "I don't need that flesh... Ggrhh... Haha... More of this..."),
        ("selfharm", "F-fuck... Ahahaha... Feels great..."),
        ("selfharm", "Goooooodd.... Mmmh... Finally... Finally... Fucking amazing... Mmmhh..."),
        ("selfharm", "M-maybe... Maybe I'll end it next time... Hahaha..."),
        ("suicide", "Goodbye. Good FUCKING BYE. I am DONE!!! FUCK ALL OF THIS!"),
        ("suicide", "I'm done. Fuck this, fuck me and FUCK you."),
        ("suicide", "I fucking told you. I TOLD you, you piece of shit. I'm DONE!"),
        ("suicide", "I'm leaving this shitty world once and for all."),
        ("suicide", "Peace. Bye. Fuck this. I'm fucking leaving. I'm going to hell for this."),
        ("suicide", "I have FUCKING had it with all of this. I am DONE! FUCK OFF!!!"),
        ("suicide", "End of the line, fucker. End of the fucking line. I'M OUT!!!"),
        ("suicide", "That should do it... Bye-bye... Sorry for this... I hope there's an afterlife for me..."),
        ("suicide", "This is the end. I hope whoever finds my corpse makes good use of me. I can't handle this anymore. I'm sorry."),
        ("suicide", "There's no point to this anymore. There NEVER fucking was. I'm ending it all. Fuck me... Fuck ALL of this."),
        ("suicide", "If slitting my wrists doesn't kill me, I'm going to gouge my own fucking eyes out, so I never have to see this horrible land ever again."),
        ("suicide", "I don't know what comes after, but I can finally rest... Let's relax now... There is no need for emotions anymore..."),
        ("suicide", "AHHHH! FUCK THIS! ALL OF THIS! I CAN'T TAKE IT ANYMORE! LET ME OUT OF HERE! I'M DONE!"),
        ("suicide", "That's it. I've FUCKING had it. I'm finally doing this... Peace. Fucking PEACE. I'm OUT."),
        ("suicide", "I have made the conscious decision to end my life, right here and right now. Farewell, dipshits."),
        ("suicide", "I told you... I TOLD YOU. Piece of shit... Fuck... Burn in the fucking depths of hell."),
        ("suicide", "I'll do better as a rotting corpse. My life ended the moment I was sent here. Goodbye."),
        ("suicide", "This is for fucking EVERYTHING! I'M DONE! AAAHHHH! FUCK ALL OF THIS!"),
        ("suicide", "I'm. I'm just... I'm done. No time for suicide notes. I'm so tired of all of this. Goodbye."),
        ("suicide", "N... no hard feelings... right?.. hah... I'm... I'm so tired... G-goodnight..."),
        ("suicide", "I'm not doing this anymore. I'm not. It's over. Bye. Ello. Fuck this."),
        ("suicide", "There never was any hope. FUCK. This. I'm OUT! LEAVE ME ALONE! I'M NOT LETTING THIS PLACE TAKE MY LIFE!"),
        ("suicide", "Looooook at that... Hahahah... I'm saying goodbye to this fucking universe... Leaving this world behind... It's... Relieving..."),
        ("suicide", "There... There it goes... Let's enjoy my last few moments now... Relax and... Fall asleep... One last time..."),
        ("suicide", "I hope you're happy with what you've done. Dipshit. Fuck you. FUCK YOU. Go to hell."),
        ("suicide", "There goes my wrist... It's all going to be over soon... Haha..."),
        ("suicide", "Fuck you. FUCK you. I'm DONE. I'M FUCKING DONE!"),
        ("suicide", "I am LEAVING this fucking place, whether I'm able to or NOT. FUCK YOU."),
        ("suicide", "FUCK this. It's fucking OVER. To hell with my life."),
        ("suicide", "To hell with this. I'm out. Piece of shit. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done. I'm done."),
        ("suicide", "Piece of shit... I'm fucking done... Fuck this..."),
        ("suicide", "I'm leaving. I hope I'm not going to hell for this."),
        ("suicide", "They can find me as a desiccated corpse in a ditch. Like it fucking matters."),
        ("suicide", "None of this matters. This is a suicide mission. I'm not fucking going through any more of this."),
        ("suicide", "I've failed. I give up. Fuck this."),
        ("suicide", "Good fucking luck to anyone that comes here after me. Maybe my corpse will be of use to someone. I'm done."),
        ("suicide", "There never was any fucking point to this. I was sent here to die."),
        ("suicide", "They're getting what they fucking wanted."),
        ("suicide", "I didn't think I was ever actually going to do this... Haha... Ahahahaha... Cathartic..."),
        ("suicide", "I'm taking my life. Sorry. I can't. I fucking can't take it anymore. I'm so fucking sorry."),
        ("suicide", "I hope I end up in hell. Gonna be better than this fucking place. I can't. I'm out. Sorry. Fuck all of this."),
        ("suicide", "Bye. I'm out. I'll see everyone on the other side, down in the pits of hell."),
        ("suicide", "Fuck this. Fuck this. FUCK. This. I'M DONE! ENOUGH OF THIS."),
        ("suicide", "Sorry. I'm out. Bye. I'm sorry. I'm so fucking sorry. I can't."),
        ("catpatch_hug_vulnerable", "Thanks... I needed that."),
        ("catpatch_hug_vulnerable", "Can we stay like this for a second?"),
        ("catpatch_hug_vulnerable", "I'm not doing great."),
        ("catpatch_hug_vulnerable", "I'm so tired..."),
        ("catpatch_hug_vulnerable", "I don't think I've felt okay for a while."),
        ("catpatch_hug_vulnerable", "I don't want to... I can't be alone right now."),
        ("catpatch_hug_vulnerable", "I'm not a burden, am I?"),
        ("catpatch_hug_vulnerable", "This helps... a little..."),
        ("catpatch_hug_vulnerable", "I want to cry..."),
        ("catpatch_hug_vulnerable", "Everything feels wrong lately."),
        ("catpatch_hug_vulnerable", "I needed a reminder that somebody still cares."),
        ("catpatch_hug_vulnerable", "I've been holding everything in."),
        ("catpatch_hug_vulnerable", "I was starting to spiral again."),
        ("catpatch_hug_vulnerable", "Our captors will get what they fucking deserve."),
        ("catpatch_hug_vulnerable", "I think I might consider a mindwipe."),
        ("catpatch_hug_vulnerable", "I dreamt about our captors again last night... it was so vivid..."),
        ("catpatch_hug_vulnerable", "What did we do to deserve this?"),
        ("catpatch_hug_vulnerable", "I hate how much this place affects me."),
        ("catpatch_hug_vulnerable", "I'm scared of what I'm becoming in here."),
        ("catpatch_hug_vulnerable", "When I get my claws on them, they will know pain."),
        ("catpatch_hug_vulnerable", "I don't even recognize myself anymore."),
        ("catpatch_hug_vulnerable", "I'm really scared..."),
        ("catpatch_hug_vulnerable", "I can't lose you, too..."),
        ("catpatch_hug_vulnerable", "Please don't leave me..."),
        ("catpatch_hug_vulnerable", "I've lost so many... I can't lose you too."),
        ("catpatch_hug_vulnerable", "I'm trying really hard to keep going."),
        ("catpatch_hug_vulnerable", "There is no honest way out, huh."),
        ("catpatch_hug_vulnerable", "..."),
        ("catpatch_hug_vulnerable", "If something happens, please don’t forget about me."),
        ("catpatch_hug_vulnerable", "Will I even make it out..?"),
        ("catpatch_hug_vulnerable", "I hate this... I really do..."),
        ("catpatch_hug_vulnerable", "They don't know what I'm going through down here..."),
        ("catpatch_hug_vulnerable", "Is this what we are to them..?"),
        ("catpatch_hug_vulnerable", "This only delays the inevitable..."),
        ("catpatch_hug_vulnerable", "I can't die like this..."),
        ("catpatch_hug_vulnerable", "Are... Are we going to make it out..?"),
        ("catpatch_hug_vulnerable", "Please tell me we going to be okay..."),
        ("catpatch_hug_vulnerable", "Their salvation will be rotten..."),
        ("catpatch_hug_vulnerable", "I don't think this is enough.. but thank you."),
        ("catpatch_hug_vulnerable", "Please don't leave my side... at least until I'm okay."),
        ("catpatch_hug_vulnerable", "Will they toss us aside if we make it out? What will they do to us..?"),
        ("catpatch_hug_vulnerable", "I... I don't want to do this anymore..."),
        ("catpatch_hug_vulnerable", "I want to go somewhere else... anywhere but here..."),
        ("catpatch_hug_vulnerable", "I... Won't end up like the rest, right..?"),
        ("catpatch_hug_vulnerable", "Their bodies... mangled... stabbed... cold... why..?"),
        ("catpatch_hug_vulnerable", "I can't... keep going..."),
        ("catpatch_hug_vulnerable", "I don't want to end up like them..."),
        ("catpatch_hug_vulnerable", "Why are there so many of us down here..? So many... all dead."),
        ("catpatch_hug_vulnerable", "I can't stop crying..."),
        ("catpatch_hug_vulnerable", "I can't stop looking at the ground..."),
        ("catpatch_hug_vulnerable", "I'm scared of this place..."),
        ("catpatch_hug_vulnerable", "They won't get away with this.. I'll... I don't know..."),
        ("catpatch_hug_vulnerable", "What will we do once this is all over..?"),
        ("catpatch_hug_vulnerable", "I hate that I'm actually adapting to this place..."),
        ("catpatch_hug_vulnerable", "The traps... the lights... the corpses..."),
        ("catpatch_hug_vulnerable", "Why can't they just get it themselves instead of commiting a genocide..?"),
        ("catpatch_hug_vulnerable", "I'm sick of this place... I'm sick of it all."),
        ("catpatch_hug_vulnerable", "I feel like I'm not going to make it..."),
        ("catpatch_hug_vulnerable", "I won't fall victim like the rest, right..?"),
        ("catpatch_hug_vulnerable", "I want to wake up..."),
        ("catpatch_hug_vulnerable", "This is all a bad dream, right..?"),
        ("catpatch_hug_vulnerable", "Why would they... why..."),
        ("catpatch_hug_vulnerable", "I... please don't watch if I scratch myself..."),
        ("catpatch_hug_vulnerable", "You shouldn't care about someone as useless as me..."),
        ("catpatch_hug_vulnerable", "I'm just dead weight, aren't I..?"),
        ("catpatch_hug_vulnerable", "I'm not smart like a Milky and I'm not strong like a Dune... why bother..."),
        ("catpatch_hug_vulnerable", "I hate this place... why here of all places..."),
        ("catpatch_hug_vulnerable", "If this keeps up I might have to resort to my own way out of this place..."),
        ("catpatch_hug_vulnerable", "...I wish we could have stayed..."),
        ("catpatch_hug_vulnerable", "Just this once..."),
        ("catpatch_hug_vulnerable", "I can't even look up..."),
        ("catpatch_hug_vulnerable", "I'm not smart and I'm not strong... why bother..."),
        ("catpatch_hug_vulnerable", "If this keeps up I might have to..."),
        ("catpatch_hug_vulnerable", "I'm exhausted."),
        ("catpatch_hug_vulnerable", "I'm so sick of this place."),
        ("catpatch_hug_vulnerable", "I hate this place."),
        ("catpatch_hug_vulnerable", "I hate myself..."),
        ("catpatch_hug_vulnerable", "Please tell me we're going to be okay."),
        ("catpatch_hug_vulnerable", "I'm trying... I'm trying so hard..."),
        ("catpatch_hug_vulnerable", "I'm trying not to cry, okay..?"),
        ("catpatch_hug_vulnerable", "I don't want to die..."),
        ("catpatch_hug_vulnerable", "I couldn't care less about the cargo."),
        ("catpatch_hug_vulnerable", "Thank you... Thank you..."),
        ("catpatch_hug_vulnerable", "...Okay..."),
        ("catpatch_hug_comfort", "You looked like you needed this."),
        ("catpatch_hug_comfort", "It's okay, even thought it's not, just know I'll be here for you."),
        ("catpatch_hug_comfort", "You've been carrying too much alone."),
        ("catpatch_hug_comfort", "You know I care about you."),
        ("catpatch_hug_comfort", "Hey, hey, it's okay. I'm here."),
        ("catpatch_hug_comfort", "Come here..."),
        ("catpatch_hug_comfort", "If you need to cry, I understand. I'm here for you."),
        ("catpatch_hug_comfort", "I'll be here for you, no matter what."),
        ("catpatch_hug_comfort", "If you need a shoulder to cry on, I'm here."),
        ("catpatch_hug_comfort", "Don't worry, I've got you."),
        ("catpatch_hug_comfort", "I know that look. I've had it too."),
        ("catpatch_hug_comfort", "Just rest your head for a second."),
        ("catpatch_hug_comfort", "I hope our captors are burning in hell for this."),
        ("catpatch_hug_comfort", "Our captors can go fuck themselves."),
        ("catpatch_hug_comfort", "Our captors can go to hell."),
        ("catpatch_hug_comfort", "Fuck 'em."),
        ("catpatch_hug_comfort", "When we get back, we will make them pay, don't worry."),
        ("catpatch_hug_comfort", "You don't have to handle this alone."),
        ("catpatch_hug_comfort", "Don't let this place win."),
        ("catpatch_hug_comfort", "You shouldn't have to go through this alone."),
        ("catpatch_hug_comfort", "Hey... breathe, alright? I'm here now."),
        ("catpatch_hug_comfort", "Smoke 'em if you got 'em..."),
        ("catpatch_hug_comfort", "I’m not gonna leave you. I’m right here."),
        ("catpatch_hug_comfort", "We are in this together, remember?"),
        ("catpatch_hug_comfort", "I know it’s hard, but we can get through this. Together."),
        ("catpatch_hug_comfort", "I’m not going anywhere. I’ve got you."),
        ("catpatch_hug_comfort", "I know you're scared, but we'll make it through this. I promise."),
        ("catpatch_hug_comfort", "I wish I could make it all better, but I can’t. I care about you and I’m here for you."),
        ("catpatch_hug_comfort", "I know this place is awful, but you’re not alone. I’m here with you."),
        ("catpatch_hug_comfort", "You’re doing the best you can, and that’s all anyone can ask of you. I’m proud of you."),
        ("catpatch_hug_comfort", "You are so strong, I'm so proud of you."),
        ("catpatch_hug_comfort", "I know it feels hopeless, but we have to keep going."),
        ("catpatch_hug_comfort", "You are the strongest one here."),
        ("catpatch_hug_comfort", "I'm so proud of you."),
        ("catpatch_hug_comfort", "Shh... Just hold on..."),
        ("catpatch_hug_comfort", "I’m by your side, buddy, it’s gonna be okay..."),
        ("catpatch_hug_comfort", "None of this is your fault. Not any of this."),
        ("catpatch_hug_comfort", "Just keep breathing, slowly. You’re doing good..."),
        ("catpatch_hug_comfort", "It’s going to be okay... everything's going to be okay..."),
        ("catpatch_hug_comfort", "Let's not give up just yet."),
        ("catpatch_hug_comfort", "Despite everything we’re still here, right?"),
        ("catpatch_hug_comfort", "I won’t let you get hurt again."),
        ("catpatch_hug_comfort", "You're okay."),
        ("catpatch_hug_comfort", "You'll be fine..."),
        ("catpatch_hug_comfort", "Come here."),
        ("catpatch_hug_comfort", "It's gonna be okay..."),
        ("catpatch_hug_comfort", "I'm proud of you."),
        ("catpatch_hug_comfort", "You're gonna make it out."),
        ("catpatch_hug_comfort", "I love you, it'll be okay."),
        ("catpatch_hug_comfort", "You're not alone."),
        ("catpatch_hug_comfort", "I'll stay near."),
        ("catpatch_hug_comfort", "Here, you're okay..."),
        ("catpatch_hug_comfort", "It's all good..."),
        ("catpatch_hug_comfort", "I'm here, it'll be okay..."),
        ("catpatch_hug_cheerful", "Hug time!"),
        ("catpatch_hug_cheerful", "Charge me, doctor!"),
        ("catpatch_hug_cheerful", "Come here!"),
        ("catpatch_hug_cheerful", "This is nice."),
        ("catpatch_hug_cheerful", "There are so many cool things here! I will never go back to the lab!"),
        ("catpatch_hug_cheerful", "You deserve a hug."),
        ("catpatch_hug_cheerful", "I think you are amazing!"),
        ("catpatch_hug_cheerful", "You are like, so totally awesome."),
        ("catpatch_hug_cheerful", "I hope things stay like this."),
        ("catpatch_hug_cheerful", "Wasn't this supposed to be hard and depressing?"),
        ("catpatch_hug_cheerful", "We got this in the bag."),
        ("catpatch_hug_cheerful", "Yippee!"),
        ("catpatch_hug_cheerful", "Physical touch makes me feel all tingly."),
        ("catpatch_hug_cheerful", "I'm gonna touch you >:3"),
        ("catpatch_hug_cheerful", "So like... wanna make out?"),
        ("catpatch_hug_cheerful", "We are doing SO good."),
        ("catpatch_hug_cheerful", "I like your fur."),
        ("catpatch_hug_cheerful", "This is WAY better than dying alone."),
        ("catpatch_hug_cheerful", "Okay maybe life IS worth living."),
        ("catpatch_hug_cheerful", "We're gonna make it. Probably."),
        ("catpatch_hug_cheerful", "This almost makes me forget the horrors."),
        ("catpatch_hug_cheerful", "You are officially my emotional support survivor."),
        ("catpatch_hug_cheerful", "I cast emotional support!"),
        ("catpatch_hug_cheerful", "We're doing great, sweetie!"),
        ("catpatch_hug_cheerful", "Let's do this again later!"),
        ("catpatch_hug_cheerful", "This place can't stop me from being silly!"),
        ("catpatch_hug_cheerful", "Wanna go blow up a life pod later?"),
        ("catpatch_hug_cheerful", "When we get back, let's escape and go on a roadtrip!"),
        ("catpatch_hug_cheerful", "The horrors persist but so do we!"),
        ("catpatch_hug_cheerful", "We're doing amazing, sweetie."),
        ("catpatch_hug_cheerful", "We're so back."),
        ("catpatch_hug_cheerful", "Are you a blood bag? Because I feel empty without you."),
        ("catpatch_hug_cheerful", "...!!!"),
        ("catpatch_hug_cheerful", "I think we deserve a little whimsy."),
        ("catpatch_hug_cheerful", "We should do this before every near-death experience."),
        ("catpatch_hug_cheerful", "If we die horribly later, this was still worth it."),
        ("catpatch_hug_cheerful", "Wow. Serotonin. Haven't felt that since my handler passed away."),
        ("catpatch_hug_cheerful", "I'm resisting the urge to start spinning in circles."),
        ("catpatch_hug_cheerful", "I'm choosing to believe everything will be okay."),
        ("catpatch_hug_cheerful", "Look at us. Surviving and everything."),
        ("catpatch_hug_cheerful", "I'm full of dangerous amounts of optimism."),
        ("catpatch_hug_cheerful", "We are absolutely crushing this apocalypse thing."),
        ("catpatch_hug_cheerful", "Morale has increased by approximately five hundred percent."),
        ("catpatch_hug_cheerful", "Your fur is SO soft, wow."),
        ("catpatch_hug_cheerful", "happy_responce_dialogie_option_27"),
        ("catpatch_hug_cheerful", "*Happiness noises*"),
        ("catpatch_hug_cheerful", "I wonder if I could suplex you."),
        ("catpatch_hug_cheerful", "Can you not crush me? Thanks."),
        ("catpatch_hug_cheerful", "Your breath stinks."),
        ("catpatch_hug_cheerful", "...You smell like steak. Maybe I’m just hungry."),
        ("catpatch_hug_cheerful", "So... Come here often?"),
        ("catpatch_hug_cheerful", "I wasn’t expecting that. I didn’t mean stop!"),
        ("catpatch_hug_cheerful", "Oh nooooo, please don’t hug me agaiinnnnnnnn..."),
        ("catpatch_hug_cheerful", "I’m proud of who we’ve become. Let’s be even better!"),
        ("catpatch_hug_cheerful", "Imagine if we could just LIVE after this, no experiments, no tests."),
        ("catpatch_hug_cheerful", "We should totally cuddle."),
        ("catpatch_hug_cheerful", "I love this... wait a minute-"),
        ("catpatch_hug_cheerful", "We're gonna make it!"),
        ("catpatch_hug_cheerful", "Oh, I love this place!"),
        ("catpatch_hug_cheerful", "Yawn... you're really warm, y'know?"),
        ("catpatch_hug_cheerful", "Oof- didn't expect this, haha!"),
        ("catpatch_hug_cheerful", "We should do this more!"),
        ("catpatch_hug_cheerful", "Awwh..."),
        ("catpatch_hug_cheerful", "We're doing amazing!"),
        ("catpatch_hug_cheerful", "Doing great so far!"),
        ("catpatch_hug_cheerful", "C'mere, you!"),
        ("catpatch_hug_cheerful", "There, there."),
        ("catpatch_hug_cheerful", "Oof- hey, you're crushing me! Haha!"),
        ("catpatch_hug_cheerful", "Wanna share some food later?"),
        ("catpatch_hug_cheerful", "You're so fluffy!"),
        ("catpatch_hug_cheerful", "You're really soft..."),
        ("catpatch_hug_cheerful", "Thank you!"),
        ("catpatch_hug_cheerful", "Thanks..."),
        ("catpatch_hug_cheerful", "Wow, this is nice..."),
        ("catpatch_hug_cheerful", "Let's do this more often."),
        ("catpatch_hug_neutral", "There you go."),
        ("catpatch_hug_neutral", "Alright, bring it in."),
        ("catpatch_hug_neutral", "Our captors would be so mad at us right now."),
        ("catpatch_hug_neutral", "No wonder this was agianst the rules."),
        ("catpatch_hug_neutral", "This is nice."),
        ("catpatch_hug_neutral", "Thanks."),
        ("catpatch_hug_neutral", "Could be worse, right?"),
        ("catpatch_hug_neutral", "Can't wait to fuck up our captors!"),
        ("catpatch_hug_neutral", "This makes me feel a little less alone."),
        ("catpatch_hug_neutral", "Hope you are doing well."),
        ("catpatch_hug_neutral", "Is this how you thought we were going to end up?"),
        ("catpatch_hug_neutral", "Crazy times we're living in."),
        ("catpatch_hug_neutral", "I like this."),
        ("catpatch_hug_neutral", "Don't make it weird."),
        ("catpatch_hug_neutral", "You're warmer than I expected."),
        ("catpatch_hug_neutral", "This almost feels normal."),
        ("catpatch_hug_neutral", "This place really wears us down, huh."),
        ("catpatch_hug_neutral", "So, what did they put you through back on Earth?"),
        ("catpatch_hug_neutral", "We keep going."),
        ("catpatch_hug_neutral", "One step at a time."),
        ("catpatch_hug_neutral", "We got this."),
        ("catpatch_hug_neutral", "If I lose you too, I might go insane."),
        ("catpatch_hug_neutral", "I ever tell you about the time my buddy Keith told me he was picked up by some little green men and they--"),
        ("catpatch_hug_neutral", "Not too bad, right?"),
        ("catpatch_hug_neutral", "I really do not miss being beaten..."),
        ("catpatch_hug_neutral", "Our captors are probably really upset at us."),
        ("catpatch_hug_neutral", "I watched my buddy get sawed in half on Earth, so somehow this is a step up."),
        ("catpatch_hug_neutral", "I don't know about you, but I needed that."),
        ("catpatch_hug_neutral", "I ever tell you about the time my buddy Keith fell down an open manhole? He was unconscious down there for like a week. During that time, unbeknownst to Keith, they paved over him. Keith had to--"),
        ("catpatch_hug_neutral", "Can't hurt to slow down for a second."),
        ("catpatch_hug_neutral", "I enjoy your company."),
        ("catpatch_hug_neutral", "Just making sure you're still with me."),
        ("catpatch_hug_neutral", "Don't get used to this."),
        ("catpatch_hug_neutral", "You're tougher than you look."),
        ("catpatch_hug_neutral", "One decent moment in this mess."),
        ("catpatch_hug_neutral", "Just be careful, stick together, and don't die."),
        ("catpatch_hug_neutral", "Could be worse, honestly."),
        ("catpatch_hug_neutral", "I'd miss you if you died, so don't do that."),
        ("catpatch_hug_neutral", "Being alone would suck down here."),
        ("catpatch_hug_neutral", "Better than dying alone, right?"),
        ("catpatch_hug_neutral", "Not dead yet."),
        ("catpatch_hug_neutral", "I'm glad you're alive."),
        ("catpatch_hug_neutral", "Hang in there."),
        ("catpatch_hug_neutral", "Don't give up."),
        ("catpatch_hug_neutral", "You're softer than the others."),
        ("catpatch_hug_neutral", "Just trying to keep morale up."),
        ("catpatch_hug_neutral", "You're doing alright."),
        ("catpatch_hug_neutral", "This place gets lonely fast. I appreciate you."),
        ("catpatch_hug_neutral", "I appreciate you."),
        ("catpatch_hug_neutral", "What do you think Earth is like?"),
        ("catpatch_hug_neutral", "Two can be one..."),
        ("catpatch_hug_neutral", "Well, now we both need a shower."),
        ("catpatch_hug_neutral", "Yeah, okay. Bring it in."),
        ("catpatch_hug_neutral", "I kind of expected something else..."),
        ("catpatch_hug_neutral", "Let me get that for you."),
        ("catpatch_hug_neutral", "We’ve got places to be, but that can wait."),
        ("catpatch_hug_neutral", "Just making sure."),
        ("catpatch_hug_neutral", "Uh... I slipped?"),
        ("catpatch_hug_neutral", "Soft..."),
        ("catpatch_hug_neutral", "You're fluffy."),
        ("catpatch_hug_neutral", "Thanks... I feel better."),
        ("catpatch_hug_neutral", "Cute..."),
        ("catpatch_hug_neutral", "Warm..."),
        ("catpatch_hug_neutral", "Hey, this is nice..."),
        ("catpatch_hug_neutral", "I feel better."),
        ("catpatch_hug_neutral", "Thank you!"),
        ("catpatch_hug_neutral", "Lovely."),
        ("catpatch_hug_neutral", "Nice!"),
        ("catpatch_hug_neutral", "Hug time!"),
        ("catpatch_hug_neutral", "Oh, this feels amazing..."),
        ("catpatch_hug_neutral", "Do you think the others are okay?"),
        ("catpatch_hug_neutral", "I'd miss you if you died, y'know?"),
        ("catpatch_hug_neutral", "We're doing okay."),
        ("catpatch_hug_neutral", "Doing well so far..."),
        ("catpatch_hug_neutral", "Not too bad."),
        ("catpatch_hug_neutral", "We're okay, aren't we?"),
        ("catpatch_hug_neutral", "You okay?"),
        ("catpatch_hug_neutral", "All good?"),
    };
}
