internal static class SimpleQoLTr
{
    public static readonly (string En, string Zh)[] GamesetKeys =
    {
        ("gameseteqpliquidtooltipfix", "液体转移时隐藏悬浮提示"),
        ("gameseteqpliquidtooltipfixdsc", "防止无关的世界悬浮提示遮挡液体转移界面。"),
        ("gameseteqpliquidsnapenabled", "液体转移量对齐"),
        ("gameseteqpliquidsnapenableddsc", "按住设定按键时，转移量会对齐到设定的步进。"),
        ("gameseteqpliquidsnapkey", "液体对齐按键"),
        ("gameseteqpliquidsnapamount", "液体对齐步进"),
        ("gameseteqpliquidsnapamountdsc", "以 1mL 为增量，设定 1~25mL 范围内的液体转移步进。"),
        ("gameseteqpclimbassistenabled", "攀爬抓取辅助"),
        ("gameseteqpclimbassistenableddsc", "按住上方向时会抓住最近的攀爬物，并跟随左右输入移动。刚松开的绳子在 0.3 秒内会被忽略。"),
        ("gameseteqpclimbassistrange", "攀爬辅助范围"),
        ("gameseteqpclimbassistrangedsc", "以 0.1 为增量，设定 1.5~3.0 范围内的攀爬辅助距离。"),
        ("gameseteqpforcemouselook", "始终面向鼠标"),
        ("gameseteqpforcemouselookdsc", "防止尸体、陷阱、炮塔、敌人等注视目标覆盖鼠标指向。"),
        ("gameseteqpchestlightenabled", "胸前照明"),
        ("gameseteqpchestlightenableddsc", "在角色胸前附近添加一盏亮度固定的灯。"),
        ("gameseteqpblueprintscreenenabled", "跳过蓝图制作菜单"),
        ("gameseteqpblueprintscreenenableddsc", "使用蓝图时不再打开制作菜单。"),
        ("gameseteqpdropitemenabled", "快速丢弃物品"),
        ("gameseteqpdropitemenableddsc", "启用后可用设定按键丢弃鼠标指向的物品。"),
        ("gameseteqpdropitemkey", "快速丢弃按键"),
        ("gameseteqpprotectfavoritedrop", "保护收藏物品"),
        ("gameseteqpprotectfavoritedropdsc", "防止收藏的物品被快速丢弃。"),
        ("gameseteqpquickpickupenabled", "快速全部拾取"),
        ("gameseteqpquickpickupenableddsc", "拾取设定范围内的所有物品。"),
        ("gameseteqpquickpickupkey", "快速拾取按键"),
        ("gameseteqpquickpickuprange", "快速拾取范围"),
        ("gameseteqpquickpickuprangedsc", "设定 1~5 米的附近拾取范围。"),
        ("gameseteqpquickpickupsort", "按容量效率收纳"),
        ("gameseteqpquickpickupsortdsc", "优先放入匹配物品标签的专用容器，其次放入负重减免最好的容器。"),
        ("gameseteqpturretwarningbeam", "炮塔射击预警线"),
        ("gameseteqpturretwarningbeamdsc", "沿炮塔炮管的射击方向显示红色危险线。"),
        ("gameseteqpscrapautomerge", "金属废料自动合并"),
        ("gameseteqpscrapautomergedsc", "自动合并金属废料至接近 90%，最高可合并至 97%。"),
        ("gameseteqpignoreattackrecoil", "免除攻击后坐"),
        ("gameseteqpignoreattackrecoildsc", "攻击墙壁、地砖或玻璃碎片时，本地玩家不再被向后推。"),
        ("gameseteqpworkouttimer", "锻炼时间预估"),
        ("gameseteqpworkouttimerdsc", "在锻炼中的角色头顶显示升到下一级力量/韧性所需的预计时间。他人的预估需要最近同步过的经验值。"),
        ("gameseteqpworkouttimerothers", "显示他人的锻炼计时"),
        ("gameseteqpworkouttimerothersdsc", "在其他玩家头顶显示其锻炼预计时间。不影响你自己的计时。"),
        ("gameseteqpcontainercapacityhint", "容器容量提示"),
        ("gameseteqpcontainercapacityhintdsc", "在容量一行显示超重数值，并用红框标出拿走后即可装下的最轻物品。仅为显示提示，不会移动物品。"),
    };
    public static readonly (string En, string Zh)[] WorkoutFragments =
    {
        ("Stat gain: STR/RES", "属性增长：力量/韧性"),
        ("Stat gain: STR", "属性增长：力量"),
        ("Stat gain: RES", "属性增长：韧性"),
        ("Time remaining: ", "剩余时间："),
        ("STR ", "力量 "),
        ("/ RES ", "/ 韧性 "),
        ("Waiting for XP", "等待经验数据"),
        ("No XP gain", "无经验增长"),
    };
}
