internal static class SimpleQoLTrTw
{
    public static readonly (string En, string Zh)[] GamesetKeys =
    {
        ("gameseteqpliquidtooltipfix", "液體轉移時隱藏懸浮提示"),
        ("gameseteqpliquidtooltipfixdsc", "防止無關的世界懸浮提示遮擋液體轉移界面。"),
        ("gameseteqpliquidsnapenabled", "液體轉移量對齊"),
        ("gameseteqpliquidsnapenableddsc", "按住設定按鍵時，轉移量會對齊到設定的步進。"),
        ("gameseteqpliquidsnapkey", "液體對齊按鍵"),
        ("gameseteqpliquidsnapamount", "液體對齊步進"),
        ("gameseteqpliquidsnapamountdsc", "以 1mL 為增量，設定 1~25mL 範圍內的液體轉移步進。"),
        ("gameseteqpclimbassistenabled", "攀爬抓取輔助"),
        ("gameseteqpclimbassistenableddsc", "按住上方向時會抓住最近的攀爬物，並跟隨左右輸入移動。剛鬆開的繩子在 0.3 秒內會被忽略。"),
        ("gameseteqpclimbassistrange", "攀爬輔助範圍"),
        ("gameseteqpclimbassistrangedsc", "以 0.1 為增量，設定 1.5~3.0 範圍內的攀爬輔助距離。"),
        ("gameseteqpforcemouselook", "始終面向鼠標"),
        ("gameseteqpforcemouselookdsc", "防止屍體、陷阱、炮塔、敵人等注視目標覆蓋鼠標指向。"),
        ("gameseteqpchestlightenabled", "胸前照明"),
        ("gameseteqpchestlightenableddsc", "在角色胸前附近添加一盞亮度固定的燈。"),
        ("gameseteqpblueprintscreenenabled", "跳過藍圖製作界面"),
        ("gameseteqpblueprintscreenenableddsc", "使用藍圖時不再打開製作界面。"),
        ("gameseteqpdropitemenabled", "快速丟棄物品"),
        ("gameseteqpdropitemenableddsc", "啟用後可用設定按鍵丟棄鼠標指向的物品。"),
        ("gameseteqpdropitemkey", "快速丟棄按鍵"),
        ("gameseteqpprotectfavoritedrop", "保護收藏物品"),
        ("gameseteqpprotectfavoritedropdsc", "防止收藏的物品被快速丟棄。"),
        ("gameseteqpquickpickupenabled", "快速全部拾取"),
        ("gameseteqpquickpickupenableddsc", "拾取設定範圍內的所有物品。"),
        ("gameseteqpquickpickupkey", "快速拾取按鍵"),
        ("gameseteqpquickpickuprange", "快速拾取範圍"),
        ("gameseteqpquickpickuprangedsc", "設定 1~5 米的附近拾取範圍。"),
        ("gameseteqpquickpickupsort", "按容量效率收納"),
        ("gameseteqpquickpickupsortdsc", "優先放入匹配物品標籤的專用容器，其次放入負重減免最好的容器。"),
        ("gameseteqpturretwarningbeam", "炮塔射擊預警線"),
        ("gameseteqpturretwarningbeamdsc", "沿炮塔炮管的射擊方向顯示紅色危險線。"),
        ("gameseteqpscrapautomerge", "廢金屬自動合併"),
        ("gameseteqpscrapautomergedsc", "自動合併廢金屬至接近 90%，最高可合併至 97%。"),
        ("gameseteqpignoreattackrecoil", "免除攻擊後坐"),
        ("gameseteqpignoreattackrecoildsc", "攻擊牆壁、地磚或玻璃碎片時，本地玩家不再被向後推。"),
        ("gameseteqpworkouttimer", "鍛鍊時間預估"),
        ("gameseteqpworkouttimerdsc", "在鍛鍊中的角色頭頂顯示升到下一級力量/韌性所需的預計時間。他人的預估需要最近同步過的經驗值。"),
        ("gameseteqpworkouttimerothers", "顯示他人的鍛鍊計時"),
        ("gameseteqpworkouttimerothersdsc", "在其他玩家頭頂顯示其鍛鍊預計時間。不影響你自己的計時。"),
        ("gameseteqpcontainercapacityhint", "容器容量提示"),
        ("gameseteqpcontainercapacityhintdsc", "在容量一行顯示超重數值，並用紅框標出拿走後即可裝下的最輕物品。僅為顯示提示，不會移動物品。"),
    };
    public static readonly (string En, string Zh)[] WorkoutFragments =
    {
        ("Stat gain: STR/RES", "屬性增長：力量/韌性"),
        ("Stat gain: STR", "屬性增長：力量"),
        ("Stat gain: RES", "屬性增長：韌性"),
        ("Time remaining: ", "剩餘時間："),
        ("STR ", "力量 "),
        ("/ RES ", "/ 韌性 "),
        ("Waiting for XP", "等待經驗數據"),
        ("No XP gain", "無經驗增長"),
    };
}
