[概要]
"GUID" = "com.rushellxyz.newfirearms/autoarsenal"
"翻译版本" = "1.0.0"
"模组版本" = "2.0"
[Locale]
# Original: AA-12
"autoarsenal.aa12" = "AA-12霰彈槍"
# Original: A fully automatic shotgun, shockingly small recoil. Uses Shotgun mags
"autoarsenal.aa12dsc" = "一把全自動霰彈槍，後坐力驚人地小。使用霰彈彈匣。"
# Original: Karabiner 98k
"autoarsenal.kar98k" = "Karabiner 98k步槍"
# Original: A supprisingly accurate rifle, somehow still works. Uses 5.56 rounds.
"autoarsenal.kar98kdsc" = "一支異常精準的步槍，不知為何還能用。使用5.56毫米子彈。"
# Original: M1918 Tankgewehr
"autoarsenal.m1918tankgewehr" = "M1918反坦克步槍"
# Original: You dont know whats more horrifying - this or the thing it was made to destroy... Uses 13.2mm TuF rounds.
"autoarsenal.m1918tankgewehrdsc" = "你不知道哪個更可怕——這個還是它用來摧毀的東西...使用13.2mm TuF子彈。"
# Original: MP7
"autoarsenal.mp7" = "MP7衝鋒槍"
# Original: Very fast firing SMG. Can fit small magazines or SMG magazines
"autoarsenal.mp7dsc" = "射速極快的衝鋒槍。可使用小型彈匣或衝鋒槍彈匣。"
# Original: Revolver
"autoarsenal.revolver" = "左輪手槍"
# Original: Heavy caliber handgun. uses .357 Magnum rounds
"autoarsenal.revolverdsc" = "大口徑手槍。使用.357馬格南子彈。"
# Original: 13.2mm TuF
"autoarsenal.132tuf" = "13.2mm TuF子彈"
# Original: a round of truly unholy caliber... Can only be loaded directly
"autoarsenal.132tufdsc" = "一發真正褻瀆口徑的子彈...只能直接裝填。"
# Original: .357 Magnum
"autoarsenal.357magnum" = ".357馬格南"
# Original: A big handgun round. Can only be loaded directly.
"autoarsenal.357magnumdsc" = "一種大口徑手槍子彈。只能直接裝填。"
# Original: Box of .357 Magnum
"autoarsenal.boxof357magnum" = ".357馬格南彈藥盒"
# Original: A box made to hold .357 rounds, can hold up to 18 of them
"autoarsenal.boxof357magnumdsc" = "專為容納.357子彈設計的盒子，最多可裝18發。"
# Original: Case of 13.2mm TuF
"autoarsenal.caseof132tuf" = "13.2mm TuF彈箱"
# Original: So much power in such a small package.
"autoarsenal.caseof132tufdsc" = "如此小的包裝蘊含如此強大的力量。"
# Original: Shotgun magazine
"autoarsenal.shotgunmag" = "霰彈槍彈匣"
# Original: A special magazaine made to hold 32 12-Gauge rounds.
"autoarsenal.shotgunmagdsc" = "一種專為容納32發12號口徑霰彈而設計的特殊彈匣。"