[概要]
"GUID" = "com.balaur.BetterLogic"
"翻译版本" = "v1.0.1"
"模组版本" = "v1.0.5"
[Locale]
# Original: <color=purple>Crafting</color>: Prefer on floor
"gamesetprefer_on_floor" = "<color=purple>製作</color>：優先使用地面材料"
# Original: Use materials on the floor before things in your inventory.
"gamesetprefer_on_floordsc" = "在消耗揹包物品前，先使用地面上的材料。"
# Original: <color=purple>Crafting</color>: Prefer not containers
"gamesetprefer_not_container" = "<color=purple>製作</color>：延後使用容器"
# Original: Use containers, like bags, later.
"gamesetprefer_not_containerdsc" = "延後使用容器（如揹包）。"
# Original: <color=purple>Crafting</color>: Prefer not wearables
"gamesetprefer_not_wearable" = "<color=purple>製作</color>：延後使用可穿戴物品"
# Original: Use wearables, like clothing, later.
"gamesetprefer_not_wearabledsc" = "延後使用可穿戴物品（如衣物）。"
# Original: <color=purple>Crafting</color>: Prefer held
"gamesetprefer_on_body" = "<color=purple>製作</color>：優先使用身上材料"
# Original: Use materials in your hands/mouth/back before things in your inventory.
"gamesetprefer_on_bodydsc" = "在消耗揹包物品前，先使用手上/嘴裡/背上的材料。"
# Original: <color=purple>Crafting</color>: Prefer higher quality
"gamesetprefer_high_quality" = "<color=purple>製作</color>：優先使用高質量物品"
# Original: Use items of lower quality, like lower hammering, later.
"gamesetprefer_high_qualitydsc" = "延後使用低質量物品（如錘擊值較低的物品）。"
# Original: <color=purple>Crafting</color>: Prefer lower value
"gamesetprefer_low_value" = "<color=purple>製作</color>：優先使用低價值物品"
# Original: Use items of higher trading value later.
"gamesetprefer_low_valuedsc" = "延後使用交易價值較高的物品。"
# Original: <color=purple>Crafting</color>: Prefer lower condition
"gamesetprefer_low_condition" = "<color=purple>製作</color>：優先使用低耐久物品"
# Original: Use items with higher condition later.
"gamesetprefer_low_conditiondsc" = "延後使用耐久較高的物品。"
# Original: <color=purple>Storage (Liquid)</color>: Allow stacking into mixed
"gamesetliquids_can_mix" = "<color=purple>儲存液體</color>：允許液體混合"
# Original: Allow a pouring this liquid into a bottle that has other liquids, only if it already has some of this liquid.
"gamesetliquids_can_mixdsc" = "允許將這種液體倒入已裝有其他液體的瓶子中，但前提是瓶子裡已經有一些這種液體。"
# Original: <color=purple>Storage (Liquid)</color>: Allow filling new bottles
"gamesetliquids_can_fill_new_bottles" = "<color=purple>儲存液體</color>：允許裝滿新瓶子"
# Original: Allow liquids to fill bottles that are empty.
"gamesetliquids_can_fill_new_bottlesdsc" = "允許液體裝滿空瓶子。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer liquids unmixed
"gamesetcompare_liquid_unmixed_enabled" = "<color=purple>儲存液體</color>：優先使用未混合液體"
# Original: If 'Allow liquids to mix' is enabled, fill containers with the fewest different liquids.
"gamesetcompare_liquid_unmixed_enableddsc" = "如果“允許液體混合”啟用，則填充含有不同液體種類最少的容器。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer liquid stack
"gamesetcompare_liquid_stacking_enabled" = "<color=purple>儲存液體</color>：優先使用混合液體"
# Original: Fill containers that have the highest amount of this liquid first.
"gamesetcompare_liquid_stacking_enableddsc" = "優先填充含有該液體數量最多的容器。"
# Original: <color=purple>Storage (Liquid)</color>: Prefer low weight liquid containers
"gamesetcompare_liquid_weight_enabled" = "<color=purple>儲存液體</color>：優先使用重量比高的液體容器"
# Original: Prefer containers that have the lowest weight to highest liquid ratio when full.
"gamesetcompare_liquid_weight_enableddsc" = "優先使用裝滿時重量與液體比例最低的容器。"
# Original: <color=purple>Storage</color>: Notify where stored
"gamesetnotify_where_stored" = "<color=purple>儲存</color>：通知儲存位置"
# Original: Create a popup that specifies where the output of crafting recipes was placed.
"gamesetnotify_where_storeddsc" = "創建一個彈出窗口，指明製作配方的輸出放置位置。"
# Original: <color=purple>Storage</color>: Store in containers first
"gamesetstore_in_containers_first" = "<color=purple>儲存</color>：優先存放在容器中"
# Original: Put crafted items into containers first, rather than in hands/mouth/back.
"gamesetstore_in_containers_firstdsc" = "優先將製作物品放入容器，而非手中/嘴裡/背上。"
# Original: <color=purple>Storage</color>: Prefer matched container type
"gamesetcompare_storage_type" = "<color=purple>儲存</color>：優先使用匹配的容器類型"
# Original: When storing crafted items, choose containers specific to this item type, such as the material pouch for materials.
"gamesetcompare_storage_typedsc" = "當儲存製作物品時，選擇該物品類型專用的容器，例如材料的材料袋。"
# Original: <color=purple>Storage</color>: Prefer higher container reduction
"gamesetcompare_storage_reduction" = "<color=purple>儲存</color>：優先使用負重減免更高的容器"
# Original: When storing crafted items, prefer containers that have a better encumbrance reduction.
"gamesetcompare_storage_reductiondsc" = "當儲存製作物品時，優先使用負重減免更好的容器。"
# Original: <color=purple>Storage</color>: Prefer fuller container
"gamesetcompare_storage_full" = "<color=purple>儲存</color>：優先使用容量佔用更高的容器"
# Original: When storing crafted items, prefer containers that are more full.
"gamesetcompare_storage_fulldsc" = "當儲存製作物品時，優先使用容量佔用更高的容器。"
# Original: <color=purple>Storage</color>: Prefer larger containers
"gamesetcompare_storage_capacity" = "<color=purple>儲存</color>：優先使用容量更大的容器"
# Original: When storing crafted items, prefer containers that are larger.
"gamesetcompare_storage_capacitydsc" = "當儲存製作物品時，優先使用容量更大的容器。"
# Original: <color=purple>Storage</color>: Prefer best condition container
"gamesetcompare_storage_best_condition" = "<color=purple>儲存</color>：優先使用耐久最高的容器"
# Original: When storing crafted items, prefer containers that have higher condition.
"gamesetcompare_storage_best_conditiondsc" = "當儲存製作物品時，優先使用耐久更高的容器。"
