[概要]
"GUID" = "com.rushellxyz.newclothing"
"翻译版本" = "v1.0.0"
"模组版本" = "v1.6.2"
[Locale]
# Original: Arm warmers
"armwarmers" = "護臂套"
# Original: A pair of arm warmers. Provides some insulation against the cold.
"armwarmersdsc" = "一副護臂套。有一定保暖作用。"
# Original: Holiday hat
"holidayhat" = "節日帽"
# Original: You've heard that people wear these for some kind of special occasion, though you're not sure what it's about. It's nice that you were sent with one, at least.
"holidayhatdsc" = "你聽說人們會在某些特殊時間佩戴這些，雖然你並不清楚具體原因。但至少有人送你一件倒也挺不錯。"
# Original: Combat Boots
"newclothing.boots" = "戰鬥靴"
# Original: A pair of heavy-duty leather boots, will last you quite a while and is fairly protective.
"newclothing.bootsdsc" = "一雙厚重皮靴，相當耐穿且防護性不錯。"
# Original: Crop shirt
"newclothing.cropshirt" = "露臍襯衫"
# Original: A crop shirt made to cover your thorax. Provides mild insulation and some protection
"newclothing.cropshirtdsc" = "一件覆蓋軀幹的露臍襯衫。提供輕度保暖和一定防護。"
# Original: Crop T-Shirt
"newclothing.croptshirt" = "露臍T恤"
# Original: A crop t-shirt made to cover your thorax and upper arms. Provides medium insulation and some protection
"newclothing.croptshirtdsc" = "一件覆蓋軀幹和上臂的露臍T恤。提供中等保暖和一定防護。"
# Original: Jeans
"newclothing.jeans" = "牛仔褲"
# Original: Jeans, provides protection and insulation. Have an exceptional high durability
"newclothing.jeansdsc" = "牛仔褲，提供防護和保暖。耐久度異常高。"
# Original: Long Sleeve Shirt
"newclothing.longshirt" = "長袖襯衫"
# Original: A long-sleeve shirt meant to cover your upper torso. Provides good insulation and some protection
"newclothing.longshirtdsc" = "一件覆蓋上半身的長袖襯衫。提供良好保暖和一定防護。"
# Original: Shirt
"newclothing.shirt" = "襯衫"
# Original: A shirt made to cover your thorax and abdomen. Provides medium insulation and some protection
"newclothing.shirtdsc" = "一件覆蓋胸部和腹部的襯衫。提供中等保暖和一定防護。"
# Original: Shorts
"newclothing.shorts" = "短褲"
# Original: Shorted version of jeans, provides some protection and insulation. Have an exceptional high durability
"newclothing.shortsdsc" = "牛仔褲的短款，提供一定防護和保暖。耐久度異常高。"
# Original: Socks
"newclothing.socks" = "襪子"
# Original: A pair of socks. Provides protection for yout paws. Have no effect against glass shards.
"newclothing.socksdsc" = "一雙襪子。保護你的腳掌。對玻璃碎片無效。"
# Original: Thigh highs
"newclothing.thighhighs" = "過膝襪"
# Original: A pair of thigh highs. Provides protection and insulation against the cold.
"newclothing.thighhighsdsc" = "一雙過膝襪。提供防護和禦寒。"
# Original: T-Shirt
"newclothing.tshirt" = "T恤"
# Original: A t-shirt made to cover your thorax, abdomen and upper arms. Provides good insulation and some protection
"newclothing.tshirtdsc" = "一件覆蓋胸部、腹部和上臂的T恤。提供良好保暖和一定防護。"
