[概要]
"GUID" = "com.rushellxyz.newfirearms"
"翻译版本" = "v1.0.1"
"模组版本" = "v1.5.4"
[Locale]
# Original: Bolt-action rifle
"makeshiftrifle" = "栓動步槍"
# Original: TODO
"makeshiftrifledsc" = "待辦"
# Original: Glock 18
"newfirearms.glock18" = "格洛克18"
# Original: A select-fire 9mm handgun. Functionaly it's exaclty like glock 17 but with option for full-auto. Can only fit small magazines
"newfirearms.glock18dsc" = "一把可選擇射擊模式的9毫米手槍。功能上與格洛克17完全相同，但增加了全自動選項。只能裝填手槍彈匣。"
# Original: M1911
"newfirearms.m1911" = "M1911手槍"
# Original: An old, small, magazine-feed 9mm handgun. Would do well in combat. Can only fit m1911 magazines
"newfirearms.m1911dsc" = "一把老舊的小型9毫米彈匣供彈手槍。適合戰鬥使用。只能裝填M1911彈匣。"
# Original: Makeshift pistol
"newfirearms.makeshiftpistol" = "簡易手槍"
# Original: A crude basic handgun, holds two 9mm rounds in chambers. Doesn't have safety. Won't last for a long. Consider switching to more capacble firearms in case of combat
"newfirearms.makeshiftpistoldsc" = "一把粗糙的基礎手槍，彈膛內可容納兩發9毫米子彈。沒有保險。使用壽命不長。如需戰鬥，考慮換用更趁手的武器。"
# Original: MP5
"newfirearms.mp5" = "MP5衝鋒槍"
# Original: A stocked select-fire submachine gun. Can fit small magazines or SMG magazines
"newfirearms.mp5dsc" = "一把帶槍托的可切換射擊模式衝鋒槍。可裝填手槍彈匣或衝鋒槍彈匣。"
# Original: P90
"newfirearms.p90" = "P90衝鋒槍"
# Original: A 9mm bullpup submachine gun, uses specialized P90 magazines.
"newfirearms.p90dsc" = "一把9毫米無託式衝鋒槍，使用專用的P90彈匣。"
# Original: Saiga
"newfirearms.saiga" = "Saiga"
# Original: TODO
"newfirearms.saigadsc" = "待辦"
# Original: Sawed off
"newfirearms.sawedoff" = "鋸短霰彈槍"
# Original: An level-action shotgun with cutoff barrels, only holds 2 rounds. Can be loaded with any 12-gauge round
"newfirearms.sawedoffdsc" = "一把截短槍管的槓桿式霰彈槍，只能裝填2發彈藥。可裝填任何12號口徑彈藥。"
# Original: Semi-auto shotgun
"newfirearms.semiautoshotgun" = "半自動霰彈槍"
# Original: TODO
"newfirearms.semiautoshotgundsc" = "待辦"
# Original: UZI
"newfirearms.uzi" = "UZI衝鋒槍"
# Original: A full-auto 9mm submachine gun. The recoil is rather, unplessant. Can fit small magazines or SMG magazines
"newfirearms.uzidsc" = "一把全自動9毫米衝鋒槍。後坐力相當，令人不快。可使用手槍彈匣或衝鋒槍彈匣。"
# Original: Vector
"newfirearms.vector" = "Vector衝鋒槍"
# Original: An 9mm selct-fire submachine gun with a special recoil-reduction mechanism and a low fire rate. Can only fit smg magazines
"newfirearms.vectordsc" = "一把使用特殊減後坐力機制且射速較低的9毫米可切換射擊模式衝鋒槍。只能裝填衝鋒槍彈匣。"
# Original: Glock 17
"pistol" = "格洛克17"
# Original: A common 9mm semi-auto handgun. You remember your capitors carrying it back on Earth. Can only fit small magazines
"pistoldsc" = "一把常見的9毫米半自動手槍。你記得在地球上時，看管你們的人曾隨身攜帶過它。只能裝填手槍彈匣。"
# Original: Carbine
"rifle" = "卡賓槍"
# Original: TODO
"rifledsc" = "待辦"
# Original: Pump-action shotgun
"shotgun" = "泵動霰彈槍"
# Original: TODO
"shotgundsc" = "待辦"
# Original: Box of 12gauge
"boxof12gauge" = "12號霰彈彈盒"
# Original: TODO
"boxof12gaugedsc" = "待辦"
# Original: Box of 5.56
"boxof556" = "5.56毫米彈盒"
# Original: TODO
"boxof556dsc" = "待辦"
# Original: Box of 9mm
"boxof9mm" = "9毫米彈盒"
# Original: An box made to hold up to thirty-two 9mm round. Use to remove round
"boxof9mmdsc" = "可容納最多32發9毫米子彈的彈盒。用於退彈。"
# Original: M1911 magazine
"newfirearms.m1911mag" = "M1911彈匣"
# Original: An handgun magazine. Can hold up to eight 9mm rounds in it
"newfirearms.m1911magdsc" = "一個手槍彈匣。可容納最多8發9毫米子彈。"
# Original: P90 magazine
"newfirearms.p90mag" = "P90彈匣"
# Original: TODO
"newfirearms.p90magdsc" = "待辦"
# Original: Saiga magazine
"newfirearms.saigamag" = "Saiga彈匣"
# Original: TODO
"newfirearms.saigamagdsc" = "待辦"
# Original: SMG magazine
"newfirearms.smgmag" = "衝鋒槍彈匣"
# Original: An magazine for use in subamchine guns. Can hold up to thirty 9mm rounds
"newfirearms.smgmagdsc" = "一個用於衝鋒槍的彈匣。可容納最多30發9毫米子彈。"
# Original: Rifle magazine
"riflemagazine" = "步槍彈匣"
# Original: TODO
"riflemagazinedsc" = "待辦"
# Original: Small magazine
"smallmagazine" = "手槍彈匣"
# Original: An handgun magazine. Can hold up to seventeen 9mm rounds in it
"smallmagazinedsc" = "一個手槍彈匣。可容納最多17發9毫米子彈。"
# Original: 12gauge birdshot
"12gaugebird" = "12號鳥彈"
# Original: An variation of 12gauge with more pellets and higher spread. Can be loaded into shotguns, or directly into the chamber if the gun's bolt is open.
"12gaugebirddsc" = "12號鳥彈的變種，彈丸更多、散佈更大。可直接裝入霰彈槍，或直接上膛（需打開槍機）。"
# Original: 12gauge slugshot
"12gaugeslug" = "12號獨頭彈"
# Original: An variation of 12gauge with only one big pellet. Can be loaded into shotguns, or directly into the chamber if the gun's bolt is open
"12gaugeslugdsc" = "12號獨頭彈的變種，只有一枚大彈丸。可直接裝入霰彈槍，或直接上膛（需打開槍機）。"
# Original: 9mm hollow round
"9mmhollow" = "9毫米空尖彈"
# Original: An variation of 9mm round with hollow points, deals more damage against living targets, but not as penetrating. Can be loaded into magazines, or directly into the chamber if the gun's bolt is open.
"9mmhollowdsc" = "9毫米子彈的空尖彈變種，對活體目標傷害更高，但穿透力較弱。可裝入彈匣，或直接上膛（需打開槍機）。"
# Original: 9mm venomus round
"9mmvenomus" = "9毫米毒彈"
# Original: An variation of 9mm round with venomus points, deals toxicosis against living targets, but not as penetrating. Can be loaded into magazines, or directly into the chamber if the gun's bolt is open.
"9mmvenomusdsc" = "9毫米子彈的毒彈變種，對活體目標造成中毒效果，但穿透力較弱。可裝入彈匣，或直接上膛（需打開槍機）。"
# Original: Gun jamming
"runsetnewfirearms.gunjamming" = "槍械卡殼"
# Original: Can guns jam?
"runsetnewfirearms.gunjammingdsc" = "槍械會卡殼嗎？"
# Original: Gun damage multiplier
"runsetnewfirearms.gundmgmult" = "槍械傷害倍率"
# Original: Gun eject casing
"runsetnewfirearms.gunejectcasing" = "槍械拋殼"
# Original: Should guns eject casings after firing?
"runsetnewfirearms.gunejectcasingdsc" = "射擊後槍械應拋殼嗎？"
# Original: Stun hitbox size
"runsetnewfirearms.stunhitbox" = "眩暈判定框大小"
# Original: When you shoot above or below an enemy, they still get stunned. This determines the size of the stun hitbox.
"runsetnewfirearms.stunhitboxdsc" = "當你射擊敵人上方或下方時，他們仍會被眩暈。此選項決定眩暈判定框的大小。"
# Original: Firearm handling course
"newfirearms.firearmhandlingcourse" = "槍械操作訓練課程"
# Original: Unlock at level 4
"newfirearms.firearmhandlingcourselock" = "抵達第四層以解鎖"
[Tutorial]
# Original: Welcome to the firearm handling course
"Welcome to the firearm handling course" = "歡迎來到槍械操作訓練課程"
# Original: Starting off from treating gun related injuries
"Starting off from treating gun related injuries" = "從治療槍傷開始"
# Original: Uh oh, seems like you are bleeding really bad from your left leg.
"Uh oh, seems like you are bleeding really bad from your left leg." = "哎呀，你的左腿似乎血流不止。"
[Global]
# Original: Firearm handling course
"Firearm handling course" = "槍械操作訓練課程"
# Original: How much damage guns deal to tiles, enemies and other players? Gets futrher multiplier by PVPDamageMultiplier rule when hitting another player
"How much damage guns deal to tiles, enemies and other players? Gets futrher multiplier by PVPDamageMultiplier rule when hitting another player" = "槍械對地形、敵人和其他玩家造成多少傷害？擊中另一玩家時，會額外乘以PVPDamageMultiplier規則的倍率。"
# Original: How much damage guns deal to tiles and enemies?
"How much damage guns deal to tiles and enemies?" = "槍械對地形和敵人造成多少傷害？"
