[概要]
"GUID" = "com.dragoon_103.regrowthserums"
"翻译版本" = "1.0.0"
"模组版本" = "1.7.1"
[Talker]
"I... I can see!" = "我...我能看見了！"
"Nothing left..." = "沒有剩餘的了..."
"I don't have an empty eye socket to fit this into..." = "我沒有空眼窩能容納它..."
"Nothing to regrow here... Thankfully..." = "這裡沒什麼可再生的...謝天謝地..."
"Not yet... Its too damaged..." = "還不行...它損傷太嚴重了..."
"Don't think this will work on my eyes..." = "我覺得這對我的眼睛不會起作用..."
"I think my face is just fine enough" = "我覺得我的臉已經夠好了"
[main]
# Original: Eye Growth Serum
"dragoon_103.eyegrowthserum" = "眼球生長血清"
# Original: Administer to missing eye socket to stimulate brain tissue to regrow eye tissue, WARNING: Do not use in conjunction while under effects of neuron regeneration sickness
"dragoon_103.eyegrowthserumdsc" = "對缺失的眼窩注射，刺激腦組織重新生長出眼球組織。警告：切勿在神經元再生病效果期間使用。"
# Original: Limb Re-Growth Serum
"dragoon_103.limbgrowthserum" = "肢體再生血清"
# Original: An experimental drug that rapidly converts existing tissue into new stem cell growth. Administer to a body part with a missing adjacent limb
"dragoon_103.limbgrowthserumdsc" = "一種實驗性藥物，可快速將現有組織轉化為新的幹細胞組織。對缺失相鄰肢體的部位注射。"
# Original: Disfigurement Serum
"dragoon_103.jawgrowthserum" = "畸形修復血清"
# Original: Administer to missing face parts to inject stem cell tissue to regrow jaw bone and tissue, WARNING: Extreme pain while regrowing
"dragoon_103.jawgrowthserumdsc" = "對缺失的面部部位注射幹細胞組織，以重新生長頜骨及組織。警告：再生過程中極度疼痛。"