[概要]
"GUID" = "com.rushellxyz.thighhighs"
"翻译版本" = "v1.0.0"
"模组版本" = "v3.0.0"
[Locale]
# Original: White thigh highs
"thighhighs.thighhighwhite" = "白色過膝襪"
# Original: A pair of white thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighwhitedsc" = "一雙白色過膝襪，保暖效果不錯。"
# Original: Black thigh highs
"thighhighs.thighhighblack" = "黑色過膝襪"
# Original: A pair of black thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighblackdsc" = "一雙黑色過膝襪，保暖效果不錯。"
# Original: Pink-white thigh highs
"thighhighs.thighhighpinkwhite" = "粉白過膝襪"
# Original: A pair of pink-white thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighpinkwhitedsc" = "一雙粉白過膝襪，保暖效果不錯。"
# Original: Blue-black thigh highs
"thighhighs.thighhighblueblack" = "藍黑過膝襪"
# Original: A pair of blue-black thigh highs. Provides good insulation against the cold.
"thighhighs.thighhighblueblackdsc" = "一雙藍黑過膝襪，保暖效果不錯。"
