internal static class CasualtyVitalsTr
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Sets and locks the ECG rhythm on the player body.", "【Casualty Vitals】在玩家身体上设置并锁定心电图节律"),
        ("Sets and locks the respiratory pattern on the player body.", "【Casualty Vitals】在玩家身体上设置并锁定呼吸模式"),
        ("Sets heart murmur type and intensity on the player body.", "【Casualty Vitals】在玩家身体上设置心脏杂音类型与强度"),
        ("Sets player heart rate, blood pressure (sys or sys/dia), oxygen, and respiratory rate.", "【Casualty Vitals】设置玩家心率、血压（收缩压或收缩/舒张压）、血氧与呼吸频率"),
        ("Sets systolic and diastolic blood pressure on the player body.", "【Casualty Vitals】在玩家身体上设置收缩压与舒张压"),
        ("Administers a medication dose directly to the player body.", "【Casualty Vitals】直接向玩家身体施用药剂剂量"),
        ("Sets blood potassium (K+) and calcium (Ca2+) levels.", "【Casualty Vitals】设置血钾（K+）与血钙（Ca2+）水平"),
        ("Resets all Casualty Vitals simulation, overrides, and body vitals to healthy normal.", "【Casualty Vitals】重置全部模拟、覆盖与身体生命体征为健康正常值"),
        ("Prints Casualty Vitals console commands guide.", "【Casualty Vitals】打印控制台命令指南"),
        ("Sets a Casualty Vitals body test field on the player body.", "【Casualty Vitals】在玩家身体上设置一个 Casualty Vitals 身体测试字段"),
        ("Logs a Casualty Vitals body test field from the player body.", "【Casualty Vitals】从玩家身体记录一个 Casualty Vitals 身体测试字段"),
        ("Lists Casualty Vitals body test fields.", "【Casualty Vitals】列出 Casualty Vitals 身体测试字段"),
        ("Resets Casualty Vitals debug state on the player body.", "【Casualty Vitals】重置玩家身体上的 Casualty Vitals 调试状态"),
        ("string rhythm", "字符串 节律"),
        ("string pattern", "字符串 模式"),
        ("string murmur", "字符串 杂音"),
        ("float intensity", "浮点 强度"),
        ("float hr", "浮点 心率"),
        ("string bp", "字符串 血压"),
        ("float spo2", "浮点 血氧"),
        ("float rr", "浮点 呼吸频率"),
        ("string systolic", "字符串 收缩压"),
        ("float diastolic", "浮点 舒张压"),
        ("string drug", "字符串 药物"),
        ("float ml", "浮点 毫升"),
        ("float potassium", "浮点 钾"),
        ("float calcium", "浮点 钙"),
        ("float value", "浮点 数值"),
        ("float seconds", "浮点 秒数"),
        ("string field", "字符串 字段"),
        ("Rhythm name (e.g. sinus, vfib, vtach, pea, afib, wenckebach, chb, stemi_ant)", "节律名（如 sinus、vfib、vtach、pea、afib、wenckebach、chb、stemi_ant）"),
        ("Optional duration to lock rhythm (default 300s)", "（可选）锁定节律的持续时间（默认 300 秒）"),
        ("Pattern name (e.g. eupnea, kussmaul, cheynestokes, biot, agonal, apnea)", "模式名（如 eupnea、kussmaul、cheynestokes、biot、agonal、apnea）"),
        ("Optional duration to lock pattern (default 300s)", "（可选）锁定模式的持续时间（默认 300 秒）"),
        ("Murmur type (none, systolic, diastolic, continuous)", "杂音类型（none、systolic、diastolic、continuous）"),
        ("Murmur intensity 0.0 to 1.0 (default 0.75)", "杂音强度 0.0 至 1.0（默认 0.75）"),
        ("Heart Rate (bpm)", "心率（每分钟次数）"),
        ("Blood Pressure (e.g. 120 or 120/80)", "血压（如 120 或 120/80）"),
        ("Optional Blood Oxygen % (default 99)", "（可选）血氧百分比（默认 99）"),
        ("Optional Respiratory Rate /min (default 16)", "（可选）呼吸频率 次/分（默认 16）"),
        ("Systolic BP (mmHg) or formatted 120/80", "收缩压（mmHg）或格式 120/80"),
        ("Optional Diastolic BP (mmHg)", "（可选）舒张压（mmHg）"),
        ("Drug (epinephrine, atropine, insulin, dextrose, bicarb, albuterol, calcium, calcitonin, ki, amiodarone, vasopressin)", "药物（epinephrine、atropine、insulin、dextrose、bicarb、albuterol、calcium、calcitonin、ki、amiodarone、vasopressin）"),
        ("Dose volume in mL", "剂量体积（毫升）"),
        ("Potassium mEq/L (normal 4.2, high >5.5, lethal >8.0)", "钾 mEq/L（正常 4.2、偏高 >5.5、致命 >8.0）"),
        ("Optional Calcium mg/dL (normal 9.5, high >10.5)", "（可选）钙 mg/dL（正常 9.5、偏高 >10.5）"),
        ("Casualty Vitals test field", "Casualty Vitals 测试字段"),
        ("Value to set or dose amount in mL", "要设置的值或剂量（毫升）"),
        ("Optional duration for timed signal modifiers.", "（可选）定时信号修饰的持续时间。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("No player body is available.", "没有可用的玩家身体。"),
        ("Usage: cvsetbodyfield <field> <value> [seconds]", "用法：cvsetbodyfield <字段> <数值> [秒数]"),
        ("Usage: cvgetbodyfield <field>", "用法：cvgetbodyfield <字段>"),
        ("Usage: cvrhythm <rhythm> [seconds]", "用法：cvrhythm <节律> [秒数]"),
        ("Usage: cvresp <pattern> [seconds]", "用法：cvresp <模式> [秒数]"),
        ("Usage: cvmurmur <none|systolic|diastolic|continuous> [intensity 0-1]", "用法：cvmurmur <none|systolic|diastolic|continuous> [强度 0-1]"),
        ("Usage: cvbp <systolic> [diastolic] OR cvbp <sys/dia>", "用法：cvbp <收缩压> [舒张压] 或 cvbp <收缩压/舒张压>"),
        ("Usage: cvvitals <hr> <bp (or sys/dia)> [spo2] [rr]", "用法：cvvitals <心率> <血压（或 收缩压/舒张压）> [血氧] [呼吸频率]"),
        ("Usage: cvdose <drug> <ml>", "用法：cvdose <药物> <毫升>"),
        ("Usage: cvelectrolytes <potassium> [calcium]", "用法：cvelectrolytes <钾> [钙]"),
        ("CV debug state reset.", "CV 调试状态已重置。"),
        ("CV administered Dextrose.", "CV 已施用葡萄糖片。"),
        ("CV administered Sodium Bicarbonate.", "CV 已施用碳酸氢钠。"),
        ("CV administered Albuterol inhaler.", "CV 已施用沙丁胺醇吸入剂。"),
        ("CV fully reset: Vitals healthy (75 bpm, 120/80 mmHg, 99% SpO2, NSR), simulation state cleared.", "CV 已完全重置：生命体征健康（75 bpm、120/80 mmHg、99% 血氧、正常窦性心律），模拟状态已清除。"),
        ("=== Casualty Vitals Console Commands ===", "=== Casualty Vitals 控制台命令 ==="),
        ("cvrhythm <rhythm> [sec] - Force ECG rhythm (sinus, vfib, vtach, pea, afib, wenckebach, chb, stemi_ant, etc.)", "cvrhythm <节律> [秒] - 强制心电图节律（sinus、vfib、vtach、pea、afib、wenckebach、chb、stemi_ant 等）"),
        ("cvresp <pattern> [sec]  - Force breathing pattern (eupnea, kussmaul, cheynestokes, biot, agonal, apnea)", "cvresp <模式> [秒] - 强制呼吸模式（eupnea、kussmaul、cheynestokes、biot、agonal、apnea）"),
        ("cvmurmur <type> [0-1]   - Set murmur (none, systolic, diastolic, continuous)", "cvmurmur <类型> [0-1] - 设置杂音（none、systolic、diastolic、continuous）"),
        ("cvvitals <hr> <bp> [spo2] [rr] - Set core vitals numbers", "cvvitals <心率> <血压> [血氧] [呼吸频率] - 设置核心生命体征数值"),
        ("cvdose <drug> <ml>      - Administer drug (epi, atropine, insulin, bicarb, albuterol, calcium, amiodarone, vasopressin, ki)", "cvdose <药物> <毫升> - 施用药物（epi、atropine、insulin、bicarb、albuterol、calcium、amiodarone、vasopressin、ki）"),
        ("cvelectrolytes <k> [ca] - Set serum potassium & calcium", "cvelectrolytes <钾> [钙] - 设置血钾与血钙"),
        ("cvreset                 - Restore full normal healthy vitals", "cvreset - 恢复全部正常健康生命体征"),
        ("cvsetbodyfield <field> <value> - Low level internal modifier", "cvsetbodyfield <字段> <数值> - 低级内部修饰"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("CV {0} = {1}", "CV {0} = {1}"),
        ("CV applied {0} mL via {1}.", "CV 已通过 {1} 施用 {0} 毫升。"),
        ("CV {0} = {1} for {2}s", "CV {0} = {1} 持续 {2} 秒"),
        ("CV settable fields: {0}. Read-only: medicationOverdoseLevel.", "CV 可设置字段：{0}。只读：medicationOverdoseLevel。"),
        ("CV transientArtifact = {0} for {1}s", "CV transientArtifact = {0} 持续 {1} 秒"),
        ("CV ECG Rhythm locked to {0} for {1}s", "CV 心电图节律已锁定为 {0}，持续 {1} 秒"),
        ("CV Respiratory Pattern locked to {0} for {1}s", "CV 呼吸模式已锁定为 {0}，持续 {1} 秒"),
        ("CV Heart Murmur set to {0} (Intensity: {1})", "CV 心脏杂音已设置为 {0}（强度：{1}）"),
        ("CV Blood Pressure set: {0}/{1} mmHg", "CV 血压已设置：{0}/{1} mmHg"),
        ("CV Systolic Blood Pressure set: {0} mmHg (auto diastolic)", "CV 收缩压已设置：{0} mmHg（舒张压自动）"),
        ("CV Vitals set: HR={0} bpm, BP={1} mmHg, SpO2={2}%, RR={3}/min", "CV 生命体征已设置：心率={0} bpm、血压={1} mmHg、血氧={2}%、呼吸={3}/min"),
        ("CV administered Epinephrine auto-injector dose ({0} mL).", "CV 已施用肾上腺素自动注射器剂量（{0} 毫升）。"),
        ("CV administered Atropine/Pralidoxime auto-injector dose ({0} mL).", "CV 已施用阿托品/氯解磷定自动注射器剂量（{0} 毫升）。"),
        ("CV administered {0} mL Insulin.", "CV 已施用胰岛素 {0} 毫升。"),
        ("CV injected {0} mL Calcium Gluconate.", "CV 已注射葡萄糖酸钙 {0} 毫升。"),
        ("CV injected {0} mL Calcitonin.", "CV 已注射降钙素 {0} 毫升。"),
        ("CV injected {0} mL Potassium Iodide.", "CV 已注射碘化钾 {0} 毫升。"),
        ("CV injected {0} mL Amiodarone.", "CV 已注射胺碘酮 {0} 毫升。"),
        ("CV injected {0} mL Vasopressin.", "CV 已注射血管加压素 {0} 毫升。"),
        ("CV Electrolytes set: K+ = {0} mEq/L, Ca2+ = {1} mg/dL (locked for {2}s)", "CV 电解质已设置：K+ = {0} mEq/L，Ca2+ = {1} mg/dL（锁定 {2} 秒）"),
        ("Could not parse \"{0}\" as a float.", "无法将「{0}」解析为浮点数。"),
        ("Unknown CV body field \"{0}\". Use cvlistbodyfields.", "未知的 CV 身体字段「{0}」。使用 cvlistbodyfields。"),
        ("Unknown or write-only CV body field \"{0}\". Use cvlistbodyfields.", "未知或只写入的 CV 身体字段「{0}」。使用 cvlistbodyfields。"),
        ("Unknown rhythm \"{0}\". Use cvhelp or tab-completion.", "未知节律「{0}」。使用 cvhelp 或按 Tab 补全。"),
        ("Unknown respiratory pattern \"{0}\".", "未知呼吸模式「{0}」。"),
        ("Unknown murmur type \"{0}\". Options: none, systolic, diastolic, continuous.", "未知杂音类型「{0}」。选项：none、systolic、diastolic、continuous。"),
        ("Unknown drug \"{0}\". Use cvhelp.", "未知药物「{0}」。使用 cvhelp。"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Main Menu Preview Heartbeat", "主菜单预览心跳声"),
        ("Enable Debug Hotkeys", "启用调试热键"),
        ("Enable Manual Pulse Ecg", "启用手动脉搏心电图"),
        ("Hold Seconds", "保持秒数"),
        ("Display Scale", "显示比例"),
        ("Head Offset X", "头部偏移 X"),
        ("Head Offset Y", "头部偏移 Y"),
        ("Left Hand Offset X", "左手偏移 X"),
        ("Left Hand Offset Y", "左手偏移 Y"),
        ("Right Hand Offset X", "右手偏移 X"),
        ("Right Hand Offset Y", "右手偏移 Y"),
        ("Loot Chance Multiplier", "战利品几率倍率"),
        ("Dynamic Hemodynamics (Bleeding)", "动态血流动力学（出血）"),
        ("If true, the main-menu monitor preview plays a quiet heartbeat synchronized to its displayed rhythm. Unconsciousness, VFib, asystole, and signal-loss previews remain silent.", "启用后，主菜单监护仪预览播放与其显示心律同步的轻柔心跳声。昏迷、室颤、心搏停止和信号丢失预览保持静音。"),
        ("If true, F7/F8/F9/F10 apply test physiology changes to the current Body.", "启用后，F7【降低血容量】、F8【缺氧】、F9【心律失常】、F10【内出血】对当前身体施加测试性生理变化。"),
        ("If true, holding an empty cursor on the head, wrist, or hand in the health panel reveals a faint manual ECG after the hold delay.", "启用后，在生命面板中空光标停留在头部、手腕或手上达到保持延迟后，会显示微弱的徒手心电图。"),
        ("Seconds to hold an empty cursor on the head, wrist, or hand before the manual ECG appears.", "在徒手心电图出现前，空光标需要停留在头部、手腕或手上的秒数。"),
        ("Manual pulse ECG UI scale. 0 auto-scales from 1080p: 1080p=1, 1440p=1.33, 4K=2. Set a positive value to override.", "手动脉搏心电图 UI 缩放。0 表示从 1080p 自动缩放 : 1080p=1，1440p=1.33，4K=2。设置正值可覆盖。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the head. Auto-scales by resolution. Presets: next-to-body +/-150 at 1080p, +/-200 at 1440p, +/-300 at 4K.", "检查头部时手动脉搏心电图的水平 1080p 参考偏移。按分辨率自动缩放。预设 : 靠近身体 ±150（1080p）、±200（1440p）、±300（4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the head. Auto-scales by resolution. Presets: under-limb -120/-160/-240, above-limb 70/95/140 for 1080p/1440p/4K.", "检查头部时手动脉搏心电图的垂直 1080p 参考偏移。按分辨率自动缩放。预设 : 肢体下方 -120/-160/-240，肢体上方 70/95/140（1080p/1440p/4K）。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the left hand, wrist, or forearm. Auto-scales by resolution. Presets: outside-left -150/-200/-300, near-body 120/160/240 for 1080p/1440p/4K.", "检查左手、手腕或前臂时手动脉搏心电图的水平 1080p 参考偏移。按分辨率自动缩放。预设 : 左侧外部 -150/-200/-300，靠近身体 120/160/240（1080p/1440p/4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the left hand, wrist, or forearm. Auto-scales by resolution. Presets: under-arm -200/-267/-400, above-arm 70/95/140 for 1080p/1440p/4K.", "检查左手、手腕或前臂时手动脉搏心电图的垂直 1080p 参考偏移。按分辨率自动缩放。预设 : 手臂下方 -200/-267/-400，手臂上方 70/95/140（1080p/1440p/4K）。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the right hand, wrist, or forearm. Auto-scales by resolution. Presets: outside-right 150/200/300, near-body -120/-160/-240 for 1080p/1440p/4K.", "检查右手、手腕或前臂时手动脉搏心电图的水平 1080p 参考偏移。按分辨率自动缩放。预设 : 右侧外部 150/200/300，靠近身体 -120/-160/-240（1080p/1440p/4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the right hand, wrist, or forearm. Auto-scales by resolution. Presets: under-arm -200/-267/-400, above-arm 70/95/140 for 1080p/1440p/4K. The probe nudges away if it would cover the checked limb.", "检查右手、手腕或前臂时手动脉搏心电图的垂直 1080p 参考偏移。按分辨率自动缩放。预设 : 手臂下方 -200/-267/-400，手臂上方 70/95/140（1080p/1440p/4K）。若探测框会遮挡被检查的肢体，它会自动让开。"),
        ("Multiplier for manual defibrillator entries in generic loot and trader pools. 0 removes them from those pools, 1 is vanilla, 2 doubles entries.", "手动除颤器在通用战利品和商人池中的几率倍率。0 从这些池中移除，1 为原版，2 使条目翻倍。"),
        ("Scales wound bleeding dynamically with arterial blood pressure, AutoPump chest compressions, volume, and vascular caliber.", "按动脉血压、自动泵胸外按压、血容量与血管口径动态缩放伤口出血速率。"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("Normal sinus rhythm", "正常窦性心律"),
        ("CASUALTY VITALS  /  CONSCIOUSNESS ECG", "伤员生命体征 / 昏迷心电图"),
        ("CASUALTY VITALS  /  WOUNDVIEW  /  ", "伤员生命体征 / 医疗视图 / "),
        ("SPO2", "血氧"),
        ("O2", "血氧"),
        ("RESP", "呼吸"),
        ("RSP", "呼吸"),
        ("RR", "呼吸"),
        ("ABP", "血压"),
        ("BP", "血压"),
        ("ETCO2", "二氧化碳"),
        ("CO2", "二氧化碳"),
        ("HEART", "心率"),
        ("HR", "心率"),
        ("Electrocardiogram", "心电图"),
        ("Live electrical cardiac activity. Use the channel labels below to view other monitor traces.", "实时心电活动。使用下方的通道标签查看其他监护波形。"),
    };
    public static readonly (string En, string Zh)[] PresentValues =
    {
        ("Native", "原生"),
        ("Clinical", "临床"),
        ("LegacyClinical", "经典临床"),
        ("LegacyClinicalAlt", "经典临床（细波形）"),
    };
    public static readonly (string En, string Zh)[] LocaleOverrides =
    {
        ("config.HealthPanelButtonStyle.desc", "通道按钮显示样式（文本、填充、隐藏）。"),
        ("config.HealthPanelPresentation.desc", "显示风格（原生、临床、经典临床、经典临床（细波形））。"),
        ("menu.value.legacyclinicalalt", "经典临床（细波形）"),
        ("config.ChannelControlMode.desc", "通过悬停或点击切换通道。"),
    };
}
