internal static class CasualtyVitalsTrTw
{
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Sets and locks the ECG rhythm on the player body.", "【Casualty Vitals】在玩家身體上設置並鎖定心電圖節律"),
        ("Sets and locks the respiratory pattern on the player body.", "【Casualty Vitals】在玩家身體上設置並鎖定呼吸模式"),
        ("Sets heart murmur type and intensity on the player body.", "【Casualty Vitals】在玩家身體上設置心臟雜音類型與強度"),
        ("Sets player heart rate, blood pressure (sys or sys/dia), oxygen, and respiratory rate.", "【Casualty Vitals】設置玩家心率、血壓（收縮壓或收縮/舒張壓）、血氧與呼吸頻率"),
        ("Sets systolic and diastolic blood pressure on the player body.", "【Casualty Vitals】在玩家身體上設置收縮壓與舒張壓"),
        ("Administers a medication dose directly to the player body.", "【Casualty Vitals】直接向玩家身體施用藥劑劑量"),
        ("Sets blood potassium (K+) and calcium (Ca2+) levels.", "【Casualty Vitals】設置血鉀（K+）與血鈣（Ca2+）水平"),
        ("Resets all Casualty Vitals simulation, overrides, and body vitals to healthy normal.", "【Casualty Vitals】重置全部模擬、覆蓋與身體生命體徵為健康正常值"),
        ("Prints Casualty Vitals console commands guide.", "【Casualty Vitals】打印控制檯命令指南"),
        ("Sets a Casualty Vitals body test field on the player body.", "【Casualty Vitals】在玩家身體上設置一個 Casualty Vitals 身體測試字段"),
        ("Logs a Casualty Vitals body test field from the player body.", "【Casualty Vitals】從玩家身體記錄一個 Casualty Vitals 身體測試字段"),
        ("Lists Casualty Vitals body test fields.", "【Casualty Vitals】列出 Casualty Vitals 身體測試字段"),
        ("Resets Casualty Vitals debug state on the player body.", "【Casualty Vitals】重置玩家身體上的 Casualty Vitals 調試狀態"),
        ("string rhythm", "字符串 節律"),
        ("string pattern", "字符串 模式"),
        ("string murmur", "字符串 雜音"),
        ("float intensity", "浮點 強度"),
        ("float hr", "浮點 心率"),
        ("string bp", "字符串 血壓"),
        ("float spo2", "浮點 血氧"),
        ("float rr", "浮點 呼吸頻率"),
        ("string systolic", "字符串 收縮壓"),
        ("float diastolic", "浮點 舒張壓"),
        ("string drug", "字符串 藥物"),
        ("float ml", "浮點 毫升"),
        ("float potassium", "浮點 鉀"),
        ("float calcium", "浮點 鈣"),
        ("float value", "浮點 數值"),
        ("float seconds", "浮點 秒數"),
        ("string field", "字符串 字段"),
        ("Rhythm name (e.g. sinus, vfib, vtach, pea, afib, wenckebach, chb, stemi_ant)", "節律名（如 sinus、vfib、vtach、pea、afib、wenckebach、chb、stemi_ant）"),
        ("Optional duration to lock rhythm (default 300s)", "（可選）鎖定節律的持續時間（默認 300 秒）"),
        ("Pattern name (e.g. eupnea, kussmaul, cheynestokes, biot, agonal, apnea)", "模式名（如 eupnea、kussmaul、cheynestokes、biot、agonal、apnea）"),
        ("Optional duration to lock pattern (default 300s)", "（可選）鎖定模式的持續時間（默認 300 秒）"),
        ("Murmur type (none, systolic, diastolic, continuous)", "雜音類型（none、systolic、diastolic、continuous）"),
        ("Murmur intensity 0.0 to 1.0 (default 0.75)", "雜音強度 0.0 至 1.0（默認 0.75）"),
        ("Heart Rate (bpm)", "心率（每分鐘次數）"),
        ("Blood Pressure (e.g. 120 or 120/80)", "血壓（如 120 或 120/80）"),
        ("Optional Blood Oxygen % (default 99)", "（可選）血氧百分比（默認 99）"),
        ("Optional Respiratory Rate /min (default 16)", "（可選）呼吸頻率 次/分（默認 16）"),
        ("Systolic BP (mmHg) or formatted 120/80", "收縮壓（mmHg）或格式 120/80"),
        ("Optional Diastolic BP (mmHg)", "（可選）舒張壓（mmHg）"),
        ("Drug (epinephrine, atropine, insulin, dextrose, bicarb, albuterol, calcium, calcitonin, ki, amiodarone, vasopressin)", "藥物（epinephrine、atropine、insulin、dextrose、bicarb、albuterol、calcium、calcitonin、ki、amiodarone、vasopressin）"),
        ("Dose volume in mL", "劑量體積（毫升）"),
        ("Potassium mEq/L (normal 4.2, high >5.5, lethal >8.0)", "鉀 mEq/L（正常 4.2、偏高 >5.5、致命 >8.0）"),
        ("Optional Calcium mg/dL (normal 9.5, high >10.5)", "（可選）鈣 mg/dL（正常 9.5、偏高 >10.5）"),
        ("Casualty Vitals test field", "Casualty Vitals 測試字段"),
        ("Value to set or dose amount in mL", "要設置的值或劑量（毫升）"),
        ("Optional duration for timed signal modifiers.", "（可選）定時信號修飾的持續時間。"),
    };
    public static readonly (string En, string Zh)[] Logs =
    {
        ("No player body is available.", "沒有可用的玩家身體。"),
        ("Usage: cvsetbodyfield <field> <value> [seconds]", "用法：cvsetbodyfield <字段> <數值> [秒數]"),
        ("Usage: cvgetbodyfield <field>", "用法：cvgetbodyfield <字段>"),
        ("Usage: cvrhythm <rhythm> [seconds]", "用法：cvrhythm <節律> [秒數]"),
        ("Usage: cvresp <pattern> [seconds]", "用法：cvresp <模式> [秒數]"),
        ("Usage: cvmurmur <none|systolic|diastolic|continuous> [intensity 0-1]", "用法：cvmurmur <none|systolic|diastolic|continuous> [強度 0-1]"),
        ("Usage: cvbp <systolic> [diastolic] OR cvbp <sys/dia>", "用法：cvbp <收縮壓> [舒張壓] 或 cvbp <收縮壓/舒張壓>"),
        ("Usage: cvvitals <hr> <bp (or sys/dia)> [spo2] [rr]", "用法：cvvitals <心率> <血壓（或 收縮壓/舒張壓）> [血氧] [呼吸頻率]"),
        ("Usage: cvdose <drug> <ml>", "用法：cvdose <藥物> <毫升>"),
        ("Usage: cvelectrolytes <potassium> [calcium]", "用法：cvelectrolytes <鉀> [鈣]"),
        ("CV debug state reset.", "CV 調試狀態已重置。"),
        ("CV administered Dextrose.", "CV 已施用葡萄糖片。"),
        ("CV administered Sodium Bicarbonate.", "CV 已施用碳酸氫鈉。"),
        ("CV administered Albuterol inhaler.", "CV 已施用沙丁胺醇吸入劑。"),
        ("CV fully reset: Vitals healthy (75 bpm, 120/80 mmHg, 99% SpO2, NSR), simulation state cleared.", "CV 已完全重置：生命體徵健康（75 bpm、120/80 mmHg、99% 血氧、正常竇性心律），模擬狀態已清除。"),
        ("=== Casualty Vitals Console Commands ===", "=== Casualty Vitals 控制檯命令 ==="),
        ("cvrhythm <rhythm> [sec] - Force ECG rhythm (sinus, vfib, vtach, pea, afib, wenckebach, chb, stemi_ant, etc.)", "cvrhythm <節律> [秒] - 強制心電圖節律（sinus、vfib、vtach、pea、afib、wenckebach、chb、stemi_ant 等）"),
        ("cvresp <pattern> [sec]  - Force breathing pattern (eupnea, kussmaul, cheynestokes, biot, agonal, apnea)", "cvresp <模式> [秒] - 強制呼吸模式（eupnea、kussmaul、cheynestokes、biot、agonal、apnea）"),
        ("cvmurmur <type> [0-1]   - Set murmur (none, systolic, diastolic, continuous)", "cvmurmur <類型> [0-1] - 設置雜音（none、systolic、diastolic、continuous）"),
        ("cvvitals <hr> <bp> [spo2] [rr] - Set core vitals numbers", "cvvitals <心率> <血壓> [血氧] [呼吸頻率] - 設置核心生命體徵數值"),
        ("cvdose <drug> <ml>      - Administer drug (epi, atropine, insulin, bicarb, albuterol, calcium, amiodarone, vasopressin, ki)", "cvdose <藥物> <毫升> - 施用藥物（epi、atropine、insulin、bicarb、albuterol、calcium、amiodarone、vasopressin、ki）"),
        ("cvelectrolytes <k> [ca] - Set serum potassium & calcium", "cvelectrolytes <鉀> [鈣] - 設置血鉀與血鈣"),
        ("cvreset                 - Restore full normal healthy vitals", "cvreset - 恢復全部正常健康生命體徵"),
        ("cvsetbodyfield <field> <value> - Low level internal modifier", "cvsetbodyfield <字段> <數值> - 低級內部修飾"),
    };
    public static readonly (string En, string Zh)[] LogFormats =
    {
        ("CV {0} = {1}", "CV {0} = {1}"),
        ("CV applied {0} mL via {1}.", "CV 已通過 {1} 施用 {0} 毫升。"),
        ("CV {0} = {1} for {2}s", "CV {0} = {1} 持續 {2} 秒"),
        ("CV settable fields: {0}. Read-only: medicationOverdoseLevel.", "CV 可設置字段：{0}。只讀：medicationOverdoseLevel。"),
        ("CV transientArtifact = {0} for {1}s", "CV transientArtifact = {0} 持續 {1} 秒"),
        ("CV ECG Rhythm locked to {0} for {1}s", "CV 心電圖節律已鎖定為 {0}，持續 {1} 秒"),
        ("CV Respiratory Pattern locked to {0} for {1}s", "CV 呼吸模式已鎖定為 {0}，持續 {1} 秒"),
        ("CV Heart Murmur set to {0} (Intensity: {1})", "CV 心臟雜音已設置為 {0}（強度：{1}）"),
        ("CV Blood Pressure set: {0}/{1} mmHg", "CV 血壓已設置：{0}/{1} mmHg"),
        ("CV Systolic Blood Pressure set: {0} mmHg (auto diastolic)", "CV 收縮壓已設置：{0} mmHg（舒張壓自動）"),
        ("CV Vitals set: HR={0} bpm, BP={1} mmHg, SpO2={2}%, RR={3}/min", "CV 生命體徵已設置：心率={0} bpm、血壓={1} mmHg、血氧={2}%、呼吸={3}/min"),
        ("CV administered Epinephrine auto-injector dose ({0} mL).", "CV 已施用腎上腺素自動注射器劑量（{0} 毫升）。"),
        ("CV administered Atropine/Pralidoxime auto-injector dose ({0} mL).", "CV 已施用阿托品/氯解磷定自動注射器劑量（{0} 毫升）。"),
        ("CV administered {0} mL Insulin.", "CV 已施用胰島素 {0} 毫升。"),
        ("CV injected {0} mL Calcium Gluconate.", "CV 已注射葡萄糖酸鈣 {0} 毫升。"),
        ("CV injected {0} mL Calcitonin.", "CV 已注射降鈣素 {0} 毫升。"),
        ("CV injected {0} mL Potassium Iodide.", "CV 已注射碘化鉀 {0} 毫升。"),
        ("CV injected {0} mL Amiodarone.", "CV 已注射胺碘酮 {0} 毫升。"),
        ("CV injected {0} mL Vasopressin.", "CV 已注射血管加壓素 {0} 毫升。"),
        ("CV Electrolytes set: K+ = {0} mEq/L, Ca2+ = {1} mg/dL (locked for {2}s)", "CV 電解質已設置：K+ = {0} mEq/L，Ca2+ = {1} mg/dL（鎖定 {2} 秒）"),
        ("Could not parse \"{0}\" as a float.", "無法將「{0}」解析為浮點數。"),
        ("Unknown CV body field \"{0}\". Use cvlistbodyfields.", "未知的 CV 身體字段「{0}」。使用 cvlistbodyfields。"),
        ("Unknown or write-only CV body field \"{0}\". Use cvlistbodyfields.", "未知或只寫入的 CV 身體字段「{0}」。使用 cvlistbodyfields。"),
        ("Unknown rhythm \"{0}\". Use cvhelp or tab-completion.", "未知節律「{0}」。使用 cvhelp 或按 Tab 補全。"),
        ("Unknown respiratory pattern \"{0}\".", "未知呼吸模式「{0}」。"),
        ("Unknown murmur type \"{0}\". Options: none, systolic, diastolic, continuous.", "未知雜音類型「{0}」。選項：none、systolic、diastolic、continuous。"),
        ("Unknown drug \"{0}\". Use cvhelp.", "未知藥物「{0}」。使用 cvhelp。"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("Main Menu Preview Heartbeat", "主菜單預覽心跳聲"),
        ("Enable Debug Hotkeys", "啟用調試熱鍵"),
        ("Enable Manual Pulse Ecg", "啟用手動脈搏心電圖"),
        ("Hold Seconds", "保持秒數"),
        ("Display Scale", "顯示比例"),
        ("Head Offset X", "頭部偏移 X"),
        ("Head Offset Y", "頭部偏移 Y"),
        ("Left Hand Offset X", "左手偏移 X"),
        ("Left Hand Offset Y", "左手偏移 Y"),
        ("Right Hand Offset X", "右手偏移 X"),
        ("Right Hand Offset Y", "右手偏移 Y"),
        ("Loot Chance Multiplier", "戰利品幾率倍率"),
        ("Dynamic Hemodynamics (Bleeding)", "動態血流動力學（出血）"),
        ("If true, the main-menu monitor preview plays a quiet heartbeat synchronized to its displayed rhythm. Unconsciousness, VFib, asystole, and signal-loss previews remain silent.", "啟用後，主菜單監護儀預覽播放與其顯示心律同步的輕柔心跳聲。昏迷、室顫、心搏停止和信號丟失預覽保持靜音。"),
        ("If true, F7/F8/F9/F10 apply test physiology changes to the current Body.", "啟用後，F7【降低血容量】、F8【缺氧】、F9【心律失常】、F10【內出血】對當前身體施加測試性生理變化。"),
        ("If true, holding an empty cursor on the head, wrist, or hand in the health panel reveals a faint manual ECG after the hold delay.", "啟用後，在生命面板中空光標停留在頭部、手腕或手上達到保持延遲後，會顯示微弱的徒手心電圖。"),
        ("Seconds to hold an empty cursor on the head, wrist, or hand before the manual ECG appears.", "在徒手心電圖出現前，空光標需要停留在頭部、手腕或手上的秒數。"),
        ("Manual pulse ECG UI scale. 0 auto-scales from 1080p: 1080p=1, 1440p=1.33, 4K=2. Set a positive value to override.", "手動脈搏心電圖 UI 縮放。0 表示從 1080p 自動縮放 : 1080p=1，1440p=1.33，4K=2。設置正值可覆蓋。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the head. Auto-scales by resolution. Presets: next-to-body +/-150 at 1080p, +/-200 at 1440p, +/-300 at 4K.", "檢查頭部時手動脈搏心電圖的水平 1080p 參考偏移。按分辨率自動縮放。預設 : 靠近身體 ±150（1080p）、±200（1440p）、±300（4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the head. Auto-scales by resolution. Presets: under-limb -120/-160/-240, above-limb 70/95/140 for 1080p/1440p/4K.", "檢查頭部時手動脈搏心電圖的垂直 1080p 參考偏移。按分辨率自動縮放。預設 : 肢體下方 -120/-160/-240，肢體上方 70/95/140（1080p/1440p/4K）。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the left hand, wrist, or forearm. Auto-scales by resolution. Presets: outside-left -150/-200/-300, near-body 120/160/240 for 1080p/1440p/4K.", "檢查左手、手腕或前臂時手動脈搏心電圖的水平 1080p 參考偏移。按分辨率自動縮放。預設 : 左側外部 -150/-200/-300，靠近身體 120/160/240（1080p/1440p/4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the left hand, wrist, or forearm. Auto-scales by resolution. Presets: under-arm -200/-267/-400, above-arm 70/95/140 for 1080p/1440p/4K.", "檢查左手、手腕或前臂時手動脈搏心電圖的垂直 1080p 參考偏移。按分辨率自動縮放。預設 : 手臂下方 -200/-267/-400，手臂上方 70/95/140（1080p/1440p/4K）。"),
        ("Horizontal 1080p-reference offset for the manual pulse ECG when checking the right hand, wrist, or forearm. Auto-scales by resolution. Presets: outside-right 150/200/300, near-body -120/-160/-240 for 1080p/1440p/4K.", "檢查右手、手腕或前臂時手動脈搏心電圖的水平 1080p 參考偏移。按分辨率自動縮放。預設 : 右側外部 150/200/300，靠近身體 -120/-160/-240（1080p/1440p/4K）。"),
        ("Vertical 1080p-reference offset for the manual pulse ECG when checking the right hand, wrist, or forearm. Auto-scales by resolution. Presets: under-arm -200/-267/-400, above-arm 70/95/140 for 1080p/1440p/4K. The probe nudges away if it would cover the checked limb.", "檢查右手、手腕或前臂時手動脈搏心電圖的垂直 1080p 參考偏移。按分辨率自動縮放。預設 : 手臂下方 -200/-267/-400，手臂上方 70/95/140（1080p/1440p/4K）。若探測框會遮擋被檢查的肢體，它會自動讓開。"),
        ("Multiplier for manual defibrillator entries in generic loot and trader pools. 0 removes them from those pools, 1 is vanilla, 2 doubles entries.", "手動除顫器在通用戰利品和商人池中的幾率倍率。0 從這些池中移除，1 為原版，2 使條目翻倍。"),
        ("Scales wound bleeding dynamically with arterial blood pressure, AutoPump chest compressions, volume, and vascular caliber.", "按動脈血壓、自動泵胸外按壓、血容量與血管口徑動態縮放傷口出血速率。"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("Normal sinus rhythm", "正常竇性心律"),
        ("CASUALTY VITALS  /  CONSCIOUSNESS ECG", "傷員生命體徵 / 昏迷心電圖"),
        ("CASUALTY VITALS  /  WOUNDVIEW  /  ", "傷員生命體徵 / 醫療視圖 / "),
        ("SPO2", "血氧"),
        ("O2", "血氧"),
        ("RESP", "呼吸"),
        ("RSP", "呼吸"),
        ("RR", "呼吸"),
        ("ABP", "血壓"),
        ("BP", "血壓"),
        ("ETCO2", "二氧化碳"),
        ("CO2", "二氧化碳"),
        ("HEART", "心率"),
        ("HR", "心率"),
        ("Electrocardiogram", "心電圖"),
        ("Live electrical cardiac activity. Use the channel labels below to view other monitor traces.", "實時心電活動。使用下方的通道標籤查看其他監護波形。"),
    };
    public static readonly (string En, string Zh)[] PresentValues =
    {
        ("Native", "原生"),
        ("Clinical", "臨床"),
        ("LegacyClinical", "經典臨床"),
        ("LegacyClinicalAlt", "經典臨床（細波形）"),
    };
    public static readonly (string En, string Zh)[] LocaleOverrides =
    {
        ("config.HealthPanelButtonStyle.desc", "通道按鈕顯示樣式（文本、填充、隱藏）。"),
        ("config.HealthPanelPresentation.desc", "顯示風格（原生、臨床、經典臨床、經典臨床（細波形））。"),
        ("menu.value.legacyclinicalalt", "經典臨床（細波形）"),
        ("config.ChannelControlMode.desc", "通過懸停或點擊切換通道。"),
    };
}
