internal static class ProstheticsTrTw
{
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Limb is missing", "肢體缺失"),
        ("This limb is already a prosthetic", "該肢體已經是義肢"),
        ("Torso augment slot opened", "軀幹強化槽位已打開"),
        ("Apply directly to an upper arm, thigh, or torso", "直接應用於上臂、大腿或軀幹"),
        ("Limb already has an augment slot", "該肢體已擁有增強插槽"),
        ("Augment slot implanted", "增強插槽已成功植入"),
        ("Ballistic: no charge — recharge with the RTG", "BFF力場：電量不足——請使用同位素發電機充電"),
        ("Ballistic: depleted", "BFF力場：能量耗盡"),
        ("Regeneration: no charge — recharge with the RTG", "MYX再生艙：電量不足——請使用同位素發電機充電"),
        ("Regeneration: depleted", "MYX再生艙：能量耗盡"),
        ("RTG: nothing to charge", "同位素發電機：無需充電"),
        ("RTG: everything charged", "同位素發電機：全部已充滿"),
        ("Treadmill battery full", "跑步機增強件電池已充滿"),
        ("Leg augment can't be installed on an arm", "腿部增強件無法安裝在手臂上"),
        ("Arm augment can't be installed on a leg", "手臂增強件無法安裝在腿部上"),
        ("Already installed on this limb", "此增強件已安裝在該肢體上"),
        ("Torso augments go on the torso", "軀幹增強件需安裝在軀幹上"),
        ("Torso is full (3 augment slots)", "軀幹已滿（3個增強插槽）"),
        ("No torso augment slot", "沒有軀幹增強插槽"),
        ("Not a torso augment", "不是軀幹增強件"),
        ("Already installed", "已安裝"),
        ("No open torso slot", "沒有空的軀幹插槽"),
        ("Deactivate Sandivistian first", "請先停用斯安威斯坦"),
        ("Balance Neuromod is cooling down", "平衡神經模組正在冷卻中"),
        ("Sandivistian is cooling down", "斯安威斯坦正在冷卻中"),
        ("Lockin Neuromod is cooling down", "鎖定神經模組正在冷卻中"),
        ("Battery installed", "電池已安裝"),
        ("Steve Jobs says NO to slow mo in multiplayer", "喬布斯拒絕在多人聯機模式中加入慢動作。\n【？意思是 多人聯機不支持！】"),
        ("Can't remove another player's prosthetic", "無法移除其他玩家的義肢"),
        ("Battery removed", "電池已移除"),
        ("Prosthetic eye removed", "義眼已移除"),
        ("Can't modify another player's augment", "無法修改其他玩家的增強件"),
        ("Bio augment slot already occupied", "生物增強插槽已被佔用"),
        ("Install an augment first", "請先安裝增強件"),
        ("Augment already has a battery", "該增強件已裝有電池"),
        ("Can't modify another player's prosthetic", "無法修改其他玩家的義肢"),
        ("Arm mod slot already occupied", "手臂插件插槽已被佔用"),
        ("Leg mod slot already occupied", "腿部插件插槽已被佔用"),
        ("Grappling hook attached", "抓鉤已安裝"),
        ("Grappling hook attached  - insert a battery to power", "抓鉤已安裝 - 請插入電池以供電"),
        ("Prosthetic removed", "義肢已移除"),
        ("Too damaged to safely remove  - fix it first", "損壞嚴重無法安全拆除 - 請先進行修復"),
        ("Chain incomplete  - disassembled into a titanium sheet", "裝配鏈不完整 - 已拆解為一張鈦板"),
        ("Prosthetic was damaged  - broke apart", "義肢受損 - 已徹底損壞解體"),
        ("Wooden prosthetic  - biochem heals it, a wrench takes it off", "木製義肢 - 生化流體可使其修復，使用扳手可以將其卸下"),
        ("Use a wrench to take off a prosthetic", "使用扳手可以卸下義肢"),
        ("Steady Hand attached", "穩手插件已安裝"),
        ("Steady Hand attached  - insert a battery to power", "穩手插件已安裝 - 請插入電池以供電"),
        ("Powergrip attached", "強力握持插件已安裝"),
        ("Powergrip attached  - insert a battery to power", "強力握持插件已安裝 - 請插入電池以供電"),
        ("Multi-Hacking attached", "多功能黑客插件已安裝"),
        ("Multi-Hacking attached  - insert a battery to power", "多功能黑客插件已安裝 - 請插入電池以供電"),
        ("Powersteps attached", "動力步伐增強件已安裝"),
        ("Powersteps attached  - insert a battery to power", "動力步伐增強件已安裝 - 請插入電池以供電"),
        ("Treadmill attached", "跑步機增強件已安裝"),
        ("Treadmill attached  - insert a battery to charge", "跑步機增強件已安裝 - 請插入電池以充電"),
        ("Battery too low", "電池電量過低"),
        ("Nothing in hand to scan", "手中沒有可掃描的物品"),
        ("Both eyes removed", "雙眼已移除"),
        ("Eye removed", "眼球已移除"),
        ("Drag onto a prosthetic arm to install", "拖動到義肢手臂上以安裝"),
        ("Drag onto a prosthetic leg to install", "拖動到義肢腿上以安裝"),
        ("Apply on the head", "在頭部使用"),
        ("Not missing an eye", "並未缺失眼睛"),
        ("No empty eye sockets left", "已無空餘的眼眶"),
        ("Not missing a jaw", "未缺失下頜"),
        ("Already wearing a copper jaw", "已裝備銅下頜"),
        ("This prosthetic is for arms", "此義肢適用於手臂"),
        ("This prosthetic is for legs", "此義肢適用於腿部"),
        ("Limb is not missing", "肢體並未缺失"),
        ("Can't attach a prosthetic to another prosthetic", "無法將義肢安裝在另一個義肢上"),
        ("This prosthetic can't use tools", "此義肢無法使用工具"),
        ("You cant hold this with a hook, you can only hold containers on a hook", "無法用鉤子提拿此物品，鉤子只能用於懸掛容器。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("{0} attached", "{0}已安裝"),
        ("{0} attached  - insert a battery to power", "{0}已安裝——請插入電池以供電"),
        ("Not enough energy to hack {0}", "能量不足，無法入侵{0}"),
        ("Can't wear {0} with two prosthetic {1}.", "無法在安裝了兩隻義肢{1}的情況下穿戴{0}。"),
        ("Recipe scanned: {0}", "已掃描配方：{0}"),
        ("Identified: {0} (no recipe in the database)", "已識別：{0}（數據庫中無配方）"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("That tastes like poo", "嚐起來像坨屎"),
        ("my ...eeth hurt!", "我...牙..疼！"),
        ("WHAT ARE YOU?", "你究竟是什麼東西？"),
        ("How awfull it must be for you, You know what? I can spare one item for you, pick any", "你一定很難受吧。這樣吧，我可以免費送你一件東西，挑一個吧"),
        ("I'm sorry you have to go further like this, I'll give you a discount though", "很抱歉你得繼續這樣走下去，不過我會給你打個折"),
        ("You scared me, knock next time.", "你嚇到我了，下次先敲個門。"),
        ("a power reactor in your chest, may I take a look?", "你胸口裝了個核反應堆？能讓我看看嗎？"),
        ("Impressive eye tech, where did you get it?", "這義眼技術真厲害，你從哪兒搞到的？"),
        ("Impressive....", "令人印象深刻..."),
        ("I guess you are the smartest of your kind, which doesn't say a lot", "我猜你是你們同類中最聰明的了，不過這也沒啥說服力"),
        ("you do look like a fool, amusing", "你看起來確實像個傻瓜，有趣"),
        ("Fri-endd has stro-ngg tee-eth. Dune like-ss stro--ng frien-d-d!", "朋-朋友牙-牙齒好結-實。沙地喜-歡強-壯的朋-朋-友！"),
        ("Frien-ddd! Frien-dd has little meat, saddd", "朋-朋友！朋友沒多少肉肉，好難難-過"),
        ("CCC-omputer Fri--end?? Comput-er tastes bad-dd......", "電電-電腦朋-朋友？？電腦-嚐起來不-不好吃......"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("kind", "種類"),
        ("limb", "肢體"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Prosthetics debug tool. Args: scrap|wood|titanium  - amputate limbs and install that kind. eye  - set bothEyesGone and equip two fully-charged prosthetic eyes. jaw  - set disfigured and equip the copper jaw. No arg  - strip all prosthetics. MP (host + sv_cheats): optional last arg targets another player by name.", "【義體】義體調試工具。參數 : scrap|wood|titanium - 截肢並安裝對應義肢。eye - 標記雙眼缺失並裝備兩枚滿電義眼。\njaw - 標記毀容並裝備銅下頜。無參數 - 移除所有義肢。多人模式（主機+作弊開關） : 可選最後一個參數指定目標玩家名稱"),
        ("kind [limb] [player]", "種類 [肢體] [玩家]"),
        ("scrap | wood | titanium | eye | jaw. Optional limb: armF | armB | legF | legB. MP (host + sv_cheats): optional player name targets another player.", "scrap廢料、wood木製、titanium鈦合金、eye眼、jaw下頜。可選肢體 : armF前臂、armB後臂、legF前腿、legB後腿。\n多人模式（主機+作弊開關） : 可選玩家名稱以指定目標"),
        ("Toggle the cybernetics panel", "【義體】切換義體編排面板"),
        ("Spawn all neuromods into the player's inventory. MP: host + sv_cheats only.", "【義體】生成所有神經模組到玩家物品欄。僅限多人模式主機+作弊開關"),
    };
    public static readonly (string En, string Zh)[] Moodles =
    {
        ("\n\n<color=\"red\">Dead flesh", "\n\n<color=\"red\">壞死血肉"),
        ("Your body no longer regenerates on its own and is dependent on the medical augment you have installed. If its charge falls below 20%, you won't be able to heal even from smaller injuries without medical care.", "你的身體已無法自行再生，完全依賴已安裝的醫療增強件。若其電量低於20%，即使小傷也無法癒合，必須依靠醫療護理。"),
        ("Waterlogged prosthetic legs", "義肢腿進水"),
        ("Damaged prosthetic shell leaves the leg wiring unprotected from outside hazards — water is getting in and the wiring is malfunctioning. Legs move slower until dried off or the shell is patched up.", "受損的義肢外殼使腿部線路暴露在外界危險中——水正在滲入，線路出現故障。移動速度變慢，直到水分蒸發或外殼修復。"),
        ("Waterlogged prosthetic arms", "義肢手臂進水"),
        ("Damaged prosthetic shell leaves the arm wiring unprotected from outside hazards — water is getting in and the wiring is malfunctioning. Strikes land weaker until dried off or the shell is patched up.", "受損的義肢外殼使手臂線路暴露在外界危險中——水正在滲入，線路出現故障。攻擊力減弱，直到水分蒸發或外殼修復。"),
    };
    public static readonly (string En, string Zh)[] MoodleFormats =
    {
        ("<color=#ff1100>{0}: -{1}% {2}</color>", "<color=#ff1100>{0}：-{1}% {2}</color>"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("LOCKED", "已鎖定"),
        ("EJECT", "彈出"),
        ("AUG INTERFACE", "義體編排"),
        ("* BRAIN CHIP", "* 腦部芯片"),
        ("* COPPER JAW", "* 銅下頜"),
        ("* EYE SOCKETS", "* 眼窩"),
        ("* TORSO AUGMENT", "* 軀幹增強件"),
        ("Prosthetic Eye", "義眼"),
        ("-- empty --", "-- 空 --"),
        ("-- insert battery --", "-- 插入電池 --"),
        ("Prosthetics Mod", "義體模組"),
        ("PROSTHETICS MOD", "義體模組"),
        ("Prosthetics Mod  v1.0.1", "義體模組  v1.0.1"),
        ("Installed: v1.0.1", "已安裝：v1.0.1"),
        ("Checking for updates…", "正在檢查更新..."),
        ("UP TO DATE", "已是最新版本"),
        ("UPDATE AVAILABLE", "有可用更新"),
        ("Hotbar: use numeric keypad keys", "快捷欄：使用數字小鍵盤"),
        ("Reset hotbar keybinds", "重置快捷欄按鍵綁定"),
        ("Mod Gameplay Sounds", "模組遊戲音量"),
        ("Mod UI Sounds", "模組界面音量"),
        ("Weld Flash Brightness", "焊接閃光亮度"),
        ("Weld Flash: black instead of white", "焊接閃光：使用黑色替代白色"),
        ("Hotbar position", "快捷圖標位置"),
        ("Hotbar position (fallback)", "快捷圖標位置（備用）"),
        ("CREDITS", "製作人員"),
        ("scroll to read more  ·  press Esc, or click outside, to close", "滾動查看更多  ·  按 Esc 或點擊外部關閉"),
        ("<b>JimmyKing</b>  —  Made CUCoreLib, Literally Furry Da Vinci. Check out his Custom Structures its awesome.", "<b>JimmyKing</b>  —  製作了 CUCoreLib，堪稱毛絨界達·芬奇。去看看他的 Custom Structures 模組，超棒的。"),
        ("<b>D3f1anc3</b>  —  Scrap prosthetic sprites, ui and minigames.", "<b>D3f1anc3</b>  —  廢料義肢的貼圖、界面和小遊戲。"),
        ("<b>Il_Disabile</b>  —  Wooden sprites for Minigames", "<b>Il_Disabile</b>  —  小遊戲的木製貼圖。"),
        ("<b>HpDz</b>  —  Many in game and ui sprites, also the welding sprites, never gona add neon nails bro", "<b>HpDz</b>  —  大量遊戲內和界面貼圖，還有焊接貼圖。兄弟，我是永遠不會加霓虹指甲的。"),
        ("<b>RushellXYZ</b>  —  for making RshLib and more awesome mods, check out New Firearms", "<b>RushellXYZ</b>  —  製作了 RshLib 和更多超棒模組，去看看 New Firearms。"),
        ("<b>artik1304</b>  —  spritework", "<b>artik1304</b>  —  貼圖繪製。"),
        ("<b>TheMagicDragon7</b>  —  singlehandedly finds most bugs I fix", "<b>TheMagicDragon7</b>  —  一個人找到了我修復的大部分 Bug。"),
        ("<b>Orsoniks</b>  —  some dude", "<b>Orsoniks</b>  —  某個老哥。"),
        ("<b>And you</b>  —  for taking your time and installing my mod, hope you enjoy :)  If you have any feedback, bug reports, or suggestions, I would love to hear them.", "<b>還有你</b>  —  感謝你花時間安裝我的模組，希望你喜歡 :)  如果你有任何反饋、Bug 報告或建議，我非常樂意傾聽。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Shell: {0}\nInnards: {1}", "外殼：{0}\n內部：{1}"),
    };
    public static readonly (string En, string Zh)[] Fragments =
    {
        ("* SCRAP ARM", "* 廢料義肢手臂"),
        ("* SCRAP LEG", "* 廢料義肢腿"),
        ("* WOOD ARM", "* 木製義肢手臂"),
        ("* WOOD LEG", "* 木製義肢腿"),
        ("* TITANIUM ARM", "* 鈦合金義肢手臂"),
        ("* TITANIUM LEG", "* 鈦合金義肢腿"),
        ("* COPPER ARM", "* 銅製手臂"),
        ("* COPPER LEG", "* 銅製腿"),
        ("* RIGHT ARM AUGMENT", "* 右臂增強件"),
        ("* LEFT ARM AUGMENT", "* 左臂增強件"),
        ("* RIGHT LEG AUGMENT", "* 右腿增強件"),
        ("* LEFT LEG AUGMENT", "* 左腿增強件"),
        (" AUGMENT", " 強化槽"),
        ("Bottom", "底部"),
        ("Top", "頂部"),
        ("Left", "左側"),
        ("Right", "右側"),
        ("Reset", "重置"),
        ("Credits", "製作人員"),
        ("UPDATE", "更新"),
        ("Close", "關閉"),
        ("forearms", "前臂"),
        ("feet", "腳"),
        ("hands", "手"),
        ("blood terminal", "血終端"),
        ("scrap eater", "廢料吞噬機"),
        ("keypad", "鍵盤鎖"),
        ("lock", "鎖"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("no battery", "無電池"),
        ("front arm", "前臂"),
        ("back arm", "後臂"),
        ("front leg", "前腿"),
        ("back leg", "後腿"),
        ("speed", "速度"),
        ("strike power", "攻擊力"),
        ("Press a key...", "按任意鍵..."),
        ("Checking for updates…", "正在檢查更新..."),
        ("UP TO DATE", "已是最新版本"),
        ("NEW VERSION: v", "新版本：v"),
        ("Could not reach update server", "無法連接更新服務器"),
        ("Installed: v1.0.1", "已安裝：v1.0.1"),
        ("New version available: v", "發現新版本：v"),
        ("UPDATE", "更新"),
        ("Could not reach update server.\n(", "無法連接更新服務器。\n("),
        ("UPDATE AVAILABLE", "有可用更新"),
        ("PROSTHETICS MOD", "義體模組"),
        ("Press any key to bind this hotbar slot\n\n<size=65%>Esc to cancel</size>", "按下任意鍵綁定該熱鍵欄槽位\n\n<size=65%>Esc 取消</size>"),
        ("prosthetics v1.0.1 powered by CUCoreLib", "prosthetics v1.0.1 由 CUCoreLib 驅動"),
        ("Unlock", "解鎖"),
    };
}
