internal static class ProstheticsTr
{
    public static readonly (string En, string Zh)[] Alerts =
    {
        ("Limb is missing", "肢体缺失"),
        ("This limb is already a prosthetic", "该肢体已经是义肢"),
        ("Torso augment slot opened", "躯干强化槽位已打开"),
        ("Apply directly to an upper arm, thigh, or torso", "直接应用于上臂、大腿或躯干"),
        ("Limb already has an augment slot", "该肢体已拥有增强插槽"),
        ("Augment slot implanted", "增强插槽已成功植入"),
        ("Ballistic: no charge — recharge with the RTG", "BFF力场：电量不足——请使用同位素发电机充电"),
        ("Ballistic: depleted", "BFF力场：能量耗尽"),
        ("Regeneration: no charge — recharge with the RTG", "MYX再生舱：电量不足——请使用同位素发电机充电"),
        ("Regeneration: depleted", "MYX再生舱：能量耗尽"),
        ("RTG: nothing to charge", "同位素发电机：无需充电"),
        ("RTG: everything charged", "同位素发电机：全部已充满"),
        ("Treadmill battery full", "跑步机增强件电池已充满"),
        ("Leg augment can't be installed on an arm", "腿部增强件无法安装在手臂上"),
        ("Arm augment can't be installed on a leg", "手臂增强件无法安装在腿部上"),
        ("Already installed on this limb", "此增强件已安装在该肢体上"),
        ("Torso augments go on the torso", "躯干增强件需安装在躯干上"),
        ("Torso is full (3 augment slots)", "躯干已满（3个增强插槽）"),
        ("No torso augment slot", "没有躯干增强插槽"),
        ("Not a torso augment", "不是躯干增强件"),
        ("Already installed", "已安装"),
        ("No open torso slot", "没有空的躯干插槽"),
        ("Deactivate Sandivistian first", "请先停用斯安威斯坦"),
        ("Balance Neuromod is cooling down", "平衡神经模组正在冷却中"),
        ("Sandivistian is cooling down", "斯安威斯坦正在冷却中"),
        ("Lockin Neuromod is cooling down", "锁定神经模组正在冷却中"),
        ("Battery installed", "电池已安装"),
        ("Steve Jobs says NO to slow mo in multiplayer", "乔布斯拒绝在多人联机模式中加入慢动作。\n【？意思是 多人联机不支持！】"),
        ("Can't remove another player's prosthetic", "无法移除其他玩家的义肢"),
        ("Battery removed", "电池已移除"),
        ("Prosthetic eye removed", "义眼已移除"),
        ("Can't modify another player's augment", "无法修改其他玩家的增强件"),
        ("Bio augment slot already occupied", "生物增强插槽已被占用"),
        ("Install an augment first", "请先安装增强件"),
        ("Augment already has a battery", "该增强件已装有电池"),
        ("Can't modify another player's prosthetic", "无法修改其他玩家的义肢"),
        ("Arm mod slot already occupied", "手臂插件插槽已被占用"),
        ("Leg mod slot already occupied", "腿部插件插槽已被占用"),
        ("Grappling hook attached", "抓钩已安装"),
        ("Grappling hook attached  - insert a battery to power", "抓钩已安装 - 请插入电池以供电"),
        ("Prosthetic removed", "义肢已移除"),
        ("Too damaged to safely remove  - fix it first", "损坏严重无法安全拆除 - 请先进行修复"),
        ("Chain incomplete  - disassembled into a titanium sheet", "装配链不完整 - 已拆解为一张钛板"),
        ("Prosthetic was damaged  - broke apart", "义肢受损 - 已彻底损坏解体"),
        ("Wooden prosthetic  - biochem heals it, a wrench takes it off", "木制义肢 - 生化流体可使其修复，使用扳手可以将其卸下"),
        ("Use a wrench to take off a prosthetic", "使用扳手可以卸下义肢"),
        ("Steady Hand attached", "稳手插件已安装"),
        ("Steady Hand attached  - insert a battery to power", "稳手插件已安装 - 请插入电池以供电"),
        ("Powergrip attached", "强力握持插件已安装"),
        ("Powergrip attached  - insert a battery to power", "强力握持插件已安装 - 请插入电池以供电"),
        ("Multi-Hacking attached", "多功能黑客插件已安装"),
        ("Multi-Hacking attached  - insert a battery to power", "多功能黑客插件已安装 - 请插入电池以供电"),
        ("Powersteps attached", "动力步伐增强件已安装"),
        ("Powersteps attached  - insert a battery to power", "动力步伐增强件已安装 - 请插入电池以供电"),
        ("Treadmill attached", "跑步机增强件已安装"),
        ("Treadmill attached  - insert a battery to charge", "跑步机增强件已安装 - 请插入电池以充电"),
        ("Battery too low", "电池电量过低"),
        ("Nothing in hand to scan", "手中没有可扫描的物品"),
        ("Both eyes removed", "双眼已移除"),
        ("Eye removed", "眼球已移除"),
        ("Drag onto a prosthetic arm to install", "拖动到义肢手臂上以安装"),
        ("Drag onto a prosthetic leg to install", "拖动到义肢腿上以安装"),
        ("Apply on the head", "在头部使用"),
        ("Not missing an eye", "并未缺失眼睛"),
        ("No empty eye sockets left", "已无空余的眼眶"),
        ("Not missing a jaw", "未缺失下颌"),
        ("Already wearing a copper jaw", "已装备铜下颌"),
        ("This prosthetic is for arms", "此义肢适用于手臂"),
        ("This prosthetic is for legs", "此义肢适用于腿部"),
        ("Limb is not missing", "肢体并未缺失"),
        ("Can't attach a prosthetic to another prosthetic", "无法将义肢安装在另一个义肢上"),
        ("This prosthetic can't use tools", "此义肢无法使用工具"),
        ("You cant hold this with a hook, you can only hold containers on a hook", "无法用钩子提拿此物品，钩子只能用于悬挂容器。"),
    };
    public static readonly (string En, string Zh)[] AlertFormats =
    {
        ("{0} attached", "{0}已安装"),
        ("{0} attached  - insert a battery to power", "{0}已安装——请插入电池以供电"),
        ("Not enough energy to hack {0}", "能量不足，无法入侵{0}"),
        ("Can't wear {0} with two prosthetic {1}.", "无法在安装了两只义肢{1}的情况下穿戴{0}。"),
        ("Recipe scanned: {0}", "已扫描配方：{0}"),
        ("Identified: {0} (no recipe in the database)", "已识别：{0}（数据库中无配方）"),
    };
    public static readonly (string En, string Zh)[] Talks =
    {
        ("That tastes like poo", "尝起来像坨屎"),
        ("my ...eeth hurt!", "我...牙..疼！"),
        ("WHAT ARE YOU?", "你究竟是什么东西？"),
        ("How awfull it must be for you, You know what? I can spare one item for you, pick any", "你一定很难受吧。这样吧，我可以免费送你一件东西，挑一个吧"),
        ("I'm sorry you have to go further like this, I'll give you a discount though", "很抱歉你得继续这样走下去，不过我会给你打个折"),
        ("You scared me, knock next time.", "你吓到我了，下次先敲个门。"),
        ("a power reactor in your chest, may I take a look?", "你胸口装了个核反应堆？能让我看看吗？"),
        ("Impressive eye tech, where did you get it?", "这义眼技术真厉害，你从哪儿搞到的？"),
        ("Impressive....", "令人印象深刻..."),
        ("I guess you are the smartest of your kind, which doesn't say a lot", "我猜你是你们同类中最聪明的了，不过这也没啥说服力"),
        ("you do look like a fool, amusing", "你看起来确实像个傻瓜，有趣"),
        ("Fri-endd has stro-ngg tee-eth. Dune like-ss stro--ng frien-d-d!", "朋-朋友牙-牙齿好结-实。沙地喜-欢强-壮的朋-朋-友！"),
        ("Frien-ddd! Frien-dd has little meat, saddd", "朋-朋友！朋友没多少肉肉，好难难-过"),
        ("CCC-omputer Fri--end?? Comput-er tastes bad-dd......", "电电-电脑朋-朋友？？电脑-尝起来不-不好吃......"),
    };
    public static readonly (string En, string Zh)[] Commands =
    {
        ("kind", "种类"),
        ("limb", "肢体"),
    };
    public static readonly (string En, string Zh)[] CommandDescs =
    {
        ("Prosthetics debug tool. Args: scrap|wood|titanium  - amputate limbs and install that kind. eye  - set bothEyesGone and equip two fully-charged prosthetic eyes. jaw  - set disfigured and equip the copper jaw. No arg  - strip all prosthetics. MP (host + sv_cheats): optional last arg targets another player by name.", "【义体】义体调试工具。参数 : scrap|wood|titanium - 截肢并安装对应义肢。eye - 标记双眼缺失并装备两枚满电义眼。\njaw - 标记毁容并装备铜下颌。无参数 - 移除所有义肢。多人模式（主机+作弊开关） : 可选最后一个参数指定目标玩家名称"),
        ("kind [limb] [player]", "种类 [肢体] [玩家]"),
        ("scrap | wood | titanium | eye | jaw. Optional limb: armF | armB | legF | legB. MP (host + sv_cheats): optional player name targets another player.", "scrap废料、wood木制、titanium钛合金、eye眼、jaw下颌。可选肢体 : armF前臂、armB后臂、legF前腿、legB后腿。\n多人模式（主机+作弊开关） : 可选玩家名称以指定目标"),
        ("Toggle the cybernetics panel", "【义体】切换义体编排面板"),
        ("Spawn all neuromods into the player's inventory. MP: host + sv_cheats only.", "【义体】生成所有神经模组到玩家物品栏。仅限多人模式主机+作弊开关"),
    };
    public static readonly (string En, string Zh)[] Moodles =
    {
        ("\n\n<color=\"red\">Dead flesh", "\n\n<color=\"red\">坏死血肉"),
        ("Your body no longer regenerates on its own and is dependent on the medical augment you have installed. If its charge falls below 20%, you won't be able to heal even from smaller injuries without medical care.", "你的身体已无法自行再生，完全依赖已安装的医疗增强件。若其电量低于20%，即使小伤也无法愈合，必须依靠医疗护理。"),
        ("Waterlogged prosthetic legs", "义肢腿进水"),
        ("Damaged prosthetic shell leaves the leg wiring unprotected from outside hazards — water is getting in and the wiring is malfunctioning. Legs move slower until dried off or the shell is patched up.", "受损的义肢外壳使腿部线路暴露在外界危险中——水正在渗入，线路出现故障。移动速度变慢，直到水分蒸发或外壳修复。"),
        ("Waterlogged prosthetic arms", "义肢手臂进水"),
        ("Damaged prosthetic shell leaves the arm wiring unprotected from outside hazards — water is getting in and the wiring is malfunctioning. Strikes land weaker until dried off or the shell is patched up.", "受损的义肢外壳使手臂线路暴露在外界危险中——水正在渗入，线路出现故障。攻击力减弱，直到水分蒸发或外壳修复。"),
    };
    public static readonly (string En, string Zh)[] MoodleFormats =
    {
        ("<color=#ff1100>{0}: -{1}% {2}</color>", "<color=#ff1100>{0}：-{1}% {2}</color>"),
    };
    public static readonly (string En, string Zh)[] Ui =
    {
        ("LOCKED", "已锁定"),
        ("EJECT", "弹出"),
        ("AUG INTERFACE", "义体编排"),
        ("* BRAIN CHIP", "* 脑部芯片"),
        ("* COPPER JAW", "* 铜下颌"),
        ("* EYE SOCKETS", "* 眼窝"),
        ("* TORSO AUGMENT", "* 躯干增强件"),
        ("Prosthetic Eye", "义眼"),
        ("-- empty --", "-- 空 --"),
        ("-- insert battery --", "-- 插入电池 --"),
        ("Prosthetics Mod", "义体模组"),
        ("PROSTHETICS MOD", "义体模组"),
        ("Prosthetics Mod  v1.0.1", "义体模组  v1.0.1"),
        ("Installed: v1.0.1", "已安装：v1.0.1"),
        ("Checking for updates…", "正在检查更新..."),
        ("UP TO DATE", "已是最新版本"),
        ("UPDATE AVAILABLE", "有可用更新"),
        ("Hotbar: use numeric keypad keys", "快捷栏：使用数字小键盘"),
        ("Reset hotbar keybinds", "重置快捷栏按键绑定"),
        ("Mod Gameplay Sounds", "模组游戏音量"),
        ("Mod UI Sounds", "模组界面音量"),
        ("Weld Flash Brightness", "焊接闪光亮度"),
        ("Weld Flash: black instead of white", "焊接闪光：使用黑色替代白色"),
        ("Hotbar position", "快捷图标位置"),
        ("Hotbar position (fallback)", "快捷图标位置（备用）"),
        ("CREDITS", "制作人员"),
        ("scroll to read more  ·  press Esc, or click outside, to close", "滚动查看更多  ·  按 Esc 或点击外部关闭"),
        ("<b>JimmyKing</b>  —  Made CUCoreLib, Literally Furry Da Vinci. Check out his Custom Structures its awesome.", "<b>JimmyKing</b>  —  制作了 CUCoreLib，堪称毛绒界达·芬奇。去看看他的 Custom Structures 模组，超棒的。"),
        ("<b>D3f1anc3</b>  —  Scrap prosthetic sprites, ui and minigames.", "<b>D3f1anc3</b>  —  废料义肢的贴图、界面和小游戏。"),
        ("<b>Il_Disabile</b>  —  Wooden sprites for Minigames", "<b>Il_Disabile</b>  —  小游戏的木制贴图。"),
        ("<b>HpDz</b>  —  Many in game and ui sprites, also the welding sprites, never gona add neon nails bro", "<b>HpDz</b>  —  大量游戏内和界面贴图，还有焊接贴图。兄弟，我是永远不会加霓虹指甲的。"),
        ("<b>RushellXYZ</b>  —  for making RshLib and more awesome mods, check out New Firearms", "<b>RushellXYZ</b>  —  制作了 RshLib 和更多超棒模组，去看看 New Firearms。"),
        ("<b>artik1304</b>  —  spritework", "<b>artik1304</b>  —  贴图绘制。"),
        ("<b>TheMagicDragon7</b>  —  singlehandedly finds most bugs I fix", "<b>TheMagicDragon7</b>  —  一个人找到了我修复的大部分 Bug。"),
        ("<b>Orsoniks</b>  —  some dude", "<b>Orsoniks</b>  —  某个老哥。"),
        ("<b>And you</b>  —  for taking your time and installing my mod, hope you enjoy :)  If you have any feedback, bug reports, or suggestions, I would love to hear them.", "<b>还有你</b>  —  感谢你花时间安装我的模组，希望你喜欢 :)  如果你有任何反馈、Bug 报告或建议，我非常乐意倾听。"),
    };
    public static readonly (string En, string Zh)[] UiFormats =
    {
        ("Shell: {0}\nInnards: {1}", "外壳：{0}\n内部：{1}"),
    };
    public static readonly (string En, string Zh)[] Fragments =
    {
        ("* SCRAP ARM", "* 废料义肢手臂"),
        ("* SCRAP LEG", "* 废料义肢腿"),
        ("* WOOD ARM", "* 木制义肢手臂"),
        ("* WOOD LEG", "* 木制义肢腿"),
        ("* TITANIUM ARM", "* 钛合金义肢手臂"),
        ("* TITANIUM LEG", "* 钛合金义肢腿"),
        ("* COPPER ARM", "* 铜制手臂"),
        ("* COPPER LEG", "* 铜制腿"),
        ("* RIGHT ARM AUGMENT", "* 右臂增强件"),
        ("* LEFT ARM AUGMENT", "* 左臂增强件"),
        ("* RIGHT LEG AUGMENT", "* 右腿增强件"),
        ("* LEFT LEG AUGMENT", "* 左腿增强件"),
        (" AUGMENT", " 强化槽"),
        ("Bottom", "底部"),
        ("Top", "顶部"),
        ("Left", "左侧"),
        ("Right", "右侧"),
        ("Reset", "重置"),
        ("Credits", "制作人员"),
        ("UPDATE", "更新"),
        ("Close", "关闭"),
        ("forearms", "前臂"),
        ("feet", "脚"),
        ("hands", "手"),
        ("blood terminal", "血终端"),
        ("scrap eater", "废料吞噬机"),
        ("keypad", "键盘锁"),
        ("lock", "锁"),
    };
    public static readonly (string En, string Zh)[] Literals =
    {
        ("no battery", "无电池"),
        ("front arm", "前臂"),
        ("back arm", "后臂"),
        ("front leg", "前腿"),
        ("back leg", "后腿"),
        ("speed", "速度"),
        ("strike power", "攻击力"),
        ("Press a key...", "按任意键..."),
        ("Checking for updates…", "正在检查更新..."),
        ("UP TO DATE", "已是最新版本"),
        ("NEW VERSION: v", "新版本：v"),
        ("Could not reach update server", "无法连接更新服务器"),
        ("Installed: v1.0.1", "已安装：v1.0.1"),
        ("New version available: v", "发现新版本：v"),
        ("UPDATE", "更新"),
        ("Could not reach update server.\n(", "无法连接更新服务器。\n("),
        ("UPDATE AVAILABLE", "有可用更新"),
        ("PROSTHETICS MOD", "义体模组"),
        ("Press any key to bind this hotbar slot\n\n<size=65%>Esc to cancel</size>", "按下任意键绑定该热键栏槽位\n\n<size=65%>Esc 取消</size>"),
        ("prosthetics v1.0.1 powered by CUCoreLib", "prosthetics v1.0.1 由 CUCoreLib 驱动"),
        ("Unlock", "解锁"),
    };
}
